### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by Blank-00000** [connext/community-sybil-reports#101]
# Related Addresses

"1st sybil"

0x24f7af72dfe2b44cdd9d0f49480e3bba6dcbd261
0x93998bc0ab2864321ace7a128abad94b596f388b
0x14ec184296189f35ec68e61e2f8eb6ca25e8da12
0x5712171abca3743563a4594430b4cfe123711d9e
0xb44107ede4a636b66b10b15a7a6cc9172970420d
0xa7edab50c9ef3d2da4cf44506eb1f306566735ca
0xdbabf33f0d2464c9ac403acb67ef0e3340a0c031
0x6491f41d0cdbbd487c61d3782b1f268733d7e2f0

"2nd sybil"

0x9a3af2dfe6c7b8241c187791912f4eb9cf497ab4
0xc830ba77b2c6b664315db80a4f9a4caa0b241ca3

"3rd sybil"

0x75749aaa3944483fe5b4d1e7083f31d3fae76145
0x455bfa61a29fb7c2440e0b6fc3d9274875881126

"4th sybil"

0xc2d70ffe112d9b18c8e093b05c2f785b1ce7cff2
0x1111212aed04902512911f9573fc146ddec74cb5
0xb0a198fa79937c594000819312aa57d04a0e477f

# Reasoning

i will explain "1st sybil" first as you can see thats 8 wallet and all of that wallet have 5.5k lp in connext and if you will check their transaction history you can see that in arbitrum around 2023/05/28 03:44 they all add liquidity at the same time and they all remove liquidity around 2023/07/02 04:50 here they remove dai and 2023/07/10 10:25 here they remove weth and if you go a little bit down in their transaction history you can see that they add liquidity then removed it then bridge to the other chain. Also you dont need to go deep down their transaction history you can see in their newest history that all of them are farming zora right now and all of them are minting and swaping the exact amount and token.
Now lets go to the "2nd sybil" wallet this one is a bit special because he is only farming in arbitrum all he do is add liquidity then remove it. At 2023/02/01 04:46 - 4:53 until 2023/06/27 06:03 both wallet  are doing the same thing they swap then add liquidity and sometimes they bridge it then doing again the same stuff and rn he is currently farming opbnb.
Now its "3rd sybil" wallet this one is a bit tricky because all he doing is he will add liquidity in this chain and he will do other task in others airdrop campaign for example in arbitrum 2023/02/20 22:55 he add liquidity in both wallet that have 2mins interval then after he do it he do layerzero airdrop stargate bridge then he procced to polygon he remove cweth at 2023/05/09 09:36 in both wallet then he do it again farming airdrop in other campaign using polygon but rn he is farming layerzero.
Now lets go to "4th sybill" wallet this one is a bit hard i really need to go to the bottom and compare their transaction history because he is not doing it all the the same time for example he add liqiudity in a different time frame 2023/03/29 17:39:38, 2023/04/02 00:32:10, 2023/03/31 as you can see there is 2days interval in every wallet but its natural because this guys is reall farming hard as in he is farming opbnb,zora,arbitrum,etch. But there is one mistake he did all of them have the same remove liquidity date that is 2023/06/24 and their number is not that apart 5,285.8309 DAI, 5,388.7156 DAI,and 5,870.5347 DAI thats the amount he remove in all three wallet in the same day and currently he is farming zerion and phi.

# Methodology
I am using DeBank platform to locate all of this wallet and how they become sybil because using this you can see all of their transaction in all chain.And Arkham for coparing the transaction and i also use debank platform for comparing their transaction amount and what time it happen also i am doing it manually so i really see what they are doing debank is really good site for finding sybil acc.

"1st sybil wallet "
https://debank.com/profile/0x24f7af72dfe2b44cdd9d0f49480e3bba6dcbd261/history
https://debank.com/profile/0x93998bc0ab2864321ace7a128abad94b596f388b/history
https://debank.com/profile/0x14ec184296189f35ec68e61e2f8eb6ca25e8da12/history
https://debank.com/profile/0x5712171abca3743563a4594430b4cfe123711d9e/history
https://debank.com/profile/0xb44107ede4a636b66b10b15a7a6cc9172970420d/history
https://debank.com/profile/0xa7edab50c9ef3d2da4cf44506eb1f306566735ca/history
https://debank.com/profile/0xdbabf33f0d2464c9ac403acb67ef0e3340a0c031/history
https://debank.com/profile/0x6491f41d0cdbbd487c61d3782b1f268733d7e2f0/history
https://platform.arkhamintelligence.com/visualizer/entity/0x24f7Af72dfe2B44CdD9D0f49480e3bBa6dCBD261,0x93998BC0AB2864321aCE7A128aBad94b596F388B,0x14EC184296189f35Ec68e61e2f8Eb6ca25E8da12,0x5712171ABca3743563A4594430b4Cfe123711d9E,0xb44107eDe4a636B66b10B15a7a6cc9172970420d,0xa7eDaB50c9eF3d2DA4CF44506eb1f306566735ca,0xdbaBF33F0d2464C9Ac403acB67ef0E3340A0c031,0x6491f41d0CDBbD487C61D3782b1F268733D7E2F0?flow=all&positions=%7B%7D&sortDir=desc&sortKey=time&timeGte=1672272000000&usdGte=0.1
![image](https://github.com/connext/community-sybil-reports/assets/130337535/f3d09455-139f-46c7-9143-1cfb303ffbce)

"2nd sybil acc"
https://debank.com/profile/0x9a3af2dfe6c7b8241c187791912f4eb9cf497ab4/history
https://debank.com/profile/0xc830ba77b2c6b664315db80a4f9a4caa0b241ca3/history
https://platform.arkhamintelligence.com/visualizer/entity/0x9a3AF2DFe6c7B8241c187791912f4eb9Cf497ab4,0xC830BA77b2c6b664315DB80a4f9a4cAA0b241CA3?flow=all&positions=%7B%7D&sortDir=desc&sortKey=time&usdGte=0.1
![image](https://github.com/connext/community-sybil-reports/assets/130337535/64a67074-df40-4a49-b954-cd11ad1f31f5)

"3rd sybil acc"
https://debank.com/profile/0x75749aaa3944483fe5b4d1e7083f31d3fae76145/history
https://debank.com/profile/0x455bfa61a29fb7c2440e0b6fc3d9274875881126/history
https://platform.arkhamintelligence.com/visualizer/entity/0x455BFA61A29fb7c2440E0B6FC3D9274875881126,0x75749aaa3944483fe5b4d1e7083F31D3fAe76145?flow=all&positions=%7B%7D&sortDir=desc&sortKey=time&timeGte=1672531200000&usdGte=0.1
![image](https://github.com/connext/community-sybil-reports/assets/130337535/9612baa7-07cf-41a3-be28-f1fbdd9619db)

"4th sybil acc"
https://debank.com/profile/0xc2d70ffe112d9b18c8e093b05c2f785b1ce7cff2/history
https://debank.com/profile/0x1111212aed04902512911f9573fc146ddec74cb5/history
https://debank.com/profile/0xb0a198fa79937c594000819312aa57d04a0e477f/history
https://platform.arkhamintelligence.com/visualizer/entity/0x1111212AEd04902512911f9573FC146ddEc74CB5,0xb0A198Fa79937C594000819312aA57D04a0E477f,0xC2d70fFE112d9b18c8e093B05C2f785B1CE7cfF2?flow=all&positions=%7B%7D&sortDir=desc&sortKey=time&timeGte=1672012800000&usdGte=0.1
![image](https://github.com/connext/community-sybil-reports/assets/130337535/674368dd-3af8-4c83-91d0-c78f769055e0)
 you can see the picture this one is really grinding and hunting airdrop.

# Rewards Address

0x21B319d5BCDa6d2570a78CFe3EBDfaD00A91E04C

**Comment by Aggari** [comment]
how bout these addresses ?

0x3a5688ba86331c4668fef062ccf4bfd6ad2a0d5d

0x437130539bcf3155a9f1614e9789697845b83516

0x1adf17f665fbf879c75767ecc87f938abc776682

0x758091a94b7904d982ee5b6d85bae5ae4afde404

**Comment by Blank-00000** [comment]
> how bout these addresses ?
> 
> 0x3a5688ba86331c4668fef062ccf4bfd6ad2a0d5d
> 
> 0x437130539bcf3155a9f1614e9789697845b83516
> 
> 0x1adf17f665fbf879c75767ecc87f938abc776682
> 
> 0x758091a94b7904d982ee5b6d85bae5ae4afde404

wait lemme check

**Comment by Blank-00000** [comment]
> how bout these addresses ?
> 
> 0x3a5688ba86331c4668fef062ccf4bfd6ad2a0d5d
> 
> 0x437130539bcf3155a9f1614e9789697845b83516
> 
> 0x1adf17f665fbf879c75767ecc87f938abc776682
> 
> 0x758091a94b7904d982ee5b6d85bae5ae4afde404

i believe yes because they have the same name in debank which is churin and their transaction history are the same although there is time interval if you compare them and also he is using other chain for example he is using polygon in other he is using arbitrum thats why its really hard to tell that he sybil, but you can still see the sequence of it i see that they are also farming layerzero,zora and there is a sequence to it

**Comment by Aggari** [comment]
You might want to add this wallet to your post or report it separately... You checked it for me :)

**Comment by blockchainuser22** [comment]
Your reasoning about the 4th group of wallets is especially ridiculous, are you not afraid that you are slandering innocent people? In my opinion, in this situation, you are the bounty hunter and not them.

**Comment by blockchainuser22** [comment]
By the way, your reward wallet, like wallets from group 3, also farms the Layer Zero and Polyhedra Network airdrops, this is clearly visible if you look at your transactions through DeBank   LOL

**Comment by Blank-00000** [comment]
> Your reasoning about the 4th group of wallets is especially ridiculous, are you not afraid that you are slandering innocent people? In my opinion, in this situation, you are the bounty hunter and not them.

ofc not bro because i check their transaction for 5months  in debank and all of them have the same pattern or maybe the 4th group is all your account hmmm why you so defensive?

**Comment by Blank-00000** [comment]
> By the way, your reward wallet, like wallets from group 3, also farms the Layer Zero and Polyhedra Network airdrops, this is clearly visible if you look at your transactions through DeBank LOL

polyhydra i didnt even know that but regarding layer zero yes im trying to farm it but not like other that used thousand of dollar just to farm it and im not using other acc to farm layer zero thats my only acc

**Comment by A-Keyboard** [comment]
Only counting the first sybil group even tho is less than <10

**Comment by Blank-00000** [comment]
> Only counting the first sybil group even tho is less than <10

am i in?

**Comment by Blank-00000** [comment]
> Only counting the first sybil group even tho is less than <10

nice hope it help you guys<3

**Comment by A-Keyboard** [comment]
@Blank-00000 Can you dm me on Discord, my discord is khlilo

**Comment by Blank-00000** [comment]
> @Blank-00000 Can you dm me on Discord, my discord is khlilo

copy bro

**Comment by Blank-00000** [comment]
> @Blank-00000 Can you dm me on Discord, my discord is khlilo

bro i dm you my user name is blank00. F67GXJ
