### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by catalyst002** [connext/community-sybil-reports#109]
# Related Addresses

0xbc1c57f00aa0e2e9eb7eecd1f9a5eb3fc73b38a3
0xbc1c7ebfc8cdb116b30acd9e90d190347af81100
0xbc1d7d85d7e962c2563f462a127674ca2e849f11
0xbc1df8dcab7acf0ecc4acb5612a80d575ca46772
0xbc1e38b21c8a65df633aeb656062104cd0cfe7d9
0xbc1e4ec874d908995eb9a9425aa6b241f9adae38
0xbc223be672ec0a846ba14f3bbbda23061502114e
0xbc22550e0b4a9d1bd236d83fdc34f8874436001f
0xbc227884ba2c5a11be60b05699d256014638983b
0xbc24ea3d239653cf4b90510ccfaa753c4275ec1b
0xbc26e27974aebb5dab4bf32c48b20a1c784f724e
0xbc274b42c8bbcac18281d6844b4681a6139bbef0
0xbc29b33fed314e55e85072b41beeb6a50890f5a0
0xbc2b401780f597b3c879ffde99fc9753340d3c92
0xbc2c11558554187845aa177b852e2fea17074ed8
0xbc2c77d7d4742a7209503e0820de27117b843b1f
0xbc2cbc4ea762750931653e367575fbc601ec03bb
0xbc2d11fc6b49be79b94c0a4d62f78ef84dca1ff7
0xbc2e07a461ef6194545c4bbad0e3f64679331ea9
0xbc2fb83af791888156e77b50585e0151568dbc9d
0xbc2fdd2522356a50781caf6db0ced244978c6941
0xbc30796cece5f885c9817dde262800289eed466e
0xbc311ecfad26e3df847bf5a385161615b1b89a0b
0xbc32559dd01274b015c5abc89e07c4c8d8b44024
0xbc33216039d01dd2bbc2688f4453fb4ba70ea655
0xbc338820fab93046371da535be087f86bf7fec83
0xbc3410868a9a49e4f7ab5921f1c68241049a5674
0xbc34cb7c23cf90508464d37eac241613e4487edf
0xbc35e2923399975481e9cfcc3ed56935bc202147
0xbc35fa8dc01e5e64b4bdbed22df8cf581c147659
0xbc3642d18dedf59ab35f655ebe7c72cd622aaac9
0xbc36a1a6972aadb8009850ee6a9c8d77aafc689c
0xbc377eeaaaf471a4fac27c1bc50c9e26708d2c16
0xbc38efbc2c2f695c08ebcbdbcc85e20d47e4ad87
0xbc39761c426b284150f39e3b10faf05360320c61
0xbc397e0ad59f5ebf7af1cad9be7d7600642d608b
0xbc39de2cfebacd65d2c94019404dc8004c71dda9
0xbc3a058d1c919f6b1f48e8846246d04d467902c8
0xbc3a065464a2839ae268861356328ce910783ad3
0xbc3afbb37c21774dfe5d6d05e17092c46bae417f
0xbc3e9e4264f8afe4913c50cb9b11f71ef28c691c
0xbc40673de7227ef249a32db7a9339aa361083cf9
0xbc40b600aea23e937a408dc6bd1f39fc1f2f279c
0xbc410580e46d1475d058a330a6c16343b0a0e1f6
0xbc4281203488cb72db77cbf568228654b35d783a
0xbc4496f7ec6b19f4642e90e7d9ba5df1edc8c2d8
0xbc452d6b2bfcb1f6ee92b84f3563643c2299706a
0xbc4534be1a42c5fec30a8a1a8836566d9e2fa953
0xbc45d3958638165905f16f270d65b4f416983ae5
0xbc4652103f3371ddade8942fceb8d6c796977133
0xbc46a5ee5a1b64046fae4b18605df989efbe8f45
0xbc46ab616b7428aba516d2e60c4c74fd26132d0f
0xbc470a43944ddc9070ac31e889ea2af23ba564ac
0xbc478493e48047cc73af3cbabd3ad97d43199698
0xbc484ff70a5839c70fd3257899ff715298ba6667
0xbc4940e28e717c77fca453b5c94aa9f53fb8fe06
0xbc4976bd3daeae9174688cb14726c2f062fa7b81
0xbc49b0b6b6a11f8a9111ccf2ef15580a6ab8ee4c
0xbc4a19e7a818393375245c741e8764ab80b54942
0xbc4bede6fae83d2ad830d7ad5ab86a6c78466cf4
0xbc4c8916891a2c2e6c344c7b98e4083d41a5dfae
0xbc4d4f3b609a85433781e175dbb807037f38054a
0xbc4d92b739b03685c64c9070b28bcfcbedffc87b
0xbc4e1e6cb76070c0bd00d550eb9f01ee6a3e557d
0xbc4e7d530e258edba7e94f24b5e477c25edbf75c
0xbc4f373b63070053e8fd266c8ed861e813dd216d
0xbc514de784b49dc43282f8340ebc3aa7b86da12a
0xbc525f5b612e02d134751271c0d82725f5722b1f
0xbc54a4f713db8f69bbcb7b816fbbb144713ec728
0xbc555e805f65fdffc6c5c3aefeaf084d0fdb76bc
0xbc557820c501074781f07d1d15879256b91752d1
0xbc569ffc1eca0d519d4c0f68a2d99f2cb9c83a2e
0xbc56c3f15d7a0c5685cbf9551cf340a8f0954db8
0xbc58f0a9abb490ded0fe8c8c399d3d0adcd52921
0xbc594680262d56076d326bc9099982cab69def1c
0xbc5a3a8d843ebca04b930435e236eea2af16016c
0xbc5b46daf2c9843da37a9a2237f1987f48b410d3
0xbc5bb69a5fed75a167d24e65a03b9d69abc7cd48
0xbc5d44f6d444522d3fb37d9b4918f7b099a3a998
0xbc60f6398cc581229ab55d58c5df8dac0dcaeea2
0xbc622c6bcc9200c68d525adf5c8b1b9c3d1c6de3
0xbc62985faabed27a8f174cbd5ea1ee7b1ed8fc12
0xbc62a301f64cebe9603ca887c9177796616e36bf
0xbc62c9510fe0c928a3f22c770b7a25474c3afc18
0xbc6374f7b094c28e47fe4adaf2e400fd152ccafb
0xbc637cb012e76f7e35c0ff5c3f0acb89893b6e97
0xbc654b09053b5115239c89ebe0cc1b08b3a54d48
0xbc68c27b8fb4b93ae3c420ddedc42ba7ad17707f
0xbc6992a89f3980d2e6af177a8b5072c4bd44bfed
0xbc6a26fd56c9188238b2829ad0de7b50128793b4
0xbc6bc4e2195c03c6b50cee36347254724b3e01ac
0xbc6c648530d28feed721bb097bff00dc012081b6
0xbc6c66558adcc464a88fc674933c9c47f48d06dd
0xbc6d606226130c45be14bc1eebccf3a9daf4b5cf
0xbc6ea2b91c6b81eed5bb9cccb0eb0ebe66d81cdd
0xbc6f7a5de7c74d5d3104cc645bd23282863c2086
0xbc70ff6614d1012234411f91d1ebd628e12f08d1
0xbc74694da28572a58435c668da26fd90cd630166
0xbc7521e0a0bc0a66bf58ddb6623c26776310f117
0xbc758407d1b560f4cab94cd58f8806af26ab7793
0xbc769e783796bab3d614683d1f2f5e1446b3724d
0xbc76f31cb937e5ed3d99ddb27d16a18f5ec5ebba
0xbc7783c9cc241e67844b284d57c8d66db461ac28
0xbc79790618c1ae3462d29207a82c69287c9330ee
0xbc7abc90651343e1d7146a27a1dbf4967ef0ee71
0xbc7ad0674f37e3a3a8ef41f0b56e828ade8912a0
0xbc7cd324c0710e23805ebde8262f9cb2e0a3eebb
0xbc7cda2fe846bdffde69a63a81c7b8ec352e3b24
0xbc7ce9b7b9ebe801f63b5f6583f1edd1699a1f6b
0xbc80c4b71c3f673391f2708deffc239b805f2261
0xbc8291f0fdbb34bb03558621b67592b176bdf1ed
0xbc839c7698b396f453d2a6170b50c37cc0f96930

# Reasoning

All addresses listed received funding on BSC about 115 days ago from address 0x666e101e6b34c277299035f7e6055e8ddc466666

# Methodology

I checked the funding addresses of wallets from eligble wallets lists.

# Rewards Address

0x1f9090aae28b8a3dceadf281b0f12828e676c326

**Comment by ArjunBhuptani** [comment]
Invalid - no clear connection between wallets
