### ISSUE TITLE
no sybil ussue lalalala

### ISSUE THREAD

**Issue by alexthegreat9121** [connext/community-sybil-reports#113]
you should stop making shit and think about better things to do in world. your project is other crypto rubbish which wont have any users after such. you will get community of rats without money and brain.
what is sybil? its a tester who help your rubbish project becomes more popular in mass and spent own money on this.
so how it matter? you should say thanks to such users, not try to cut them off from miserable airdrop.
think about this! i had hopes about your project and now i wont even go on your site again. very smart move) 
be happy with rats who will get penny from you. USSR is here, its in your project! think about become more modern and clever)

**Comment by tripo1** [comment]
I totally agree!

**Comment by kampenk** [comment]
scam project
take your drop for yourself, no one needs it with such an attitude

**Comment by ainozz** [comment]
Your project doesn't catch my interest; it appears to be devoid of purpose, akin to the deceptive nature of the entire Sibyl campaign. I have no use for your offering, and I firmly intend to steer clear of your innovations and connections.

**Comment by Zeck17** [comment]
This project is my biggest disappointment.. it's looking more and more like a scam.. I don't advise anyone to contact this hole.

**Comment by windi25** [comment]
Your project is full of bullshit.  
I will never use your product again. I think you are swindlers who fool people.

**Comment by arikfatmawatik** [comment]
This project fails to capture my attention, as its purposelessness mirrors the deceitful essence of the Sibyl campaign. Your proposal holds no value for me, and I remain resolute in my decision to abstain from engaging with your advancements and associations.

**Comment by baboy4547** [comment]
Totally agree with the main post. I immediately understood that something was wrong here and that they wanted to deceive me.

**Comment by asruk-sudo** [comment]
The project you're presenting lacks any appeal to me. Your offering holds no relevance in my perspective, and I assert that I'll never find utility in your innovations and connections.

**Comment by yonandamcp31** [comment]
Your project is complete bullshit.
I will never use your product. You are scammers who fool people.

**Comment by memphisamirqe** [comment]
Your proposal holds no value for me. This project is my biggest disappointment I assert that I'll never find utility in your innovations and connections.

**Comment by jancok009** [comment]
I find no interest in your project, perceiving it to be void of purpose, much like the dishonesty prevalent in the Sibyl campaign. Your proposition has no place in my plans, and I stand by my decision to disregard your progressions and associations.

**Comment by nando67** [comment]
A complete shame. Such a worthless service has not existed for a long time. Terrible and dangerous project!A complete shame. Such a worthless service has not existed for a long time. Terrible and dangerous project!

**Comment by Djoko007** [comment]
The project of fraudsters
and scammers.

**Comment by uzii77** [comment]
Shame. You don't have the right to use personal data, I didn't expect you to. I will never use your products. Shame.

**Comment by asruk2131** [comment]
I agree with the author of the post, this crap doesn't appeal to me, given its apparent lack of purpose, which reminds me of the deception woven into all the gray matter. I am not comfortable with what you are offering and I pledge to never take advantage of your achievements and relationships.

**Comment by gilang33-svg** [comment]
this site is a scam. I will not recommend him to any of my friends. I will not use their bridges. it collects personal information. this is a scam.

**Comment by daphnejovan** [comment]
I am writing to you about the activities of a project that, in my opinion, is systematically deceiving people. I would like to express my concern about this situation and submit a formal complaint.

**Comment by tothemoonid** [comment]
The project you're promoting doesn't intrigue me; its seeming lack of purpose resembles the dishonesty that characterizes the Sibyl. I have no desire for your offering and firmly declare my intention to steer clear of your innovations and associations.

**Comment by toyil** [comment]
Your project Sibyl is unethical and immoral. That is why I have no desire to deal with you in the future.

**Comment by A-Keyboard** [comment]
Create as many alts as you want, the program will not stop
