### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by catalyst002** [connext/community-sybil-reports#114]
# Related Addresses
0x5b236d19f680ff47e7bf2a9eb88fc5cc03d443a8
0x5b24724e1ce706ea7411131b642ad237dd72ae2c
0x5b265252bc30f74154c597fd045cbc98311ca577
0x5b26c872bcdab99afd6dcf073803640a930d142d
0x5b2740746db94d629f8c49af5fb4622a830e90d2
0x5b2a09732257eb100e6e9fce64e8f645dd53439f
0x5b2b45e503bc6e00c5479e50466d89577d6faba4
0x5b2be0acf25e6491e2358a56c168c17def656d80
0x5b2c1e57847fbc24402ae5c4d79877cf921f04d2
0x5b2d006f10c5a90a7282f999173235ea9ce79e1f
0x5b30e7bd5bd21354e3014bdae9b9fdbdc4ea79f4
0x5b31b0ee6cb1ddce48d1133641eee091c9da6154
0x5b31ee90cba8e2e55b99910266fadb43dd935afb
0x5b3287c72773e9f3d5472d9fc6c88a719ea07420
0x5b328bb20fbf15bbecc82298db269254c3fddb5d
0x5b33d36844c6dc8093b9e8a6a9b3893c59f36920
0x5b35999dd1e5bee0a9b2519308830ad5f9a47cee
0x5b36002e5ee1103a44246f67b067fd5509b97a9e
0x5b360f53220c54b3403867e4680ec2a73f244e33
0x5b3a9a05fec4434c6182246576a425c4472a3ec0
0x5b3ae21ec757ae1ed6e7379e982a372b052ab6a6
0x5b3b60889685005c1d1deb269112bc14179c04dc
0x5b3b7508eb1b33803fcaf623b7ff04d35deffc04
0x5b3d05c8719aba4dac42944a577bac7c8b97a02d
0x5b3ea1deffd61ff316d14770601b03ed070962a8
0x5b40c4ad0989f1f8b03ea2fd64ba953656f3f5a7
0x5b40ff938547de30f1bb7cfa79cdf8c2422645df
0x5b42ce17a8f582f261b10dcffa2d2e26fa3fbf4d
0x5b43af9a48c90ac6144b77dbfd6448b228ea7e2c
0x5b441f7ccf29ef51494008cbab224ffd45e153b2
0x5b443cd7739b4eb26b7db17f9ee556d75a069401
0x5b45002a412e15a06aade10f6f2af267c6e7de17
0x5b451d01675c9f81ad9bca73624535b9ba7528cf
0x5b46ca3587c45894bda6c9f2bf213a517a6e3558
0x5b481b65e277df1deccc2952c90f32014f5f777c
0x5b4be05814c7ccb9df725855e60b513138344d80
0x5b4e5f225f3e3c451ab14e535f68931a99dfeeb9
0x5b4f385e568a2bec87f3eb24b8fb3b97b2d87642
0x5b502e93a54e9911824df927287cf59fa886bed1
0x5b520fdeb2c661800af38e5c6e379038b6939aa7
0x5b557b10fbdac402b5fe04d46020ac0cd6335b4e
0x5b55b13f1f37a8acd6f051f353eda50dc68e9944
0x5b5614b9fffab7c751799eb12d5cb9165c8c40ad
0x5b56aca8cb6a26b7022977d459baf54a8ff6fe29
0x5b56d3e2bef58adfc11a4e91a8a01f4a12c01c33
0x5b56ede3410572b3257daf19d0e0fb31738fe86c
0x5b5720029e870fe2f246017b28a6d9ad68e69cac
0x5b573b9b0c24291b91a6dcbc88de2ec55ec6b740
0x5b598829fe39feec901fc48ec6c0697b1692e977
0x5b5b2bc80c42c70b1d14d0bd9dac7da270a58701
0x5b5b4182911dfe451247cbf9a57c8952c3f41ee0
0x5b5bcaa0066cc8a67d6bee664d149a966f73d3be
0x5b5bd55e73fcc28b978e4520aa55d9cf68fd1c91
0x5b5d6d2cd7ab7708b7cc8131902aa355070f45dc
0x5b5f35d3460c57f6aef8dedbf8974e010c94812e
0x5b607d28180f7260c6726048e909cb8f1a271ce0
0x5b627f46f9d350745f4b82a9d004e33d90662266
0x5b63eed8fd22cca74df0ebd84e07e85065b7fb3c
0x5b6585279d732594bf4848ef45d21f8dc608e540
0x5b6593d49384f906c6db7b5e39bf7864e0540f3b
0x5b674ec9133ff43137c24161c9e93d972e422c04
0x5b67e3d2c948ede416ca94048f285e67889fb2d7
0x5b6a25010a1740179efd8756bbabc8131d73a4cb
0x5b6b5d0cfbe56b81d76cd76d16f24c2845fe1a60
0x5b6c6fa53532772320b2924702e45e874f1663ec
0x5b6ec14f450f6f7c87d679b504f4f1e5dec86dda
0x5b6febf3a66220eaf3ab756aa99a07fc10343e3e
0x5b706777510b384fda85e16ad69d19eb4961a42a
0x5b708ba75ad5e08ac2822312016946a933a5b55c
0x5b71b2c51fbba24d7d59d8ab3a52ab047e897157
0x5b72a0d7b763904fb1658918bb147fe6fab1648f
0x5b741c08af7abbd794bfb65d73a546866aad704a
0x5b7534aab9293516fe8e32acc1e38b75fef69c35
0x5b75d6f4359a36a29b3b9a59e3f558f5b145f972
0x5b781bc29110cf3d36be0105e1134c2c7d48d91c
0x5b78c2f8db6c5bf921de7999482c27c7bae27862
0x5b78f06123ee99dc8b21d4e1ef51afe08059d5ec
0x5b79e3de3fae551714f260c8419938dfed0708a1
0x5b7a66cd9dfccf87ba304273838560b94cfcb057
0x5b7ab4b4b4768923cddef657084223528c807963
0x5b7b0293635b1b72c978beacf2343e066a1a4402
0x5b7cef050ee4b3ab8e0c157b574768aadc2fc029
0x5b7df4f55154e88adf963c89fcf20491763fd3ba
0x5b7e09fd51a3981ba55e3cc2383dde417405859d
0x5b7e6ce345e4e78e280ed3730fd969049e0d8af4
0x5b7f37ed7720944ea5f6a20a847405100f36884c
0x5b829d8efcdb00ab5adf83b944d2cdd2c19933b5
0x5b834bbe7d3d5ec1f0ddf41f3471be1fba16f64b
0x5b83ab13830eaaa0d3c272a486bdf4b0a34ffde1
0x5b8588c34448f18d36f65ddac9afdffac9c90d17
0x5b8687f15c3edba87551787e2c7f68931f8f9074

# Reasoning

Same transactions with same timings and amounts on wallets with same dates and no other activity except connext network. Using same cex to withdraw funds from the wallets. Wallets are controlled by the same person.
# Methodology
I used debank and etherscan to check wallets that was active in connext network.
Based on the same patterns these wallets were created in order to receive a drop and are controlled by the same person.

# Rewards Address

0x1f9090aae28b8a3dceadf281b0f12828e676c326

**Comment by ArjunBhuptani** [comment]
It's extraordinarily unlikely that sybils will have addresses starting with the same chars. 

I investigated your last report to make sure and, as expected, there was no relationship between the addresses. Marking this as spam and closing (as well as your other reports).
