### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by arcsin3x** [connext/community-sybil-reports#116]
# Related Addresses

0x79e68338Ddf980939995ec5b30Ab53465E041fa1
0x244e77233AdCD46Ac6a03d383244237321fd86e6
0x368F92655B92c9a8c4923575a85CD64Ae3e50E53
0xd9EDeb614dF54f8eE80a080051F55b9F4F582926
0x44A710632EbFBbC46f486753Fe5517aD01B8CBBF
0x9150fb4daA57AEC107128A9e1695778962A7a6C2
0x404BE1f0593cAbbd5Ff76Fb65D21bE59F8E43a0F
0xfF973FA9c57f6dDAA7c6c8979cF7E0913F049A62

# Reasoning

The following wallets have transactions with each other.The initial funding for these wallets comes from one of them.
Here are the transaction records of these wallets transferring funds to each other.

https://etherscan.io/tx/0xd55caf4c5bbddbc440868b70a591e53e5ef07f25cf2d7a72a96a0c2bcce12361
https://etherscan.io/tx/0x7f0645afe577d69a3c67d38ee812f1c01f4100046dd6f1cccb7a3a96d7b3f08e
https://etherscan.io/tx/0x4a4ef9c0c095ebb16e350211355146926bb8038cf3deadabe49afda80354b46a
https://etherscan.io/tx/0x80172e13ee316bd69d53cbe72d27d49e39dc225fa7b19d670baeb16374fa6aa9
https://etherscan.io/tx/0xbed99edd0944a57b1131b57567e59f3e991ae50051155672d43953d910169e50
https://etherscan.io/tx/0xabce1714932e45cdcc3eca3f0084047e76d179e686b07dd69ff4a1131d8d576d
https://etherscan.io/tx/0x9cceabc5c847b038552f5930219b9e089e733f1f07e38f1cb483f4e242600132
https://etherscan.io/tx/0x6dd6c1ee8e71ba16e53cd981321428f4deea1de8fda7a353faa1fdf30f2ad904
https://etherscan.io/tx/0xc655ccbe58750ddd1595d5457f94610821f27e31223baef3140917fefb5f123c

# Methodology

Explain the method used to discover the addresses and provide proof that they are all related and likely operated by a single individual/entity with a high degree of probability. The methodology should be easy to verify or the report will not be considered. Please, also include links to any additional materials you’d like to provide like a github repo containing the script used to uncover the reported addresses.

The reported addresses were discovered by checking irregularities in the number of bridge transactions made via Dune. The resulting addresses were analyzed to find repeating transfers at standard intervals and sequence.

https://dune.com/queries/0123456
https://github.com/airdrop-hunting

# Rewards Address

0xaAd28d1c5a578abDaFE51f289602275900f09B2b

**Comment by Grraarrgghh** [comment]
Less than 10 wallets; please add another sybil cluster to this report to be part of consideration

**Comment by arcsin3x** [comment]
> 

sorry，I had found this problem and closed this report，
