### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by neketskk** [connext/community-sybil-reports#12]
# Related Addresses

```
0xb18af22479f14f26487aa6354dad7d7cbcd527f1
0x470169600e08c6733cbafeeedef1352f4738b0c7
0xc5263403c4b068e0efafa3463e08e40f8ade391c
0xe6d36da02583c1acd79ffc7065f6d9bb1e8a6c30
0x3d4f2f2feb4963bdcc0cd48d6e2b57806c3f2ff3
0x00493ba4e1864acd75e2d76d7b6f4e6593615631
0x0715b21a1f43c80ce41dacb7e1ea89aa8fe3fc2a
0x1690c3435802ca8482f76ecfc32158b345057649
0x5df9576b0c6441f69809ca510685c01f09dba1e9
0xf0a9da8cc27830d4a7cc9da49a18655371653321
0x2c382dae1a94d689becf78edbeb1900c46f75ca2
0xc218e61c2f6ede9bfdb504f85bdf8802cbece31a
0x1ea05e66559c497b7d786a3f657baa5ba7fe0bc3
0x63ea96398ffcac3b4bede15de824468328e3bc45
0xcb8189bcf385867db54e72c390472d646a448003
0xec911027c5956c4b7e3b79b06c0d107b3a003f1f
0x53716f7ff7949e06afaeed5aa169ca31e53d7d46
0xaac2f9d9d26c7cdd9b8d2cca67a08323e525f641
0xdfe9e837a7bc21b0c928066e471e542ff75d3831
0xa2d8425a38fad12058519c0d334d89172ae42d2c
0x552f386a3c6fda19eb75acde84f013df69a7006e
0x71254be0af9f5522425c75a2dd1c0fc42162655f
0x0a26c375ee357dfb67441871ddec53f57ffe6d65
0x503d17563769a941f9c877966790c389053f79a1
0x1f27f86dbb71f47222ccb50f8a19ace82cdf29b4
0x9542495bbe11840eb64287f73ac78da61c837714
0xc2b1faa0a2615c6e315596dc6cbe3c1049c0aa0f
0x1d9d739004473c231cd08111bb5dd5e7c082dcd4
```
# Reasoning
**These 28 addresses were replenished from 1 account at the same time. May-28-2023 04:36:31,May-28-2023 04:36:18 AM,May-28-2023 04:36:01.... for the same amount of 7,000USD (USDT) from address
0x0161eb3be364eabbbcf5c8e59a3a989ab03e77d5.**
Example:
https://arbiscan.io/tx/0xeb93980cf506d3860c0474946fa34381148d8b8b4032ae1e9d37b1ad3f669b14
https://arbiscan.io/tx/0xb035880491afa1c6ee03f8b973ff2271847945b7aee00747b81e7625112d7012
https://arbiscan.io/tx/0x5cbd7bc4105ed4f87316534c282e3cf3e41af0b7ec32a6134b087953a95c0149
https://arbiscan.io/tx/0x55f4f854e8ae9f68b3ff82a188989e32661a34033e0049ce957203f5085d1942
https://arbiscan.io/tx/0x55f4f854e8ae9f68b3ff82a188989e32661a34033e0049ce957203f5085d1942
https://arbiscan.io/tx/0x599a034d5abb043d15e78a394cb87faa73ec96a9c0c946415a27f5e0c5790439
https://arbiscan.io/tx/0x5cc9ac637702e695197b202cb95d3652fc447d8fdfce325e91f3d9a1b8964dbe
**Also, after analyzing these addresses, it turned out that these accounts performed the same activities at the same time.And they also have approximately the same amount on the account.**
**Example:**
https://optimistic.etherscan.io/tx/0xc9b21e194e3eb994c53d8398449c2c7f19286ce006ecc511274c22240740a192
https://bscscan.com/tx/0x76146883f20142525199d9b20f946b1acd5d07991eefdeef4422e2c929dd433d
![image](https://github.com/connext/community-sybil-reports/assets/73196137/4516416c-7072-4cc5-9b45-2d3c17c73120)
![image](https://github.com/connext/community-sybil-reports/assets/73196137/04bdbb4f-4f60-4696-b805-d9cf5c1bf79c)
https://bscscan.com/tx/0x0942d0f707e5a061a2e0d19f8a577970f15af90055510051301771e66bb9b6fa
https://optimistic.etherscan.io/tx/0x73cd7f5dc1e8fee5f94f77a9ac33fe72da1021cea1de0791ea0d48f33f366310
**All accounts were created at the same time, we will deposit the same amount from one account on ethereum.**
**Example:**
https://etherscan.io/tx/0x6e5e28eb8e48810919a15ffcbbf202714122fee274cdd3b1fde4ad560a986964
https://etherscan.io/tx/0x279d9ad61ccb89af5fa849621ebc34f4680fe076e19deb90972032f2ce971be3
https://etherscan.io/tx/0x6bdc0a1e15291791cc3ddacebade52bd0a99ea8ff16125011cd6f2526613b5c8
https://etherscan.io/tx/0x5f85a4a2bc1a1b1b063e2d0bf8ce964e14bcbac464359eb8e569564e1aa89f2d
https://etherscan.io/tx/0x954dbf87d06e0cd2ef22b83d898653fbb20c71f73c95844e3f6c5f54955abb0c
  |   
Time 
  | 143   days 8 hrs ago (Apr-03-2023 01:33:11 PM +UTC) |   
  | 143   days 8 hrs ago (Apr-03-2023 01:33:23 PM +UTC) |  
  | 143   days 8 hrs ago (Apr-03-2023 01:33:35 PM +UTC) |    
  | 143   days 8 hrs ago (Apr-03-2023 01:33:47 PM +UTC) |  
  | 143   days 8 hrs ago (Apr-03-2023 01:33:59 PM +UTC) |   
Transfer 
| 0.05 Ether |  
From 
| 0x0161eb3bE364eaBBbcf5C8E59A3A989AB03E77d5 | 
# Methodology

**After analyzing the dune, a bunch of accounts with the same scores were found https://dune.com/KARTOD/connext-bridge-activity-and-top-30percent-depositors. After that, I switched to one of the accounts and found patterns using Debank 
( https ://debank.com/profile/0x470169600e08c6733cbafeeedef1352f4738b0c7/history ) and found the main SYBIL account ( https://debank.com/profile/0x0161eb3be364eabbbcf5c8e59a3a989ab03e77d5 ). Basically, I watched how the accounts were replenished, their procedure, transaction amounts and time.
these accounts were created at the same time by a deposit transaction on Ethereum.**

**Visual example using the arkham platform**

https://platform.arkhamintelligence.com/visualizer/entity/0xB18Af22479F14F26487Aa6354dAD7D7CBcd527F1,0x470169600E08c6733cBAfeeEdeF1352f4738B0C7,0xc5263403C4B068e0efaFa3463e08e40F8aDe391C,0xE6d36Da02583C1acD79FFC7065f6d9BB1e8a6C30,0x3d4f2F2feb4963BdCC0cd48d6e2B57806c3F2ff3,0x00493ba4E1864aCd75e2d76D7B6F4E6593615631,0x0715B21A1f43C80CE41daCb7E1Ea89Aa8fe3FC2A,0x1690C3435802CA8482F76ecFc32158b345057649,0x5dF9576b0C6441F69809Ca510685C01F09DbA1e9,0xF0a9dA8cc27830D4a7Cc9Da49a18655371653321,0x0161eb3bE364eaBBbcf5C8E59A3A989AB03E77d5?flow=all&positions=%7B%220x470169600E08c6733cBAfeeEdeF1352f4738B0C7%22%3A%7B%22fx%22%3A0%2C%22fy%22%3A30%7D%2C%220xc5263403C4B068e0efaFa3463e08e40F8aDe391C%22%3A%7B%22fx%22%3A58%2C%22fy%22%3A35%7D%2C%220xB18Af22479F14F26487Aa6354dAD7D7CBcd527F1%22%3A%7B%22fx%22%3A18%2C%22fy%22%3A32%7D%2C%220x0161eb3bE364eaBBbcf5C8E59A3A989AB03E77d5%22%3A%7B%22fx%22%3A21%2C%22fy%22%3A-54%7D%2C%220x00493ba4E1864aCd75e2d76D7B6F4E6593615631%22%3A%7B%22fx%22%3A37%2C%22fy%22%3A33%7D%2C%220x0715B21A1f43C80CE41daCb7E1Ea89Aa8fe3FC2A%22%3A%7B%22fx%22%3A-3%2C%22fy%22%3A96%7D%2C%220xE6d36Da02583C1acD79FFC7065f6d9BB1e8a6C30%22%3A%7B%22fx%22%3A-28%2C%22fy%22%3A96%7D%2C%220x3d4f2F2feb4963BdCC0cd48d6e2B57806c3F2ff3%22%3A%7B%22fx%22%3A-21%2C%22fy%22%3A27%7D%2C%220x5dF9576b0C6441F69809Ca510685C01F09DbA1e9%22%3A%7B%22fx%22%3A38%2C%22fy%22%3A93%7D%2C%220xF0a9dA8cc27830D4a7Cc9Da49a18655371653321%22%3A%7B%22fx%22%3A14%2C%22fy%22%3A95%7D%2C%220x1690C3435802CA8482F76ecFc32158b345057649%22%3A%7B%22fx%22%3A65%2C%22fy%22%3A94%7D%2C%22connext%22%3A%7B%22fx%22%3A17%2C%22fy%22%3A63%7D%2C%22stargate%22%3A%7B%22fx%22%3A67%2C%22fy%22%3A63%7D%2C%22the-t-resolver%22%3A%7B%22fx%22%3A102%2C%22fy%22%3A63%7D%7D&sortDir=desc&sortKey=time&usdGte=0.1

# Rewards Address

0x482cD4246886A0D50bd04FF288cb20f53D291255

**Comment by neketskk** [comment]
[Report №2](https://github.com/connext/community-sybil-reports/issues/56)

**Comment by preethamr** [comment]
VALID REPORT. Passed these checks:

1. Most addresses were first seen in this report.
2. >10 addresses are in the allocations.csv
3. Sybil-like activity found:



https://platform.arkhamintelligence.com/visualizer/entity/0xB18Af22479F14F26487Aa6354dAD7D7CBcd527F1,0x470169600E08c6733cBAfeeEdeF1352f4738B0C7,0xc5263403C4B068e0efaFa3463e08e40F8aDe391C,0xE6d36Da02583C1acD79FFC7065f6d9BB1e8a6C30,0x3d4f2F2feb4963BdCC0cd48d6e2B57806c3F2ff3,0x00493ba4E1864aCd75e2d76D7B6F4E6593615631,0x0715B21A1f43C80CE41daCb7E1Ea89Aa8fe3FC2A,0x1690C3435802CA8482F76ecFc32158b345057649,0x5dF9576b0C6441F69809Ca510685C01F09DbA1e9,0xF0a9dA8cc27830D4a7Cc9Da49a18655371653321,0x2C382DAe1a94D689BEcf78eDBEB1900C46f75ca2,0xC218E61C2f6EDe9bfdb504f85BDf8802CBEce31A,0x1eA05E66559c497b7d786a3F657BaA5ba7FE0Bc3,0x63ea96398ffCaC3b4BEdE15DE824468328E3BC45,0xCB8189bcF385867Db54E72c390472D646A448003,0xec911027C5956C4B7e3b79B06c0D107b3a003F1F,0x53716f7fF7949e06AfaEED5aA169cA31E53d7d46,0xaac2F9d9D26c7CDD9b8d2cca67a08323E525F641,0xDfE9e837A7BC21b0c928066e471E542fF75d3831,0xA2D8425A38fAD12058519c0d334d89172AE42D2c,0x552F386a3C6fda19eB75AcdE84f013dF69a7006e,0x71254Be0AF9f5522425C75A2dD1C0fC42162655F,0x0A26c375EE357dfB67441871dDec53f57FFE6d65,0x503d17563769a941f9c877966790C389053F79A1,0x1f27F86dBB71F47222ccb50F8A19acE82cDf29b4,0x9542495bBE11840eB64287f73aC78DA61C837714,0xC2B1FAA0a2615C6e315596dc6CbE3c1049C0aA0F,0x1d9D739004473c231cd08111bB5dd5E7c082dCd4?flow=all&positions=%7B%7D&sortDir=desc&sortKey=time&usdGte=0.1

**Comment by ArjunBhuptani** [comment]
Valid report. All addresses are clearly linked to the root 0x016 address.
