### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by Ytra10** [connext/community-sybil-reports#120]
ALL THOSE ADDRESSES ARE SYBILS

0x02e760ca0eb9e2b25b175e236dd75ed97c22968b
0x02e9782c01825ed6780e9a7aed02de598783bbb5
0x02ead9f4ea5a2d46c8fa193486aadc3f51598232
0x02ec0f10d10e16edacd7705491f5f60540fe5318
0x02ed7d45040fc9b930040e30a2cdbc796792035b
0x02eda1f851cd6112362a8cbbd39fd07cf390c5ae
0x02ee000fcffd268add482dd9fc560cdd3343ff9e
0x02f02c0a48a65930faef5f7250b8a79169efc1f9
0x02f077064e807240e1f3808e9ce912b6027dfcf4
0x02f223f50f8fb46f2a60ef3f04a396ba141f736d
0x02f28cd2b38f2476274d8cbb774f177e008d4afb
0x02f2df020aea51137f815e865c5adb2e23b2a21f
0x02f2e4ce9f05489d379afe6c91c2a929ab5a9d28
0x02f46d34de2f52bbe4d5f7cbcbfc1a8b91e66cc3
0x02f73b8e29dd6ec38bc5d8b3826051dc562c3060
0x02f86a8783152f5f048afc57b5a2afb5529ee745
0x02f8a8a0ff36cd0eb55f00120a50101441b598c8
0x02f935f324bfd547ce8c062f02e02c0599c5cc5e
0x02f9c6044b4eb4e3fe8a2204161221ae0d0a912c
0x02fa4e471e58917924543a9641aab1cce48c26ee
0x02fa51fa818203ac01f4d856a3579fd49e295c85
0x02fafec4c577431e5229f01df088cb699a7cc691
0x02ff537c4e2995d7ce0be764fea5b9fa5d782cf5
0x02ffb9b4bbc29f9a59b20c541d369c5add62a5a3
0x03010715fe21f4c1fd254607ffcabb3c708cc903
0x0301a4dc3ee5ba8463620b7f518e3445173d4f7c
0x03024d89d4e00e091686ac8d133a0a62db348cac
0x03062af6c98f5e2b8708c181142b909fe59260d5
0x0306cdffe3531e597b83b048658c1aca4a84256b
0x03072273f14392d147899f6faebe4bd0ebfa21f6
0x030a70190a94bc7a02d358088931fde036e6d359
0x030ac75f57c3c809f3de82104795784a33cc8395
0x030b525068614681e2cbf5010cb4b2651007f938
0x030c0ccdfd51a18ae3f89966956de16b3ff24776
0x030d40a52eee98f6e349498c5499347422bad754
0x030d7d09fc84f0958be657a5821eadd3a6c9fc95
0x030dff1946806b8d36db64826401db94faa673aa
0x030e3e488576b8fbef29f84fcc25088b9ceb7dfa
0x03104c9661f97a1a882a797964f46d968d518126
0x0310a29c841e8cd7205e1526d4f34e4f2e35024f
0x0311447b23e00e0aed6d393213b010838185f846
0x03128048d3e41605ae2d63b3dbdbda5d73e8fe3b
0x031310abd63c22a8d6daa122b00249100503aeef
0x031330daa7705217d0033d22c939b78888929971
0x03148e5d55d5a2382c644e78910d13cdb7218235
0x03152262082daa63a2a32236efd486f47c6bc9ec
0x0315963aefa1d5c1999872ef53959e2a5c517885
0x0315ff6e6435bdb59b9291f25f37bbfd0506ed73
0x031856e656f04560b5e1415e7771131b4f4d573b
0x0318d38dcb790e4014935d708874833560bb0d40
0x03192570cbc1f2f73e84047f057a93ae31884913
0x031a6e2e396b5ab7ef3fc7a647d34c56bb1a91ff
0x031b80626f474613fb4b6a59d13785efff091d5b
0x031f7995cfb04e844d1318d2cc56e71cbbade358
0x0321e89a7b9484f47e8ccd4daf97ee8066783c04
0x03224d605304480ccd541ad37f602ae6ef72108c
0x03235e7feb5739b53fa42f9d5206c8861762f27a
0x03240ba9b0bd26a3aead2dc5e3c09c838d010467
0x03255aa885e10fcfa835ede1dba31e7aee17773a
0x03269a02129b54790ff3e19e059afb0d265e1bbc
0x0326d0ac7ca9ef19c9c2d5474f6264a0149a5e87
0x0327081bfda9d0d7ab8416155f51ac16869e0b36
0x03274cb7e051fe86146a53ccbd765505d1844b9c
0x0327b212cffe5b80fa2f54fd4be9a56d734dc36b
0x0327d880665d0a65bc578a82e9d83f21b993756c
0x0327e3cbfc775d0da583d7b84b43fd0dbe5db98a
0x0328472a6e5d49b0a0c4f77acf2ecb1990408a88
0x032865e6e27e90f465968ffc635900a4f7ceeb84
0x03297b2112263b1aeb2c964081f3463259334b00
0x03297d4858cb442059e53c4c12cceb98ca30f8e6
0x032cbb52dcbe38efe3c6eafb44401c715bde3401
0x032ea9a532703f8c1a84aecda184a76ea5daf5e6
0x03300279d711b8deb1353dd9719eff81ea1b6bed
0x033038855d5c7bbc01e46db73c587b901bbf8741
0x03307205b67b112007361a34bd97ecbfe849efae
0x0331debc490c5540ef4773da5b9df146aa2d58c3
0x0332ee53e7299f913229a2585dfb7867b2518a0f
0x0333f6c7b94c154f8c3d8f89cc34523103aab704
0x033486cf526f0548fbae195b5af979dab8043734
0x0334a52a59e972403af61dedc6b7d087c5b85bf3
0x0334e081f088642f7628030bc6b28289495c5400
0x033547a797eb8430a071d58d87fb17650f268c09
0x033711ab64fa1cdeaeecd5e899a4963399a4390a
0x03399f9e628b5d1f41794bc2e24c2ddbd73f43d6
0x0339cef12a92ecfb9700d051400abfa6ee585c97
0x033a876783d4a68db84e357791b531b01191fce2
0x033c6728ce67510feae338bb1d2ced699a6a27a4
0x033d815f4fb30b2459a396e004c5a7ecfe30ec39
0x033f68fd9df6bac726e6651e95ac399dbca3dc58
0x033fc3eaac0173d00b4f80d67f29429b0285d50a
0x0340ead03ae07ab1c50731af5a4279ccf266e91d
0x03440bbf84f54da54e6c0a48a415d907c3906e23
0x03485453f0b0511dd6bd4173ad05093b1e0313de
0x034908f882843c22b7a7f22715dcbe9fec9c0fa9
0x03494e1e442c42ad4a67f22829b60d262858e84d
0x034db39ea329a0d3aa8a20fe973e2481fde8a394
0x034e48a1faae44e0600e9d03df331f550086dd19
0x034f43c4e5e2250cd9e35df66bb1cac52f3d192e
0x034fa3814782ff1d2994bf5587a25ac4c0dc82c0
0x035142fe02eaa95cff06ca4c0ad4d58b28b98ce2
0x0351b0b81fdd1db5dad0617d97c598cd3c37baaf
0x0352510add4fd4072d2aa76fbd9126c31c781900
0x035312d384efaef0fb1e4f44d5d57b389d3ddbc6
0x035396e1056d3619e68afe12da621ee7dd258097
0x035495b687850f79cb1652f416ea7ec19907557c
0x0355786221c9c34935c61ecae9a68c8c044c0161
0x035648071a7ebb842fc55a01e44ce01ab8b844ed
0x035719f46ff6a671a1101fca5d9fc9c7dce44d42
0x03571b2baf2f3b763fc4b47bd6138dfe04f17e74
0x0357c25786374544801a2e741a5abd33b2a7a3e9
0x0358764500c707882c9035c4ea3a8d127d39ea75
0x035abaa006448d4025712c9f5fa9bdf83ab652b6
0x035ac045ab35ceb520af9f794077644e041b5cbc
0x035c89aad2417fdea50a7c280fbe7ad6d87e1a93
0x035d12de312e06d8bf30e8200ad90a80d153888e
0x035d5e9aef9c24c42764a90b1ef6207d22fda0e7
0x035d7ab350ed549c22a0bcd24412f39391144f41
0x035dd9460f0d804f5e927883174553d874082801
0x035e8a0a57f24fd10d447c6ce44524513dd6e09c
0x035eb970b4c364c0e1f0c56fdc601fc75df433b6
0x035ebd096afa6b98372494c7f08f3402324117d3
0x03610e7b922ed126eb2c63c5b532e93d893aeacc
0x0362630a31ebc56d06db4606efb19f26f9703a66
0x03630b8ed7d32abbaf1b9c99459c02826d0f1d42
0x0363b1bc04365087ef6e1360e35872b60187a013
0x0364b3ee7f6f426fd173eeea159f998a87c0d351
0x03652b73bee719a69544d3e8b4c0f856658dbbaa
0x036594cd34728e809cf84b279fe7ca41bb184d53
0x0365abb7e79beccb71dee16cb8a04645d370dad8
0x02e760ca0eb9e2b25b175e236dd75ed97c22968b
0x02e9782c01825ed6780e9a7aed02de598783bbb5
0x02ead9f4ea5a2d46c8fa193486aadc3f51598232
0x02ec0f10d10e16edacd7705491f5f60540fe5318
0x02ed7d45040fc9b930040e30a2cdbc796792035b
0x02eda1f851cd6112362a8cbbd39fd07cf390c5ae
0x02ee000fcffd268add482dd9fc560cdd3343ff9e
0x02f02c0a48a65930faef5f7250b8a79169efc1f9
0x02f077064e807240e1f3808e9ce912b6027dfcf4
0x02f223f50f8fb46f2a60ef3f04a396ba141f736d
0x02f28cd2b38f2476274d8cbb774f177e008d4afb
0x02f2df020aea51137f815e865c5adb2e23b2a21f
0x02f2e4ce9f05489d379afe6c91c2a929ab5a9d28
0x02f46d34de2f52bbe4d5f7cbcbfc1a8b91e66cc3
0x02f73b8e29dd6ec38bc5d8b3826051dc562c3060
0x02f86a8783152f5f048afc57b5a2afb5529ee745
0x02f8a8a0ff36cd0eb55f00120a50101441b598c8
0x02f935f324bfd547ce8c062f02e02c0599c5cc5e
0x02f9c6044b4eb4e3fe8a2204161221ae0d0a912c
0x02fa4e471e58917924543a9641aab1cce48c26ee
0x02fa51fa818203ac01f4d856a3579fd49e295c85
0x02fafec4c577431e5229f01df088cb699a7cc691
0x02ff537c4e2995d7ce0be764fea5b9fa5d782cf5
0x02ffb9b4bbc29f9a59b20c541d369c5add62a5a3
0x03010715fe21f4c1fd254607ffcabb3c708cc903
0x0301a4dc3ee5ba8463620b7f518e3445173d4f7c
0x03024d89d4e00e091686ac8d133a0a62db348cac
0x03062af6c98f5e2b8708c181142b909fe59260d5
0x0306cdffe3531e597b83b048658c1aca4a84256b
0x03072273f14392d147899f6faebe4bd0ebfa21f6
0x030a70190a94bc7a02d358088931fde036e6d359
0x030ac75f57c3c809f3de82104795784a33cc8395
0x030b525068614681e2cbf5010cb4b2651007f938
0x030c0ccdfd51a18ae3f89966956de16b3ff24776
0x030d40a52eee98f6e349498c5499347422bad754
0x030d7d09fc84f0958be657a5821eadd3a6c9fc95
0x030dff1946806b8d36db64826401db94faa673aa
0x030e3e488576b8fbef29f84fcc25088b9ceb7dfa
0x03104c9661f97a1a882a797964f46d968d518126
0x0310a29c841e8cd7205e1526d4f34e4f2e35024f
0x0311447b23e00e0aed6d393213b010838185f846
0x03128048d3e41605ae2d63b3dbdbda5d73e8fe3b
0x031310abd63c22a8d6daa122b00249100503aeef
0x031330daa7705217d0033d22c939b78888929971
0x03148e5d55d5a2382c644e78910d13cdb7218235
0x03152262082daa63a2a32236efd486f47c6bc9ec
0x0315963aefa1d5c1999872ef53959e2a5c517885
0x0315ff6e6435bdb59b9291f25f37bbfd0506ed73
0x031856e656f04560b5e1415e7771131b4f4d573b
0x0318d38dcb790e4014935d708874833560bb0d40
0x03192570cbc1f2f73e84047f057a93ae31884913
0x031a6e2e396b5ab7ef3fc7a647d34c56bb1a91ff
0x031b80626f474613fb4b6a59d13785efff091d5b
0x031f7995cfb04e844d1318d2cc56e71cbbade358
0x0321e89a7b9484f47e8ccd4daf97ee8066783c04
0x03224d605304480ccd541ad37f602ae6ef72108c
0x03235e7feb5739b53fa42f9d5206c8861762f27a
0x03240ba9b0bd26a3aead2dc5e3c09c838d010467
0x03255aa885e10fcfa835ede1dba31e7aee17773a
0x03269a02129b54790ff3e19e059afb0d265e1bbc
0x0326d0ac7ca9ef19c9c2d5474f6264a0149a5e87
0x0327081bfda9d0d7ab8416155f51ac16869e0b36
0x03274cb7e051fe86146a53ccbd765505d1844b9c
0x0327b212cffe5b80fa2f54fd4be9a56d734dc36b
0x0327d880665d0a65bc578a82e9d83f21b993756c
0x0327e3cbfc775d0da583d7b84b43fd0dbe5db98a
0x0328472a6e5d49b0a0c4f77acf2ecb1990408a88
0x032865e6e27e90f465968ffc635900a4f7ceeb84
0x03297b2112263b1aeb2c964081f3463259334b00
0x03297d4858cb442059e53c4c12cceb98ca30f8e6
0x032cbb52dcbe38efe3c6eafb44401c715bde3401
0x032ea9a532703f8c1a84aecda184a76ea5daf5e6
0x03300279d711b8deb1353dd9719eff81ea1b6bed
0x033038855d5c7bbc01e46db73c587b901bbf8741
0x03307205b67b112007361a34bd97ecbfe849efae
0x0331debc490c5540ef4773da5b9df146aa2d58c3
0x0332ee53e7299f913229a2585dfb7867b2518a0f
0x0333f6c7b94c154f8c3d8f89cc34523103aab704
0x033486cf526f0548fbae195b5af979dab8043734
0x0334a52a59e972403af61dedc6b7d087c5b85bf3
0x0334e081f088642f7628030bc6b28289495c5400
0x033547a797eb8430a071d58d87fb17650f268c09
0x033711ab64fa1cdeaeecd5e899a4963399a4390a
0x03399f9e628b5d1f41794bc2e24c2ddbd73f43d6
0x0339cef12a92ecfb9700d051400abfa6ee585c97
0x033a876783d4a68db84e357791b531b01191fce2
0x033c6728ce67510feae338bb1d2ced699a6a27a4
0x033d815f4fb30b2459a396e004c5a7ecfe30ec39
0x033f68fd9df6bac726e6651e95ac399dbca3dc58
0x033fc3eaac0173d00b4f80d67f29429b0285d50a
0x0340ead03ae07ab1c50731af5a4279ccf266e91d
0x03440bbf84f54da54e6c0a48a415d907c3906e23
0x03485453f0b0511dd6bd4173ad05093b1e0313de
0x034908f882843c22b7a7f22715dcbe9fec9c0fa9
0x03494e1e442c42ad4a67f22829b60d262858e84d
0x034db39ea329a0d3aa8a20fe973e2481fde8a394
0x034e48a1faae44e0600e9d03df331f550086dd19
0x034f43c4e5e2250cd9e35df66bb1cac52f3d192e
0x034fa3814782ff1d2994bf5587a25ac4c0dc82c0
0x035142fe02eaa95cff06ca4c0ad4d58b28b98ce2
0x0351b0b81fdd1db5dad0617d97c598cd3c37baaf
0x0352510add4fd4072d2aa76fbd9126c31c781900
0x035312d384efaef0fb1e4f44d5d57b389d3ddbc6
0x035396e1056d3619e68afe12da621ee7dd258097
0x035495b687850f79cb1652f416ea7ec19907557c
0x0355786221c9c34935c61ecae9a68c8c044c0161
0x035648071a7ebb842fc55a01e44ce01ab8b844ed
0x035719f46ff6a671a1101fca5d9fc9c7dce44d42
0x03571b2baf2f3b763fc4b47bd6138dfe04f17e74
0x0357c25786374544801a2e741a5abd33b2a7a3e9
0x0358764500c707882c9035c4ea3a8d127d39ea75
0x035abaa006448d4025712c9f5fa9bdf83ab652b6
0x035ac045ab35ceb520af9f794077644e041b5cbc
0x035c89aad2417fdea50a7c280fbe7ad6d87e1a93
0x035d12de312e06d8bf30e8200ad90a80d153888e
0x035d5e9aef9c24c42764a90b1ef6207d22fda0e7
0x035d7ab350ed549c22a0bcd24412f39391144f41
0x035dd9460f0d804f5e927883174553d874082801
0x035e8a0a57f24fd10d447c6ce44524513dd6e09c
0x035eb970b4c364c0e1f0c56fdc601fc75df433b6
0x035ebd096afa6b98372494c7f08f3402324117d3
0x03610e7b922ed126eb2c63c5b532e93d893aeacc
0x0362630a31ebc56d06db4606efb19f26f9703a66
0x03630b8ed7d32abbaf1b9c99459c02826d0f1d42
0x0363b1bc04365087ef6e1360e35872b60187a013
0x0364b3ee7f6f426fd173eeea159f998a87c0d351
0x03652b73bee719a69544d3e8b4c0f856658dbbaa
0x036594cd34728e809cf84b279fe7ca41bb184d53
0x0365abb7e79beccb71dee16cb8a04645d370dad8
```
-->

On February 14th between 7:20 pm UTC and 7:35 pm UTC in the same sequence, the accounts added liquidity to the pool on Arbitrum One. At the next day on February 15th between 2:43 pm UTC and 3:25 pm UTC, the accounts removed all liquidity from the pool in equal parts and then transfered all the money from the accounts to the parent adress 0x0364b3ee7f6f426fd173eeea159f998a87c0d351

Then the parent adress 0x0362630a31ebc56d06db4606efb19f26f9703a66 on February 15th 15:37 pm UTC sent 1100 nextUSDC on Arbitrum one chain to 0x035eb970b4c364c0e1f0c56fdc601fc75df433b6 .
00x035eb970b4c364c0e1f0c56fdc601fc75df433b6 added 1100 nextUSDC to the next pool on Arbitrum one. On March 10th between 10:00 pm UTC and 10:03 pm UTC removed all liquidity from the pool, swapped 510.6678 nextUSDC to 510.8353 USDC(Bridged) and sent them to the parent account 0x9bee3465119d4091421eefeedc66742dede98c1c.
On March 16th between 5:01 pm UTC and 5:03 pm UTC parent account 0x9bee3465119d4091421eefeedc66742dede98c1c transfered 1205.1459 USDC(Bridged) and 0.003 eth on Arbitrum one chain to the 0x03485453f0b0511dd6bd4173ad05093b1e0313de. in the same window 0xeb13593a73a5608c9fa7e4422a3126c33e3522a4 added 1205.1459 USDC to the connext pool. On May 14th between 5:44 pm UTC and 5:46 pm UTC removed all liquidity from the pool (1204.974 USDC(Bridged) and sent 1204.974 USDC(Bridged) to the parent adress 0x03485453f0b0511dd6bd4173ad05093b1e0313de.
On May 23rd between 12:02 am UTC and 12:55 am UTC received 0.004 eth and 4000 usdt on Arbitrum one from parent adress 0x03485453f0b0511dd6bd4173ad05093b1e0313de and added 4000 usdt to the connext usdt pool


MY WALLET FOR REWARDS 
0x0365abb7e79beccb71dee16cb8a04645d370dad8

**Comment by nigolov** [comment]
copypaste

**Comment by YFalse** [comment]
@Grraarrgghh copypaste from #58
