### ISSUE TITLE
ЛУЧШИЙ ТГ ПАБЛИК В СНГ  - AIRDROP ЖДУН

### ISSUE THREAD

**Issue by kukushkinace1** [connext/community-sybil-reports#137]
https://t.me/AIRDROP_Zhdun 
https://t.me/AIRDROP_Zhdun
https://t.me/AIRDROP_Zhdun
https://t.me/AIRDROP_Zhdun
https://t.me/AIRDROP_Zhdun
https://t.me/AIRDROP_Zhdun
https://t.me/AIRDROP_Zhdun

**Comment by ArjunBhuptani** [comment]
Never gonna let you down
