### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by linhhacak** [connext/community-sybil-reports#138]
# Related Addresses

0xcdc8ba9815c76e838a759e932f57bf6f990a6e71
0x8f3b0058d12b7b30edf4e51b89133198406f4dd6
0xb3875eb64faf2881e3abc48e5a96bb66ffe6f100
0xb1ade58c1e818a6534e3583873e70e325a00e00d
0xcc38b8c0da47a7cc315bfa5d96246843ed7f6d12
0x023f4115e3a625c0806f891439186df6cbcc7660
0x52b9f71371f7b8e56e975366cb4b5202a4d1a7a3
0x73882a4b07196db8054e37068ed728611555b0bd
0xf5a732928a14f9475c7e29ea1d48cf802dfff383
0x69220d543effba00beaa47a5cea8729fb7f090f4
0xa48224743bd5f8027ded6990e226e124034e2855
0x3c8714e3ca4f206fbec3920b6f09cf3fb6ba9244
0x614d98a57a5d879d717152de0690ed2b04562ade
# Reasoning

Above addresses received dai and usdt from one master account 0x614d98a57a5d879d717152de0690ed2b04562ade to farm liquid nft campaign and removed and sent to 0x614d98a57a5d879d717152de0690ed2b04562ade when event ends
Checked on Arbitrum network

# Methodology
https://arbiscan.io/tx/0x1451255dcf8982c25f59571a58fb6dbb2527164861cd4b831dfacc84fb7a23af sent dai to sub address to farm liquid nft campaign
https://arbiscan.io/tx/0x5c13b8615db23218119ae300c7e0ed4a8a920d870b1c4bae8c6ac75376b8bcce sent usdt to sub address to farm liquid nft campaign

https://arbiscan.io/tokentxns?a=0x614d98a57a5d879d717152de0690ed2b04562ade&p=2 received usdt and dai from sub accounts after removed liquidity
# Rewards Address

0x973B91699ad3f9368371A482dbD3E9eCE3191212

**Comment by corrick1** [comment]
@Grraarrgghh 
Additional evidence found. My report is #454, sorry for spamming my report number and marking.

### Related Addresses

0xcdc8ba9815c76e838a759e932f57bf6f990a6e71
0xb3875eb64faf2881e3abc48e5a96bb66ffe6f100
0x8f3b0058d12b7b30edf4e51b89133198406f4dd6
0xb1ade58c1e818a6534e3583873e70e325a00e00d
0xcc38b8c0da47a7cc315bfa5d96246843ed7f6d12
0x023f4115e3a625c0806f891439186df6cbcc7660
0x52b9f71371f7b8e56e975366cb4b5202a4d1a7a3
0x73882a4b07196db8054e37068ed728611555b0bd
0xf5a732928a14f9475c7e29ea1d48cf802dfff383
0xcc0e514543251877334f59d65778e1e84dc10dbb
0x69220d543effba00beaa47a5cea8729fb7f090f4
0xa48224743bd5f8027ded6990e226e124034e2855
0x3c8714e3ca4f206fbec3920b6f09cf3fb6ba9244

An address that hasn't been found: 
0xcc0e514543251877334f59d65778e1e84dc10dbb

### Methodology
Used [Debank](https://debank.com/profile/) and [Scan](https://arbiscan.io/) service.
On all the above wallets, the transactions and times are identical. I sent only a small part of screenshots, but I checked all addresses. 
![#1](https://github.com/connext/community-sybil-reports/assets/108121531/582425d4-e47e-4ac1-9ce0-d3b153edcc5d)
![#2](https://github.com/connext/community-sybil-reports/assets/108121531/1931ed6b-a6e8-4e1a-9c21-fa52324b0ff2)
![#3](https://github.com/connext/community-sybil-reports/assets/108121531/31843613-20c9-4eb9-9dcc-f6cddc29d203)

All of these wallets belong to the whale https://debank.com/profile/0x614d98a57a5d879d717152de0690ed2b04562ade/follower?start=1700 
who can also get the drop.
![#4](https://github.com/connext/community-sybil-reports/assets/108121531/669aec32-c635-4b8b-a69a-2766ac3c280f)

### My wallet
0x34BAff9e28533Ff655ba946137c671367D935dFa

**Comment by linhhacak** [comment]
@corrick1 is trying spam comment on other issues,cc @ArjunBhuptani


I reported these above addresses of sybil earlier, don't try to spam to get a reward @corrick1 
I can explain more about above addresses without you

**Comment by linhhacak** [comment]
On May-19-2023 7pm utc, master address 0x614d98a57a5d879d717152de0690ed2b04562ade sent Dai to 0x52b9f71371f7b8e56e975366cb4b5202a4d1a7a3, Then 0x52b9f71371f7b8e56e975366cb4b5202a4d1a7a3 sent Dai to other addresses on above list(on May-19-2023 07pm utc,same time to all above addresses,Check on https://arbiscan.io/token/0xda10009cbd5d07dd0cecc66161fc93d7c9000da1?a=0x52b9f71371f7b8e56e975366cb4b5202a4d1a7a3)
Then these addresses spent Dai to connext lp to farm lp campaign 2 on May-19-2023 07pm utc,same time on all addresses 
and removed lp same time on Jun-16-2023 10am utc, same time on all addresses.
example:
add lp same time
https://arbiscan.io/tx/0x27daa14d5fb5fe48edcf1ea9152e615c54af22902d237a36d89fe7ab5c5c2092
https://arbiscan.io/tx/0xcf9b5d843e65b26abf6bca86bc66f01e93206770c522bf67d5a17e82b0827a9b
https://arbiscan.io/tx/0x3e982a10c37e6b56f121d31fd70c740f105409ad025723c38264d2adadc187e7
remove lp same time
https://arbiscan.io/tx/0x61a7177c7c8ecf2a29db1438f22ec8899557c5a6c14c64c17ca0e32ea13ca6fe
https://arbiscan.io/tx/0xaa53025a4c24b916d46e4c94c3e6b5199abd322a078666ed936d5fd99177cad8
https://arbiscan.io/tx/0x27123bbdb251d422a496d1bf146dd4a534fee98f935167549af42fffac7b566b




On May-19-2023 07pm utc  master address 0x614d98a57a5d879d717152de0690ed2b04562ade to 0xcdc8ba9815c76e838a759e932f57bf6f990a6e71 . Then 0xcdc8ba9815c76e838a759e932f57bf6f990a6e71 sent usdt  to other addresses on above list on above list(on May-19-2023 07pm utc same time to all above addresses,Check on https://arbiscan.io/token/0xfd086bc7cd5c481dcc9c85ebe478a1c0b69fcbb9?a=0xcdc8ba9815c76e838a759e932f57bf6f990a6e71) 
Then these addresses add USDT lp on lp campaign and remove lp same time
example:
add lp:
https://arbiscan.io/tx/0xc546d2e0522cddceba595ecca28cce558858f49c2cb3027b777bf4ab40b24c16
https://arbiscan.io/tx/0x83bbc14ffea5fceb025e462fb1e5429d6b29e3fddcf70c362c85dcd65a399a44
https://arbiscan.io/tx/0xb0c83224d466f48135f9705ad00a5fdf0d6b283e7c014b8b01ededa983621f11
remove lp:
https://arbiscan.io/tx/0x5d5b87537c304d9fa449b07d970a31ab99da0efec20219dd31d941b86e23451d
https://arbiscan.io/tx/0x65dac32ea1cd3e5f430646d7bd93d9a796d1267fbc635710d71d40527ae6d8fb
https://arbiscan.io/tx/0x5d5b87537c304d9fa449b07d970a31ab99da0efec20219dd31d941b86e23451d



After removed lp,all above sybil addresses sent their Dai and usdt to master account 0x614d98a57a5d879d717152de0690ed2b04562ade on Jun-16-2023 10am utc. Same time on all above addresses. Check:
https://arbiscan.io/tokentxns?a=0x614d98a57a5d879d717152de0690ed2b04562ade&p=1
https://arbiscan.io/tokentxns?a=0x614d98a57a5d879d717152de0690ed2b04562ade&p=2

**Comment by corrick1** [comment]
> @corrick1 is trying spam comment on other issues,cc @ArjunBhuptani
> 
> I reported these above addresses of sybil earlier, don't try to spam to get a reward @corrick1 I can explain more about above addresses without you

I'm not spamming. Many users have not added, new proofs for 2 days now. So I decided to add them myself. You can take my comment and use it in your report, and I will delete the comment.

**Comment by ArjunBhuptani** [comment]
Valid report

https://platform.arkhamintelligence.com/visualizer/entity/0xcdc8BA9815C76e838a759E932F57bf6F990a6e71,0x8F3b0058D12b7B30EdF4E51b89133198406F4Dd6,0xB3875EB64faf2881E3aBc48E5a96bB66Ffe6f100,0xb1adE58c1E818A6534E3583873e70E325A00E00D,0xcC38b8C0Da47A7CC315BfA5D96246843ed7F6d12,0x023f4115E3a625c0806F891439186DF6CbCC7660,0x52b9f71371f7B8e56E975366cb4b5202A4D1A7a3,0x73882a4b07196Db8054e37068ED728611555B0Bd,0xf5A732928A14f9475c7e29EA1D48CF802DFff383,0x69220D543eFFBA00bEaa47A5CEa8729Fb7F090f4,0xa48224743BD5f8027deD6990e226e124034E2855,0x3C8714E3cA4F206fbeC3920b6F09cF3FB6Ba9244,0x614D98a57A5D879D717152dE0690ed2b04562adE?flow=all&positions=%7B%220x614D98a57A5D879D717152dE0690ed2b04562adE%22%3A%7B%22fx%22%3A58%2C%22fy%22%3A-33%7D%2C%220xa48224743BD5f8027deD6990e226e124034E2855%22%3A%7B%22fx%22%3A96%2C%22fy%22%3A-5%7D%2C%22wincrypto10%22%3A%7B%22fx%22%3A101%2C%22fy%22%3A-45%7D%2C%22connoisseurpeen%22%3A%7B%22fx%22%3A38%2C%22fy%22%3A-48%7D%2C%22p89017%22%3A%7B%22fx%22%3A96%2C%22fy%22%3A21%7D%2C%220x023f4115E3a625c0806F891439186DF6CbCC7660%22%3A%7B%22fx%22%3A104%2C%22fy%22%3A-26%7D%2C%220x73882a4b07196Db8054e37068ED728611555B0Bd%22%3A%7B%22fx%22%3A83%2C%22fy%22%3A-53%7D%2C%220x3C8714E3cA4F206fbeC3920b6F09cF3FB6Ba9244%22%3A%7B%22fx%22%3A18%2C%22fy%22%3A-45%7D%2C%220xf5A732928A14f9475c7e29EA1D48CF802DFff383%22%3A%7B%22fx%22%3A54%2C%22fy%22%3A39%7D%2C%22totheloom%22%3A%7B%22fx%22%3A5%2C%22fy%22%3A32%7D%2C%220x52b9f71371f7B8e56E975366cb4b5202A4D1A7a3%22%3A%7B%22fx%22%3A-21%2C%22fy%22%3A1%7D%2C%220x69220D543eFFBA00bEaa47A5CEa8729Fb7F090f4%22%3A%7B%22fx%22%3A-3%2C%22fy%22%3A-25%7D%2C%22sp2916%22%3A%7B%22fx%22%3A116%2C%22fy%22%3A-8%7D%2C%22connext%22%3A%7B%22fx%22%3A32%2C%22fy%22%3A-5%7D%7D&sortDir=desc&sortKey=time&to=connext&usdGte=0.1

**Comment by A-Keyboard** [comment]
@linhhacak Can you dm me on Discord, my discord is khlilo

**Comment by linhhacak** [comment]
G768CCC from discord

**Comment by linhhacak** [comment]
> @linhhacak Can you dm me on Discord, my discord is khlilo


G768CCC
