### ISSUE TITLE
ЛУЧШАЯ ПРИВАТКА ПО СОФТАМ - ALFA ЖДУН

### ISSUE THREAD

**Issue by kukushkinace1** [connext/community-sybil-reports#140]
Стоит всего 50 баксов в месяц. Писать сюда - https://t.me/ezhik_admin
Есть вся хуйня и без скама скриптами, плюсом есть обучалки по скриптам. 

Рекомендую зайти или как минимум подписаться на фри канал - https://t.me/AIRDROP_Zhdun

**Comment by ArjunBhuptani** [comment]
Never gonna give you up
