### ISSUE TITLE
ВЕБ3 ВАРВАРЫ ТУТ НИКАКХ СИБИЛОВ ДРОП АБСОЛЮТНО ВСЕМ ЛФГ АБАМА С ДР https://t.me/BarbarianRoyale

### ISSUE THREAD

**Issue by ilovalapilo** [connext/community-sybil-reports#142]
- https://t.me/BarbarianRoyale
- https://t.me/BarbarianRoyale
- https://t.me/BarbarianRoyale
- https://t.me/BarbarianRoyale
- https://t.me/BarbarianRoyale

**Comment by ArjunBhuptani** [comment]
Don't tell me you're too blind to see
