### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by Den453** [connext/community-sybil-reports#144]
# Related Addresses

"0x0231f3508b741db1e79b42af043d9fc5f61b8678"
"0x0232b359e3685c977bd0994571aeeb92b72c7c78"
"0x0232f3d56b54ef620ec27e465e87974bed340fb4"
"0x02342f1116ed19727ca0170364996e8a42acb056"
"0x02349bc43d584a0f18fef86627d22eb4f362454b"
"0x023637ab03b5eba550c74ef56622d5c0653d34a3"
"0x0238059828b5cdb8b05d12e93b75610b11523761"
"0x0238be3921ae83189a0e85efb5ff5c7a3c13951b"
"0x023a3aabadb61d59e4c4f909064a87859e4e1ac1"
"0x023a43b2617d64b822ecfce12931b274017aa460"
"0x023de0bf90aebbd62b43c5df43d57a6590fddf70"
"0x023f4115e3a625c0806f891439186df6cbcc7660"
"0x0241143c94a45802f66766993a9884365b6c8240"
"0x0241410c6162692db077ff9af535934f232d81ee"
"0x02416a5fe802dd75b73f6e1b9c0f377e50dcb15e"
"0x024224b6976859c7f1b21ba6328d22b6138b1b96"
"0x02430d8f0dd95bdf3c9da6f50eaf33867ebebdb1"
"0x02452e744f78c30f92618e21143944b9ec7ae0bf"
"0x024599937976fe14a2b47389de83c549809d952d"
"0x024610e956a55e09917dbf16248b5addcdcd3adc"
"0x02467d049abd0d09b93bae549ad42f2260f2147c"
"0x0246b0a279dd8466ecba9b3b0af5f51076763e09"
"0x024713784f675dd28b5ce07db91a4d47213c2394"
"0x024813b4972428003c725ea756348dcd79b826e6"
"0x024899f1b2e7c3cfc5e3db7f54ecc284fd775d29"
"0x024940cfca9ceb1813f9244d83c9a581ac12f6aa"
"0x0249dcb927b71908609ed8a9973c292282f6ccf4"
"0x024af6a5b1caf3ccc7e98136c4e557fb5e291528"
"0x024c91ad166c96efd4bee8150784576e979a4a53"
"0x024dcd278b57232c8c166045b7e97b8e942370b5"
"0x024f2369e6c544e767ae33f72814167c7f535b17"
"0x0250cd163a13b41030bc20d96868d93acdf51cf8"
"0x02525d3ff30117a5f8ee09b903ff71836a0e6314"
"0x0252e421e4caaac32c1313239babc8c354f2b726"
"0x025369a02db5a1b729546ed239cd437abc685640"
"0x0253ce8465a3f7c0417d1f4bdc730ac606f48ad5"
"0x0256ba1f18ca0f91a93bdb2f218d91dd20ee428a"
"0x0259825c9bd714926f4b43bcf7c052259325936c"
"0x025a86702d51fbe0cfbe7c5a2e2921b3e52e835d"
"0x025acefa3cf20e71f44ccd3b81e2c1924602c48b"
"0x025ae1c8fd97c0405d16142ce03963a5e97ef00a"
"0x025c9dcb52d6a87b8b933e6114a0e55bce13a7be"
"0x025cf2379b5611d20629624d8e0c371a838e83bf"
"0x025e5034179ff44591087851bed2bff22d08ba10"
"0x025f7cb6bdb8cd6ed126e1cb2efe2fc3539602b8"
"0x02604a19202db1b391c0384520296ca8868df062"

All addresses listed received funding on Arbitrum about 440 days ago from address 0xA60113f7d43130919802b0863abdCdb956664fD5, in the sum of around 0.035 ETH. Additionally, all of the addresses have the exact same 4 last transactions on Arbitrum, which are 2 Connext Liquidity removals followed by an USDT and USDC transfer.
-->

# Methodology

I checked this Dune Dashboard: https://dune.com/KARTOD/connext-bridge-activity-and-top-30percent-depositors, under Arbitrum LPs at which point I saw that multiple addresses had similar points and amounts and saw that their transactions were the exact same. I then ran a script that would check for addresses on that list that had the exact same 4 last transactions as I described before & were funded by 0xA60. If it is needed that I provide the script, please let me know

# Rewards Address

0x0253ce8465a3f7c0417d1f4bdc730ac606f48ad5

**Comment by vi11am12** [comment]
The reasoning and methodology here are a copy-paste of my submission here: https://github.com/connext/community-sybil-reports/issues/1
Also, the addresses that are posted in this submission are just random addresses in order from the eligible list
Spam/scam submission.

**Comment by Stakeridoo** [comment]
@Grraarrgghh @rhlsthrm may you have overseen the comment from @vi11am12 but this submission is just a fake, please compare to your eligible list and you will see the list is just copy & paste
![image](https://github.com/connext/community-sybil-reports/assets/84278683/cb96ea53-1151-48e4-848d-fa6546a78395)

**Comment by Grraarrgghh** [comment]
Closing as it is indeed a copy of #1
