### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by Den453** [connext/community-sybil-reports#146]
# Related Addresses

"0x8ceef2a108d0ba389f511fbd562b3679e74d1260"
"0x8cf0477f411d61448f4f638838c0698e9afd0351"
"0x8cf14440780bdb1dab2808ef5bca5f2ea4046c5a"
"0x8cf54d42007f7d93982880d46ff1e7ea1e3b1457"
"0x8cf59ea79710b2379bc93128b0b10e88dae438ad"
"0x8cf7071f9418662b4a3a3396d2f08bec7c563e79"
"0x8cf7454938d2ed8cd98eae9d34a83931c283de58"
"0x8cf877e91118ab50ff00de1e6e6a566c9c2b8228"
"0x8cf930121d33d157bedf206a8cf99afc482c44a6"
"0x8cf9c3a6a639607d484ea3e26d00044b6c7151ca"
"0x8cfee9540fda895e2323781391b49620e7909d77"
"0x8d0172e88bd400884708318bac77bc69f76ae082"
"0x8d040c23aca23d3159004c499246791c894ccfab"
"0x8d047eb60ecec57dadd9277e84ecb51e9237c956"
"0x8d04acef51abfab1bf5df94d5b80ac4de46300e4"
"0x8d071fa6905e1fb872903603a6239947c03fd450"
"0x8d0734865f984374435d5e9f814a9704fdc51a64"
"0x8d0d855bbc88d7d74b63e194a9cce385dc613c0a"
"0x8d0efe7db232fe95f9073d3a0abdb4b6bb7cc68e"
"0x8d0f77b10b519c295b0850d906f6bf566ed8d01c"
"0x8d11fcbbf601261a8fa9ddbd6a2ece90a3241011"
"0x8d12857c33e610fe051430f11df877e033cd260f"
"0x8d12a0bd5b36f0b32588a5745472183983342104"
"0x8d12bd5102af066d25bb386c164838471e080eb8"
"0x8d12bf7ab9a3b45ddf6c7302da052c38ad522e47"
"0x8d14db06f458e01dc77f8734208b686645ab8bf3"
"0x8d1509e0240eba23cccd58941fa2b5d7ff1fc70f"
"0x8d160063e641252f4b424a9af89e88b24e04e444"
"0x8d1774d8e34834b017e8cfe280b3638445dfbb84"
"0x8d1854ef9bae977a0282fe9f21ec6dc3e171e43f"
"0x8d189a8f4417e388e64356a09ea1efe51540156e"
"0x8d198fc0e5254cc969b955a5718d05e388150aa0"
"0x8d19fcd4418261094285046265346aad62e9fe5e"
"0x8d1a7beefcccbab825ab3b024a2abf408e776100"
"0x8d1dfd58b9f39bbfe14dea7dd3137fc5e431fc96"
"0x8d1e46e92dc5b24c09bdf46f9b7d20a8e47cea70"
"0x8d1f338f8abd714fd09ec13c100a0d7df693cd5d"
"0x8d1f5f48955aa23d3a376e7e26ed60f8745a3220"
"0x8d200373f44bb836218ae699577de48bb38254aa"
"0x8d2056c4c9fa7947774f2377eb76509ab1bbc55a"
"0x8d216b875b5a1355e5938cdef73b503231a81c6f"
"0x8d217f5a73f489f912dae0ee49a0e77b4a2d7ce0"
"0x8d21e3c8993633546e89cb4a24e5c0a5bc4d97e5"
"0x8d220b54b3421f56c9021852e8befadbeea509e1"
"0x8d224e0b1373ffffbd73e0fd83d2b62c1cb1866f"
"0x8d22845a0e2dbbca06c56bcec81cfd83eba431f7"
"0x8d2364f1781c3afb533665b054e17e094021cdf4"
"0x8d23c803b8d3db7439c16d0b82199c0763aa9f8d"
"0x8d24aac6b5931f31a905c8ea08ff4eb5fc19cb93"
"0x8d24deff9892e86660aa37a3abd70bda6efd5e4d"
"0x8d2563e97805cf30fec491a84ac246e50a32d3d7"
"0x8d25b3e415ee15bc404a7b46dd866f2f86ddbf0f"
"0x8d2642ca480c36650efed2bbb0a6bb665203d1c4"
"0x8d27380842381b300dc20169ce22d7e6eabb5be7"
"0x8d273abff2bd712f55475ecd2cc810957b9211b3"
"0x8d2876ad4d2a994c529f19d846ca541015dc3f05"
"0x8d28ec4ae6b5d950824d5a942ab7c2edddc0ec4b"
"0x8d29d5e77d7716afce386d9d31cb3fa224df4bf7"
"0x8d2b3a8c331d1d060c969d88fa47b420fab406e7"
"0x8d2b5b26bd71071944f78551c3c4f47da9cb24e4"
"0x8d2d2b09477c10fdfcc79ec6471945cfda13c99e"
# Reasoning

All addresses received funding from the same parent address `0x8d220b54b3421f56c9021852e8befadbeea509e1..`. After funding, each transferred funds from Optimism to Arbitrum between 5:30pm UTC and 7:30pm UTC on September 23rd. On October 1st in the same window and sequence, the accounts sent funds from Arbitrum to Optimism. 

# Methodology

The reported addresses were discovered by checking irregularities in the number of bridge transactions made via Dune. The resulting addresses were analyzed to find repeating transfers at standard intervals and sequence.

https://dune.com/queries/0123456
https://github.com/airdrop-hunting
-->

# Rewards Address

0x8d25b3e415ee15bc404a7b46dd866f2f86ddbf0f

**Comment by kunstenar** [comment]
Your links to dune and github not workin. Reason a little funny, some of the addresses listed do not have transactions in Optimism on the dates listed. Looks like an attempt to deliberately discredit wallets that have nothing in common except for similar numbers at the beginning of addresses

**Comment by ArjunBhuptani** [comment]
Impossible that a real sybil cluster would have addresses like this. Marking as spam
