### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by arcsin3x** [connext/community-sybil-reports#163]
# Related Addresses
part1
0xEc28195C616d1D354075b7631d8161927D873e46
0xb95ec89153bf6047f10cff1165572a505ff83bbf
0xFd7caFd4F6Ea144D62c81810168646057508aD1b
0x60294c5865B9B1f72fa9F7acC50675A0591e6533
0x4A5539dC921051AAF57B927E108F0Bb4f738aF79
0x8bcDF64ccEEa505445BBD5683FfD60FE941BdEc3
0x0E997f9e87eA35b81E680e61F8dC07e57Fa58Ec9
0x6a4Bb3812f202b3Effb4e88F08a3408FDFB67a0F
0xb2AdC921Bd01A1e926B9ce7986736764b2fC08d8
0xf0e0fe2082f33620a50ecc7b8c3483bd4dc68c9b
0x6c9315f6e288949b1a36b1f9c641ce7912230181
0x7ac6505f21ef2adD85987c79018F1A06Bc600e08
0xa00c1cccfc9a7ba5b648cd6bd720a26752417880
0x677e808e07fd01e94c9a81a51e772a601555ca20
0xbae6fda910ee3b0d52c0ab7994e46d897d8acdb6
0xc157f7b57436a094a59ad01c1fb26bf4cef3818d
0x577e2827d4ba6dc3f976b0afdabc9c27b6584923
0x13ff873f372e3780577d41f95d9932e56aff7bb1
0x7d31f3ae69fce41dba385a46aed5a6ab682bc239
0x09ef27ab4e8ecc63718b6a8cd25bc02d78d85da0
0xbfa10b44ac4df71bf51f50b80e98b296c51ee89d
0x7784eb95684e37da505bb63f6c21b494ddc2655e
0x7cf508b2be466d118f13e3daf700d77c13334be9
0x989f58d48910ee3c3cf6cdb11b88b835b6e7c660
0x95bec4310934ba8895773f07a7dfa9038d0d8504

part2

0x9fc080feacc3c9c7620d2e0618d4c35433e6f626
0x81754d2bBB367Ca0951C7997254D568FaB9adc43
0x5b0d34a235f52b322f8345ec07c8210a633477cd
0x16e7f78a60e166df986d1d51691caf22080caee2
0xb81da70312638fb32fd9d4d0650908ef69d67328
0x7321e634dcaec6b0f92a09f2e3bac53788e1856a
0x625a39bbbccb13bd093e1a31952c68d184045780
0x51336f4d75358b791a9697394b1698167ba3ae00
0x2034c34e0dca945f66b11d7e9ab853a38561a14f
0x6b44733ad66a69f21101dfef67564abe42e843db
0x2d2297393fda1c1828bb588e0cedf5b2728a90fc
0x622475c8c64d055fe88cf22ec38b0a972f2cb4cb

# Reasoning
part1
430 days ago, this address (0x8bcDF64ccEEa505445BBD5683FfD60FE941BdEc3) provided initial funds to multiple other addresses and ultimately recovered the funds.These addresses behave similarly, as if using scripts to automatically complete the interaction.Each of these addresses has had a transfer transaction with another address.
Below are the transfer records between these addresses.Some addresses directly transfer all funds to the next account for interaction after completing the interaction.Their behavior is very similar, and the order of interaction is basically the same.

0xEc28195C616d1D354075b7631d8161927D873e46 → 0xb95ec89153bf6047f10cff1165572a505ff83bbf    
https://polygonscan.com/tx/0x2da2ae61899d96e13a39060969f291638fa19aab3a91ebb58510a7116c7f93e2
https://polygonscan.com/tx/0x8757feb16272e504e2837e6443b24fb3c52477cb426fc290632bf91fd50b56e8

0xFd7caFd4F6Ea144D62c81810168646057508aD1b → 0xb95ec89153bf6047f10cff1165572a505ff83bbf
https://polygonscan.com/tx/0x1fade0ba52aedd4ddce07a8e23bc1c35bee714299c0de4f632e518640b7b4566
https://polygonscan.com/tx/0x91f8af0744df92451e86464967cfb772a026484ffb12f7de66e14d4dd78dd00b

0xb95ec89153bf6047f10cff1165572a505ff83bbf → 0x60294c5865B9B1f72fa9F7acC50675A0591e6533
https://polygonscan.com/tx/0x1ba832fa82b0e1124bbd3968e1040ee3492209c2df08439d6406e2e348987b4c

0x4A5539dC921051AAF57B927E108F0Bb4f738aF79 → 0xEc28195C616d1D354075b7631d8161927D873e46
https://polygonscan.com/tx/0xd029b63c47c376311600527bc04a57c1d914b88e143b5a30b7263d3f51284b06
https://polygonscan.com/tx/0xe33ecc490caa36fd0ba8a63475df92535ebbe0ba822b5141aa784cb0bd0c7f45

0x8bcDF64ccEEa505445BBD5683FfD60FE941BdEc3 → 0xfd7cafd4f6ea144d62c81810168646057508ad1b
https://polygonscan.com/tx/0xeb4b77b6c6f928d3e22e5bdd1b3d6e9a467846c0541d51221673a9ead8e38b40

0x8bcdf64cceea505445bbd5683ffd60fe941bdec3 → 0x0E997f9e87eA35b81E680e61F8dC07e57Fa58Ec9
https://polygonscan.com/tx/0x029ece39463c17ebfb9e37b6e2f01684cd6742e55a7a81751350b02c30351560

0xfd7cafd4f6ea144d62c81810168646057508ad1b → 0x0e997f9e87ea35b81e680e61f8dc07e57fa58ec9
https://polygonscan.com/tx/0x2e8b84439b00a92a494be451ddb4962a0e78a50b92ec0cff8c0ad5500f051ad6

0x8bcdf64cceea505445bbd5683ffd60fe941bdec3 → 0x6a4Bb3812f202b3Effb4e88F08a3408FDFB67a0F
https://polygonscan.com/tx/0x6e5968ca41cd87c7100c6c3e0977bc38222ca2916c9129f0ca4330260cda6303

0x0e997f9e87ea35b81e680e61f8dc07e57fa58ec9 → 0x6a4bb3812f202b3effb4e88f08a3408fdfb67a0f
https://polygonscan.com/tx/0xa406c57b48af834bd4ad902484c52b57c51e5aa6bfb5e76772432897ca590f89

0x6a4bb3812f202b3effb4e88f08a3408fdfb67a0f → 0xb2AdC921Bd01A1e926B9ce7986736764b2fC08d8
https://polygonscan.com/tx/0x84c8204f06d2648df2a88217cfadac3b138ada8d81d195133d37c383fc4ba5e1

0xf0e0fe2082f33620a50ecc7b8c3483bd4dc68c9b → 0xb2AdC921Bd01A1e926B9ce7986736764b2fC08d8
https://polygonscan.com/tx/0xa74acf911868881c206ee0d74f3d0e26edfda48cee95bebca011b4aeba6eda3f

0xf0e0fe2082f33620a50ecc7b8c3483bd4dc68c9b → 0xa00c1cccfc9a7ba5b648cd6bd720a26752417880
https://polygonscan.com/tx/0x72726629e6da42c190f0f64cee92b5447c5edbbd2a18b556cb31a7d2c8cbc009

0x60294c5865b9b1f72fa9f7acc50675a0591e6533 → 0x6c9315f6e288949b1a36b1f9c641ce7912230181
https://polygonscan.com/tx/0x2a2c3ebc474b2fc9e7cf406526bc93314c1f65ccc973440ca8e99a955cb8dfd4
https://polygonscan.com/tx/0x960edc4e0b9bf1544a09885678ac99f607c2ee73e4b86629035a858f3acb7f57

0x7ac6505f21ef2adD85987c79018F1A06Bc600e08 → 0x4a5539dc921051aaf57b927e108f0bb4f738af79
https://polygonscan.com/tx/0x2894dc221f750c1042a1a2eb089365c3c4bb90c93bb9ef5bd27cee931edf12ea
https://polygonscan.com/tx/0xae65456c3f73a2b3c11702bbd955afb9d46c58985bb511cb0d0404151f83034f
https://polygonscan.com/tx/0x6582b7e7a66f98c618712a93d0ebd34a7a8e7f789264763648d526651e1e308e

0x677e808e07fd01e94c9a81a51e772a601555ca20 → 0x7ac6505f21ef2add85987c79018f1a06bc600e08
https://polygonscan.com/tx/0x085e09d08de79b3c009466ec0061909fec9a73401938dfc8165b85355a4b11e6

0xbae6fda910ee3b0d52c0ab7994e46d897d8acdb6 → 0x677e808e07fd01e94c9a81a51e772a601555ca20
https://polygonscan.com/tx/0xba3ff59d0976f2c442cd9b8cf77ce8c6692b1612e57b029daf2d879b77e5d328

0xa00c1cccfc9a7ba5b648cd6bd720a26752417880 → 0xc157f7b57436a094a59ad01c1fb26bf4cef3818d
https://polygonscan.com/tx/0x034849647d6809676e63534bd9eea05d5232f1c3805245da5609ffd3e18dab3b

0x577e2827d4ba6dc3f976b0afdabc9c27b6584923 → 0xc157f7b57436a094a59ad01c1fb26bf4cef3818d
https://polygonscan.com/tx/0x5c692fecac89cfacfa22705da4cad5052c2d611ba661abb4952731a1680c70d4

0x577e2827d4ba6dc3f976b0afdabc9c27b6584923 → 0x13ff873f372e3780577d41f95d9932e56aff7bb1
https://polygonscan.com/tx/0xee128b6b021f25c08a0562acf4860dc69f61b3282bb4d53990db4dfc3d2f7380
https://polygonscan.com/tx/0x4104bd4c982b833bfda7d0c33c6a49e50f0cdb99700dd6e8336f139e28d61892

0x13ff873f372e3780577d41f95d9932e56aff7bb1 → 0x7d31f3ae69fce41dba385a46aed5a6ab682bc239
https://polygonscan.com/tx/0x7786af2a37918110c4b1a3c2062ab0ed2c9fa65e8e001f702e5ebc085abfd4db

0x7d31f3ae69fce41dba385a46aed5a6ab682bc239 → 0x09ef27ab4e8ecc63718b6a8cd25bc02d78d85da0
https://polygonscan.com/tx/0xb99bd5f2a30bb1da9b7ae6322f1d4cc262d5635289f95728d2648d36cb660517

0x7d31f3ae69fce41dba385a46aed5a6ab682bc239 → 0xbfa10b44ac4df71bf51f50b80e98b296c51ee89d
https://polygonscan.com/tx/0xca7a33491c2ad94ce14e52cc760cfb424c4dbcba758729762289b4bacf74ea49

0x09ef27ab4e8ecc63718b6a8cd25bc02d78d85da0 → 0x7784eb95684e37da505bb63f6c21b494ddc2655e
https://polygonscan.com/tx/0x539db704cce78975953dbfdd5c3d20d2a3064ee451760344fcb6a165c8f016e1
https://polygonscan.com/tx/0x24a3c63a49e8bfd722324a4cb6a423d83852beb366dece9d8fdf5a1b32be1960

0xbfa10b44ac4df71bf51f50b80e98b296c51ee89d → 0x7cf508b2be466d118f13e3daf700d77c13334be9
https://polygonscan.com/tx/0xd5221d851759fea32b093b46cd7133387839167656925e633240642b825280e8

0x7784eb95684e37da505bb63f6c21b494ddc2655e → 0x989f58d48910ee3c3cf6cdb11b88b835b6e7c660
https://polygonscan.com/tx/0x4f1dfd178c46bfac1ae4dc6d4565500535be8265848859cde300802386c9cc6f

0x7cf508b2be466d118f13e3daf700d77c13334be9 → 0x95bec4310934ba8895773f07a7dfa9038d0d8504
https://polygonscan.com/tx/0xde58fee4e2aa39e0666d90e6025eac977a7b871d9d390e10a83c8a10d63e6b4a

part2

These addresses have a relatively small number of transactions and their behavior is very similar. Just like A → B → C.......

0x9fc080feacc3c9c7620d2e0618d4c35433e6f626→0x81754d2bBB367Ca0951C7997254D568FaB9adc43
https://polygonscan.com/tx/0x994313decf985afe354f605c5bd526fb75ea73ba9ff7482ee287b7376dffb33d

0x81754d2bbb367ca0951c7997254d568fab9adc43→0x5b0d34a235f52b322f8345ec07c8210a633477cd
https://polygonscan.com/tx/0x49a25f723f027917ca3c12bf836195b5c1aa59c453a2f50d918f328e9ad6e09c

0x5b0d34a235f52b322f8345ec07c8210a633477cd→0x16e7f78a60e166df986d1d51691caf22080caee2
https://polygonscan.com/tx/0x5db6669a5b3e10fd5aaf97b125843ca3a50afe94fc4f546ba979abe1214ac71c

0x16e7f78a60e166df986d1d51691caf22080caee2→0xb81da70312638fb32fd9d4d0650908ef69d67328
https://polygonscan.com/tx/0x2e38a2762aca2fab4ee33a20df148d9b7792499dc01a8b53b32e87fa9fa9f457

0xb81da70312638fb32fd9d4d0650908ef69d67328→0x7321e634dcaec6b0f92a09f2e3bac53788e1856a
https://polygonscan.com/tx/0x45cb8096edc33e556351333838d6ec21deb6b5ed79ce65c292014b8b28a48da3

0x7321e634dcaec6b0f92a09f2e3bac53788e1856a→0x625a39bbbccb13bd093e1a31952c68d184045780
https://polygonscan.com/tx/0xe08fd908d8171bd535a105a8df6759c12d1c1fca09b475d0235020e2127271fd

0x625a39bbbccb13bd093e1a31952c68d184045780→0x51336f4d75358b791a9697394b1698167ba3ae00
https://polygonscan.com/tx/0xf814a03687519459938c76f74ddcc3d15d6289a581fedadc6bc3bf404ac96c49

0x51336f4d75358b791a9697394b1698167ba3ae00→0x2034c34e0dca945f66b11d7e9ab853a38561a14f
https://polygonscan.com/tx/0x0091e381957d08354816ddbb38dedd75e8bde3d0cbf1189f9623e76a060c3423

0x2034c34e0dca945f66b11d7e9ab853a38561a14f→0xc6dc9c732d9e6695575a45be9cb7d27ede1c9384（Not on the airdrop list）
https://polygonscan.com/tx/0xdc6a1cdeaece5d49d65e722df1ff2f67019043e336214d925256dad811e9baf7

0xc6dc9c732d9e6695575a45be9cb7d27ede1c9384→0x6b44733ad66a69f21101dfef67564abe42e843db
https://polygonscan.com/tx/0xc19de71c089cc72d9269b744b39ec9575e544bdc2cd92857812831eaa9f65830

0xfafa5f724f75c0f649fcff139479200c2392c21d（Not on the airdrop list）→0x6b44733ad66a69f21101dfef67564abe42e843db
https://polygonscan.com/tx/0xfa2c2f21085efc0442ee9e9761af8f7c9b7565f5ada975b3d747680aba660a9c

0xfafa5f724f75c0f649fcff139479200c2392c21d（Not on the airdrop list）→0x2d2297393fda1c1828bb588e0cedf5b2728a90fc
https://polygonscan.com/tx/0x7c04e5f7ad7ed41972a3d9f03aab1f625b5465803a3e2a9132ce9ffbc17e63fa

0x2d2297393fda1c1828bb588e0cedf5b2728a90fc→0x4787f78a7ff3dd045a6b3c20acd8c5b6fe1f186c（Not on the airdrop list）
https://polygonscan.com/tx/0xf371cb1aa57b1fd537137581059e8a123134e291992b596e9a9eae407ed4dc32

0x622475c8c64d055fe88cf22ec38b0a972f2cb4cb→0x4787f78a7ff3dd045a6b3c20acd8c5b6fe1f186c（Not on the airdrop list）
https://polygonscan.com/tx/0xd1c547f087936f2010593cfbbc366a1c9de004be7f9aa1e325d50ca74bd898b0

# Methodology

I discovered it from the blockchain browser. I randomly checked the transaction records of an address from the airdrop list and found that the transaction quantity and balance of this address were very low. After searching, I found that the address associated with it was also in the airdrop list. Then I checked the transaction records of the address associated with the first address until I finally discovered these associated addresses.

# Rewards Address

0xaAd28d1c5a578abDaFE51f289602275900f09B2b

**Comment by arcsin3x** [comment]
I have updated some of the addresses

**Comment by A-Keyboard** [comment]
Part 2 is a duplicate

**Comment by A-Keyboard** [comment]
Part 1 okay

**Comment by A-Keyboard** [comment]
@arcsin3x Can you dm me on Discord, my discord is khlilo

**Comment by arcsin3x** [comment]
> 

ok

**Comment by arcsin3x** [comment]
> @arcsin3x Can you dm me on Discord, my discord is khlilo

@A-Keyboard " X223X" ,It‘s ok ？
