### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by pachepot** [connext/community-sybil-reports#192]
# Related Addresses

0x3Eb4054da1Dbe73d3bf13eCC02Bf584a7288BCff
0xFA3e3c3988B18822d6e79F92630faD60CEb5B223
0x67F50Bb19541dF8C532D00b2327D894E0e6695Ea
0x2CA71460be88070E96781E4E4faF59318d2FE06c
0x22a17FAcDd0ecb395692861240c9B5B2ef01e61A
0x5b132aa2B53eD555f90f2D8c4802d1241D2c6D4F
0x144A32CEBFafFc19c86aAA36e2e10Ddf5e2aE202
0xD82e11db7c158c528761e7590c566Dd83e6C2A4f
0x6F3e3B567054C66D5947f204A2BB2C6ba1449125
0xEA0F9Dc326f9A6c47235169d6Ad3f024D2Ba0BFF
0x8B0467A0f1951632581d85678BB8DD39c188A36D
0xF84691432c1CCEbD0ef312Ef2c1c17517ce7321f
0xAEb6736b3bC0297554c2125FfDa3AD5beFA7Ec87
0x212841c92AF844ab487b4825e53B7038247C9451
0xBf7aCA9e6598529355c820b9B65B8467F5f4CBd4
0x80d6B5ACF7A927b4ce90ff42be25A1dc02A467B6

# Reasoning

These wallets are have transfer history between them.
And have similar pattern

![image](https://github.com/connext/community-sybil-reports/assets/69146825/ec231687-03a6-43a6-b7a0-679490e845d2)

![image](https://github.com/connext/community-sybil-reports/assets/69146825/1c9db318-ade9-4a5b-b0b8-fb68ba512c97)

# Methodology

I noticed that these wallets have a similar pattern at bscscan.
And used arkham to find transfer history

![image](https://github.com/connext/community-sybil-reports/assets/69146825/e1a07995-e2fc-4a74-91a1-8b1758914ab9)

![image](https://github.com/connext/community-sybil-reports/assets/69146825/d715bf11-c03f-4327-af1f-0f648d0220a9)

# Rewards Address

0x4E1A43D3f255d7eB2F3D16764394D1b1cb0F1B20

**Comment by preethamr** [comment]
Addresses with <5 transfers, to be excluded from the report
0xFA3e3c3988B18822d6e79F92630faD60CEb5B223
0x67F50Bb19541dF8C532D00b2327D894E0e6695Ea

Others are valid for further review.

**Comment by A-Keyboard** [comment]
@pachepot Can you dm me on Discord, my discord is khlilo

**Comment by pachepot** [comment]
> @pachepot Can you dm me on Discord, my discord is khlilo

49689
