### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by LL19888888** [connext/community-sybil-reports#204]
# Related Addresses
0x131975ca3e75259e60afeb1cd34051a6804da505
0x18d072a783fae1ac81af576276dc1561cfba1013

0x261e1fbc2d5c7200de55289dfab9ebbc5fd585be
0x27d4a79f9096f1b337de23d089d27c0eca313979

0x47e5d263778b1d6afb4468f92fc7b09b306d7997
0x6c13fc8ef50144a21702415d57ece0a09879fcfb

0x7506e3d710c4005c085f548c70ced46ffd5447ea

0x891ade8337151b26dcbe6662e5180f00ed14959d
0x8ea502092eab16e340808dc75ef3c982e2d71d15

0xaa6c7b556449e1d5a75b6322a256180edd1c8edc
0xaea79e61d658690b2cc0c4078d37ab18cfd2afaf
0xbcf224cb3771bb32b7a9d49d573375ffa5e29b9d

0xc266e461c0aa65cf7ae307783f8a7681424e0b76
0xfe3142024baae2a07e257d67bf25492ef414f351

# Reasoning
From https://github.com/hop-protocol/hop-airdrop/blob/master/src/data/eliminatedSybilAttackers.csv

# Methodology
https://github.com/hop-protocol/hop-airdrop/blob/master/src/data/eliminatedSybilAttackers.csv

# Rewards Address
0x7ba7593f35cb1d2bfe7950d693ea5021fd96e17b

**Comment by Grraarrgghh** [comment]
Hop sybils already filtered
