### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by danisimo1** [connext/community-sybil-reports#215]
# Related Addresses

0x001564ef59906625ab3e8a32e28fc8ab224760a5
0x0268f26c311fee1e2652b78e0f4b186239bb30e3
0x349d9688f1e2727243a619c212c38bd383240b62
0x0438f24609f1ed303e0e1ad6b6407ecb2db83df6
0x51c41f6a43821cd267ba2eaa243e6f470e592f1e
0x7475a2bc89577507948bd72762d237e933198e2a
0x8dd32a8a3b965b02d8a5c23d79b066cd9a6a0756
0xb6d14871b1b3e597f0c6acc17fd69002bf785681
0xd45e5dc6490c54c956bf6f4cc377cd2d2182ada8

# Reasoning

all addresses were created at the same time and transfer tokens at the same day 02 june . added the same 1111 usdt in connext pools for 14 days 

# Methodology

i used arkham and dune 

# Rewards Address

0xd47083dfd4024e5d7c329ddf7e627fa4783c7398

**Comment by prathmeshkhandelwal1** [comment]
Wallets are not heavily connected.
