### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by lookerVir12** [connext/community-sybil-reports#216]
# Related Addresses

<html>

<body>
<google-sheets-html-origin><style type="text/css"></style>

ACCOUNT | CONNEXTSCAN TXs
-- | --
0xe563bad50fcaef4767116d945e35b87ef5acc4f0 | 9
0x4b7ec805ae47e8696c212ee1e259a291316440d4 | 8
0x52da6fc418863f0cc96e8fff496454401557ceae | 4
0x8e930f0e61a70ab7a6d082a11761fbe53c7b33e2 | 1
0xB1f72d694711FcE55C62eA97BD3739Ff11ceF986 | 29
0xce97488ddfe8c92ccdd6c23191bc90c6e93a4718 | 1
0xddf67766823a949f0d5ed88c944a098f93c51535 | 2
0xe3444be2085f4b2c7ae1b50b0980ad6a4c257017 | 2
0xf6cee0b7d093d3e716461da80be035da8080d754 | 3
0xf84856531e2d89b438f7820630db02cdfb2ae69f | 2
0xfab8b317625fc99a3989d894b1962f668101aec4 | 1
0xfd5cf3a11baf13f2cdb5b1de5cc77f5fc122820c | 9
0x0b8b7f5db541620e441cb212d9ca5ae4b631d89e | 2
0x1ec44deed1524080e79d19fd481c100a484595ef | 3
0x37ba03d426d481b9c18c35d6cd7d6b010baac9dc | 1
0xacc9df058068c40e8d23978eb3dfad7edf8a2577 | 1
0xeea62f22f176c0bcc4d21e9a3bf773e9eb20b9f6 | 1

</body>
</html>

# Reasoning

![image](https://github.com/connext/community-sybil-reports/assets/143200126/bbd35b17-d618-4e35-9085-e6b9ea10486e)

Found a cluster of 17 addresses with many transactions between them and every one of them having interacted with Connext. 
In this cluster, there are 2 addresses that stand out as "core" addresses: 0xe563bad50fcaef4767116d945e35b87ef5acc4f0 and 0xB1f72d694711FcE55C62eA97BD3739Ff11ceF986.

In the table below I've put 1 transaction per involved address bolding the "core" addresses I mentioned and including a transaction hash involving both "core" addresses.

<html>
<body>
<google-sheets-html-origin><style type="text/css"></style>

FROM | TO | HASH
-- | -- | --
0x4b7ec805ae47e8696c212Ee1E259a291316440d4 | **0xe563bad50fcaef4767116d945e35b87ef5acc4f0** | https://etherscan.io/tx/0x0b130075ee95a0a1ffe2b2e0904d1c8d00129c525ea235261416500f6d0d20b5
0x52da6fc418863f0cc96e8fff496454401557ceae | **0xe563bad50fcaef4767116d945e35b87ef5acc4f0** | https://etherscan.io/tx/0x9bc051e61e5e8e9314978cb31471bea88d8757e2ae13a381e0acc652714f0e3e
**0xe563bad50fcaef4767116d945e35b87ef5acc4f0** | 0x8e930f0e61a70ab7a6d082a11761fbe53c7b33e2 | https://optimistic.etherscan.io/tx/0xa620c8e05f24bd40d24a6502fdb45da569e23b51dc9384c2a4c49473f54e96f6
**0xe563bad50fcaef4767116d945e35b87ef5acc4f0** | **0xB1f72d694711FcE55C62eA97BD3739Ff11ceF986** | https://etherscan.io/tx/0x031e165be3221328e643aa43f4b63ba5bce96c816a87bb9998ca5e9b6aa75ad5
**0xe563bad50fcaef4767116d945e35b87ef5acc4f0** | 0xce97488ddfe8c92ccdd6c23191bc90c6e93a4718 | https://optimistic.etherscan.io/tx/0x7db6dc0acb3c88bf3885ffae60014dc2213971feda2a71eb453d0f86f17aa558
**0xe563bad50fcaef4767116d945e35b87ef5acc4f0** | 0xddf67766823a949f0d5ed88c944a098f93c51535 | https://optimistic.etherscan.io/tx/0x8eb9e8199e7b6f76195035206152e76fa45433bdf77791a766aeeaa692dd4b57
**0xe563bad50fcaef4767116d945e35b87ef5acc4f0** | 0xe3444be2085f4b2c7ae1b50b0980ad6a4c257017 | https://optimistic.etherscan.io/tx/0xea5ea1fd4fbbf2892300dcdc634500f74d852cb89385f0e7ea47d294bc2a3590
**0xe563bad50fcaef4767116d945e35b87ef5acc4f0** | 0xF6cee0b7d093D3E716461da80bE035Da8080d754 | https://etherscan.io/tx/0xadb8e1ee0150e978d0cee35987cae9b74046919b1726cd6c8d7bc38c559cff76
0xF84856531E2d89B438f7820630Db02cDfb2aE69f | **0xe563bad50fcaef4767116d945e35b87ef5acc4f0** | https://etherscan.io/tx/0xf24735a5733f71839bdd5643a396201f2ed056bebcc25d11df914775910e30ad
**0xe563bad50fcaef4767116d945e35b87ef5acc4f0** | 0xfab8b317625fc99a3989d894b1962f668101aec4 | https://optimistic.etherscan.io/tx/0xf710936b4cd50195d80474d068164341f504b5533b3e75865e890f28a18dac7d
0xFD5cF3A11baf13f2CdB5B1De5cC77F5Fc122820C | **0xe563bad50fcaef4767116d945e35b87ef5acc4f0** | https://etherscan.io/tx/0x1c69bb5e2cb23c47866878fc114d203dccf7d7d66703787dfd1439cd5aa3e3fa
0x0B8B7F5DB541620E441Cb212d9ca5aE4b631d89e | **0xB1f72d694711FcE55C62eA97BD3739Ff11ceF986** | https://etherscan.io/tx/0xfdcc40392b8f08a81f61529676e37e163c31848d09261ed87da7914d012eb58b
0x1Ec44DeEd1524080E79D19FD481C100A484595Ef | **0xB1f72d694711FcE55C62eA97BD3739Ff11ceF986** | https://etherscan.io/tx/0x6274a6916659de83a50e7a9b72789dae023f20eb5037f08c68a202cdea736284
**0xB1f72d694711FcE55C62eA97BD3739Ff11ceF986** | 0x37Ba03d426D481B9C18c35d6CD7d6B010baac9DC | https://bscscan.com/tx/0x39b919c188677f6d49fec9da431f03b7489e80f0fe790d15c4bfa891f80f16c3
0xACC9df058068C40E8d23978EB3dFaD7EDF8a2577 | **0xB1f72d694711FcE55C62eA97BD3739Ff11ceF986** | https://etherscan.io/tx/0xb5d0c484340f6e044cf75bf14dd44d4db85a487b377948ebb3b7468b24a324c0
**0xB1f72d694711FcE55C62eA97BD3739Ff11ceF986** | 0xeEa62F22F176c0bcc4D21E9A3BF773e9eb20b9f6 | https://etherscan.io/tx/0xfb67e41c1b91e8718fc787100a2727e5d2236aea76a5315a1f17937f9b091329

</body>
</html>

# Methodology

Methodology used was querying the blockchain and finding transactions between distinct accounts on allocations.csv.

# Rewards Address

0xf0b53000782354156C4046caD9e13B4e420FE6b2

**Comment by lookerVir12** [comment]
Some of this addresses can be found on report #11
My report includes 9 more addresses that are part of the same cluster.
These are the addresses not included in report #11 

0x4b7ec805ae47e8696c212ee1e259a291316440d4
0x52da6fc418863f0cc96e8fff496454401557ceae
0x8e930f0e61a70ab7a6d082a11761fbe53c7b33e2
0xe3444be2085f4b2c7ae1b50b0980ad6a4c257017
0xf6cee0b7d093d3e716461da80be035da8080d754
0xfab8b317625fc99a3989d894b1962f668101aec4
0x0b8b7f5db541620e441cb212d9ca5ae4b631d89e
0x1ec44deed1524080e79d19fd481c100a484595ef
0x37ba03d426d481b9c18c35d6cd7d6b010baac9dc

**Comment by A-Keyboard** [comment]
@lookerVir12 Can you dm me on Discord, my discord is khlilo

**Comment by A-Keyboard** [comment]
@lookerVir12 can you dm me please
