### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by prosto93** [connext/community-sybil-reports#227]
# Related Addresses

0x92b47ef90831c08ac4b8d11e9a9e1ff19c76a089
0xec050ab24b986be4c2e196d8a66e0fd1e2b8c895
0xe64f89577e3b088f99a524b2d381d49c5ab9affb
0xbaef2821c2c2be02687f70fc52a18c830f45b7e0
0x83534ed817c036f95d68430ec37c292d463a2850
0xf7023091ffa7907c3ca229b09c1f8c4bee62154e
0x188b5df497ed444497510ddfe43bfb2c9669a8c3
0xe4edb277e41dc89ab076a1f049f4a3efa700bce8
0x3a09136807a31f93dd2e83f3bc6e7f39b31f794e
0xdf6a0dac863f972565cbf1cedace1781a4a996fb
0x43e40c84d1fe00be3c6211fbd7bc7fdc639b2d9c
0xd3b5fc539d2168ba4bc3f174b5e1e68632823621
0x8dc9ba5b21343cfc38f95e906a9c8b6a6d1d5e66
0x71ee0cafe7e22823938d9f46c48f9168ce285f84
0xca6c1f4fb72f80a2438495a8f62ec44aa6fd28d2
0x0770b04558b8c3500248954cbba1a2c49b143136
0x5693a2e8890ae2ca1600010a17fc91f4444963ef
0xe1d730be27f2e125611ee8442fc07d3682a5e131
0xb1408ad56ec16915ff0f145a18b417451bbb592f
0xedb469e750e6e102eddfa2aca721dfbdd568e8c8
0x81814e1245ded58229ec120b5dfa223c7ca0e9dc
0x29fb831f1d45ff2ba239a8a1b0cbd2080942f117
0x9ba956ee346a1d03fcbc97dcb4fb2b09dd2e304e
0xc150affe0f9ab829eeff91fa838a355bfe298e75
0xe314ad98d744cb467f96ef9d1f9b864070227584
0x7ad24ddd2d0bf3f60fd2987513377db6bcae9217
0xbd8e3d3fcf2dd00dca21fb5925909430e0d41c64
0x801df17a469f5bd00193fa24cde1c1d911caaa76
0xe6e84d3c1970c477f8a5c67a4031dfabbe3115e7
0xc6d031603df15bdb09844dfffd4510ccd33f3aa2
0x52f3259b7dee2000b6e9bcbaa7a7cd504545ac70
0xe6a3327977ed06369e2ba031103b4c96d993c7ff
0x6517ad5cbadfce6b4de83bc2040feb069877c55d
0x4b633130ae13a6eae484b41ce5a80867229d5755
0xd56aea22a665bc60f619b3ab02c1187ae5fecc50
0x0ef642a5ee481fbd2699162668ad0a9a984d61c6
0x2726611d48357dd194ba29ee430c1d2b2be3b66d
0x9c9ed33e211a5fe0729fc25942ce1be98df5c0d0
0x0d8b38349c34246ce6e6afb760e1ee17004ba14d
0x2411397e9b3226b6ee618a9a6db17d36425dd6d2
0xfa8d3bf77fc8aac497e01207c2a82ca4b643922a
0xbc1784eaf36190f5e939404dd42704956ebc8707
0xf664639c8b1e30b20821af37b52e3bc02734266b
0x267931e534051b03318e847474f57a981f8d173b
0xe41fc4081daf16f59126545cac2f27c214e97f6b
0x4c1f4255fbe3a889774f0e2332a3674e05f2303e
0x4749c5e564fd082b3dc2990f9eb31f3d10aec747
0x8abdabe2b4caf17ae4cd3c007b951791967cdaa7
0xcf0b9da44e09f6dbd08036c08813f27d3a3f6860
0xd435efc8d298f5d933ba32b9637752aadd10b908
0x74bdb34362923bd235147ef536d236c1ed46bfab
0x7e2f06add709172156d455e77741c75786677bb4
0x83237d68c9448d3490360936b186e7cb12c24856
0xb34419c0d941ff08fcada62949ab31d3739426ba
0xb3fb4369d1079dc85c10ac6366b345925df71adb
0xaa857a73393130b31b058b6c02c10a604a5c3b5a
0xb0d4dc42eb9e8aa9d2221a1220a97141915e199d
0xcc135a2803e0934736007e85fc98e06db797c830
0x621ab967a88157663c061b8d8eb661aa86a09bc1
0xc4040be8c7242cd4777a3bc1153f23107e415e6e
0x147110c964362965bd2610633a8c30d93000ebfd
0x1e10248255734d33586d90dddd4416042da6cc07
0x3ff718b097c87f59437cf5ee59a02ef25e19cdd8
0xce43294b1371f88eeac015adb1b5713ff8542d3b
0x057609ab955115b4248ec01df07b6d68660e3671
0x7b718870c55c2d47695933fad62e8972b03e8b02
0x4d32708c2b0793ecc271544c781b00dbe2694e71
0xd0bcafd9b130072624bc781e0be2d1140bb1bbee
0xfd60c715ba3f3e3ee1e8520d1403f0b4d096aebc
0x4589cdd303114de22a98f43aea1ed2ff0da92dbb
0xe76032bc46786178591ffb937efaf5bacc47c5c4
0x072d2f138cedb4df48e60af0a7e77dfbce7cbf3a
0x59bc7fd6fc0b897707475a916b2a50cb85368eea
0xc698d15811c7d4e765addcd9c2ab35d244a57a14
0xb6c6e323c220c0656ca5d03e86c17422395e4eaa
0xbafdb2fe73d44ff828366e85063b920a9cbdce21
0x60c1cbc7ed635363be38e909d0b82eb13644bc59
0x93d52a37867a6c183177172a5d28aae13c2321b1
0x8d2eb832420f730b973e775e49bbfe062002d926
0xd3bb9e5c16f7889829d03c49e1ca1927cde9ea57
0x3a687ec5e907ee8938973477efdcf9d61b426c4f
0x05e8473b03f97088d63470d53fba688491e98e3f
0x0e985e27f4c30ca47652994af7cb1258f76e3929
0x9399c03641eabc8d2864d9b1d33fc38867cd265e
0xee17ffb0a84acf44d2f5c20e61f768c3f0496835
0x7ca88097a9c44ec78ef3cdb195a18ac1e1a1c8de
0x0af0277beffd1c91ba8f513431a1e987d937c7ef
0x2ea3037053eb9d2a8abe2d385920a995416bfdff
0xcc45b1becebca5bda27fe62b7c7589211065b869
0x945ef9486bb0ac3be2e986a1b74f62f35b6573d3
0xfde29ad757ee353784bddf77e2aaf24b99161129
0x9588c6f9118aac10b3a9df46eb7478b9c233772a
0xe91fd7a7b86281f273122c44272eb4b5c1af3794
0xea3c9c9d282d1910de568c47643f45fbdaae03b5
0xcd269e805fd496051bd7c6135474d6d4c2b8e23e
0xadcf06a838ab9d48c271264c24b4ccacc7adc4ce
0x01130ef4c1cf900c024ff53bf2d952acb86c06a5
0xf2564712e0edc577dccf9b8f591b26cd3abe7d17
0xe6dbf649f59f3914f0ff181c47002eb30f1c672b
0xd7c0bd00258df1db143b79152e1af177f949f055
0x69a4f9c542bd7cc116f64a42b3216646edf8fdf6
0x0228c69c8ea20e58871487b9c3359c0823b38860
0xc599ab1021f9e8eb1012bbc63155874cc60f2f40
0x45f8a175eb623ae094785ed36c67407b3f67b591
0x1f0466b283f76c950c0d40a83acd24b0261175cc
0xf184c5504299fdc5dc5e6b3594d0db0266e021f7
0x69fce2b5ed7cb7b1b66f5b96db657e53de4926c9
0x2f4a66a5c8465b6b363d811f494f73ff00f68926
0xaa08a02f79951f410edf661b0f23202e9681e4c8
0x8bcaa98a1abb10ecd64aa550b503abf12eb17267
0xf4a8dd751fde247c42a5ff3c712fef17c1db722a
0x1fe5cc984abe1a747944fd0451992c2a4bdbf891
0x09e41d9f253b0fd531ec0ba8380f9bb3255c7ab6
0xa4e8482e991774651e840a7836802513c1843e1b
0x542de10febe8ef4b350529cdc3afc60ebfb6afd2
0x6085cb4aeca1d5c8c3f269d8e52290c546065212
0x17afe8df9dbe6a00a7a7c53c2ef151e7a91f1069
0xc104761db5bdd0ebd0c2b1f804db832126093666
0x05c6631c28587d1fa5a5c2e9ae44640ff38211ac
0xf071e091064afd679dfc9cf6d95f62663c4e2bce
0x4cd10044da689c2020c7aa1bed05a4cf88924a9f
0xd9f391d8ab8bd1220c4de3fbd7e7a60c7e94876e
0x6dc5f7cdf0209a4d44b4855428a1ba7c08722793
0x1bc035f9f004a9a36fd6a07e698b0798c3a3d015
0x7adf349e7414978fa6b9c3bc305715eda4d8a636
0x56e5c9eef7c1757cef6e0996f0f4bfb8cb2e5325
0x9f6e9dc6d8a281568ad75b4da98fe09eba9e8a54
0xaa156fedf52998fb81811d6536c07c9085678ca8
0xf1c5d3463ee3741f14213a8ee841b439a0e1aefb
0x7ec85dfc0cfa0f41c02a3ace3e22043f834ace6e
0x7ea8d4b30747703d16cc027098b41abf8f915ed0
0x70531fbafee892e9f897992b87d3ef78d5b8530b
0x30874aba48d8c0d055106b9ee360a3e485253c23
0xf5b2f819d7f2e3831814bc5e5936cf37c6bb637e
0xb0ddfd7c1127ee8e45edc3e813eb38bed70c230c
0x971300c9f35c73a0404a50ee2cca554040bd11d1
0x02d68e3f628b68d461738993139e7fa116efde3e
0xfe6e6f7aa7c7be4a0d3420d83ffff16bb3d0bc13
0xec7d01b1208674b8e5fd8dc7f86edc95042629df
0xf67f4d5c26a5e1299c745899c56a965b394e924b
0x730fbf1d52d43846bb65c0df19f78ad0fbcaae83
0x26456e2d8db79fced40e4a5d8d355888d94a51bd
0xfabbdd02135da66b2d4633eef835e25de8ffe06b
0x58ff5b006924c441ebdc8cf35f9a71902915d87d
0x6113b212a4ec58f66ef75a0773e02386b8e252d6
0x66dc4ea617eabd6aa1ff0fcd02bd9b449e57d2a6
0x7b877e7904412514126e99b01e7a96c8e4a08fd7
0xe742ce86d0bf9810ac4284e26ea04680a256273e
0xf400a300dc46470e95ac74d9970ee354bc43f938
0x917b8cee6daedae8b3fb009c4c0a59f70197ec50
0xffaa7ee8fe0d828e5844d3fd991fcfd7288390c9
0xdee55ceb9d7c17c695aa21ab6119760906aec716
0x18a5b85fd43562d18fe60298cda4ddee51972f61
0xca81a4203a49b3031331de3b3648d135143b611a
0x591fa3ec38a10ac8300239801171943bb7ad6366
0x4a63d01001178273ee8c1c861be1a81ae97a1c40
0x2fc341a64f461fb053932f852ddf4ba0b10b13a9
0x9857b0f852dd6be5f9ba799909d72598f8a01ff0
0xd941505e83e772ff4ccf078e08a69bcb22718322
0x851aec735ecda933832b5c02d9d6d485e164373d
0xbf6e18caa74cfde86b912b61d9683012046ba293
0xaf9a2bdaaefb996ac4b41b5215cf5106cf7dc488
0x6738fe380694f6712c617bae29c538b23fe69d40
0xb389e5cd7d7ecb739d2256cfd74a638d01a6dfef
0xab887ed848a72b9e3296634879b27abaf35339ee
0x18a69d5e06b2191b1e0980f71c062fa75d9f54c9
0x865d61b718a7bd1927ac76c1b72d85223e73f866
0xf1f6a0c93677dd9104f1dede4f2eb0621339f282
0xf1ed6a9574b92d4c41fafb6550661e0b9491f9a7
0xdd38f42cfc0c3ae95ae5675aecb512c9cc27ae78
0x4a5ce0d20422e3e0b094aa4dd90060d997b07c3d
0x603ca91e2826c46e2f3e9e443a45b5c004774032
0x00f2761b75d614b39970c654e014087a9ddf2302
0x9cb1a446a81614a25f0c8596a99e652d8ea119dc
0x50bd83ad92338c8d95a5c68b11f4233666c47c25
0x8dd595255f83f1a743104fff2a2389da40d43f3d
0x63bc15f2f407297ab3bd4b8be3714279959d3b0e
0xff59cda17df58bcaa4cc297290411453c7474ef2
0xb405dc76dea0423fbef6e7531841aff69d88ca78
0xd10a1801b2e403857a27842f243216bbde736634
0x9affb82be39c463e0b5bd0bebd8139e832e00109
0xcb22a3c7cb5fd9fa4344a1b15e25743b930db4ea
0xddde86b24858e8ed68c9ccffc45255739d354a93
0xafea9a3ed0ed032282e885edb4d5934593132810
0x4a37a5164de24342ffabfc763c1b36c5006d4bbd
0x04c7e1f713f83284f0e4630456fc4e5a74b3b86d
0xedcf9ecb2d94b40da4ea8b6c729e53ddd30eda83
0x03abbd179d9cc63cf91ee25aefe8e733a5a566bc
0x67e8268fa468c5b1c8eceefb8eb56c20d14b8ce5
0xed1bf309dc2c005abb708434a4cc539711a4b0fd
0xe9b5520ccd92e6b44a3d9b7715e6a52f8269518b
0xc11cedd0b23402c03dbf18fe6b0d9ca01311451d
0xb497825125742f501ef5767a1e4d02179fb04134
0xc707c94b7999d5b2ef4ea7e315fbeb42b6473ae7
0xd02476cf8dc8d0ee9454df30ae7eff11eaa82090
0xee7aa78a598b3c17264e778edada22528b570a7c
0xda0555c1e6f681f0813728d34c6507ad0b8bcb47
0x618b53e2e58469bc492ded210f552923aad95dfb
0x267fd15c3d6ea1064c81ba200bed4a12b1143d5d
0x6baa4f185ecff9f4202d14e20cc269c1295e3c8b
0x2f547f03bef385948aa40b4ad64a97ec57ef2a15
0x40e2ca7ba4bb8b1308d759e00d3e4d1a6477ee77
0x4f9449aa64ab75202386f516feb9c9dff40c5525
0x07917460d46fc972d3519d08df70f6c912078c99
0x68180b0cf96022423a2ac8394a741bac64f67b99
0x730fe305bb5d21e02b8413eb535e22248b357c26
0xda3aefb28dc276887b048ce542265afbf7e1dc3a
0xb65a15a39ef16fff00317e377b58bca076074787
0x1e3a5121313ee84e8c9acb7060d1c8db6267e5c5
0xffafb44a8c8b8b6c61deaddc19491dabfa5e5ceb
0xbab0130c021b063d8bd157fe283d85db54fdff84
0x6c98cb0688952a8c7bece2e3a0b1b3ef832ccc5f
0xd16e05b858bccf07aeb6183917a73262f3cd43d1
0x998ca1ac15b6c9eca16dc32a0059e0261e0405db
0x724dd92ad932bf4f0145097822f76dfe769dc6fa
0xc81e81d9b24182f11cfbeeb7b38944dc83c37f3e
0xd5703be52309687258ad7fec14953c1532e103cd
0xc6d8e3022917da0d1dada84cf7e9c23937a06a02
0x06e08c167f38deea72e750ca1a3e147e1a7c5141
0x3e8f74e86ef6e7d291cc8220c9d29057676f6425
0x547b6ecbfa5ce6a03be132ffb89b1482b128c9b1
0x702b8027ebf73727538de13206ea8d53597448b2
0x1a52c2cb90259484ae14c7231909f3a92eec21d1
0xec6451c4a49d2a5495db77810209715934426a2b
0xa9d7e27bd2a9b6be72c15deaee7ad66cddcd3a58
0x40fc1ebb4c8ff8d9b40483acc019ab216d194065
0xca831efa4c7be275162f802fc4fefd7c1a5473a5
0x603185e5ad6900e4affc27fb6ec3a351a19b88b5
0x5dbdf9070d25e6060b365db2a3ee01eac71a645d
0x16329594fc3529738f8feb8482a3b2886a1322c7
0x1383708e2baffe5a756af62251ceb94cdecf7286
0xd5a93d999bfc4c9e6ab8ad33db68a8a45a61b0bf
0x6737aa586d7ef1312ac2bfa3274140ba5dc614d9
0x28dbefe21bf137b9dc138fc5afd55d4c566d5756
0x694bdf119e4e41c1492c012a71ec93307f17c5e5
0xc32ae36de14637a9fd821f606bebfe8d1f73fc59
0xa82de4b6d7f90a4a318133e84d6f381895086540
0xe768249c12cb56e5eb12a80d3a7970fd9432b8c5
0x9bb7e7dfe461b6875c0ecd680658bccdce2f4256
0x62ea243b2f67b821b663bbdaedabb53583c358ff
0xa03bacf084c5ab7c86c9f0f1568a1ce615e73445
0x9942d87cc604ced68b0b18a5a3432f297a7ccaf8
0xd556a6f0858c4b6cf56549476fc9507e5d4886d1
0xbd482d49f620cdc1312f920a2ef0e8247787bdec
0xe761b4cb60a8dbee019a4af6534dd43a3af0940a
0x2d2df9c4ff7c96dbc1d605ed9b807105b385f48d
0xab2b710c84024900679dea256447d75ae7c904a9
0xa31aa9def419b0b80a647d1f76633d6b66e5a673
0x1fcd9ff7a81ece32c600126853f8d4d83a9f9991
0x9f406cbe28facf6cba66e874edc997124a02e2ff
0xff44c3e8e686945cd15a30f5cff2b8b3304943b3
0xa672ed80b07faed83fdf4d9bc757dc5b9586b3b6
0x01fe7f091db3f339dd5a333d82a90c8a3274a208
0xd3e1c7b4b9506c1d03acfc478bef87578b5803a2
0xb3e40d615c2257e1c00cd0612104d0f188781e3e
0xbdc208ba690020334f0aac7929e7011a2b2137cd
0x78cc5fb49e41b9d5b3fe7278cb5eef8626e076ac
0xbffc53fbfafbad11a07984e5b0689ef7826f60e1
0xfc27b85e14e4c7c0c52fe82dcb02d7295e085162
0xce6b6976edde4cc6d57fe9e589c834fc759ffa58
0xd450ac7ddbfac635b18b162897b3a6608501cb9d
0xeeab04aea77e669e91efef5bd76a71905eae737f
0x249560d3c5d1944f8b14781710e2e06273ea14b3
0xe31d6d23f7ba67c31092b0e331302ab19da2c6e8
0x33fc72f5a8937b067320da7c0f030ea66bc5eeab
0x6234214ab11595264ad88783cec10c291ff7a12a
0xc5032c3d4b0e407226b7f3e8ce78a52aad295a71
0x9eb343a72cd4bbaff9ad1814d91f35cdd847b402
0xfa45456d63d3ff6cd85dd952d786c3bf30c5358c
0xf63b0a34864679dcdc7ba1e93356ed2d37ad14e2
0xcaf50989c094e61b2eca1ca9d0dce2c6ef1a8233
0xe5bd046a34067f0f3567cde48514cf2930561543
0xe96b00e8463a52957d43b50b91d148d5e8fe94a1
0x3f2bf39c9d63b29912c44efc5cfff85cf4699665
0xe4459912be25388bd68a9579c73745a5702578a1
0x623b629576f483aa138fe3f85da029d9be2bb5f4
0x806402844e9af76ecd72c91bcd80e7b35bf4b217
0xf99a2b3427536cd89f402ea669c111ea865656e7
0x194cb3f53ca005932bea75003cc24d5f5d5cbaef
0xec4246e11f5d25c9f8e3cf74f16f4b5cf8589d92
0xe878bd77ff636bf8044708f288fd4a2c2db7db67
0xe296f922da4e082e810e4cef716cc4b9e1e5a0b9
0x7d84c998578f20e4834586a61a2fe4a929df8ea9
0x54dba9f09d1fa58213162ab3436eb8506ef905c7
0x11d26bd5b0cc0762431e5be22ed10317a6440e6b
0x1c94219aa4ab74e559b5d022301aedab9b8787e9
0x0fed1747dc150ce031c19baa6486af35de553d72
0x31b5fa87ad053614e84c34819cf81ec9890ebc09
0x62055d714826569c3ac6896ed982579f91cb040b
0xb8cc1a0a02eb4d6d3b3d65685255873a10d0b08b
0x8de7959b98df1f4ba1ce964625de15c0ad9788b5
0x02410f972d614eb3540059b4cb3304435c898e21
0xcc7d33e91e24bf807b940f38c9f1197614ffc97d
0x6816c4d086aae8ea5406c45c58a1a07dddf26854
0xa0b789dbeff1152feab128243bd5d87412dcc3fd
0x5cf53e2ad3558b9fe9312c8c046b10a847f1d32a
0x5a4ad3abf9bdbccdbf761bbc4f3e0c647528150e
0xd7ff46efdf74f317bbb71cf20d5da9389d7a92f2
0x92552e89096312902ff0e88a491ee369c4239338
0xd13229296fc286ec9efc2beac6acdc39a7249c36
0x62a1bd4f15aac0eebeb64522266df1917c6e6f1d
0xbb5113d9d3179f7d9b0f18fe5f36fe83b114baea
0x363e3018ce9b1b1a5b1add482d5e38211bb35104
0xef5a918f73b7efe793aff167066eb14176de7818
0xbcc31e495fa01b47f4fc6eefc9aa55e810f655ef
0x7c4c5d05892e08f2ad993680a41e99fa06c55c91
0x06b82a2245b0b9f1a646c73de2829ec8001dd60f
0xda4cfa332c0da88c6db56af1ef9f02db132a86b7
0x1c81a786b3c75f5cde022ef606125ffad76bb488
0x4ec078fd99d505bf065f168ebc6ab320f5e6784b
0xe56bd2436d654bfba5662f98dd5f8f56cd30e65c
0x2e5601e52912bfed0586efa03d1134f1bc2d0d51
0x3245fc8048bcfff0ce817d382ed055d7f32280f1
0x295741596e4efc554e9a594b320856391806ab0d
0xa1f1a1be380eb051951bb93e27d106fdc6288830
0xa5a2bb7cbc87125c9547ad6b4bf501ef475880d8
0xf7ecc070e11f8e920e30320d208fbc7a50e18ef6
0x278e74840d59f8e960c8437e559772042d425874
0xcf1f4e11f1f4b06540af472e1c9c7875ecdf4a61
0x31a3d20eced9a4100523a01cd71992ae3aafd796
0xa2f9081571bd29a789679711f2242800e6e9ee3e
0x129ba73fb77fc10adf536024f4c8140d265bf814
0xc2d9fee27cce4e1528cb1a81a1e7e27b7dafc849
0x8a1fdb9a7ffad35f503d4f07e90146570f26e1ec
0x68bb3957960dbe9ce1cf511dda9ea2f4e26a453b
0xe0f950c83cea100ee8d169d260dac7db854a1712
0xc0e451b6809704565f6f6a74eac08a8bf85f5722
0x4d78fd24ad93df7a5735f91f201c577f6e7a30db
0x8344b527cfa8154617b21eafb341d1cad89a6935
0x1d9d724f42d6cfd7c8265d29fe52fba099f796b2
0xbdb385ee06d1c56b96ec1a49a81fce73ab4157d0
0x09b8b2cb7fa38eb22cb5544036d6166f479288fd
0xfa5981c785bcff8e7ae6707ef76b06d2fb51dc8e
0xa9deba418754ac4cc0a7cb5c92662f76a711027f
0x31f9dfe538384ded98ae409d2bad85eb094aaaec
0x74164987ef332b510b4216ea61bfc7752894c47b
0x03c0c1c9caff8f05da035f0cd8e583b829ac4437
0x685f7f2e06f60fcb6f3c99f77904cdc642215610
0x54d7fa9fe756730aa38123b6927b1c4cf0d96ddd
0x726e82a460f9d81cd08132e793e87d43eb6819d2
0x48fbf1d91a0c945806d0f500cdfffc9e005c5c80
0x094378b5fdb80ed4e988741044eb97f5c506ef36
0x9d8d1b2502938df8ef665f5297c0b0943d8975b9
0xbf1c1b7be84178fcba1bad33e193ee0bdb27402b
0x9ef20371af0607b1413ec59bc4442d7ed7913c6f
0x30e874c72f952dec7f57bdf679c8366828281357
0x81d3ff6c2a815a460ff371fad3f98e424ffd9bf8
0xafd55bff9b803c673e05bf623d58bfaf7adb8bf5
0x7fcd8cd3af2e7fa0f7a606f54fc20be0d888bdd6
0x4b017c2066b1c9dd06d74334d1aa27c56c173fa4
0x24f6ac3410b08502d6af2eed813df2606415a4c4
0x0cdff9c2b774a6ca860c8716cfbc0f049ced6625
0x60b5ceb25a5cb5b5551b911db66e3df65cbf80db
0x1ea760edc6451359c4670b7717ef158dbe3226cf
0xaab64a0300472f8dad581c346acfa8d783a35ffa
0x1e34208179a0494d0ffa5208c061f50f22a00793
0x5e1eee4eefe0013054483a6b6a5bd06c34f26b1e
0x349e55513a866c7a40cacc13ff427e04d9532430
0xef165005db5b820d0b99336414f8e40043121672
0x33b3ffcde0bba668099eb117dab88e4ab8615b78
0x314a565c67c841ef46569998412bbe810332ec77
0xb27f87b817cf939a9d41c7f31eae0876e83b1d9b
0x1b5b782d9b46ba6429c71c8008b6706f934f5ccd
0x1830cf5e5b7884200fe5fb5c6bf1c2b512130b00
0x35e0f794465a23060361f8b6a816b817b45e4b69
0xb9994802bd6f18bc6631252f91ffc79e5d0138d6
0x5d2d8e02cbf0ecc6606776328ec9486b3b3541fc
0x57a2f64898486d29d52e223918d82a419afde6e1
0x4c607b1c2fd8d91ee9f464aef72b0006ad6c97cd
0x5c36a8fe602a21728eb511382c7a2b9ccfb16558
0x7ff108128cd50fcb923466d722bf2d31662aedeb
0xe48f16de8c03aadbd644530dddf4e2324343d40b
0x2ead0c5dd74b73d6494568b79c801f8dc987e1bd
0xf881f3a88f166d28e6cc8b7193873251a9bd20e1

# Reasoning

All these addresses (and others at the link) were attacked by a virus specializing in Sybil - 
https://dune.com/queries/2962943/4909102

# Methodology

The reported addresses were discovered by checking irregularities in the number of bridge transactions made via Dune. The resulting addresses were analyzed to find repeating transfers at standard intervals and sequence.

https://dune.com/queries/2962943/4909102

# Rewards Address

0xc3a3C29F6656B9435a5DFf1C874E5c33531fDd4c

**Comment by Grraarrgghh** [comment]
Virus/botnet controlled wallets?

**Comment by prosto93** [comment]
> Virus/botnet controlled wallets?

these guys used Sybil software. They are all similar. They missed something and got cut
