### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by lehoaivsybil** [connext/community-sybil-reports#232]
# Related Addresses

0x42d2184dac8580e6224b361a36ca3a917f7ea67b
0x30aB3C4C1fdaE40146D990F8dDACF456cF72a50e
0xf6A11C6f1A6307122AFa11acad33d4A2027Af154
0xcd389Cf4f0cd5b3C3f0d103C898099A959316528
0xf0944415Ec94eE9036E268115CC565cAC1bef93B
0xe358cf0540578a9cb3021088520f59af46d387de
0xb5cc53be3e586ce7f85034398a6031d32f8ca180
0xc3e357a84b29670f5a0c066a61d1658b4a70c800
0x806e3318419fc1b942bfb7804d9d4e12f7424006
0xc010b6AB4D5FDb22B5DeA72afbF5d22431Ec5D50

# Reasoning

I saw sybils tried to sent 0,1eth from main account 0xc010b6AB4D5FDb22B5DeA72afbF5d22431Ec5D50 to 9 sub accounts on Dec-14-2021 12pm utc. Checked on Optimistic scan.
All sub accounts also removed connext liquidity on same time May-15-2023 11PM UTC
All sub accounts also add onnext liquidity on same time May-10-2023  9AM UTC

# Methodology

https://optimistic.etherscan.io/txs?a=0x42d2184dac8580e6224b361a36ca3a917f7ea67b&p=7 sybils sent 0,1eth to sub account
Example 1 address:
https://optimistic.etherscan.io/tx/0x113e62247a8c41957095362e0a6bd5334d7038b40b77f9d95379f94fafd7fd5d add lp
https://optimistic.etherscan.io/tx/0xff5bcb70ca476b140c6989b617a26a220e969d15a0db035eae9fa0090b5293bc remove lp
Same on all sub account

# Rewards Address

0x7a3507ee691a30133392CC7397c4B8Bc987A6ab7

**Comment by lehoaivsybil** [comment]
All above addresses have the same type transactions,same time of transactions . Checked on optimisticscan and connextscan

**Comment by lehoaivsybil** [comment]
I found all above addresses earlier than everyone
#133 #217 These owner issues copied above addresses and add to these issues by editing issues to become earlier.

You can check edited versions on their issues. I reported above addresses earlier than them. But they edited their issues and add above addresses to become earlier than me @ArjunBhuptani @Grraarrgghh 
Please consider carefully connext team

**Comment by Stakeridoo** [comment]
Hey @lehoaivsybil I have a list of 6567 detected Sybils, unfortunately I can not upload them all in once and needs time to make for all screenshot etc., so if you was first and I updated later it was for sure not with purpose.
I think you reference to my cluster 5, and there is a difference, I have 12 Wallet's and you have 10 Wallet's. I asked earlier in the Discord how this will be handled special when I add them later but didn't get a clear response only that they will lock into.

**Comment by lehoaivsybil** [comment]
Hey @Stakeridoo @wisecrypto
Please remove all above from #133 #217  to avoid misunderstanding
Thanks

**Comment by lehoaivsybil** [comment]
> Hey @lehoaivsybil I have a list of 6567 detected Sybils, unfortunately I can not upload them all in once and needs time to make for all screenshot etc., so if you was first and I updated later it was for sure not with purpose. I think you reference to my cluster 5, and there is a difference, I have 12 Wallet's and you have 10 Wallet's. I asked earlier in the Discord how this will be handled special when I add them later but didn't get a clear response only that they will lock into. Between our reports there is 4 hour difference so when I made my first checked your report was probably not even online and I startet to report.

What do you mean? You don't think I not reported above addresses before you?
The rule of sybil hunter program is fcfs. I reported all above addresses earlier than everyone. Why don't you remove  above addresses on your issues to avoid misunderstanding?

**Comment by wisecrypto** [comment]
@lehoaivsybil 
My report have more wallets. So that i will not delete it.

**Comment by lehoaivsybil** [comment]
@wisecrypto  @Stakeridoo 
I don't say you need to delete your issues
I only want you edit and remove  above addresses which existing in my issue to. avoid misunderstanding.
0x42d2184dac8580e6224b361a36ca3a917f7ea67b
0x30aB3C4C1fdaE40146D990F8dDACF456cF72a50e
0xf6A11C6f1A6307122AFa11acad33d4A2027Af154
0xcd389Cf4f0cd5b3C3f0d103C898099A959316528
0xf0944415Ec94eE9036E268115CC565cAC1bef93B
0xe358cf0540578a9cb3021088520f59af46d387de
0xb5cc53be3e586ce7f85034398a6031d32f8ca180
0xc3e357a84b29670f5a0c066a61d1658b4a70c800
0x806e3318419fc1b942bfb7804d9d4e12f7424006
0xc010b6AB4D5FDb22B5DeA72afbF5d22431Ec5D50

Do you recognize I reported above addresses earlier than everyone?

**Comment by lehoaivsybil** [comment]
**In case Connext team need more information to review**
As I said all above addresses have same time add lp( May-15-2023 11am utc and May-10-2023 08am utc) and and remove lp(May-10-2023 08am utc and May-15-2023 11pm utc) ,can check that on https://optimistic.etherscan.io/
Example:
https://optimistic.etherscan.io/address/0x42d2184dac8580e6224b361a36ca3a917f7ea67b
https://optimistic.etherscan.io/address/0x30ab3c4c1fdae40146d990f8ddacf456cf72a50e
https://optimistic.etherscan.io/address/0xf6A11C6f1A6307122AFa11acad33d4A2027Af154
Can check on all above addresses,same add and remove lp transactions on same time.

Check one more time on avalanche chain,we can see all above addresses received first fund from 0xa16f524a804beaed0d791de0aa0b5836295a2a84 on Mar-24-2023
All above addresses have same type of transactions on avalanche time on same time.
Example: 
https://snowtrace.io/address/0x42d2184dac8580e6224b361a36ca3a917f7ea67b
https://snowtrace.io/address/0x30ab3c4c1fdae40146d990f8ddacf456cf72a50e
https://snowtrace.io/address/0xf6A11C6f1A6307122AFa11acad33d4A2027Af154

**Comment by ArjunBhuptani** [comment]
Hey guys - no need to fight. We're recording all addresses with the timestamp of your github edit and they are being sorted prior to finalization.

**Comment by A-Keyboard** [comment]
@lehoaivsybil Can you dm me on Discord, my discord is khlilo

**Comment by lehoaivsybil** [comment]
> @lehoaivsybil Can you dm me on Discord, my discord is khlilo

I am from Discord 5765CVC6
