### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by prodwamkn** [connext/community-sybil-reports#233]
# Related Addresses
0xcf5D55B15B72cd0359801d1F5Cd161f94E68eF74
0xf2A1019766Dbee12347Eae8dBcDB4Ce6eDc80188
0xe4fA90d3124521a176dF09120f7F424B200577C8
0xAFDa7FdACD7163c21175f2229dd3cAAdb6222BFB
0x7fafd93Bc7a3FBf68DA92534A09Dda5E1A321426
0x6194f55b24D7Eb5754Ab2fed2A41246805ff779d
0x0437401Ac43c86823B850F38f8A5dFab4BA30B49
0xd66058f6b558Ae6f05FB631261E0C42aaf607A80
0x46767Bd877fCC80A3C9d2DB53B2f54648C13E89e
0xca0EaA022C244740Ec668AaCA31adB008EE2Aa33
0x3968Ec3E9FBa54eD125Cd26ac3DBaE8966ca6DFB
0xA0986be920D0bAcbB761c68e49bDC2ff6475ddF6
0x9B4c8B2326a3f54bC51ef1EdE9C8021716526FE4
0xF4694312B3AeC07171a3f6567710e714D8cb6D71
0x5d05853b5eC0B17484d32376E156Fe3e65e273D9
0xB2564EEdd2D812b190D164277c9057b89B2655dB
0x1A8af7aa47227D010aEE489e968B08Ba87eF855F
0x1B8716fAD6c8e9Cd931e7897F32F7c640bc0ed8e
0xA3AA30a27E10A45f1808405663173F09BFCA7913
0x8e1c604a1b1776Cb647C31D15F2fb66eAd5D3477
0x57096652FdcfDF58e9A9466A066a1BAEd26D56C7
0x23D34df874a9b3FEA78edAcE54c190d375B49C34
0x45190Aa403b7eD021Ac79B8dEA3152AD39368E06
0x1a37FFC7A8E5b92BE9cF8c229FAf25498eea8f30
0x85Cc79b6781d25ee9538A1e7A9cf032788733719
0xb8B1FBb57ea3520d8Eb81228620CC29ddC38A884
0x46cEdEfDb52863F058AAE9E002c3B21843c9c528
0x79378c0ccB671bFb6D369c4D399Cd2f37a1dEb77
0xeA20C39a67F1b52bA46Ec14e532F79C659b9EEa1
0xaA2D13b7e04bf16A654aae2D6F37B1A32C65130a
0x49af2Cde5182983593a08350419784dBb1C274b9
0xA92f7eeb73d39B6f739750e21232136CD2D5B721
0xd775fCac21C680B44a74408e79821de2775ff428
0xB3A58807D7499030aF4d15E32a555cFA8A396308
0x6e486aDD9BD0fa4115Bc20Da7456cd579d7F12bB
0x0D003E8821ed1405cd692CF27428C2d52Fe9538B
0x423d64f97a6935F8876899B0aE82A83ed2356507
0x1e3497db29DDCBdEb3f7E7BA649391527ceaFc5e
0x1A6285092bf8075a34267Ce1f8E10f673449CDc6
0xdEABcE8bcbf80a896Baa08225dC1dbB5792658AC
0x9C225fC60A692f233d3D6Ee7Ca48c4Fb9C0adD24
0x42B103D674165ACe6C64e471f1B9B0223C8eAb90
0x810fe6777AB7B6Ad71A32a4078c2e4D8bfa9a880
0x647638aF3a6c31d36d265cAb9030C920357A0Da3

# Reasoning
Exactly the same pattern of actions on all accounts. In connext deposit dai and nextdai in arbitrum network , the same actions are performed , also if you open all accounts in debank and arkham you can see that it uses the same contracts now its zksync contracts and base , also the same nft in 4 networks 

# Methodology
To find the sybil I took the address and went into arkham visualizer and saw the same pattern of wallets 
Let's take the first wallet
[1 wallet](https://platform.arkhamintelligence.com/visualizer/entity/0xcf5D55B15B72cd0359801d1F5Cd161f94E68eF74?flow=all&positions=%7B%7D&sortDir=desc&sortKey=time&usdGte=0.1)
Let's go to any wallet related to this for example - 0xf2A1019766Dbee12347Eae8dBcDB4Ce6eDc80188 
[2 wallet](https://platform.arkhamintelligence.com/visualizer/entity/0xf2A1019766Dbee12347Eae8dBcDB4Ce6eDc80188?flow=all&positions=%7B%7D&sortDir=desc&sortKey=time&usdGte=0.1)
Let's take another one of any wallet related to this one - 0x91b574FDed060b35E4d61e6baA9aE87c3D420800
[3 wallet](https://platform.arkhamintelligence.com/visualizer/entity/0x91b574FDed060b35E4d61e6baA9aE87c3D420800?flow=all&positions=%7B%7D&sortDir=desc&sortKey=time&usdGte=0.1)
**We see exactly the same actions for clarity I will add 6 wallets in one block** 
[Pattern 6 wallets](https://platform.arkhamintelligence.com/visualizer/entity/0x1A8af7aa47227D010aEE489e968B08Ba87eF855F,0xf2A1019766Dbee12347Eae8dBcDB4Ce6eDc80188,0xe4fA90d3124521a176dF09120f7F424B200577C8,0xAFDa7FdACD7163c21175f2229dd3cAAdb6222BFB,0x7fafd93Bc7a3FBf68DA92534A09Dda5E1A321426,0x6194f55b24D7Eb5754Ab2fed2A41246805ff779d?flow=all&positions=%7B%220x1A8af7aa47227D010aEE489e968B08Ba87eF855F%22%3A%7B%22fx%22%3A1%2C%22fy%22%3A-32%7D%2C%220xf2A1019766Dbee12347Eae8dBcDB4Ce6eDc80188%22%3A%7B%22fx%22%3A-3%2C%22fy%22%3A76%7D%2C%220xe4fA90d3124521a176dF09120f7F424B200577C8%22%3A%7B%22fx%22%3A-13%2C%22fy%22%3A50%7D%2C%220xAFDa7FdACD7163c21175f2229dd3cAAdb6222BFB%22%3A%7B%22fx%22%3A-5%2C%22fy%22%3A16%7D%2C%220x7fafd93Bc7a3FBf68DA92534A09Dda5E1A321426%22%3A%7B%22fx%22%3A-5%2C%22fy%22%3A-5%7D%2C%220x6194f55b24D7Eb5754Ab2fed2A41246805ff779d%22%3A%7B%22fx%22%3A34%2C%22fy%22%3A115%7D%2C%220x23D34df874a9b3FEA78edAcE54c190d375B49C34%22%3A%7B%22fx%22%3A37%2C%22fy%22%3A74%7D%2C%220x9B4c8B2326a3f54bC51ef1EdE9C8021716526FE4%22%3A%7B%22fx%22%3A30%2C%22fy%22%3A88%7D%7D&sortDir=desc&sortKey=time&usdGte=0.1)
**And they all use Opensea Victor Kim collection so I guess that's how some of the balance is distilled.**
I'll assume his primary wallet is  - **0x9B4c8B2326a3f54bC51ef1EdE9C8021716526FE4**. Because it's connected to most wallets

# Rewards Address
0x900c8B28FE52e03A8c4CB85E8f30ceE2000628F2

**Comment by prodwamkn** [comment]
**Found another sybil with 3 accounts**
all interacted with each other through disperse and directly at the bottom of the arkham link.
0x9Ea8cE3Bc0f460e496e0Bc9fC457D9c05Ee7C031
0xeaBD185058C6212413D0A4c71E63Ada0C6EdC767
0x4427B20b769ccE775833A7bAaaEF887CaA223d03
**Also identical patterns 2 and 3 wallets that are mults of 1**
[An example of one of the transactions through the disperse](https://platform.arkhamintelligence.com/explorer/tx/0x0e2d2e0cc4e2cd153d0f934407e9742003008c03cd90d549cb7677d34425f839)
[All three wallets see direct connections and interactions with disperse and connext bridge](https://platform.arkhamintelligence.com/visualizer/entity/0x9Ea8cE3Bc0f460e496e0Bc9fC457D9c05Ee7C031,0xeaBD185058C6212413D0A4c71E63Ada0C6EdC767,0x4427B20b769ccE775833A7bAaaEF887CaA223d03?flow=all&positions=%7B%22disperse-app%22%3A%7B%22fx%22%3A-142%2C%22fy%22%3A-13%7D%2C%220xeaBD185058C6212413D0A4c71E63Ada0C6EdC767%22%3A%7B%22fx%22%3A-42%2C%22fy%22%3A177%7D%2C%220x9Ea8cE3Bc0f460e496e0Bc9fC457D9c05Ee7C031%22%3A%7B%22fx%22%3A19%2C%22fy%22%3A34%7D%2C%220x4427B20b769ccE775833A7bAaaEF887CaA223d03%22%3A%7B%22fx%22%3A-214%2C%22fy%22%3A137%7D%2C%22connext%22%3A%7B%22fx%22%3A-142%2C%22fy%22%3A46%7D%7D&sortDir=desc&sortKey=time&usdGte=0.1)

**Comment by prodwamkn** [comment]
### Related Addresses
0x19cbE930328A649Ae0BB207773C74e8c6151e475
0x7674188d8fa2fFEa8c01E9C324c088337FB672b2
0x5f1f8031545Da171E450c827E8C1f2B9a9F15Af7
0xBE80dDdA3FB2Cc53c3Bc4c39Da8631C538D16a3b
0xC4554066c824f725F15392349abaf61094B2Bf73
0xc6fd29AcEDa56598f9734A03197C67D6e1A586D5
0xF9Bae7459Ad3a296cFd5FDf20738C2d0415a9aeD
0x3060fC49F746891748D09A48ECFE4036f7a9B647
0x5Eeb3A8819f8753aDeE6049647Ab783965481E45
0x552359d1eD25158ccd7E3156661fb718c181AF36
0xcd9F9D54F7550bBB87F6C7054a7FC31953921285
0x12bB6c8EC9dFa57779D4c877a95002D3Cf1FDD6d
0x1D1Fb93Ba0e68Fa693C6270f40Ff3A66F3e62a3e
0x9b42a4d1A84211224be1B54B08628287108A0144
0xa9347cbE2fb678Ec141f9fDd890Aa27C997be36a
0xeAfF2D91831BAd18A56120Dd528fad2947211Fe2
0xf4faF3d78C5B832Bdd836679FfBB77C88fCA6640
0x33C10d6cEaE9b0D080F30B69caBD6a6CD07f87C9
0xa97B0AE8ab3C403683ad4af84EFA6BB1615cd503
0x8c12c947e6F346BFDabf724d6c7b051136B368a8
0xBe77905eC30f5467E0Ac22B54DDd2b44BAeDb715
0xFe8B1DD7fc3D570Bcc83759BDf31D9C679F757Ce
0x0EfEbD575C967Ad2637114297F7a581fD489D162
0x046C1A91C1A8054e42fBde05321f5b8Bfa0D8375
0x844CC2dE3FA1D786cB31aa383E25fa4078349573
0x624A2D47BB14fb5B091779E95Cc4460C497dbE3e
0x81B8F6EBB344a5fa3F21b1DBaBf9d028f7158F60
0x50ead3D4D414492B189fe1d7271200BC92E9E9D7
0x851222206e5dA763F2D4040DBaD328f5fF4C5037
0xa3604E2655c773390fd709a7c2D2Bd2a4f2D2bd7
0xE17B603656b22A99C46DCF9365FEC0419c9aB50F
0x9BAF9f3D333b4e91a8095cE324abb066E09e41B5
0x11f96A1BF3b067025519B79B2B209240fe215853
0x53B0326695E04cf26BFe588652b839C02C762551
0x6e0bA02114274940FD20e36D2813d045389074DD
0x796Ed1F420b71F223d341C58278253eBE3297b33
0x3e4C8F253a42F7EbBf95b8D52a16a9BD0F5e73f4
0x41Cc35dA5dc1305166f1DF127E768b2248557521
0x4A1708373Ef05C292BcA12E28Fab5389c08cf5Ad
0xBf793B364682e141F777007Fd84aeA9523BC6624
### Reasoning
exactly the same pattern and amounts
### Methodology
arkham , took one account and began to unravel the chain is not difficult to guess that it is one person interacts with the same protocols below I will attach some of the addresses in visualizer
**0x81B8F6EBB344a5fa3F21b1DBaBf9d028f7158F60**
[1 wallet](https://platform.arkhamintelligence.com/visualizer/entity/0x81B8F6EBB344a5fa3F21b1DBaBf9d028f7158F60?flow=all&positions=%7B%7D&sortDir=desc&sortKey=time&usdGte=0.1)
**0x50ead3D4D414492B189fe1d7271200BC92E9E9D7**
[2 wallet](https://platform.arkhamintelligence.com/visualizer/entity/0x50ead3D4D414492B189fe1d7271200BC92E9E9D7?flow=all&positions=%7B%7D&sortDir=desc&sortKey=time&usdGte=0.1)
**0x81B8F6EBB344a5fa3F21b1DBaBf9d028f7158F60**
[3 wallet](https://platform.arkhamintelligence.com/visualizer/entity/0x81B8F6EBB344a5fa3F21b1DBaBf9d028f7158F60?flow=all&positions=%7B%7D&sortDir=desc&sortKey=time&usdGte=0.1)
**0x624A2D47BB14fb5B091779E95Cc4460C497dbE3e**
[4 wallet](https://platform.arkhamintelligence.com/visualizer/entity/0x624A2D47BB14fb5B091779E95Cc4460C497dbE3e?flow=all&positions=%7B%7D&sortDir=desc&sortKey=time&usdGte=0.1)
[6 wallets](https://platform.arkhamintelligence.com/visualizer/entity/0x624A2D47BB14fb5B091779E95Cc4460C497dbE3e,0x81B8F6EBB344a5fa3F21b1DBaBf9d028f7158F60,0x50ead3D4D414492B189fe1d7271200BC92E9E9D7,0x851222206e5dA763F2D4040DBaD328f5fF4C5037,0x844CC2dE3FA1D786cB31aa383E25fa4078349573,0x046C1A91C1A8054e42fBde05321f5b8Bfa0D8375?flow=all&positions=%7B%220x851222206e5dA763F2D4040DBaD328f5fF4C5037%22%3A%7B%22fx%22%3A-28%2C%22fy%22%3A-18%7D%2C%220x624A2D47BB14fb5B091779E95Cc4460C497dbE3e%22%3A%7B%22fx%22%3A-1%2C%22fy%22%3A-28%7D%2C%220x81B8F6EBB344a5fa3F21b1DBaBf9d028f7158F60%22%3A%7B%22fx%22%3A23%2C%22fy%22%3A-20%7D%2C%220x844CC2dE3FA1D786cB31aa383E25fa4078349573%22%3A%7B%22fx%22%3A26%2C%22fy%22%3A6%7D%2C%220x046C1A91C1A8054e42fBde05321f5b8Bfa0D8375%22%3A%7B%22fx%22%3A-31%2C%22fy%22%3A7%7D%2C%220x50ead3D4D414492B189fe1d7271200BC92E9E9D7%22%3A%7B%22fx%22%3A0%2C%22fy%22%3A3%7D%2C%22connext%22%3A%7B%22fx%22%3A-48%2C%22fy%22%3A50%7D%2C%220x%22%3A%7B%22fx%22%3A37%2C%22fy%22%3A55%7D%2C%22slingshot-finance%22%3A%7B%22fx%22%3A-4%2C%22fy%22%3A60%7D%7D&sortDir=desc&sortKey=time&usdGte=0.1)
### Rewards Address
0x900c8B28FE52e03A8c4CB85E8f30ceE2000628F2

**Comment by ArjunBhuptani** [comment]
Cluster 1 and 3 valid. Cluster 2 too small.

**Comment by A-Keyboard** [comment]
@prodwamkn Can you dm me on Discord, my discord is khlilo

**Comment by prodwamkn** [comment]
> @prodwamkn Can you dm me on Discord, my discord is khlilo

1655
