### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by nikolas88888** [connext/community-sybil-reports#245]
# Related Addresses

 0x760abcb76dc592113e1b8757711c9067dd85e7b3
0x983bee954f9556e7a64fc60be537b1f40a4cf14a
0xc68a658f6f85329ad9bd4345d3a03dacb0a1ae31
0x5f3b6acf9dd08f46e8ebe8cbec3927ebb2853028
0x5604e27a759c78d1ebf33aa6327aa2deb30a4ed8
0x7003d62e923e647658d274bf967b47696a69e574
0xe4deac4c2b075ee64814483d9038daaf83542f71
0xf730572ad4dd4d62da7beeb3dbb858e460edc68b
0xb0d078d875b75d56c4736506ecba6f6708bd8578
0x060dab069ab2877a06ffcb2ad4f7cfc583bb5ecf
0xeb9d16b9ce4a749fe792f7fa84b52caeaa44bbab
0x06eed51e4c6abc5f665dee49bf8c72eeb9fd9d48
0x5FFa959eAca894E0Ae2504e6e0c542eC4ae55e56
0x483034ddc7f555a48c939df1d0f3bdd7c9af043c
0x5319af7ee6e9fb412e0374bb0ae6e409b1a1ad01
0x81b0cbbbc1a69bd7ceca46a61684103bd9a6fb21
0xb4a2b428f5f46772abc83b553e4ed7bc6e096378
0x38c7e7478696a60c887411cdec8c0f976ae4a93e
0xf1134df0432bbe85d0e325a0cb69fdafe76fb724
0xb4da408106a7545130e64c559ecb65fdce8c21ef
0x90e6fa98cd6af3249b4a37b9b26c12d2f5f12fb8
0xb4a2b428f5f46772abc83b553e4ed7bc6e096378
0x26320fe886f9147eec8023e89a86fbb264450211
0xcdc4a8ffe4c7a604c6985b51c729e9c1f07ca0ae
0x520406029190b07dd68f993bd75e65d22a75d8da
0x824381c0363d21452093797ef3259fc1271789cf
0x8d23c803b8d3db7439c16d0b82199c0763aa9f8d
0x8ab2dc94f8eedd3c2a9f1c524b2f74eae771099b
0xd4a7385d50fa958d66d0df590e3204211a6027e0
0xb302560a220d1adcc69c5f8d19279f572555b01b
0x8beb4c2e9f5f9651a8bcbac6ee050b6906cb26b5
0xd95738db635043e417a84ad199516770a779b4da
0x3bc4dafde6d2f748e8966f1da21275a8c511bb28
0x9ca2a3191c069c390e24bcb0ec4489ace688095a
0x0b83ba16f4b69147852ca47a9db3b88c1b40404c
0x3cbecafdb1ba14e85cc401a1d99f6b87dd40ebd7

# Reasoning

 The addresses appeared highly suspicious due to their synchronized execution of identical transaction types, all occurring simultaneously, and a consistent pattern in the order of their transactions.

# Methodology

I came across these addresses while browsing PolygonScan, trying to identify a pattern of multiple identical transactions occurring simultaneously.
<img width="901" alt="Снимок экрана 2023-08-25 в 9 38 49 PM" src="https://github.com/connext/community-sybil-reports/assets/116903646/d921805a-8a7c-4c16-b566-24d7b728c058">
<img width="943" alt="Снимок экрана 2023-08-25 в 9 46 32 PM" src="https://github.com/connext/community-sybil-reports/assets/116903646/6407ff56-ab9a-4335-b047-a8dd05f41436">

![Снимок экрана 2023-08-25 в 9 46 22 PM](https://github.com/connext/community-sybil-reports/assets/116903646/dcef9b55-4c55-4f2e-8694-75a89956108c)

https://polygonscan.com/txs?a=0x11984dc4465481512eb5b777e44061c158cf2259&p=199

# Rewards Address

 0xd515cbd2249Bc4861769940e3F31f12611392280

**Comment by nikolas88888** [comment]
0x849f5236804c52274064a8e65d92e11b3a1cec1a
0x4fa4af4863ab38dd2cd60986b094cfdc12b7b31f
0x4f3eb298fc67a3251779a8ab4446c48eac77c89e
0x7f3476f2684d34c6238ca9d225b67a5046977a62
0x16df64e6a049836b3b9ae036b2393b75cac

![Снимок экрана 2023-08-25 в 10 59 55 PM](https://github.com/connext/community-sybil-reports/assets/116903646/42137dbf-5247-4354-af35-9a4fce1d9254)
620f4

0x108328107a84cdc36e7b31b08985e805b3f273c8
0x4b7dbc51bb2dede996c1c64c9aa25b7ecbe989d1
0xa392977e2bfcb654426407f170d133d77854fb14
0xcC0d8f409B149b92c089B5a9177331338671501c
0x578e141720128eafff1261815c85cdfed438b1cd
0xbfa6cb1d06e9c5f8a7ef56b9229adc6ca3f9b90f

![Снимок экрана 2023-08-25 в 11 09 01 PM](https://github.com/connext/community-sybil-reports/assets/116903646/5281b286-1eb2-4a14-b023-75c333b6cf1e)

**Comment by nikolas88888** [comment]
0x6118Ff5540cFf10C8B9b5F224C00A7E1826fF5E2
0x0E4AD76dDE4C015657bbB4722494D8ce494596B2
0xA914a625c187656A03Da7dd9Ed5391D93B3E7313
0x22Ff380987437d83E95D20597e50397129D2Aa3F
0x759D5fb57a77cF45a07b48eE582Df49e008e603b
![Снимок экрана 2023-08-25 в 11 22 03 PM](https://github.com/connext/community-sybil-reports/assets/116903646/561a5d0c-9235-409f-804a-8af03d0441f3)
![Снимок экрана 2023-08-25 в 11 22 03 PM](https://github.com/connext/community-sybil-reports/assets/116903646/041594df-950b-442d-81b3-4c31f4457875)

![Снимок экрана 2023-08-25 в 11 22 10 PM](https://github.com/connext/community-sybil-reports/assets/116903646/baadf96e-dea0-433e-a80f-57ffe56de484)

![Снимок экрана 2023-08-25 в 11 22 21 PM](https://github.com/connext/community-sybil-reports/assets/116903646/bc65b06f-b16f-4c1e-8b98-4c5da6e45f33)

![Снимок экрана 2023-08-25 в 11 22 30 PM](https://github.com/connext/community-sybil-reports/assets/116903646/ffa863dd-fd01-4b86-9916-5542527fc6ed)

![Снимок экрана 2023-08-25 в 11 22 35 PM](https://github.com/connext/community-sybil-reports/assets/116903646/b4490c54-dd4d-4d0d-bb06-a91024c7ec9e)

**Comment by nikolas88888** [comment]
0x6DE24A67FCA8040Fb2301a246f514369811e3Caa
0x35B1C63d6aF0053cD4801Cb8dACA5f38009fd215

![Снимок экрана 2023-08-25 в 11 58 52 PM](https://github.com/connext/community-sybil-reports/assets/116903646/690f1baf-734b-4be8-8fb0-e480b41e63c3)

![Снимок экрана 2023-08-26 в 12 00 05 AM](https://github.com/connext/community-sybil-reports/assets/116903646/1e7d75a2-e838-4681-a0d7-e344d6603f2f)

![Снимок экрана 2023-08-26 в 12 00 29 AM](https://github.com/connext/community-sybil-reports/assets/116903646/74b161fb-26bd-43b1-bd82-d8493052efe5)

**Comment by nikolas88888** [comment]
0x9e82b02E338d3468c7d2A6413738Eb0b04F48230
0xe601eCC3254a02D0614Ab96fDD3D54E5e3A78F0D
0x587d82E031dd3f9899aFc785Efbc5b8a738D4B8e
0x78eea64Ec1f22E8f852A9aEfDC512b002723B649

![Снимок экрана 2023-08-26 в 12 18 17 AM](https://github.com/connext/community-sybil-reports/assets/116903646/78ee8edd-137d-4d5b-adf9-ab7017bf67a2)

![Снимок экрана 2023-08-26 в 12 18 32 AM](https://github.com/connext/community-sybil-reports/assets/116903646/38e7b9c1-bcf5-4188-bb18-02c147533338)

![Снимок экрана 2023-08-26 в 12 18 38 AM](https://github.com/connext/community-sybil-reports/assets/116903646/22849515-a431-483d-8ae7-5b13d1923948)

![Снимок экрана 2023-08-26 в 12 18 43 AM](https://github.com/connext/community-sybil-reports/assets/116903646/b04e1855-70c8-4b58-82ba-46e8e9d9d6c1)

![Снимок экрана 2023-08-26 в 12 18 50 AM](https://github.com/connext/community-sybil-reports/assets/116903646/8d7b836b-60ad-4518-b89e-29164f7efaab)

**Comment by nikolas88888** [comment]
0x01BB1D3AECa59e770cbBf02496A8f6f6cEF44164
0x855965D2770fe6c073FcCFB4CC22e5F6C3A81F62
0x8Fe653787a38a11C5e65D7957925571E6926DB32
0xf0FB9dBBc425dEB464b84D16E2DF0D9C754ec33C
0x5Cf8622a1A9D79e8a5c8B061498019165D0b4fCd
0x7cE9d66f526dB0E081CB54fA79FAa126795E09f2
0x1F6554217877592605fCbD47c5cb0FA50af040ed
0xD78769f4b18b2CA9575F999cBF4C2cFeDF90D3ec
0x29db6E5b6a42F336Ae258f03e483cA8CCD2139e6
0x172AD449704370C797BcDd2d40e8C5D42BFbBBe9
0x43952d1A193fea86c278D0F944A3E62B2d81a8F2

![Снимок экрана 2023-08-26 в 1 06 48 AM](https://github.com/connext/community-sybil-reports/assets/116903646/983056ca-8e41-4928-89de-5143185364ee)

![Снимок экрана 2023-08-26 в 1 07 26 AM](https://github.com/connext/community-sybil-reports/assets/116903646/7cdcaa1e-e658-4d95-afd7-5d233081f61c)

![Снимок экрана 2023-08-26 в 1 08 15 AM](https://github.com/connext/community-sybil-reports/assets/116903646/f5f7ea0c-8aba-4e4f-933c-036aff99076a)

![Снимок экрана 2023-08-26 в 1 07 47 AM](https://github.com/connext/community-sybil-reports/assets/116903646/a65356b7-9425-4008-8509-a80b2c86c77b)

![Снимок экрана 2023-08-26 в 1 07 33 AM](https://github.com/connext/community-sybil-reports/assets/116903646/ffe3daf9-a1d5-498d-8ca9-b0a88908aaae)

![Снимок экрана 2023-08-26 в 1 07 56 AM](https://github.com/connext/community-sybil-reports/assets/116903646/47ab6cbe-5e32-4157-b99a-5a9dc64b20c4)

**Comment by nikolas88888** [comment]
0xeEA1B646C62aC2Fa68aA0F8516521075c998C906
0xDeDD2899c6FF5CAFA755D8bC467F221E9834B7Be
0x1Ea0f6Ae11B5376B04a4ee17145BaAdDC00F30Ba
0xBa8B41EA2C131B156aA9a5226038869162A62D06
0x285810Afd4DC705397E6F57107220f7925E285dF
0x690DB8761e955E5Ce31A44E10c84EE49dB26e3f1
0x83e734c2b9795b7A7878eebdd27D29Cd02DA60D4
0xC4a423F3BE737a4afb0BcEd588b109B7FBd44B38
0xCBE25321f5cC59a32f8249599446F8Bcd614A190

![Снимок экрана 2023-08-26 в 1 57 44 AM](https://github.com/connext/community-sybil-reports/assets/116903646/cf74c43c-9bbf-4429-941a-014fd965ea9b)

![Снимок экрана 2023-08-26 в 1 58 45 AM](https://github.com/connext/community-sybil-reports/assets/116903646/b898b075-b012-4b95-a658-4fe7e756aa96)

![Снимок экрана 2023-08-26 в 1 58 57 AM](https://github.com/connext/community-sybil-reports/assets/116903646/9e46845d-ac67-4467-94cb-ae344b8e7aaa)

![Снимок экрана 2023-08-26 в 2 02 32 AM](https://github.com/connext/community-sybil-reports/assets/116903646/e52bcdf9-59e3-4bad-b239-5c2993be5bd9)

![Снимок экрана 2023-08-26 в 1 59 53 AM](https://github.com/connext/community-sybil-reports/assets/116903646/f83fb95d-f789-45e9-a37c-4c40d3aeecd1)

![Снимок экрана 2023-08-26 в 2 02 37 AM](https://github.com/connext/community-sybil-reports/assets/116903646/a6ef2a31-8076-4614-850d-8e0342568409)

![Снимок экрана 2023-08-26 в 2 01 04 AM](https://github.com/connext/community-sybil-reports/assets/116903646/f8f70580-2896-45bb-a18d-9b1ad7ec29ef)

**Comment by nikolas88888** [comment]
0x516d7eA8c5CE055F9dF1D2E6532886f78ca560a0
0x9D97228B09749328C05F88541A5c3E502FC8ed73
0x1Fd07bE8D0608a99427f8402Bf584A6dd637e37f
0x93E29d728c0FCFD7eEbe52c0D12C28Be4CE34a75
0x0B0b3E5eBEa0dEba3Ec0eBf759f84C2b65bd34b1

![Снимок экрана 2023-08-26 в 4 27 08 PM](https://github.com/connext/community-sybil-reports/assets/116903646/e34bf2a0-1cb5-445b-b1f4-65dd0ff62c7d)

![Снимок экрана 2023-08-26 в 4 29 46 PM](https://github.com/connext/community-sybil-reports/assets/116903646/da84dc89-aec7-4cc6-a5e9-b8d0f86c8da3)

![Снимок экрана 2023-08-26 в 4 30 07 PM](https://github.com/connext/community-sybil-reports/assets/116903646/9386532f-fa96-4fc1-a794-07e5bb3247f4)

![Снимок экрана 2023-08-26 в 4 30 37 PM](https://github.com/connext/community-sybil-reports/assets/116903646/db99581a-969e-48b8-a13b-b88c82828c61)

![Снимок экрана 2023-08-26 в 4 30 21 PM](https://github.com/connext/community-sybil-reports/assets/116903646/bb21cbf6-f88d-4bb3-94a6-a78451f194a6)

![Снимок экрана 2023-08-26 в 4 30 28 PM](https://github.com/connext/community-sybil-reports/assets/116903646/77263554-9ea6-414b-b628-8d0ba30f2e2d)

**Comment by nikolas88888** [comment]
0x2FdedEdf48B50d1467624811727933499ABa3273
0x1B9DC86Ce3C096963b0096051601ee674a6Ac124
0xCE4DaF676812b3B4A50ed2d022D7AD19F1E1700F
0xCFaAB786126C9a0774a894d2f35730F071552E23
0xbAC74cF83197433DaEd3018A74a7EE85678B6bC9
0xF2C4Ffb11DeA3dAeA9BB7E465fA77F3b7e7d661B

![Снимок экрана 2023-08-26 в 9 57 50 PM](https://github.com/connext/community-sybil-reports/assets/116903646/fd308c7d-50be-4287-b9ba-ab2af4c02208)

![Снимок экрана 2023-08-26 в 10 03 36 PM](https://github.com/connext/community-sybil-reports/assets/116903646/5de471cb-a2e2-40f3-8600-d030f369b334)

![Снимок экрана 2023-08-26 в 10 02 58 PM](https://github.com/connext/community-sybil-reports/assets/116903646/e84fb8bc-aecc-4a18-9e2b-2baa9d1f6150)

![Снимок экрана 2023-08-26 в 10 03 14 PM](https://github.com/connext/community-sybil-reports/assets/116903646/08dcb877-9b00-4ac7-84c0-cbe69be11b6c)

![Снимок экрана 2023-08-26 в 10 03 23 PM](https://github.com/connext/community-sybil-reports/assets/116903646/75c98b91-b3d4-4eda-9060-83d9e55d77b1)

![Снимок экрана 2023-08-26 в 10 03 30 PM](https://github.com/connext/community-sybil-reports/assets/116903646/a5f5deb8-ae0b-4b61-b65f-9810211eb8d0)

**Comment by nikolas88888** [comment]
0x71DCbf17822E0c646be53736b7684b529e565a1e
0xb8274B19cD02EA36EdbaFb10a14C02b0e98c6925
0x87ea8190F9842a9162bAdbA7ce31F5519ed2AF86
0x0e8f0925C0D1E238F1f44BA2985CA7c830599b2C
0xc98F318c43af71F4d2366f893f442f0Ff99D3a4c
0xB6D43Bb5D1E8987048780597092856dC7357272D

![Снимок экрана 2023-08-26 в 10 42 56 PM](https://github.com/connext/community-sybil-reports/assets/116903646/b7848f6c-0a7b-412d-a467-76dfe835dd3e)

![Снимок экрана 2023-08-26 в 10 53 34 PM](https://github.com/connext/community-sybil-reports/assets/116903646/75cb0538-f1d9-4064-a7d3-4ff6c70c8f61)

![Снимок экрана 2023-08-26 в 10 53 54 PM](https://github.com/connext/community-sybil-reports/assets/116903646/2f0c09e1-5c8a-431c-9abf-33e2a4f6ad35)

![Снимок экрана 2023-08-26 в 10 53 59 PM](https://github.com/connext/community-sybil-reports/assets/116903646/9a6bd5da-089a-44f2-a42b-989e4b4b06c2)

**Comment by nikolas88888** [comment]
0xb08f7F5AA7c7bD215a55e6D65A23829b3678506b
0x5edcDdE88926AC331324648b3A613baBfC072dc9
0x73ff9b6d2391a7eAF3Fe697A36F6489A47C6f330
0xeF1755Da5E9e359A6B1D8B8F8cFbE18719582CD5
0x2146dfDd9144D5f327d0556a3d3148DA87342F27

![Снимок экрана 2023-08-27 в 12 34 41 AM](https://github.com/connext/community-sybil-reports/assets/116903646/cdd886e4-36e4-4fe7-96d2-c288d3817ad5)

![Снимок экрана 2023-08-27 в 12 42 32 AM](https://github.com/connext/community-sybil-reports/assets/116903646/4765b1ca-9340-42bc-8d48-92a8ddafaa02)

![Снимок экрана 2023-08-27 в 12 41 46 AM](https://github.com/connext/community-sybil-reports/assets/116903646/7a0e7a84-5859-4d87-9f87-6c78970e5044)

![Снимок экрана 2023-08-27 в 12 41 52 AM](https://github.com/connext/community-sybil-reports/assets/116903646/86827720-ccc5-4337-b63f-be44d5f59893)

![Снимок экрана 2023-08-27 в 12 41 57 AM](https://github.com/connext/community-sybil-reports/assets/116903646/f5bfec64-b168-4151-a3fe-2ac995b906af)

![Снимок экрана 2023-08-27 в 12 42 02 AM](https://github.com/connext/community-sybil-reports/assets/116903646/732841d1-80c9-4ca3-8bc5-13b48551d5da)

**Comment by nikolas88888** [comment]
0x285392cf53f5247123db984a81e79488fb5162c3
0x0e39e0aa2a1d94b33e6694075afc0516aadbe404
0x21c94aba9184da7340f78b94a00b4d5f9724a65f

![Снимок экрана 2023-08-27 в 5 42 43 PM](https://github.com/connext/community-sybil-reports/assets/116903646/a18423c1-d274-4405-b618-2af35e91b2ab)

![Снимок экрана 2023-08-27 в 5 43 18 PM](https://github.com/connext/community-sybil-reports/assets/116903646/4b1184b0-f87a-4bc6-85e7-d3ea5fe801b6)

![Снимок экрана 2023-08-27 в 5 43 29 PM](https://github.com/connext/community-sybil-reports/assets/116903646/1c323420-36c8-47e8-9b72-609ebcaf8a8b)

![Снимок экрана 2023-08-27 в 5 43 36 PM](https://github.com/connext/community-sybil-reports/assets/116903646/643c996c-c2d3-4e24-8e89-2e76b3f6a778)

**Comment by nikolas88888** [comment]
All addresses bellow was top up from the same address (0xedcDa5fB2D1c9ff98F042D974a69a382B027e765):

0x0450acb8f62456e4c2a7f84c5f5a8c229157e2c2
0x69155E7cA2E688ccDc247f6c4DDF374b3ae77Bd6
0x9Ba01dC4E5De13257e9Dfd01fa68132b41d1E766
0x814942045fa68DFB742915422b6a1c0Cd96cF4fc
0x4b040a88cB4Edd02b97F0AB8C97d3da540FC2Cf0
0xe98f0B95292c2c7A3CEe33E091Cc953F0F1C3CBE
0xe8b384917ed2650f06406e7c7f87dd9df0080fd7
0x850d0120c6475092c0ec94236a22c998a35b47ef
0x6aDa6454cD458E230C26E8cbA2Ba18b0b41f041F
0x88B0BE658E72C5518B37cE0A5625D3fD494dBAFA
0xb731c1da69c3bff9b4d13a911895f052a71f19bb
0x92cbe89b5cb1c22c2c16bc465caf34e3c80b617d
0xafC29C2ae80c368A7350766B882b9C891e0c5a06
0xb7eba91e21325d16eAe515948990fbE69e8Cd181
0x1A74d0285a569120AA2836CB2b0fa58038ADB800
0x75be7f29f8241f1bac65a6c5aa5ac4ba9365ba11
0x52c36a5c5181DEC9A46445b5a3b499E74fE438f9

![Снимок экрана 2023-08-27 в 6 39 54 PM](https://github.com/connext/community-sybil-reports/assets/116903646/88f44cc9-8be8-48be-8c8e-251a88caf96e)

**Comment by mnkrdo** [comment]
> All addresses bellow was top up from the same address (0xedcDa5fB2D1c9ff98F042D974a69a382B027e765):
> 
> 0x0450acb8f62456e4c2a7f84c5f5a8c229157e2c2 0x69155E7cA2E688ccDc247f6c4DDF374b3ae77Bd6 0x9Ba01dC4E5De13257e9Dfd01fa68132b41d1E766 0x814942045fa68DFB742915422b6a1c0Cd96cF4fc 0x4b040a88cB4Edd02b97F0AB8C97d3da540FC2Cf0 0xe98f0B95292c2c7A3CEe33E091Cc953F0F1C3CBE 0xe8b384917ed2650f06406e7c7f87dd9df0080fd7 0x850d0120c6475092c0ec94236a22c998a35b47ef 0x6aDa6454cD458E230C26E8cbA2Ba18b0b41f041F 0x88B0BE658E72C5518B37cE0A5625D3fD494dBAFA 0xb731c1da69c3bff9b4d13a911895f052a71f19bb 0x92cbe89b5cb1c22c2c16bc465caf34e3c80b617d 0xafC29C2ae80c368A7350766B882b9C891e0c5a06 0xb7eba91e21325d16eAe515948990fbE69e8Cd181 0x1A74d0285a569120AA2836CB2b0fa58038ADB800 0x75be7f29f8241f1bac65a6c5aa5ac4ba9365ba11 0x52c36a5c5181DEC9A46445b5a3b499E74fE438f9
> 
> ![Снимок экрана 2023-08-27 в 6 39 54 PM](https://user-images.githubusercontent.com/116903646/263539294-88f44cc9-8be8-48be-8c8e-251a88caf96e.png)

0xedcda5fb2d1c9ff98f042d974a69a382b027e765 - that wallet belongs to Clipper Team, they were sending rewards in MATIC to Discord members who win some contests, raffles, etc etc.

In general, I would say that pattern, where some address sending funds to group of some other addresses once, says nothing about Sybil activity. That could be just marketing address, or just some spam transactions.

**Comment by nikolas88888** [comment]
> > All addresses bellow was top up from the same address (0xedcDa5fB2D1c9ff98F042D974a69a382B027e765):
> > 0x0450acb8f62456e4c2a7f84c5f5a8c229157e2c2 0x69155E7cA2E688ccDc247f6c4DDF374b3ae77Bd6 0x9Ba01dC4E5De13257e9Dfd01fa68132b41d1E766 0x814942045fa68DFB742915422b6a1c0Cd96cF4fc 0x4b040a88cB4Edd02b97F0AB8C97d3da540FC2Cf0 0xe98f0B95292c2c7A3CEe33E091Cc953F0F1C3CBE 0xe8b384917ed2650f06406e7c7f87dd9df0080fd7 0x850d0120c6475092c0ec94236a22c998a35b47ef 0x6aDa6454cD458E230C26E8cbA2Ba18b0b41f041F 0x88B0BE658E72C5518B37cE0A5625D3fD494dBAFA 0xb731c1da69c3bff9b4d13a911895f052a71f19bb 0x92cbe89b5cb1c22c2c16bc465caf34e3c80b617d 0xafC29C2ae80c368A7350766B882b9C891e0c5a06 0xb7eba91e21325d16eAe515948990fbE69e8Cd181 0x1A74d0285a569120AA2836CB2b0fa58038ADB800 0x75be7f29f8241f1bac65a6c5aa5ac4ba9365ba11 0x52c36a5c5181DEC9A46445b5a3b499E74fE438f9
> > ![Снимок экрана 2023-08-27 в 6 39 54 PM](https://user-images.githubusercontent.com/116903646/263539294-88f44cc9-8be8-48be-8c8e-251a88caf96e.png)
> 
> 0xedcda5fb2d1c9ff98f042d974a69a382b027e765 - that wallet belongs to Clipper Team, they were sending rewards in MATIC to Discord members who win some contests, raffles, etc etc.
> 
> In general, I would say that pattern, where some address sending funds to group of some other addresses once, says nothing about Sybil activity. That could be just marketing address, or just some spam transactions.

i was not sure about that one, your comment made it clear for me, (deleted)

**Comment by ArjunBhuptani** [comment]
Invalid report - there's definitely sybil activity here, but not all of them

**Comment by nikolas88888** [comment]
@ArjunBhuptani my report will not be consider ?

**Comment by nikolas88888** [comment]
I count about 50+ addresses with clear proofs that they are Sybil. @Grraarrgghh

**Comment by nikolas88888** [comment]
> 0xe601eCC3254a02D0614Ab96fDD3D54E5e3A78F0D

@ArjunBhuptani my report will not be consider ?
I count about 50+ addresses with clear proofs that they are Sybil. @Grraarrgghh those I add first for sure. they start from the comment section

**Comment by nikolas88888** [comment]
> Invalid report - there's definitely sybil activity here, but not all of them

@ArjunBhuptani my report will not be consider ?
I count about 50+ addresses with clear proofs that they are Sybil. @Grraarrgghh those I add first for sure. they start from the comment section
