### ISSUE TITLE
Sybil Report - Incorrect Address Has Been Added

### ISSUE THREAD

**Issue by westonnelson** [connext/community-sybil-reports#249]
# Related Addresses

Address 0xD131F1BcDd547e067Af447dD3C36C99d6be9FdEB should not be included in the Sybil Report. 

# Reasoning

![50Tx](https://github.com/connext/community-sybil-reports/assets/29180454/07a9fa06-d90a-4926-bcd6-1a2f00577ec6)

![image](https://github.com/connext/community-sybil-reports/assets/29180454/3ada940c-4c56-45d5-bab1-3c6b1d410122)

![image](https://github.com/connext/community-sybil-reports/assets/29180454/6a3ce559-de01-47b5-b896-311e10fd3ea1)

Example:

Address 0xD131F1BcDd547e067Af447dD3C36C99d6be9FdEB should not be included in the Sybil Report. Attaching screencaps for review - unsure of which user submitted the report but may be likely they have reported other inaccurate data as well.

# Rewards Address

Please provide an address or ENS name that will receive any rewards earned from this submission.

Example:
0xD131F1BcDd547e067Af447dD3C36C99d6be9FdEB

**Comment by paolitahack** [comment]
Weston of course you are a sybil, with that same wallet you embezzled the Optimism grant to L2DAO and with that same wallet you defrauded people with your NFTEARTH token, you have that wallet and many others that can be obtained in the Optimism forums and Arbitrum of the number of complaints you have, tonight I will take the time to investigate all your wallets to see how many you have classified for connext and I will report them
