### ISSUE TITLE
Sybil Report 

### ISSUE THREAD

**Issue by yazatehnologii** [connext/community-sybil-reports#265]
Rich sybil cluster, 64 wallets liquidity provider

# Related Addresses

0x1de54b3ceb149647ba7417bfb738c6302e8bb57f
0x7ac21d972e8260cd6882bd548f88c248b620c44b
0x4b997e91a086392e4af1a0789d189e935a7485ad
0x49b26fb864d41951bb7cc8aec4b82d90101c4675
0x8f9b13a8eb7b5e32e580ff7ea17a3624677ca246
0x204d6db417420c1f45a399acbd3c622fba3cc865
0x4ce5144d76378196f8109985e8c2ac6563427ea1
0x0eef5b5464de9125df73dd43f63435b76ec42f4c
0x51d2004033743634a56afbeba27a2be193d2dc7c
0x2d58350c8071de154ec3d8aea7b027fd9ce1fdca
0x17473b05bf05ca843716a6dae2398ab1a1e5196e
0x3c00f174d560721e1e0b45a7db847a9d05026467
0x90ce791ffb07da27cca9585eaff47ce2adbb1b24
0x2cf231b57391f74d182b0143d6e797cf6789cdc1
0xa5ce00edc077a4c50069ad7dbbe82562989bc6c4
0xb8c3b42d11ec208ca1a831115943690dd8f7775d
0x350a9c5949fe580ad7770b97a37de330683f3ec9
0x9f3f775907eeda3ebf8c445939cd47b5626f4d72
0x15ab18efacd1152e1aaa0e556bb215ea263e0d53
0x4bfef70d63d382d236b22ac130cb9c66c030d1ab
0x80b4a16f0226dcc607a92213e0545aa155eea108
0x306f9ce5325e5e033d1af43b45c90f27c5219329
0xf0c48130303ed4f34208f9815161bf1ebabed8b1
0x7717835cd61252b30bec8c6522a33297e9eec958
0xc2ab62c4821ceab7a4d14140f0bfa64ac8a3ba1b
0x7fd63a8fc7133354b6c7a26080d864c345adbd9d
0xe9810594eacc66305c03dbf82122049a8e7e346d
0xb140b1bb3b5485fe790eea90ec079a548f12cae8
0xa41a35f602dec103e66b6f4f3fee4e609e58b460
0xd0bb62afcc75be359460f54f0d226c81aacea8ec
0xadd0dff89cb4ea220afa0a25fe901089b8cde106
0x68837bf512dadbdee8cff8a415203a1132f52346
0x396f95e3f0077f9ac74d6bcb2b685b17ebbe9baf
0xc8f9e048c1825b4b5879dc4f2d183375670d3078
0xc38cf11e8e4d41215df6deee2e9c9ec4db16ec45
0xd06cb3bfd8caad74696a97efeec5a10cd918d5c9
0xf142fb3763e5740b6057c52e91fa7b938b95f05f
0xf2111c6f395c2379585895d503d7586ec5295dc0
0x20fc4d551d457edcdcb28f9a5846b417d7691c97
0x92fbdf2cc69ca5268d3393a4a6b73fa1eb27066d
0x2cb5cb9799430437ce429130d4842b52e137a8b9
0x34fc6674be6ff02bf746c6fcb0890adfa1907060
0x590bd6b69b4e74d18970b7a5d6bb57322e4f64a4
0x0f00e1a74cd15c4e786c1c8bfab7ebcbc35d5209
0x825b76c6c44fa1db4fe29ba1920c1bacd882023f
0x56751aa00d610a4fdc55a6ee5abee52a0c922143
0xa1e7b0b912e329c474e6b0055ff5978b7e47118c
0x18dcd6d7b45fc73e8c79fab158a9363f882ca896
0x37528d958cce45cc41d37be5cad70372cf3ba509
0xe40f140ccfbc72b20de822a56decb612ef4979c1
0x165f65ca86fd7b4047a43a22cbe4f9a62a8e58bc
0x3a8dea6af608c6c6b2caf86239d8b223ce4aede2
0x09869c9d9e61d68d8994e8fe5e4f2a2ad3385821
0x4d4dd31603867436fd87fa8f2a95ceb034880bdf
0xd01963f7b73fd5c20f309287cdb7e02315dcc000
0x2a304c54310e1c28d7caff72ca0cdfb76beeba77
0x21e1f54daf64b8a996befad961ffea89c9fe20ea
0x3ae31b86e67d1ffb9badf33d4a62f2ebc36ffc33
0x1921de329c84e74ea0b213015d2535a2d7464c2d
0xcfbb3841242f6c9e11e03a855ccf53415159b1e5
0x8e9e6f0976f76f216102eb916d4a823a74fc4af4
0x479196d31835c73ef7355bb5865e80780058a4d2
0x722ccf20c7bb560bf6f2c56a1f46d99891671175
0x73a58cb28335b38e24e2201b62f3721685471ad3

# Reasoning
All accounts created on 2022-06-04 have a similar balance, simultaneous transactions from all wallets (most likely AdsPower Synchronizer is used for multiaccounts), for example, on 08/24/2023, most of these accounts simultaneously minted the same nft in Zora chain. The first addition of liquidity to Connext Polygon was in 2023/02/25 at 17:55-18:30 with similar amounts for 1158USDC
Wallets are divided into 3 groups: most now have a balance of 1360-1430usd and the same procotols and balances, some have 10500-10800 in the Base network and some have 300usd, but they are all united by the date of creation of the wallet 2022-06-04, the amounts and dates of transactions.
All these wallets synchronously and almost simultaneously added and removed liquidity, simultaneously minted nft from Connext on Galaxy, simultaneously made transactions on Stargate with the same amounts and other sybil attacks. All wallets successfully participated in the Connext LP Campaign 1 on the polygon network and received the Connext Polygon NFT
In Connext LP Campaign 2, the number of addresses was reduced, liquidity was added to the arbitrum with an approximate LP Balance of 5.5k and 180k points

These wallets were not identified as sybil, since their owner does not link addresses to each other and uses okx subaccounts, but the pattern of behavior, date of registration, time and amount of transactions are the same and give out a large and rich sybil cluster. I am sure that this is not the only one cluster of addresses of this violator, but these 64 wallets are 100% owned by the same person, which is easily seen by the date of creation and the same activity.

![image](https://github.com/connext/community-sybil-reports/assets/143197974/c45b911a-62e6-4f11-b10c-2be0a49afcfa)
![image](https://github.com/connext/community-sybil-reports/assets/143197974/ae81b1f9-0bf9-4aec-a741-6d8273e37ec8)
![image](https://github.com/connext/community-sybil-reports/assets/143197974/031f7ea4-ce93-4ee6-a767-076f4a8d65e6)
![image](https://github.com/connext/community-sybil-reports/assets/143197974/303c4860-e085-4f56-b9c7-683dc92c143b)

# Methodology

I noticed this cluster six months ago when I checked debank profiles of polygon liqudity campaign participants and saved all these addresses, and apparently for good reason. 
same activity and wallet creation date:
https://debank.com/profile/0x1de54b3ceb149647ba7417bfb738c6302e8bb57f
https://debank.com/profile/0x7ac21d972e8260cd6882bd548f88c248b620c44b
https://debank.com/profile/0x4b997e91a086392e4af1a0789d189e935a7485ad
https://debank.com/profile/0x49b26fb864d41951bb7cc8aec4b82d90101c4675
https://debank.com/profile/0x8f9b13a8eb7b5e32e580ff7ea17a3624677ca246
https://debank.com/profile/0x204d6db417420c1f45a399acbd3c622fba3cc865
https://debank.com/profile/0x4ce5144d76378196f8109985e8c2ac6563427ea1
https://debank.com/profile/0x0eef5b5464de9125df73dd43f63435b76ec42f4c
https://debank.com/profile/0x51d2004033743634a56afbeba27a2be193d2dc7c
https://debank.com/profile/0x2d58350c8071de154ec3d8aea7b027fd9ce1fdca
https://debank.com/profile/0x17473b05bf05ca843716a6dae2398ab1a1e5196e
https://debank.com/profile/0x3c00f174d560721e1e0b45a7db847a9d05026467
https://debank.com/profile/0x90ce791ffb07da27cca9585eaff47ce2adbb1b24
https://debank.com/profile/0x2cf231b57391f74d182b0143d6e797cf6789cdc1
https://debank.com/profile/0xa5ce00edc077a4c50069ad7dbbe82562989bc6c4
https://debank.com/profile/0xb8c3b42d11ec208ca1a831115943690dd8f7775d
https://debank.com/profile/0x350a9c5949fe580ad7770b97a37de330683f3ec9
https://debank.com/profile/0x9f3f775907eeda3ebf8c445939cd47b5626f4d72
https://debank.com/profile/0x15ab18efacd1152e1aaa0e556bb215ea263e0d53
https://debank.com/profile/0x4bfef70d63d382d236b22ac130cb9c66c030d1ab
https://debank.com/profile/0x80b4a16f0226dcc607a92213e0545aa155eea108
https://debank.com/profile/0x306f9ce5325e5e033d1af43b45c90f27c5219329
https://debank.com/profile/0xf0c48130303ed4f34208f9815161bf1ebabed8b1
https://debank.com/profile/0x7717835cd61252b30bec8c6522a33297e9eec958
https://debank.com/profile/0xc2ab62c4821ceab7a4d14140f0bfa64ac8a3ba1b
https://debank.com/profile/0x7fd63a8fc7133354b6c7a26080d864c345adbd9d
https://debank.com/profile/0xe9810594eacc66305c03dbf82122049a8e7e346d
https://debank.com/profile/0xb140b1bb3b5485fe790eea90ec079a548f12cae8
https://debank.com/profile/0xa41a35f602dec103e66b6f4f3fee4e609e58b460
https://debank.com/profile/0xd0bb62afcc75be359460f54f0d226c81aacea8ec
https://debank.com/profile/0xadd0dff89cb4ea220afa0a25fe901089b8cde106
https://debank.com/profile/0x68837bf512dadbdee8cff8a415203a1132f52346
https://debank.com/profile/0x396f95e3f0077f9ac74d6bcb2b685b17ebbe9baf
https://debank.com/profile/0xc8f9e048c1825b4b5879dc4f2d183375670d3078
https://debank.com/profile/0xc38cf11e8e4d41215df6deee2e9c9ec4db16ec45
https://debank.com/profile/0xd06cb3bfd8caad74696a97efeec5a10cd918d5c9
https://debank.com/profile/0xf142fb3763e5740b6057c52e91fa7b938b95f05f
https://debank.com/profile/0xf2111c6f395c2379585895d503d7586ec5295dc0
https://debank.com/profile/0x20fc4d551d457edcdcb28f9a5846b417d7691c97
https://debank.com/profile/0x92fbdf2cc69ca5268d3393a4a6b73fa1eb27066d
https://debank.com/profile/0x2cb5cb9799430437ce429130d4842b52e137a8b9
https://debank.com/profile/0x34fc6674be6ff02bf746c6fcb0890adfa1907060
https://debank.com/profile/0x590bd6b69b4e74d18970b7a5d6bb57322e4f64a4
https://debank.com/profile/0x0f00e1a74cd15c4e786c1c8bfab7ebcbc35d5209
https://debank.com/profile/0x825b76c6c44fa1db4fe29ba1920c1bacd882023f
https://debank.com/profile/0x56751aa00d610a4fdc55a6ee5abee52a0c922143
https://debank.com/profile/0xa1e7b0b912e329c474e6b0055ff5978b7e47118c
https://debank.com/profile/0x18dcd6d7b45fc73e8c79fab158a9363f882ca896
https://debank.com/profile/0x37528d958cce45cc41d37be5cad70372cf3ba509
https://debank.com/profile/0xe40f140ccfbc72b20de822a56decb612ef4979c1
https://debank.com/profile/0x165f65ca86fd7b4047a43a22cbe4f9a62a8e58bc
https://debank.com/profile/0x3a8dea6af608c6c6b2caf86239d8b223ce4aede2
https://debank.com/profile/0x09869c9d9e61d68d8994e8fe5e4f2a2ad3385821
https://debank.com/profile/0x4d4dd31603867436fd87fa8f2a95ceb034880bdf
https://debank.com/profile/0xd01963f7b73fd5c20f309287cdb7e02315dcc000
https://debank.com/profile/0x2a304c54310e1c28d7caff72ca0cdfb76beeba77
https://debank.com/profile/0x21e1f54daf64b8a996befad961ffea89c9fe20ea
https://debank.com/profile/0x3ae31b86e67d1ffb9badf33d4a62f2ebc36ffc33
https://debank.com/profile/0x1921de329c84e74ea0b213015d2535a2d7464c2d
https://debank.com/profile/0xcfbb3841242f6c9e11e03a855ccf53415159b1e5
https://debank.com/profile/0x8e9e6f0976f76f216102eb916d4a823a74fc4af4
https://debank.com/profile/0x479196d31835c73ef7355bb5865e80780058a4d2
https://debank.com/profile/0x722ccf20c7bb560bf6f2c56a1f46d99891671175
https://debank.com/profile/0x73a58cb28335b38e24e2201b62f3721685471ad3

also besides debank, i used
https://platform.arkhamintelligence.com  
polygonscan.com
arbiscan.io
and Dune
https://dune.com/KARTOD/connext-bridge-activity-and-top-30percent-depositors

# Rewards Address
0x7fb0D436693A3a77c5cc0353e244EAe7BBE7Ee63

**Comment by vi11am12** [comment]
All already reported in #46 
except three:
0x90ce791ffb07da27cca9585eaff47ce2adbb1b24
0x350a9c5949fe580ad7770b97a37de330683f3ec9
0x479196d31835c73ef7355bb5865e80780058a4d2
