### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by Kristagg** [connext/community-sybil-reports#294]
# Related Addresses

0x1b7028cD39A2A2C23d00f05f3edb07aFC4A7a9CE
0xb62cf21621b63c7a4e86af0a30c541f99fac1497
0x34570bace8e4825d08aa0c1eb11c6abef9e0456c 
0xFFc200427bEFe00f7eb22328bDfEd1edc998B93D
0xb62cf21621B63C7a4E86Af0A30C541f99fac1497
0xAAdf9d285FbeF2600B23dBFF0cEffcbdc0c9b877
0x257DB2D54ACeaAf12f4D08a9Dd5972Df909b6282
0x7c131eF24c60b6eD5B6669BEe7AF7777c476938f
0x41982604fDDce37bf04624A6F4A511f94043DEE0
0x30CC7Ee12B80539d573464C13f67b704aB8804d8
0xa2e54a1e6Dd447732677Db9E06401cEdd3c598D4
0x8A3D2420d3094Ac3EFfAF50BCaC4F7CDaF3f97a9
0x22676faFacdd20D503a22f67Af8e3918f604470B
0x7252b12d67d5eea492EBe50d4205758926DeEfb2
0xE2b381109bb65c3f7550D344c9b2d3d65DcDF761
0xBc4c8916891a2C2e6c344C7B98E4083D41a5dfAe
0x28d9C7850677e3359Ab27C3a4737Ee4F0007f3AE
0xba19468bC96017dD60E768be4C4C35e50a613DA9
0x2183626760fF7AC5Cf3788D2b464409550C7726f
0x7ccC703085D4Fef8510149408ad47daf01a29f67
0xA2c4f2ca3541FB9c685177BC11734F6e398585D8
0x63CB8e52862F01D95eCe1320F0d34de070ce686d
0x820115dEe8380A002Df6d886029ce2d5f0F2c29a
0x1aaa406C21a84Bd6390547DDDABbf13079d62779
0xDBEB351588ac522F09581C2d1Dc3Fc6B2e096682
0x85db8DD6a30F1AbA9297Bd47bC4537377601D2dB
0x7d76DdEC33dfa2Eb8e10b18119856992E7AA80dC
0x4DB98dD198eF7C15b7a119d0d22CbC6a7363eA47

# Reasoning

PARENT WALLET : 0x1b7028cD39A2A2C23d00f05f3edb07aFC4A7a9CE

2021.02.08 the date of transfer to half of the wallets from the list on the Ethereum network within 1 hour, the size is the same for all wallets.

The rest of the wallets almost all received deposits from the parent address but on different dates.

Wallets also interacted with each other on the Ethereum network. If you yourself can’t see it in the ethereum chain, the rest of the transfer dates, I can show the transactions.

In the arbitrum network, most of these wallets also interact with each other.

Some of another wallet connections : 
1) 2021.07.30 wallet 0x7ccC703085D4Fef8510149408ad47daf01a29f67 sent to:
0xE2b381109bb65c3f7550D344c9b2d3d65DcDF761
0x820115dEe8380A002Df6d886029ce2d5f0F2c29a
0x1aaa406C21a84Bd6390547DDDABbf13079d62779

2) 2023.04.15 wallet 0x7ccC703085D4Fef8510149408ad47daf01a29f67 got 0.077 eth from 0x85db8DD6a30F1AbA9297Bd47bC4537377601D2dB

3) 2021.04.03 wallet 0xb62cf21621B63C7a4E86Af0A30C541f99fac1497 (connected with many of other wallets) got 0.03 eth from 0x7d76DdEC33dfa2Eb8e10b18119856992E7AA80dC

4) 2022-02-13 wallet 0xb62cf21621B63C7a4E86Af0A30C541f99fac1497 got deposit 0.03 eth from 0x4DB98dD198eF7C15b7a119d0d22CbC6a7363eA47

All these wallets have the same transactions. The sequence of transactions, sizes, protocols, the time of interaction with the protocols on these wallets is the same. Check it out for yourself at https://arbiscan.io/.  Screenshot from https://arbiscan.io/ below :
![image](https://github.com/connext/community-sybil-reports/assets/143223120/883e563f-3c6c-44c5-b92b-9204518ee4f3)

# Methodology

I found wallet with small balance with https://debank.com/ help. And then it became obvious that it was a sybil. It took several hours to find all addresses using https://etherscan.io/ and https://arbiscan.io/

If I had a script, it would be much easier to look for sibilers.

The sequence of transactions, sizes, protocols, the time of interaction with the protocols on these wallets is the same. Check it out for yourself at https://arbiscan.io/

# Rewards Address

0xAF24e31B602dA4962fb5Ca93cC6ff3F301EDb1ae

**Comment by artjomikas** [comment]
duplicate from #221 group 3
