### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by doxxer69** [connext/community-sybil-reports#301]
# Related Addresses
###1
0x043e0C15eC1fde23Db7D62e61744B630D0aDb345
0x0f062B7F500B24D9A946c330282296e8C099ED98
0x0Fe1225A729ae3833fA4e2F489ff4b373E3D61Aa
0x29a975DB2e4c36966f16490d791134a9632BD37B
0x3C9417c673fc34768A47D0473eA3131D55D586FC
0x4bf46b2D646f34b242C4a7B8f322f25673F6abaf
0x60720d40bBE9877a826bFEe240c55C62A9A40E2D
0x67eBe61C72A663074e2CA9F14397945Af398bb6E
0xe07Ea2E5984A1f86Dc3E5Eba3802A92244620142
0xC81596b7c0Da8cFb6618399bbe419D227486E64B
0x554B89b34f96782a22807963ff1b3d347E96606a
0xcd546e60542b121be62d9aDf73Be6d5eC1dd564E
0xDe2Ee19d6687Ed3b45e9D2E3489a726a53E4a693
0xA75352c75DbDF076Ee3187D0B5b7dd0c5bDF66da
0xdbC40Ddc24a13BD44624b7c3e42be06B9aF14D8A
0x884a8370292cb961570c5fe93641c7E77fC33dbf
0xbA070e5Aee213777A5621c2acD2a0D1f68bA65f5
0xA1c2aEf77644aE6CA711239e7b60120ed95d3F35
0x005ffAAB63d99CE611E52124597BFbb57bDF79a7
0x0dc19DBED130022050EB1B3f86f4B63AD87a5EE8
0x8193ED5692633a6a484b07C825F4CAA441ad7044
0x159EdB292df8CA46E374b7c55f7eC6113DE89753
0x836f77d1C32Cc7F26b25E2E3fc9209F6F653911a
0xD445C39D1c34Ba68Ac454A28108Ab82920cb00C5
0x8a40B950f67FA58a2a5982dA9F23353986039Ec9
0xde5A463E8Bb0fc8bbF79EFbe2022002621cBae2C
0x5BEF2BE5C934B9A6254f261b670804b75b8d660A
0xC08e5aFa74b2b11c05A22F31467a18436112Bbb6
0xd02c44A97114BA492eE4f69b1993c3c971c137a8
0xE019607b12109C1Cd643d7a979fB5d983d003a67

###2
0x0143860b891551c03e9c34113148b7287227d405 (someone else reported)
0x6ac8f5ae64e60e73db32cfaf15466ef7706a7126
0x14f1ae9087c7b3992835cb2fc6c8d7b500d34c3c
0x4e5a5bb7d48779247b71af540a27acc518abeba2
0xde8b1d9624bf8ce0d81c1c2f35d3ae11f143701a
0x91f04a1ef4e34ffd964b4051c22429048e1da6c6
0xfbcbed8b89efb75a86638b1ff9935fef55813679
0x0c3caa2a91900727e3cbd8f47dfd79ca96b9f8b2
0xc5e031c13a09e62be3010cc95cd47446a7d7e40a
0x25c24de48d6bb4808947d1e61067a2d3afc0c9e0
0xed39f15bfd24229ec43e5eaa3d9adcb26dca3204
0x0dadb9848caed80ba3122a53a3b0208fcde18ff5
0xf092f913b2cf86a96d62a36be56c64ba85005e2a
0x0437ce3571602135e17c7dbb71a2aa47ccdad555
0xaab3fd5e7debcae68920af8e72a93818c6ba2971
0x2fdededf48b50d1467624811727933499aba3273 (someone else reported)
0x8b48fd5c06f23c63a18fd04d8c8dc657087a74a7
0xfe41d0395a16f94d49c93ccdb4a10e2576cf6da4 (someone else reported)

# Reasoning
###1
Dune query: https://dune.com/queries/2976858
All addresses received funding from Huobi, approve USD, Add Swap Liquidity to Connext, Claim Galxe: Space Station 3. Last 5 basically the same, just didn't claim Galxe nft. All hold at least 1880 CUSDCLP. All have similar total value on Debank. Transactions submitted in same time intervals.

Two examples:
![image](https://github.com/connext/community-sybil-reports/assets/143224220/996d8ecb-90f3-437f-b6bc-16f74923f670)
![image](https://github.com/connext/community-sybil-reports/assets/143224220/189f5664-6400-4ce5-bd5b-46e4a2edb4ef)

![image](https://github.com/connext/community-sybil-reports/assets/143224220/c41706d7-923e-460a-a244-0b1ce343bcc1)
![image](https://github.com/connext/community-sybil-reports/assets/143224220/2127780f-6557-4cce-a357-8048d8d415e5)

![image](https://github.com/connext/community-sybil-reports/assets/143224220/26d1293e-9a62-4321-8ba7-cabbe11e9034)

###2
Dune query: https://dune.com/queries/2977258
All addresses lock similar amounts of STG, increase_amount  similar amounts of STG and withdraw  similar amounts of STG from the contract around the same time (see Dune query). All addresses hold 100-120 STG. All have similar total value on Debank. All addresses have 30-50 STG locked. All addresses have 1000-1030 USDC in Stargate farm. All wallets received Trader Joe & Stargate ERC1155 NFT on the 23rd of February 2023. All wallets minted the Arbitrum Odyssey NFT on the 28th of June 2022 or on the 11th of July 2022 and still hold it. 2 wallets were alreasdy reported, merked those, but still included as they are in the Dune query. All addresses have ENS names registered.

Two examples:
![image](https://github.com/connext/community-sybil-reports/assets/143224220/458a2db6-2637-4ba6-b9b9-d9f93480d476)
![image](https://github.com/connext/community-sybil-reports/assets/143224220/78c45509-9282-4fb3-8625-60fd2f9245bc)

![image](https://github.com/connext/community-sybil-reports/assets/143224220/03da37d9-a304-4f15-b923-cd57ac6d4025)
![image](https://github.com/connext/community-sybil-reports/assets/143224220/f4132580-ddcb-4af8-a3f1-50e54be1568f)

![image](https://github.com/connext/community-sybil-reports/assets/143224220/51922a48-7084-4146-9fc9-3f8c5337f6f3)
![image](https://github.com/connext/community-sybil-reports/assets/143224220/865b9441-d715-4de8-9db2-fa293fec4468)

![image](https://github.com/connext/community-sybil-reports/assets/143224220/fa89a9eb-6738-4ed0-8a3b-9c257c04937c)

# Methodology

I was checking CUSDCLP holders on polygonscan looking for irregularities. For the second batch I was checking nextUSDT holders on arbitrumscan.

# Rewards Address

0x2474F6B08Cf2Aa68b6603c7eE53002F5CD4c48B5

**Comment by doxxer69** [comment]
# Related Addresses
0xcC42c84426831de99750FB2268ed3943f4706F5f
0x9F872206C26DeedF09913466E71949025bEa067E
0x65b2E8781D00a7E25A5DA2A9565156629ABc3E02
0xaf910f5B108C3593c00cB61aBeff5b0fEA89BF33
0x23b1203a3caBC775793cbDc3783E8239ff9C14E2
0xd3D262C5E33f2313961BC3217665Ac1df92E5DD4
0xE0061373e8810C4a3EbD751F748fC2fc1E19cAB2
0x44A59101AbF2AD5768cBC418cB0363422E6a7EF1
0x33F363c444a27484B1484f4c288fe2fd5e65CD4f
0x146719BaC42BB8b5EE453c9fac4e3CF26349E85B
0xaA759aB9C1574Ab8926Ae45268b6ba2c2473E467
0x8aC5613cAEAB427ec24e53cf896067f21C6b5052

# Reasoning
I checked mainly transaction history on Polygon. All wallets did Collect With Sig tx on Lens between 2023-02-11 and 2023-02-16 (except 0x8ac5 and 0xcc42). On 2022-06-27 all wallets did Outbound Transfer To tx to Socket Registry except from 0xe0061, 0xaa759 and 0x146719). All wallets have Internal Txns from 0xf2e4209afa4c3c9eaa3fb8e12eed25d8f328171c for different amounts of Matic (except from 0xd3D2, 0x23b12 and 0xe0061). All the internal transactions are from around 600 days ago. From Arkham it can be seen that the acticvity on the wallets is very similar.

# Methodology
Did a Dune query: https://dune.com/queries/2988450
After Dune, inserted the addresses into Debank and Arkham to look for more similar wallets. https://platform.arkhamintelligence.com/visualizer/entity/0x9F872206C26DeedF09913466E71949025bEa067E,0x65b2E8781D00a7E25A5DA2A9565156629ABc3E02,0xaf910f5B108C3593c00cB61aBeff5b0fEA89BF33,0x23b1203a3caBC775793cbDc3783E8239ff9C14E2,0xd3D262C5E33f2313961BC3217665Ac1df92E5DD4,0xE0061373e8810C4a3EbD751F748fC2fc1E19cAB2,0xcC42c84426831de99750FB2268ed3943f4706F5f,0x44A59101AbF2AD5768cBC418cB0363422E6a7EF1,0x33F363c444a27484B1484f4c288fe2fd5e65CD4f,0x146719BaC42BB8b5EE453c9fac4e3CF26349E85B,0xaA759aB9C1574Ab8926Ae45268b6ba2c2473E467,0x8aC5613cAEAB427ec24e53cf896067f21C6b5052?flow=all&positions=%7B%220x9F872206C26DeedF09913466E71949025bEa067E%22%3A%7B%22fx%22%3A-12%2C%22fy%22%3A48%7D%2C%220xaf910f5B108C3593c00cB61aBeff5b0fEA89BF33%22%3A%7B%22fx%22%3A13%2C%22fy%22%3A51%7D%2C%220x65b2E8781D00a7E25A5DA2A9565156629ABc3E02%22%3A%7B%22fx%22%3A-56%2C%22fy%22%3A46%7D%2C%220xd3D262C5E33f2313961BC3217665Ac1df92E5DD4%22%3A%7B%22fx%22%3A64%2C%22fy%22%3A49%7D%2C%220x23b1203a3caBC775793cbDc3783E8239ff9C14E2%22%3A%7B%22fx%22%3A39%2C%22fy%22%3A50%7D%2C%220x497F300c628cd37Bc4f2E1A2864b11570E0f22A8%22%3A%7B%22fx%22%3A-11%2C%22fy%22%3A66%7D%2C%22socket%22%3A%7B%22fx%22%3A8%2C%22fy%22%3A-81%7D%2C%22slingshot-finance%22%3A%7B%22fx%22%3A8%2C%22fy%22%3A-69%7D%2C%220x%22%3A%7B%22fx%22%3A7%2C%22fy%22%3A-60%7D%2C%22connext%22%3A%7B%22fx%22%3A8%2C%22fy%22%3A-92%7D%2C%220x8E3D050437Fe7C05E1e6d136a24537B41878Db3F%22%3A%7B%22fx%22%3A78%2C%22fy%22%3A37%7D%2C%220xFb2dc580Eed955B528407b4d36FfaFe3da685401%22%3A%7B%22fx%22%3A30%2C%22fy%22%3A97%7D%2C%22ftx%22%3A%7B%22fx%22%3A98%2C%22fy%22%3A-45%7D%2C%22binance%22%3A%7B%22fx%22%3A8%2C%22fy%22%3A-47%7D%2C%22disperse-app%22%3A%7B%22fx%22%3A1%2C%22fy%22%3A75%7D%2C%220xE0061373e8810C4a3EbD751F748fC2fc1E19cAB2%22%3A%7B%22fx%22%3A0%2C%22fy%22%3A49%7D%2C%220xcC42c84426831de99750FB2268ed3943f4706F5f%22%3A%7B%22fx%22%3A5%2C%22fy%22%3A23%7D%2C%220x7e0823C377D6820fB8D2B5Eb5AE10aD9B7c01bB4%22%3A%7B%22fx%22%3A-114%2C%22fy%22%3A5%7D%2C%220x44A59101AbF2AD5768cBC418cB0363422E6a7EF1%22%3A%7B%22fx%22%3A49%2C%22fy%22%3A49%7D%2C%220x33F363c444a27484B1484f4c288fe2fd5e65CD4f%22%3A%7B%22fx%22%3A24%2C%22fy%22%3A50%7D%2C%220x0EDE4E9467E326BAF33Dd66056A6d51d8f553294%22%3A%7B%22fx%22%3A-42%2C%22fy%22%3A49%7D%2C%220x60dA3d0EcAaE804cA360348e3a58cAB6E633Ba2B%22%3A%7B%22fx%22%3A97%2C%22fy%22%3A95%7D%2C%220x573ABE86e3bea9223D78E3ae8626Bf9346447AEc%22%3A%7B%22fx%22%3A-69%2C%22fy%22%3A91%7D%2C%220xf56c7b1449a8577271CBD59101c588944F4217Dd%22%3A%7B%22fx%22%3A-99%2C%22fy%22%3A70%7D%2C%220xaA759aB9C1574Ab8926Ae45268b6ba2c2473E467%22%3A%7B%22fx%22%3A-41%2C%22fy%22%3A46%7D%2C%220x146719BaC42BB8b5EE453c9fac4e3CF26349E85B%22%3A%7B%22fx%22%3A-28%2C%22fy%22%3A49%7D%2C%220x8aC5613cAEAB427ec24e53cf896067f21C6b5052%22%3A%7B%22fx%22%3A-73%2C%22fy%22%3A41%7D%2C%220xc2f13C6cd3C14D39294073879cDBb751D0aBdf3C%22%3A%7B%22fx%22%3A-4%2C%22fy%22%3A102%7D%2C%220x54abEef1e6E913E808Ff196ACE33BC00112d30E2%22%3A%7B%22fx%22%3A-111%2C%22fy%22%3A47%7D%2C%220x1bee2d17b20f829c2F0fDF79b938f5D65b522C91%22%3A%7B%22fx%22%3A124%2C%22fy%22%3A21%7D%7D&sortDir=desc&sortKey=time&usdGte=0.1

# Rewards Address
0x2474F6B08Cf2Aa68b6603c7eE53002F5CD4c48B5

**Comment by just-a-node** [comment]
Valid cluster 1
Invalid cluster 2
Invalid cluster 3
Valid cluster 4

**Comment by A-Keyboard** [comment]
@doxxer69 Can you dm me on Discord, my discord is khlilo

**Comment by doxxer69** [comment]
462214
