### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by conoreben** [connext/community-sybil-reports#31]
# Related Addresses

0x59bccff173d8215e7111db7b4c59cf56a7e90a92
0xac34457d13cd6bd41be54ef3644e5be9ffe683e4
0xec5aff28d9e2454efdf860bfd1fddbb82f5a1933
0xfb63f9d1bd7aa2345c7d213e9d855a330e68caba
0x23190dbd482e8f29d348cf624cf34213d1f4fbf3
0x0aa92bab89d46203c9f2827f299b5e5729a06b28
0xbacc31ebd9750c5d709a8c6d321ce1a07dacb74a
0x2086e96d962dfd158e70b38adba4abd33d6009f5  
0x7e2789628743497cb5ae9d8d128bc4f7cf416a6d 
0xe6a048adfaaa19e86a2c9909c1ebb206a7c67b99
0x2c51ee45d3f03ee613cc2b5f7bc6b0d6c68d3b77
0x9d9ae20f5157506916772aaf0f9757a84fa3be44  
0xe8800facbc14db958e4d45f9d2c3c29b0956a8c0
0x71bc8c7064d2ba87dc7f33a1b06225c6dec1645b  
0xeae80c4dffd03b5352a237e6d2214bde00b9a521  
0x20873237adc2a42e1409842ae42ff9d933daeda9  
0x214c5b2a2503faa592ee3b1a87e8f9bb964282b9 
0x532a21e3a36d68591a444c3e7a6e2cd230cffba5  
0x04aeff321363a3507f83dbedb435e555db086e48  
0xc28e5139c298fb0c0060117825602696ec81e178 
0x852ef7f8a44e9a9c01c8a19e7adef4d4c924c50b  

# Reasoning

We believe that the provided list of addresses is possessed by one entity.

First batch of wallets was created 1040 days ago(7 wallets)
The second batch was created 286 days ago(14 wallets)

All of these wallets have approximately the same proportion of tokens by blockchains
Same amount of tokens provided to the same protocols.

For example, 2$ was provided to Mute io on these wallets

They also interact with each other pretty often! This is proved by the file provided and Arkham Platform

All of the provided wallets interacted with Squid Bridge on either 25 august or 29 august.

Each of the 21 wallets provided made the same transaction 

https://platform.arkhamintelligence.com/visualizer/entity/0xfb63F9D1bD7aa2345c7d213e9d855A330E68cAbA,0x23190Dbd482e8F29D348cF624cF34213D1f4fBF3,0x0aa92bAB89D46203C9f2827f299b5E5729A06B28,0xBAcc31eBD9750c5D709a8C6D321cE1a07DaCB74A,0x2086E96D962DfD158E70b38AdBa4abd33d6009f5,0x7e2789628743497cB5AE9d8d128Bc4f7cF416a6d,0xE6a048ADfAAA19e86a2c9909c1eBB206A7c67b99,0x2C51Ee45d3f03Ee613CC2b5F7bC6B0d6c68d3b77,0x9d9AE20f5157506916772aaf0F9757A84fA3Be44,0xE8800facbC14DB958e4D45F9D2c3c29B0956a8c0,0x71bC8C7064d2bA87Dc7F33a1B06225c6dEc1645B,0xeAE80c4DffD03B5352A237E6D2214BdE00b9a521,0x20873237adC2a42e1409842aE42Ff9d933DaEDA9,0x214C5b2A2503fAa592ee3b1a87e8f9Bb964282B9,0x532a21E3A36D68591a444c3e7A6E2CD230CFFBa5,0x04AEFf321363A3507F83DBeDb435E555dB086E48,0x852eF7f8A44E9A9c01C8A19e7adEF4D4C924c50B,0x59bCCFf173D8215E7111db7b4c59cF56a7E90a92,0xac34457D13cD6bd41be54Ef3644E5Be9FfE683e4,0xEC5aFF28D9E2454Efdf860Bfd1FdDBb82f5a1933,0xC28E5139C298FB0c0060117825602696eC81E178?flow=all&positions=%7B%22axelar-network%22%3A%7B%22fx%22%3A-47%2C%22fy%22%3A49%7D%7D&sortDir=desc&sortKey=time&timeGte=1691971200000&to=squidrouter&usdGte=0.1

**Check each one of the 21 transactions with the Squid Bridge** 

All of these transactions have the same amount of 0.7$-.8$! Moreover, the token transfers for all of the transactions include swapping 0.45-0.46 AXLUSDC! 
<img width="999" alt="image" src="https://github.com/connext/community-sybil-reports/assets/128084567/93caaa9b-cc2f-406f-a780-ca1186e76fd9">

https://platform.arkhamintelligence.com/explorer/tx/0xd919975092c5efc7c9ef0096faccacb1b43025a5d561f3dc77125e78a43049eb

https://platform.arkhamintelligence.com/explorer/tx/0x9b94b9381bc40cfaef2ce458109c66f6d9477543a3586c07d92d0dbeb87db47e

https://platform.arkhamintelligence.com/explorer/tx/0xd9bfecc9844f67314c47ab7adfc411dc53817512140b77e63c25a7eec26ce874

https://platform.arkhamintelligence.com/explorer/tx/0x4a52be38dd0483205906bf5bade70b687da5d2e602843490f6b3c8502842a687

https://platform.arkhamintelligence.com/explorer/tx/0x93c6f8eebf8b5d77ff5283b5f2839bb8ac455262f4252fa53091cbfbf2ac552d

https://platform.arkhamintelligence.com/explorer/tx/0x07410dae38f43fcd35bce10e8693454bef7a64e876f62efc3ec9645d939f0e68

https://platform.arkhamintelligence.com/explorer/tx/0x07410dae38f43fcd35bce10e8693454bef7a64e876f62efc3ec9645d939f0e68

https://platform.arkhamintelligence.com/explorer/tx/0xeb8f3b87edda41c2414435b1801f442b990ee73f0cb2840bca1a50a34b68ef0f

https://platform.arkhamintelligence.com/explorer/tx/0xd735dcdde8209937d89881211b5eba7601456a915df893033bc11463907e70d3

https://platform.arkhamintelligence.com/explorer/tx/0x49475afbf93b7066d3a3d7b4db31458b9f79d220eaa9ba7fd4edda58a3b7d77e

https://platform.arkhamintelligence.com/explorer/tx/0xab7c93318220a3be8e0c2498ca9b7e3ebeded5c0672c071985e2b625f834594d

https://platform.arkhamintelligence.com/explorer/tx/0x7defc4ea104b56db54454cafcacb9c0badf579c437139ef3e5f8f60bb1f81ed0

https://platform.arkhamintelligence.com/explorer/tx/0x1e8e7bf0c9973dea88b47ff13afee5222c8c090c5dbb45eaa71c7b4680cfdff5

https://platform.arkhamintelligence.com/explorer/tx/0xd9be42219a13c6c706948956c4b0370ac9c8f9847124b097dfb029028cdbb052

https://platform.arkhamintelligence.com/explorer/tx/0xd9c467db686dfba357479717622794e8342d0856cb87eb811710c3fe61625678

https://platform.arkhamintelligence.com/explorer/tx/0x19f49de2a9ec7f7d5ee220c2b1b292f4b47c1937137550cd435bc64247facb79

# Methodology

The reported addresses were found via Dune Dashboard

We have exported the csv file of all the Arbitrum LP Providing addresses from this dashboard https://dune.com/KARTOD/connext-bridge-activity-and-top-30percent-depositors

Then we converted csv to xlsx and sorted the wallets by LP provided

We found 21 wallets with almost the exact LP balance!

Then we checked each of them on Debank -> date created, balance, amount of tokens and LP provided to different protocols

We have also detected the transactions, which the entity made, intersecting with their other wallets. All the txs can be found in this file 

Some wallets were intersecting with each other

[report_7043.csv](https://github.com/connext/community-sybil-reports/files/12476969/report_7043.csv)

Moreover, some of these wallets were topped up from OKX on the same time with the same amount of funds 

0x0aa92bab89d46203c9f2827f299b5e5729a06b28
0xfb63f9d1bd7aa2345c7d213e9d855a330e68caba
0x59bccff173d8215e7111db7b4c59cf56a7e90a92
0xec5aff28d9e2454efdf860bfd1fddbb82f5a1933
0x23190dbd482e8f29d348cf624cf34213d1f4fbf3
0xbacc31ebd9750c5d709a8c6d321ce1a07dacb74a

Check the txs 

https://etherscan.io/tx/0x219485a8319be7a61a98ffde8dfc5d2198309637f866cca8c9f7b2deadd4861b
https://etherscan.io/tx/0x3b859803c8bffa18cf2c9f8d22e15d926b3253125ea5a4916879129082a09dae
https://etherscan.io/tx/0x57d7ae1ba9b7384f0e73d0c73d1d3e7b80c8e00a783c64c86087ed3451038ca1
https://etherscan.io/tx/0x70a4da9f65b0a4403b3ce346d2de0eb7558fef2526c58f9272322257d10c5a37
https://etherscan.io/tx/0x80ad3fee6e8b4c83d50545399d9b2dc563ecf3ceb562dc12ce55f8670669e194

https://etherscan.io/tx/0xef5ee7766d2b0f88209076c751886b3432e84d15ee29a1ef144d70264a6a2d95

# Rewards Address

0x2ACC5FD4D5A83F8BAc6228A1b8e7B6c51936A0CD

<img width="1009" alt="image" src="https://github.com/connext/community-sybil-reports/assets/128084567/2c691858-54e1-4591-b5a5-e46e1d5dfcd3">

<img width="1008" alt="image" src="https://github.com/connext/community-sybil-reports/assets/128084567/ad216cbe-9f35-4514-817b-46e9f5e09964">

<img width="974" alt="image" src="https://github.com/connext/community-sybil-reports/assets/128084567/f0af7b47-2a15-49a9-b699-d529671954b1">
<img width="1018" alt="image" src="https://github.com/connext/community-sybil-reports/assets/128084567/c7c0601c-2d34-4f00-a182-68aa24093b34">

**Comment by conoreben** [comment]
What you think guys? Pretty sure its a sybil!

**Comment by conoreben** [comment]
@Grraarrgghh updated

**Comment by A-Keyboard** [comment]
@conoreben Can you dm me on Discord, my discord is khlilo

**Comment by conoreben** [comment]
hi there, added you. My nickname is ikh011

вс, 3 сент. 2023 г. в 21:04, Khalil ***@***.***>:

**Comment by conoreben** [comment]
4864596
