### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by pedrolucascrypto** [connext/community-sybil-reports#314]
# Related Addresses
```
0x82dc92b01c7ff54911842956083795f60f6f64f4
0xc4b37e4e86a18871cedaf644af79914a81874a1a
0x35d9aa2629e89ae11e63be07c015fca8b4a87620
0xfc7a7c104982e91472f6135f943b01902c00e7e1
0x0450acb8f62456e4c2a7f84c5f5a8c229157e2c2
0xe379ad19528a01de884a7ca6a7fe480dd157c182
0x21c94aba9184da7340f78b94a00b4d5f9724a65f
0xab595a18366454608c3be0babd8d96436d60ec8d
0x5ab124f18056113d0884251d45544e2188af5fae
0xcc5b087283d69db4237da489d487140f2745fd28
0xfe41d0395a16f94d49c93ccdb4a10e2576cf6da4
```

# Reasoning

There is direct funds transfer between several wallets(0x5AB to 0x21c 0x045) or trough middleman wallet(0xCC5 to 0x82a to 0x82d) He used Blur to buy/sell orders to farm blur points(washtrading) between wallets(0x5ab and 0xab5), same TXs for L0/Stargate/1inch. Eigenlayer connection(0xab5 and 0x35d) TLDR . he used same projects, same ammounts, same routes etc. He added same ammount of LP 10k for all of his accs

# Methodology

i gathered wallets from Dune and watched for same ammount of LP position. after that i checked them on arkham

[Example:

The reported addresses were discovered by checking irregularities in the number of bridge transactions made via Dune. The resulting addresses were analyzed to find repeating transfers at standard intervals and sequence.

(https://platform.arkhamintelligence.com/visualizer/entity/0xfE41D0395A16f94D49c93ccDb4a10e2576Cf6DA4,0xcc5B087283D69dB4237Da489d487140f2745fD28,0x5aB124f18056113D0884251D45544e2188aF5FAe,0xAb595a18366454608c3be0babD8D96436d60ec8D,0x21C94aBa9184dA7340f78b94a00b4d5f9724A65f,0xe379AD19528A01dE884A7CA6a7fE480Dd157c182,0x0450Acb8F62456E4C2a7F84c5F5A8C229157E2c2,0xFC7A7c104982E91472f6135F943b01902c00E7e1,0x35D9Aa2629e89ae11e63bE07c015fCa8b4A87620,0xC4b37E4E86A18871CEdaf644af79914a81874A1a,0x82dc92b01c7fF54911842956083795f60f6F64f4,0x82dc92b01c7fF54911842956083795f60f6F64f4?flow=all&positions=%7B%220xfE41D0395A16f94D49c93ccDb4a10e2576Cf6DA4%22%3A%7B%22fx%22%3A-164%2C%22fy%22%3A20%7D%2C%220x17e8A43ee27E57491777F4F3D3c507300aCE2518%22%3A%7B%22fx%22%3A192%2C%22fy%22%3A-37%7D%2C%22layerzero%22%3A%7B%22fx%22%3A-5%2C%22fy%22%3A58%7D%2C%22connext%22%3A%7B%22fx%22%3A-5%2C%22fy%22%3A-86%7D%2C%22stargate%22%3A%7B%22fx%22%3A54%2C%22fy%22%3A73%7D%2C%22krittapart-p%22%3A%7B%22fx%22%3A346%2C%22fy%22%3A-147%7D%2C%22aave%22%3A%7B%22fx%22%3A-175%2C%22fy%22%3A-30%7D%2C%22orbiter%22%3A%7B%22fx%22%3A-43%2C%22fy%22%3A80%7D%2C%22uniswap%22%3A%7B%22fx%22%3A159%2C%22fy%22%3A39%7D%2C%220xADdb70cC899480F87C472E796Fe7e810D1bc8442%22%3A%7B%22fx%22%3A151%2C%22fy%22%3A-134%7D%2C%220x5aB124f18056113D0884251D45544e2188aF5FAe%22%3A%7B%22fx%22%3A-331%2C%22fy%22%3A-37%7D%2C%220x21C94aBa9184dA7340f78b94a00b4d5f9724A65f%22%3A%7B%22fx%22%3A-333%2C%22fy%22%3A-70%7D%2C%220x82dc92b01c7fF54911842956083795f60f6F64f4%22%3A%7B%22fx%22%3A50%2C%22fy%22%3A110%7D%2C%220xAb595a18366454608c3be0babD8D96436d60ec8D%22%3A%7B%22fx%22%3A468%2C%22fy%22%3A61%7D%2C%220x82aF49447D8a07e3bd95BD0d56f35241523fBab1%22%3A%7B%22fx%22%3A419%2C%22fy%22%3A35%7D%2C%22blur-io%22%3A%7B%22fx%22%3A148%2C%22fy%22%3A117%7D%2C%22binance%22%3A%7B%22fx%22%3A113%2C%22fy%22%3A-150%7D%2C%220xC4b37E4E86A18871CEdaf644af79914a81874A1a%22%3A%7B%22fx%22%3A-163%2C%22fy%22%3A117%7D%2C%220xe379AD19528A01dE884A7CA6a7fE480Dd157c182%22%3A%7B%22fx%22%3A-377%2C%22fy%22%3A8%7D%2C%22bybit%22%3A%7B%22fx%22%3A-341%2C%22fy%22%3A142%7D%2C%22space-id%22%3A%7B%22fx%22%3A-393%2C%22fy%22%3A-50%7D%2C%220x0450Acb8F62456E4C2a7F84c5F5A8C229157E2c2%22%3A%7B%22fx%22%3A-387%2C%22fy%22%3A90%7D%2C%22eigenlayer%22%3A%7B%22fx%22%3A-21%2C%22fy%22%3A133%7D%7D&sortDir=desc&sortKey=time&usdGte=0.1)
-->

# Rewards Address

0xb6Dc3181148ba8a3Ec7120f90d173D32cFC92227

**Comment by Furyb67** [comment]
bro they are not a sybils lol hahaha
