### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by lawrencewinth** [connext/community-sybil-reports#317]
# Related Addresses

```
0x6e03F76fb77C3b27A1742BbaB1fFA6aB4907eD5B
0x4aF997F78067dC2458CDe261FFAb863afa5Cc357
0x36DEE064Cde06fb3dbc51491e86f39c50Cb91B52
0x938e3b0e9e70607c50C2629fA434B9a4e5f28421
0x55e1962677f05ebE8a9A86a4c769bbD6909C925c
0x204d6dB417420c1f45a399ACBd3c622fBA3Cc865
0xD67d2F08Cbc0E3b4Cd6db121b5E0C0e5425268A2
0x8F9b13A8eB7b5E32E580Ff7Ea17a3624677cA246
0x56751AA00D610a4FdC55a6eE5ABeE52A0C922143
0xD737631129CFC510F5256cFA921BF9f6C271F0f5
0xa855EB069CAd82D7e2f785EBe21c45bc988BFa5D
0x256Bd0D84B4b50d739F82f4918723cDb34Af9445
0x762009518245AfcB8CF624A4116265eA7745F6AC
0x9C17c8Cd345C54083dF54997f545FA8C4331120F
0x1De54b3cEb149647Ba7417bFb738C6302E8bb57f
0x0f87452A7Eac3BCFE90Fe4187d2f922d1D6699AE
0xE66e4B4F43B6C7e7DF71C0E325aD6797f3e66B3F
0x21e1f54DAf64b8A996bEfAd961FfeA89C9Fe20eA
0xC52d24a78207b8c380d9B0Ac2E5Ec699DaD04241
0x37528d958cCe45cC41D37be5cAD70372cf3bA509
0x390fd846c06Ff8e98E60B5FCde42c58AB33A9FA3
0x7ac21D972E8260CD6882bD548f88C248B620C44B
0x49b26Fb864D41951Bb7CC8AeC4b82d90101C4675
0x9152B598995EcD590DEe9C67f649E1E8533af46f
0xE40f140CcfBC72B20dE822A56DECb612eF4979c1
0x4653ff13b065B170f28C03871E343Bb2425ADF2c
0x3A8Dea6aF608C6c6B2CAF86239d8B223CE4aEDE2
0xE2B6b8E9aa2c9C9e16A672DdC655B4712F28Ce86
0xEA1c10435Ba64c02aD3d7B1C15F7255222967BC1
0x9308Bd4fDEc064521ba86D61fbe606569964AbB9
0x2e44BF02BAA8a4D83A08FAdB3Fd9e901A0c53108
0xD330A7d4Fa8500d35e538dC724A74c00559b2257
0x4455ddaFFE71cFBB094fF6864330BCfcCd7E4680
0x4E9a4bD232B23D95D75Bd553dA3025400825309e
0x7c042956468e5993a994008b5966EDb3fD1b26FD
0xE8CC278fa39bE0600D042214cD35f0154D15Cfa9
0xD471A840Ec81bE3ce5E1325413581a1EaF5dcC11
0x6806f5A7d35f6B31F8cee5799Fa7f70571B0D2b6
0x495446F7fD604608A23009fA12E65d0a7554b5F3
0xba181DeB98AfC2202202C9AeBf26B18f46D70497
```

# Reasoning

all addys used to make TXs with the exact the same amount of $ + exact the same timeframe, same protocols, projects.
![image](https://github.com/connext/community-sybil-reports/assets/138682155/827f22f8-5a50-428f-a304-75ac9b5eb7fa)
![image](https://github.com/connext/community-sybil-reports/assets/138682155/c5854434-bac6-47ba-951b-a90d0e85ec8b)
![image](https://github.com/connext/community-sybil-reports/assets/138682155/680b1097-2c65-4d55-8f54-296d972a4996)
Set filter like that and you will see it
![image](https://github.com/connext/community-sybil-reports/assets/138682155/c9033c53-297f-4602-9ae4-0ec7fbc5d8f2)
https://platform.arkhamintelligence.com/visualizer/entity/0x6e03F76fb77C3b27A1742BbaB1fFA6aB4907eD5B,0x4aF997F78067dC2458CDe261FFAb863afa5Cc357,0x36DEE064Cde06fb3dbc51491e86f39c50Cb91B52,0x938e3b0e9e70607c50C2629fA434B9a4e5f28421,0x55e1962677f05ebE8a9A86a4c769bbD6909C925c,0x204d6dB417420c1f45a399ACBd3c622fBA3Cc865,0xD67d2F08Cbc0E3b4Cd6db121b5E0C0e5425268A2,0x8F9b13A8eB7b5E32E580Ff7Ea17a3624677cA246,0x56751AA00D610a4FdC55a6eE5ABeE52A0C922143,0xD737631129CFC510F5256cFA921BF9f6C271F0f5,0xa855EB069CAd82D7e2f785EBe21c45bc988BFa5D,0x256Bd0D84B4b50d739F82f4918723cDb34Af9445,0x762009518245AfcB8CF624A4116265eA7745F6AC,0x9C17c8Cd345C54083dF54997f545FA8C4331120F,0x1De54b3cEb149647Ba7417bFb738C6302E8bb57f,0x0f87452A7Eac3BCFE90Fe4187d2f922d1D6699AE,0xE66e4B4F43B6C7e7DF71C0E325aD6797f3e66B3F,0x21e1f54DAf64b8A996bEfAd961FfeA89C9Fe20eA,0xC52d24a78207b8c380d9B0Ac2E5Ec699DaD04241,0x37528d958cCe45cC41D37be5cAD70372cf3bA509,0x390fd846c06Ff8e98E60B5FCde42c58AB33A9FA3,0x7ac21D972E8260CD6882bD548f88C248B620C44B,0x49b26Fb864D41951Bb7CC8AeC4b82d90101C4675,0x9152B598995EcD590DEe9C67f649E1E8533af46f,0xE40f140CcfBC72B20dE822A56DECb612eF4979c1,0x4653ff13b065B170f28C03871E343Bb2425ADF2c,0x3A8Dea6aF608C6c6B2CAF86239d8B223CE4aEDE2,0xE2B6b8E9aa2c9C9e16A672DdC655B4712F28Ce86,0xEA1c10435Ba64c02aD3d7B1C15F7255222967BC1,0x9308Bd4fDEc064521ba86D61fbe606569964AbB9,0x2e44BF02BAA8a4D83A08FAdB3Fd9e901A0c53108,0xD330A7d4Fa8500d35e538dC724A74c00559b2257,0x4455ddaFFE71cFBB094fF6864330BCfcCd7E4680,0x4E9a4bD232B23D95D75Bd553dA3025400825309e,0x7c042956468e5993a994008b5966EDb3fD1b26FD,0xE8CC278fa39bE0600D042214cD35f0154D15Cfa9,0xD471A840Ec81bE3ce5E1325413581a1EaF5dcC11,0x6806f5A7d35f6B31F8cee5799Fa7f70571B0D2b6,0x495446F7fD604608A23009fA12E65d0a7554b5F3,0xba181DeB98AfC2202202C9AeBf26B18f46D70497?flow=all&positions=%7B%220x36DEE064Cde06fb3dbc51491e86f39c50Cb91B52%22%3A%7B%22fx%22%3A-58%2C%22fy%22%3A-7%7D%2C%220x8F9b13A8eB7b5E32E580Ff7Ea17a3624677cA246%22%3A%7B%22fx%22%3A54%2C%22fy%22%3A-11%7D%2C%220x938e3b0e9e70607c50C2629fA434B9a4e5f28421%22%3A%7B%22fx%22%3A127%2C%22fy%22%3A-18%7D%2C%220x4aF997F78067dC2458CDe261FFAb863afa5Cc357%22%3A%7B%22fx%22%3A130%2C%22fy%22%3A5%7D%2C%220x204d6dB417420c1f45a399ACBd3c622fBA3Cc865%22%3A%7B%22fx%22%3A67%2C%22fy%22%3A13%7D%2C%220x56751AA00D610a4FdC55a6eE5ABeE52A0C922143%22%3A%7B%22fx%22%3A91%2C%22fy%22%3A20%7D%2C%220xD67d2F08Cbc0E3b4Cd6db121b5E0C0e5425268A2%22%3A%7B%22fx%22%3A82%2C%22fy%22%3A-52%7D%2C%220x6e03F76fb77C3b27A1742BbaB1fFA6aB4907eD5B%22%3A%7B%22fx%22%3A116%2C%22fy%22%3A-41%7D%2C%220x55e1962677f05ebE8a9A86a4c769bbD6909C925c%22%3A%7B%22fx%22%3A104%2C%22fy%22%3A-58%7D%2C%220x256Bd0D84B4b50d739F82f4918723cDb34Af9445%22%3A%7B%22fx%22%3A57%2C%22fy%22%3A-44%7D%2C%220x9C17c8Cd345C54083dF54997f545FA8C4331120F%22%3A%7B%22fx%22%3A75%2C%22fy%22%3A-22%7D%7D&sortDir=desc&sortKey=value&usdGte=0.1

# Methodology

I have anlyzed TXs of these addys and tried to find direct transfers of ETH but found common pattern. He has used same amount of funds to farm airdrops for many projects. same timing, same dates, same $

# Rewards Address

0xEf55a4cE12abc04459f30BfB4BCD0a65Ec1F6475

**Comment by ArjunBhuptani** [comment]
There are valid sybil addresses here but also normal users. Marking as invalid to avoid collateral damage.
