### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by Svetusikk** [connext/community-sybil-reports#37]
Related Addresses:
0x363b52c2c0c6084a7e14b39ec517e710528228e2
0x057f24b395b20d4ca7632355d3c24d998b02cd6a
0xa386136f9d200ffd911ead40f61e563e2195781b
0x0e789d0ac19ec4c1ff74c34bd84f60722fdf86b8
0xada164a43673b0cb03d779e634530b4e1315596e
0xa97497823e22029b120f4be9afed4d4ccca9a831
0x24250d58a9a5765704ede78ed5263d526b73c842
0x0f90e3acc151116d39169b8471e06a75149e140a
0x7c8eec3773404ff52fe8358083b7557c91f06a4b
0x6b510f8cf06875da3a951fd60e02761a1a60f203
0xf3a3aef8b4ca0c8570c0f3dc96d96648e5562108
0x29c173b78d72d96cab64869f4c5b10c07668798c
0x25b6db48d5c9e2e831987586854163d4fbb63a99
0x316d6cc40e14be9bcd00a509c29efd2a20261da3

 Reasoning
 On June 6th they have added liquidity with the amount of 500ish or 1200ish usdt and removed it right away (Connext on Polygon). Then they came back on the 11th of June and added liquidity of 5000 usdt and removed it right back (Connext on Polygon). Please take a note at a very similar time when these transactions have been made. It is too big of a pack of addresses for such coincidence. 

Methodology: 
As I was a part of a liquidity campaign,  I was looking out for everyone adding liquidity so I would make sure to get in top 30%. And then I noticed a pack of accounts adding the same liquidity at the similar time. As I was just using PolygonScan to analyze these are the only addresses I could recognize at the moment.

# Rewards Address

0x1de65419BEADbAD7204d724abE66f6F471d006Bc

**Comment by ronaskin** [comment]
![image](https://github.com/connext/community-sybil-reports/assets/137379395/9ee6df82-5e19-4be4-a2b8-bf3acc205d2a)

**Comment by preethamr** [comment]
VALID REPORT. Passed these checks:

1. Most addresses were first seen in this report.
2. ≥10 addresses are in the allocations.csv
3. Sybil-like activity found:

https://platform.arkhamintelligence.com/visualizer/entity/0x363B52c2c0C6084a7e14b39eC517e710528228e2,0x057F24b395B20D4CA7632355d3C24D998B02Cd6A,0xA386136f9D200ffD911ead40F61e563E2195781B,0x0E789d0AC19EC4C1Ff74c34bD84f60722fdf86b8,0xADA164A43673b0cB03D779e634530B4e1315596e,0xA97497823E22029B120f4BE9Afed4d4CCCA9A831,0x24250d58a9A5765704EDe78ed5263d526B73C842,0x0F90e3ACC151116d39169B8471e06a75149e140a,0x7c8eEc3773404FF52fe8358083B7557C91f06a4B,0x6b510f8cf06875Da3A951Fd60E02761A1a60F203,0xF3A3AEf8B4ca0C8570c0F3Dc96d96648E5562108,0x29C173B78d72d96Cab64869F4C5b10c07668798c,0x25b6db48D5c9E2e831987586854163D4fbb63a99,0x316d6cC40E14bE9bcD00a509c29eFd2a20261dA3?flow=all&positions=%7B%22connext%22%3A%7B%22fx%22%3A-38%2C%22fy%22%3A-116%7D%2C%220x363B52c2c0C6084a7e14b39eC517e710528228e2%22%3A%7B%22fx%22%3A47%2C%22fy%22%3A-109%7D%2C%220x057F24b395B20D4CA7632355d3C24D998B02Cd6A%22%3A%7B%22fx%22%3A-252%2C%22fy%22%3A-43%7D%2C%220x0F90e3ACC151116d39169B8471e06a75149e140a%22%3A%7B%22fx%22%3A204%2C%22fy%22%3A-52%7D%7D&sortDir=desc&sortKey=time&usdGte=0.1

**Comment by ArjunBhuptani** [comment]
Valid report. All addresses have the same patterns:
1. Funded from Binance Hot wallet or bridge ~430 days ago
2. Removed $5k of liquidity on June 11th
3. Most recently received tx from Binance hot wallet related to Radiant

**Comment by A-Keyboard** [comment]
@Svetusikk Can you dm me on Discord, my discord is khlilo

**Comment by Svetusikk** [comment]
> @Svetusikk Can you dm me on Discord, my discord is khlilo

I did, golubeva.zhm#2522
