### ISSUE TITLE
Sybil Report (230 addresses)

### ISSUE THREAD

**Issue by lexkeks** [connext/community-sybil-reports#385]
# Related Addresses

0xaFD592c41Bd914b58a7eFB62b30D80a97b19647d
0xfa3e1bbb9afe09cd620bdf7ca35d55f6b7eb7672
0x731e452c716354b255bac9abe39d98d8900648ca
0x4411a55c0474e788473bc3db8ebd8bb4657a6a43
0x6e7dfc974a3bc79d0696831db9fe90ace75231c4
0xa546d95f4447ab0099ee5d15568a998a3c533f74
0x42172ae1581d49012ad8d587eabf8ec553705b13
0x7a9437b71b6ab04bc220a0686e0bdb1716aca62d
0xeed2e58ede86352e4db8bfebebfb3749e82d7778
0xb700b60a85452c112b3985fe5df8f0815fe3cff3
0x31887c2ed34f9e50fce9d5c93e15ea83733c0a11
0x5524af5aa91b5f4262cab24ee1962882e12309ac
0xb34ea8cb05d499257727f2aea342ff35b1722800
0x56bb7eb3e64659b465b84e1e429dc9b5932ddc9a
0xaf9198debcbb2f43ee023bfd9a621e2070a273f5
0xb29d1bc1e3eefcc112c417a6b30c5550971a4e80
0x152e1025b4f85a04fe877dd2770e001b56b6b584
0x1fe5e913a63b1329b38cb21fbcc76d888c98ae7d
0x4a945311f40647d2732dbfa5b10eed5f65eb892b
0x0a9c426c91f386981d8f609b4441e8050b1433a4
0x95961a09041cae851b2d53e45c8d55eb0746d830
0x09ed04f8908b77a45f67413fc018b2b5ad83d372
0xaeae4559f21b256cad73cfcaa53cfa0942c95c76
0x09077cf938d974230fcf9ac445bd14a05729968c
0xd8f20c53ddff16ad010e5f32540bd5d0d81942bf
0x18683fee247f0370f55bb50bdb2962c0690971b7
0xbdea6b37fbe5b3697e6e28fb82dc70901dc9d292
0x84ac1ed97a15fa11c2d874c8edf94f8db66cf37e
0xc163940f4bcf0bfe1457e1dd93951a7e269cce2f
0x6ff38230f577e721cb204a8a3e4b7ea681a5e50a
0x618e8cce74ddf76f31817daba1363ba144a5b1ee
0x8967a6a1d9030ad6f54462070eda1e4873f55677
0x11f0bd6c0a83df7530a93011733e98519bb5ecbf
0xb97e2d7902b6567d68e152a520278cfa86327349
0x6e9a48a397d5ac07982f280405375046853c43b0
0x7828153621152874be7c555be917f7a2a7590f32
0xd1fbca43b694b721a7e25d5d3a24bebd840c5b1b
0x51f458a8365beb6726aeda9e22b15ea42d081512
0x3af325ba23b44ca5beab3c331fe989e76efc31e4
0x407d5544aed83b7b8888e0958000d6d5303902c2
0x2feb23b60d4bb2c265fc0b53ba003b68cf2e39a8
0xdaecdfc98b8350c3b1309ff10d7580e4fbabe80a
0xedf177c20755668f0e8a1bf8371aa61964a67c96
0xca446c62c8c41094e3afdddab5148a5f187fd36c
0x75730ca245bf76fb90ce88f5c1694bb126ab77a1
0xda078b02158a908d43fa47a09f094e93b350cbdd
0x927d4b636e1961edaef264f38bc7657430650469
0x0175b7d55033c3de0f29236cd96ad94250278f84
0x646bfbeefc313218caf7ffc966a0cf20cbc93c76
0x972dcec68ff2a0e8e58dc7efc6f52555231fee5a
0xc2f4ecae14e9d4f07a43165c9c1917839ec83040
0xcfc085d720dcbbf6299b554866385e7379ebec3d
0x286d95a9acc919311b0dd0b6c8dbccae98e1a468
0x41222891fa5d0ea04974ba6b9f07d179224a52f1
0xe313cfc2724d32955514857d13e447c050b5976e
0x7474497c5a9ea142d4b6ebfb0cb9af7a5cfa7337
0x67368d20ac1e58335af699df37b7898100a0ceea
0x53161edded3f313e2e0de0309b440e63e1b5f789
0xa4134e9c8b3768c35d3e7cbc6bdbb3464fb4721b
0x3b0f05d65cc2e9161e188bed3c217f926e5bbc77
0x9d394ea66fec0212b3d935da7c68b9ba1dbc8663
0x9f92d64440512bd6d7a9516e3e1f857ea5ef122d
0x330d4b229a2a70cad248b4fcb15d272cc629eeae
0xcce72882616b18f6f60adb711dbf4dff9cd7d661
0x65b1a8796eafc49b5c47779a834e4a5376aa4298
0x346da83a6a9580bd18473c5dbc0aed30b2809ca2
0x3d7282966d04d05de54b7d778766cf9b123548ec
0x624d3abefcd65efc0565445649a5bffca86b9777
0x04228991b89bc108db76e13c053846f5f7c02c48
0x0fdd5236bb3955c0991742863c09dea11f2cc8e0
0xdc5c4ad6a0dec834c5c880b504e5f65da3d37d7e
0x9e0345637f85fac20c24acfdad41ea4f07160ccd
0xf0c4dd89d7ddfb17a70ef5530b0f777bbcc7c744
0x222a8eac9c66487eeba66f8c5fec8c1281eeee4b
0x7d4c1a5bf3ef1598747cd6471c9d4e2664a5f4ad
0x6946524e8ef26fd6085a2179df746b356b96a464
0x4187c2130972b9c3b13a5980e2883dcd1d13c1a8
0xac16d8101da0559623ab94eaa8d31ea03dbaa470
0x7f739cfb534596ef494181f3a1f2d787511e847d
0x0aebb95e22771565c5e8baea09fd508b349060ac
0xcfc352a6d3911369bb0be78b8f00d58fde89a966
0x3289a1a9b635c6a74450b16e722f872b2a841059
0xfd1178f94050953183daba75edf7003fd3a33380
0x986b81cc0285fa4ab9abd8be0aec0cf3ddb6a405
0xb9f5298a0034b0053c6592f9a4e8ba52063ba28e
0x7e503df57b8f70928d80a7c89522981bd37b1e8a
0x6128454244bbadd532236e9290b05b15a2f73249
0x96896280b8f829f03175ddf32db1cc4c0fdea067
0x33fd27cdd1a286a11f848458e717510427c53638
0x636b790a337ff8a1a56e1b87db7c0d3c48976e01
0x9a158e96c341bdcf4d6dced83f62d1866b6eca39
0x143315585aed39710c3e4ba92b5f43fb5d442d44
0x6763bc4c2f6f41b11d445948890ba77d6cb6a739
0xda08543b808f4f9faef5262bebcff8d3758e4b2e
0xfefc4b36cc12a4fb84356416014c4af2de7b48ec
0x6ab5c9e50bed9a3dd37b912ed3e003c3c74c886d
0xde7bcfe034b4af2a7cc4d20cb5d08c58a92ffc10
0xdcb6a3881826427b58cc0a8b4860d49104e78ab7
0xd2d2c6161584af9de9d8649348f8203ab4413e17
0xdff24f6369c3055a9f72c5b98b3579ba6cea3439
0xa5caee452b101053d4c79226401b5834106618f6
0x85779b02e46d3a3ace9cd6853bd73d164679e0c5
0xbd53bcf01f5b881d82670c1303174c46e0507665
0x28d4f69173413105af5cac1002e08e50ca76e601
0x84b3bb4b81e8a0aea1cd3cc83a17aeaabffa27ca
0xebea5006ce632515f1c0686f91169677685ff88c
0x820410f81004b52540fd0ac80bc4af68c4584a73
0x93ab5760893d899368492079d38a115c240eb36f
0x1d3c09fc3bc1d616c6087fd8d6f68a68de6b1720
0xc0350e81e062a2c2dccfa2a82cb9aa9be4774d4e
0x9d518d97eb33df1a07ca48ed4096b398c82b4df1
0x7eff49d29cce9806d22076aec44946462f4092c0
0x4067800a691171dfe9764f136827344902525426
0xc3ad5f129a4a165a36b78805b11aa951b8b0af69
0x675a9ea58f37b9fc743087f974f774159f5e9fad
0x24489e9e51c0eb41092543ea1b57375792aefa15
0xad8a372376a675e446b8bff3e11e2337edd30f59
0x2e021af492f9c685de6d2a023161efec8bf04b0b
0x65302725dd5924452c70eb6c94b37168b990aa65
0x2405343d67664e1612cd0f5238d95c92f767ccc8
0x8442be0729c80ab1d02867eb931a1df415b3093f
0x395d6c22b3c8946a23ff4403a45e5523d30ccc38
0x6b9b4d9d21bb6395286648b8a4d0359868357665
0xffe3cf42a9fe3ce1c515c3e09667fb63af7f6035
0x6f2f5cfadfb6cb78acc0a7ecf69cd3835af03427
0xb94443f5452bd0634d277cdd717e907c11778c0d
0xd7139972c2a1f0fcc301118d8b29f915e527da4f
0x40874a7ca3ab17cd8acfcf301f6ace1c0221f888
0x0f1d9b625ed9061d95b3c8964c2bb511d9e8581e
0xab40511755d0f50ee3234b7221e588cf6bb9b94d
0xbd5a9deebbf8e220186ebeab82d3674d3224b0b3
0xc9315ce9daeaf6cf87d16309050ee544a6a229f1
0xa527793da1c77eee1ac54fa07ecaf69d013eefe7
0xc1065c85e51d092d52fe4cc8206135e506983972
0x96157f2a4ef96c06868a4c28ccaa71a7c3987aee
0x0d43a632483248fe8d3a27bbb195b3e3ce6032c8
0xb93a41911933eac9d4e98664896919fb26f0610d
0xa5a1e282181536c317626440b54b4c1a3321c838
0x6dd8e268d3fd3af0cbc3120ae5c4379374682f83
0xff3d9b068fdbf2adf9621e9547515dc822b0ef12
0xa95d5e916cdb07c62f5f111d57785c93194e8eab
0x77c5a19077a116ea1b7c8315c24ba6334439357b
0x250d3b6efe00580ba5eba2c46124635e00b2eb33
0x4fbe35a858d70ae5f0f3ea35ebca36acca5b40a4
0xf7027faf9954ea4af9a42e3937d97a74e9513f54
0xadf188432546d48ccfa5401b2dc0468f0808318e
0xf79e7ef458ac182fe48d34595a28caa77865fd6f
0xf98c41e12ebcafb49457a13665505cef8c6b3172
0x492182849225664a24becf044a58f3ccab18edf4
0x1884a6341194b41cb024d716237f1d1e47fcc7ac
0x865f991095f6652f20acf56ca8bb16999d88c686
0x599403c7efaf8664de14682fc07c367b7eb71c6a
0xa683a8505ff54349bab594b9eb2b3015df5d6ac2
0x9d1368bfbf3eaa00e604a3e5a957f99de2376b54
0xd7d10a45b5a00132d73b04e5b94e899db6febd1d
0xd1503ea668640c33881ae230c8a8e9fdd855b1c0
0x88f0e1a109235e3c6752b7d64e5c57d65a1e1729
0x9ab30ade7c63f42f1f4899e821b61a94e040d751
0x2b155ec5fd22dae1ba79e5cec90fde6ce6535fc4
0x41e4d43e2c9f5de89539d2415f94198be4f58e5c
0xe9ecc845d0566115fb0163f35c689f532c2455be
0xed0f6e5d329659a74ddca8a8ba2ffec8cea4dee7
0xaa0c024cbbdfebec6d1a4c766c829e4c7681b740
0xcb520acbbe6696f4349513b964db86985ce3b395
0xe48908ae625c36c19ea0b1c42b1c33aace1d20cc
0x33553c68917289aec1ddd521c7a2ac84516625a8
0xc481f9ea9e80636a4d40f7882cd50426d15eedd2
0xaadaddd2ae586d7533f689ed92f2241006c62f41
0x58c88e76bd888184761a1718f9db75d7437b29ce
0xe01855cb79d351c36b39af756356fd3919625b98
0x6788564fb1251c5e984df97bb7909474a3d078f2
0x0be0e55841897d8ee56974eaf2af3dd8ac599893
0x88990242b561bdc49e738804955ea5de69610656
0x3a46d0dc38d5c0a49d15dfe4affceee0fcacb884
0x57370d706df241118bce479af48cf3f6a4474294
0x9352c1006e0fb1684130bcf4b276415b9ac1c1bb
0x1dc8bf04c401bb2a1f76abef010da3801a25811f
0xbd9f50699cf94be1028acffa7b2343f59a5db86c
0x88f6ad22150ba28fa413bf44f465c6820e602d8f
0x3c7036c261eb5cb78cde852f259e073a5cdeb421
0xa0ae4af970328be1d9b641adc290d931153645d9
0xdf96bd6c51aa8eacd20af31dcd9add9e680db29c
0xd73f4d5bd0a71f0000b7ae193d0838b6684d7318
0xfb7e2b9b4fb436634ad6182ec062e651f0334a77
0x1e1dffd133fa23bac8ad18f8b7bb03ab508e02c3
0xf05df256337f2b0d59e26775266cfb6e07bbea55
0xe6e9d63f19ac8e59d28fd997a7fa7d665082f3f7
0xd33700661f11a0902db9d2e2a6db57b4cc1af3da
0x7989c0eec1177b5f26cd76fc2ff43905306dd9ce
0x168ccae7ff5db7456588d6b2c458642fe4d74351
0x022cb26394bbf50f0f7d7d6a1a265b905fd9910c
0x97ae1418fbbca97c284f707810eb43b4929fb501
0x4872352c06241eefcfa2b78a7e266c24ee3a34d6
0x7ba8378fc9fadb2c96153158a0ebd6693de29f95
0xe11a1bfb06aa22161b9479c8c8c8d04b0e85222d
0xf38401c98bb0cf13ef98f269b3e7125dbb0bae0b
0xaa38abfd96e43f6af54c49931b62723788510d86
0xf8b16e448d44ab2ba819c9f668cae365acf87d58
0x36d86ea9642c277030cb2e45dc0da506cd824c79
0x88a161cfb0439587fedd5006410694dad0111e65
0x5adbd8edc77d6c8604ef906913fdf424a96df342
0x23fa9daeab06fe46b268611d77dada5cd8cc6d60
0xdb1c53055065e0d6370566d70b1080a7e4c408ea
0xaac7dff46bb18a7543d86108ddb37e101a943ec5
0x37b9c6e73155b18883445e2a02182cef8a5fbf08
0x3b328a85a1176a87fd97fe4f12358ea48526fd83
0x89cc7a098a152b419dbad942a1773fa57b2d49ba
0xed659796a9f40b21a832a1f425c78707b232333f
0x52f09827f3d842370359b54c87480b89059082d7
0x9caff7825efffd8a35fa91ca83f84bd11c1b421a
0xf103f7d28b45f242d725a1fc92cca12e8313339b
0x1a78915f002955ca32f286982e9e1a6f2571cd07
0x1dc8020695b34ef7082af49b3e562ad9998b0f43
0x6a44694f6a370632f669b8dbbf0077aedb994958
0x2c115f24b22c5a9ffd0ed66c431f63f89dcbbdc1
0x4111a85c5b668315b29d261438b46a231ac40aca
0xef26016bfac27fc28047f90ab239336de0405188
0x8c92bfc09833f8e41b791d499d3d56485a9dcc1b
0xf9a5121245d47c5b7c5e2261ffc1a2d0edc5a4bb
0x9583f411d8848daf0e390644aec80d1a8c234869
0xc4bc6108555c6f70b133129bfac2b0f60cdeb5ae
0x61d4ba0cab93d26314380ee4ce708e5fbaf15bbd
0x4f7962496442aa359041a7807862db5a8e6ad6d4
0x0f0047f984d200d9974f6813cf43759912be0776
0x1ae714d1b7503c883a6c00af4a13a1499e571d90
0x39654358c0028fb5b2b3d3333a72aafb3f411102
0x83309d4dd0fd9a160547ecdbc0929217e4a1882c
0x66f0c50f3de2aa153f60db53b64df0332547f493
0x4a1ecfa5cfda20a6efea7a20f718bca2dc857747
0xa93068e8b6d7c0f584599acd94eb0fd50fd7a7b9

# Reasoning

Addresses were created 2022-09-27 (~130 addresses) and 2022-10-27 (~100 addresses). Funded with binance and clustered with dispersed with "disperse"

All addresses have absolutely identical transaction histories from first to last:

 - Farm arbitrum drop transactions approve tokens on odos (only approve on odos, nothing else)
 - Collecting shitcoins that were available to addresses that received the drop arb
 - Distribute DAI tokens using disperse in a quantity of 12 to 24 tokens in one day and add to liquidity pool on connext, 2023-05-18
 - Collecting LP tokens on one wallet on 2023-07-17 and then deleting liquidity for all these LP tokens (I discovered it because of these transactions) 

# Methodology

 - Collection of LP tokens on ONE WALLET 
![image](https://github.com/connext/community-sybil-reports/assets/133111020/451602ac-b781-4992-a168-db8085a102a6)
 https://arbiscan.io/token/0x61b3184be0c95324bf00e0de12765b5f6cc6b7ca?a=0xafd592c41bd914b58a7efb62b30d80a97b19647d
https://platform.arkhamintelligence.com/visualizer/entity/0xaFD592c41Bd914b58a7eFB62b30D80a97b19647d?flow=all&positions=%7B%220xaFD592c41Bd914b58a7eFB62b30D80a97b19647d%22%3A%7B%22fx%22%3A-54%2C%22fy%22%3A-10%7D%2C%22connext%22%3A%7B%22fx%22%3A39%2C%22fy%22%3A-38%7D%2C%22slingshot-finance%22%3A%7B%22fx%22%3A61%2C%22fy%22%3A-31%7D%2C%220x1A18735f738C21465c6885f5787fd28e4b71Fe4a%22%3A%7B%22fx%22%3A73%2C%22fy%22%3A-14%7D%2C%220x0000000000000000000000000000000000000000%22%3A%7B%22fx%22%3A63%2C%22fy%22%3A-5%7D%7D&sortDir=desc&sortKey=time&timeGte=1688601600000&timeLte=1688860800000&usdGte=0.1

 - Examples of addresses that were sponsored by binance, and then sent eth through disperse
 https://arbiscan.io/txs?a=0xf0c4dd89d7ddfb17a70ef5530b0f777bbcc7c744&p=6
 https://arbiscan.io/txs?a=0xafd592c41bd914b58a7efb62b30d80a97b19647d&p=10
 
 - DAI token dispersal transactions for subsequent entry into the pool
 https://arbiscan.io/tx/0x8e3efd4e7ca2fd180ebd38ff96852ff6adf657c9273475adc66f4fc613010c14
 https://arbiscan.io/tx/0x1028204c94b29b427d0b5d06397a4a5945a881014df7545ddebd237b8ba64f5d
 https://arbiscan.io/tx/0x8e8baae65571d31575e92761c0ad37721970281fdc2abd4ca82702eeea606e23
 https://arbiscan.io/tx/0x0260c7d8d79e6ad614b83bca69290fac870ee1f78bd581d81ed3d48740f930a5

# Rewards Address

0x6f9bBD2D72C9F42e8fafa524c50f28D904590a12

**Comment by ArjunBhuptani** [comment]
Copy pasted from other reports (without changing order of addressses). E.g. Fourth farm of #133
