### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by dexter0808** [connext/community-sybil-reports#388]
# Related Addresses
**Group 1**
0x0fa5f802967ad61e6a9335a7d0e3a59c68dfb0d6
0xd253b2d95aa793d99b92895f2e6b4dbad889cf0d **<- main**
0xe453bbd39a1b3ec58ecec53d6bb2d06709839012
0x451932128a719d7f977de300910157aa910f68c0
0xfb394aeb48291bb1e455e19a4ea6ba5258c0d345

**Group 2**
0x131b76b9b89dd3d98147ec3b7e2cb73adf245133
0x070330e027a3e4327ba69f0c8a1885df4b545837
0x77edee3b888d9ce54df25b18a4badf9f6340d733
0x6afd0cf9e929bf7c46b8b729233697bc22607888
0xdb9718552f6b5a06422d7ce790a0f47241178753
0x8de42a7b282832b84bfcf7c2e9edb882b99abaac
0x56df4482739435c82d8129a98555ac93d1f3f525

# Reasoning
Group 1
Each of the wallets has a huge number of transactions between each other. The primary wallet has been found. It also has transactions to all wallets. 
Drops from Arbitrum are sent to the same Binance address.
0xcb215587b481327f78ee10acf740a934b1a6de12
tx:
https://arbiscan.io/tx/0x812e9a87bc116b1f9fe984bfa1c604b0e60e8cc2345f583dec10a7d6bd9dc140 https://arbiscan.io/tx/0x617ef89843db24c805a1b1c806ee26ea654299534cf1c8fee64e702d35d3892b https://arbiscan.io/tx/0x4106ab863d26343dfec6e83f920d658d8a7a36674a5e3ce0e3a7ba44f3350d6e https://arbiscan.io/tx/0xd2e21830187c9de11d68d43f6bd786605f15fd4cf143de97d99c0a272fd3cd54 https://arbiscan.io/tx/0x83594ff9a8b452cb00f467eee5380eabae918ec6cd2d4e675f21df0ae30d4233

For further proof, claiming SOFT :
Date: (Aug-25-2023 07:03:47 AM +UTC) to (Aug-25-2023 07:07:11 AM +UTC) in 4 minutes.  0x0fa5f802967ad61e6a9335a7d0e3a59c68dfb0d6 this one in not eligible for soft. https://etherscan.io/tx/0xd705baac3644eb8b96970488a4b72e6adf5f7145d095945a7d6314a516cdb27d https://etherscan.io/tx/0x3aedd04087b1a362c0fdd8064ac9090f3a4265b3993e25d598aac99c77810868 https://etherscan.io/tx/0x5daab313a18a3cc0a93e9e8b4090c46311d38531b92df38fc1f7f36bd03ddb7e https://etherscan.io/tx/0x4c98933d2ca3e4d62136f9097c44027601b840f33d57e4a0cffedae87d986f10

And last: absolutely similar pattern of activity, that we can view in DeBank AND screenshot of Arkham between wallets: 
![photo_2023-08-26 18 11 34](https://github.com/connext/community-sybil-reports/assets/95591801/87e25339-5750-4f0e-a91b-48651d5b93d8)
![photo_2023-08-26 18 11 33](https://github.com/connext/community-sybil-reports/assets/95591801/5e2d1abf-6e70-4a76-88ee-8680e3b166b9)
![photo_2023-08-26 18 11 10](https://github.com/connext/community-sybil-reports/assets/95591801/87b5e2f2-c6fd-4b3e-a9b1-205955374b36)
![photo_2023-08-26 18 11 09](https://github.com/connext/community-sybil-reports/assets/95591801/ad722c0a-829f-4aff-8f1b-256a9ea67215)
![photo_2023-08-26 18 11 08](https://github.com/connext/community-sybil-reports/assets/95591801/34f9b3a2-3bf9-40c6-a134-d56f320409fb)
![photo_2023-08-26 18 11 04](https://github.com/connext/community-sybil-reports/assets/95591801/1278d2ee-6ff4-4207-badf-7eae6e27d540)
![photo_2023-08-26 18 11 01](https://github.com/connext/community-sybil-reports/assets/95591801/66bd9319-9a2f-4407-b8b2-51ecf3b18cb3)

**Group 2**
This wallets have the same deposit address in Binance. 
https://arbiscan.io/tx/0x1802c2957fe6119572444b33ac7eb7f509b58a6b2f8b3709d306642e55a2f79d https://arbiscan.io/tx/0x0cb65578b559cf7f9808c8f0c1e33d56512dc07d9f6a917d12235effbb7b783a https://arbiscan.io/tx/0x02cd4f7aa8fc26f9d44d02b2edd87b3173506e254d20a5a2c8a8dcb73745bcb8 https://arbiscan.io/tx/0xb16b6a8662ac92f84bb8dffe26a5f8b097a9842e6bd95376bb6553f0553719db https://arbiscan.io/tx/0x5b7943fa671047bc2f057424d2d8d47a8874fee44bf0354b0089ac9d60358655 https://arbiscan.io/tx/0x353f7bc84d8fa1365da45600b015551e8974ccabafa5cd96ea6bc0e6d0599010 https://arbiscan.io/tx/0xcaf347448feb5b80da4cd9b9704bb19aec3cd4b8a8755e7968a60f9ea65e2162 
It is tx with transfer ARB airdrop to 1 Binance wallet.
They all have the same time of claiming. except MAIN wallet( in 1 hour)
In DeBank they have the same pattern :
![photo_2023-08-26 19 18 00](https://github.com/connext/community-sybil-reports/assets/95591801/9a6d7210-add9-46d2-91a5-d2b5e0055f20)
![photo_2023-08-26 19 18 01 (1)](https://github.com/connext/community-sybil-reports/assets/95591801/740efbfb-659b-4026-ae4a-714e28474e23)
![photo_2023-08-26 19 18 01](https://github.com/connext/community-sybil-reports/assets/95591801/8c302c55-0634-4f8e-939b-2fa47a7523ef)
![photo_2023-08-26 19 18 02](https://github.com/connext/community-sybil-reports/assets/95591801/e2df2bab-3550-40e2-a557-170d23f249d7)

# Methodology
Im used this simple Dune - https://dune.com/queries/2971072/4924426
By hands search some sybils. Re-check in scans, in DeBank, in Arkham. Only hands. 

# Rewards Address
0x2E26013c4a52c6a80F58C36A5E1301FaA849A2DD

**Comment by preethamr** [comment]
INVALID. < 10 addresses are first to report here.
