### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by jessepinkman24** [connext/community-sybil-reports#392]
# Related Addresses

0x07bafbca23c27d7102883d87ceb931deed804f9c
0x0b5ba3f1234e239acd7c196c7d23c873ca45172a
0xb4b1e0c6f2e728c17612751f75f62278790fda3d
0xe28dd7dba26ba3fa8581fc381ffff57f4fbce3ce
0xde64c2925893a6c9841c0ab0d274a886a494f2a8
0xd17fc86bc9d50872df4d2b10d8855e1965a6baca
0xcf2cd1a1113a24cfa89f935466c46c22107fa75b
0xafad93492b75cdfb3e685c09966aa8ee6ad872c4

# Reasoning

A farmer who collects the arbitrum airdrops he received in 70 wallets, 8 of them are entitled to the connext airdrop. However, these wallets are definitely airdrop farming, these 8 addresses must be eliminated.

main address : 0x12e36250117cc840e515f75557621d4a66f630ce

0x07bafbca23c27d7102883d87ceb931deed804f9c | https://arbiscan.io/tx/0xb86cf5ec4c65943ccf3411d585ef1cdd4fd375a1eb7964b98e18ddf05462280e

0x0b5ba3f1234e239acd7c196c7d23c873ca45172a | https://arbiscan.io/tx/0xc8b160cd6a3788dd88d20f37b903a826ed210546708503669e2f3420decd498f

0xb4b1e0c6f2e728c17612751f75f62278790fda3d | https://arbiscan.io/tx/0x37f56086fa77d4e7342ac1a24d67b7e3db9d36d6188b940a4c2744fe3479e17d

0xe28dd7dba26ba3fa8581fc381ffff57f4fbce3ce | https://arbiscan.io/tx/0xbff1c4518ff8c82af1f96f6804cb268c95c2534b317c1fd2826821c33f2a2786

0xde64c2925893a6c9841c0ab0d274a886a494f2a8 | https://arbiscan.io/tx/0x3cf3046ab90a0ccdce5ac916bef1133aef4f10fb044e03ce0bf28c085cef078b

0xd17fc86bc9d50872df4d2b10d8855e1965a6baca | https://arbiscan.io/tx/0xbf38f489781426909c96eb9c391dc10e67b849a3636be7c688a7d3f9df344f03

0xcf2cd1a1113a24cfa89f935466c46c22107fa75b | https://arbiscan.io/tx/0x96eb3cc8e217590ed62b7dddf80d7171a8e79e5608891d1020b140b703143617

0xafad93492b75cdfb3e685c09966aa8ee6ad872c4 | https://arbiscan.io/tx/0x78ad93bcee658f7226564d4e644f330733e8eb9c43e30ca73180c15dd23a5d9e

# Methodology

I did research manually without using any code

# Rewards Address

0x88A99B7275f53399EaAEFd700c19a04E0b39c163

**Comment by Alexiyko** [comment]
0xde64c2925893a6C9841c0aB0D274A886A494f2A8
It`s my adress, but it`s was hacked by hacker and he put drainer to steal all my funds

**Comment by Grraarrgghh** [comment]
Doesn't meet 10 address minimum

**Comment by jessepinkman24** [comment]
yes there are 8 addresses but the owner of these wallets is airdrop farming, only 8 addresses are eligible doesn't mean it's not sybil

**Comment by jessepinkman24** [comment]
> Doesn't meet 10 address minimum

yes there are 8 addresses but the owner of these wallets is airdrop farming, only 8 addresses are eligible doesn't mean it's not sybil
