### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by Targaddon** [connext/community-sybil-reports#457]
# Related Addresses
1.	0x5ea836c9b6524a91537a66b9905aae0c567ad12a
2.	0xa0c9cc79a51b2c9d8396f23a28da20aeca009524
3.	0x59e7be55a5fb2d76895b93742d7a2d256012d6ae
4.	0x0d7ee099c445e283c3177d0ed70613791fd2f5a2
5.	0x4bf16e85fe6f0d3d644a754699f7557cd206dc21
6.	0x3c3b6463756c82ca72da501d7c53f3774a613d15
7.	0x5536d2006b92f835bff0dc92f0b2e36e4743f9d0
8.	0x021847aaa30a9cd843f20ee25d67c42498e0d2c3
9.	0x21a2a14d42e657674768154b75e8e654c5c2941f
10.	0xd456f3757d5719e5ba738669895eac1a3c4cba14
11.	0x35eeeccbb551a4260ed111194070706d16f154df
12.	0x3aebf13d319905c382934bb33c9db73c0a87f8da
13.	0xa19c0af2d75b30e382778b4b76dd7cc7c653eb23
14.	0x014c7050ac169b7474bff7c75c653c4a49b08ea4
15.	0xe36cddf55252866fac28d977e7f1bcce35108bce
16.	0x4c8dc87beefacf5aaf693ff60af5a141bb1d6132
17.	0x75d1b87c99ed380dd7d9436e10bcf521956e1080
18.	0x88f50472daa8a0b2f1a31293329eae5a70f50f5d
19.	0x99bc877e25bcfb3ff3d61a84acc825857866046c
20.	0xec1d809c60e8c4713fb2d7775d8f1781c106db2d
21.	0xd99eea8642df6bdda53faf0a0d1142c08df8a956
22.	0xca15c62021604b1f5ab90007e16c9053cbedc87e
23.	0xe6ad9a32a46811d83477016ab68d46fa3f1423d5
24.	0xd7e55f2902354b1762af36ef2c97b5acb45e05c4
25.	0xa83e8fbe108c3491f4a316d84e23693cadb5b140
26.	0xf9490b5036b219a68eb7555e7cfa066edb68db8c
27.	0x11fed407a8795a39ece1a123e5cefb4ef02f5aef
28.	0x3b109b38dc3740c63b1d2f80f48efef21469fc57
29.	0xed8921a75ac2e8ab833f9ed9466fafec53e88526
30.	0x8a451b7f66c9cc230c850095b5ac5cd5a1f3c9dc
31.	0xa47bc1f001d461aecd9d88e620d49779c19fc8f2
32.	0xcd0eb64a1d58c77f824108c9aa0439060ccdf5b4
33.	0xee8c4e9a1524b2bf0c6294a9c15a06f9546735ee
34.	0x2d84ea94f67292a245076c97a9ebad9d260bba2e
35.	0x1354ee9b9748fb265a16789fb4d2bb1b54312e50
36.	0x707246b1af830122aadda41bddf61e18f759fdc4
37.	0x2dba4d669239fb04ebab5720fc181ae48f5159f1
38.	0x0355786221c9c34935c61ecae9a68c8c044c0161
39.	0x6e43ed92ce1ba8c1b7ed405abe70981748877033
40.	0x54f34ff31b8039f2d96019be59d51c8fc07d4341
41.	0xd3570efe4023cdf53db84c5910e7f147ec9b9d0a
42.	0x00d116e7212cc575b3f4903a29190bbbbc52f322

# Reasoning
The first dates of activity of all this wallets the same - 2022-10-25 - 2022-10-26.
All accounts made consecutive transactions in the Connext network within minutes for comparable amounts by Add Swap Liquidity.

Below I attach links to all this transfers on https://arbiscan.io/ and to accound on https://debank.com/
You can check all this information there.
Also you can download a https://arbiscan.io/exportData?type=tokentxns&contract=0x2983bf5c334743aa6657ad70a55041d720d225db&a=0xee9dec2712cce65174b561151701bf54b99c24c8&decimal=18 to see this table:

![image](https://github.com/connext/community-sybil-reports/assets/95530388/12023b69-df44-4f08-8111-c511542c2682)

Wallets have almost complete transaction identity in Connext:

a similar volume of transactions;
the same sequence of transactions;
same transaction times.

1.	https://debank.com/profile/0x5ea836c9b6524a91537a66b9905aae0c567ad12a	https://arbiscan.io/tx/0x2099e7fbee5db3bd3559449559a710c3796ca7cbc55c678fb44be5e50155fc86
2.	https://debank.com/profile/0xa0c9cc79a51b2c9d8396f23a28da20aeca009524	https://arbiscan.io/tx/0x1ffb682c284e272d7323c61880398f8b995250c113d7c3fcb0b0713870cccb3d
3.	https://debank.com/profile/0x59e7be55a5fb2d76895b93742d7a2d256012d6ae	https://arbiscan.io/tx/0xb9e4afd8dfb161a21763e05988a6ab1c0c632fe7ccc98dc7d2717e414206a4fd
4.	https://debank.com/profile/0x0d7ee099c445e283c3177d0ed70613791fd2f5a2	https://arbiscan.io/tx/0xe9a9e054404f67783b5549047c0d35b4216e91daee9379ff5aa23a32633667f6
5.	https://debank.com/profile/0x4bf16e85fe6f0d3d644a754699f7557cd206dc21	https://arbiscan.io/tx/0xba2525fe14df66ff25663b7713f6d5c91f0d5551560a72b141681e4e3bd1e0fe
6.	https://debank.com/profile/0x3c3b6463756c82ca72da501d7c53f3774a613d15	https://arbiscan.io/tx/0x8a1d5fe3211c09b44e655fd3332e6217499d62266550582e8b9c814b8345ff14
7.	https://debank.com/profile/0x5536d2006b92f835bff0dc92f0b2e36e4743f9d0	https://arbiscan.io/tx/0x3276a623fd571403f51ca53bc41a0df706f5d3c2705f6a10072b9c2ce2bf6524
8.	https://debank.com/profile/0x021847aaa30a9cd843f20ee25d67c42498e0d2c3	https://arbiscan.io/tx/0xc2af9e9224fe3f33435baec7741f435d83eb73e8ccbdbd0a36e7888de157b222
9.	https://debank.com/profile/0x21a2a14d42e657674768154b75e8e654c5c2941f	https://arbiscan.io/tx/0xc99ce42659de48e6dd3d61b2298ffa87e582aab1e608619eac70461c4f7002bb
10.	https://debank.com/profile/0xd456f3757d5719e5ba738669895eac1a3c4cba14	https://arbiscan.io/tx/0x67dae97382d4893e55d8a1a44f3f3cbd21acb4f82f39c6b2eda86ca5fd6be438
11.	https://debank.com/profile/0x35eeeccbb551a4260ed111194070706d16f154df	https://arbiscan.io/tx/0xbb995c16412163ad78aa68e8b0400d0d1dc79a647b111e8edec79d9fe4bc4269
12.	https://debank.com/profile/0x3aebf13d319905c382934bb33c9db73c0a87f8da	https://arbiscan.io/tx/0x24d0fe593c785a8ad806063fd0d4f9f4fe9ccdaf84ed4affd01b21d6c08ca910
13.	https://debank.com/profile/0xa19c0af2d75b30e382778b4b76dd7cc7c653eb23	https://arbiscan.io/tx/0xf2295a96d493ef31cdb0ce8bf9667555cb293c166ba5f17e314a371314a30a39
14.	https://debank.com/profile/0x014c7050ac169b7474bff7c75c653c4a49b08ea4	https://arbiscan.io/tx/0xc4e2b154dddbc6d5f8dc70f16ad7cacd674ae619b83a9391f0ce71679402b900
15.	https://debank.com/profile/0xe36cddf55252866fac28d977e7f1bcce35108bce	https://arbiscan.io/tx/0x95c8a3a4ffe936f7c9f353b880dd1d4738f706bf4155465f8bf75270278ec757
16.	https://debank.com/profile/0x4c8dc87beefacf5aaf693ff60af5a141bb1d6132	https://arbiscan.io/tx/0xa4cdae506693ad4ae4241e3fbc0982feed0ba6e78d0f5b3699b65ad0b01066cd
17.	https://debank.com/profile/0x75d1b87c99ed380dd7d9436e10bcf521956e1080	https://arbiscan.io/tx/0x6b04a4168800ec76004a3807f3852f5977bf2c4d871b942525fc9c83398a3cd8
18.	https://debank.com/profile/0x88f50472daa8a0b2f1a31293329eae5a70f50f5d	https://arbiscan.io/tx/0xb66bd5a1d466eb1f53e6bd272db7cf21c146ff9ff7eb79b5ed6e97aa99fc2bf8
19.	https://debank.com/profile/0x99bc877e25bcfb3ff3d61a84acc825857866046c	https://arbiscan.io/tx/0x926086d6a165b1bdc0406f57be0fd6622254f349b1ee52944afc5703a12c0f87
20.	https://debank.com/profile/0xec1d809c60e8c4713fb2d7775d8f1781c106db2d	https://arbiscan.io/tx/0x42625f702ac3f360ee5638f7db4ee8f9ab30bd02f36659abd2044bb2e5c8048e
21.	https://debank.com/profile/0xd99eea8642df6bdda53faf0a0d1142c08df8a956	https://arbiscan.io/tx/0x27c06962ddcfa265d25e1507be4fdc380139b8fcba2f3c2ca0ac8a8ec5a153c8
22.	https://debank.com/profile/0xca15c62021604b1f5ab90007e16c9053cbedc87e	https://arbiscan.io/tx/0xeaf624f5d79b104285983f991868921ea01f8f0c908772666509b2b767221ab0
23.	https://debank.com/profile/0xe6ad9a32a46811d83477016ab68d46fa3f1423d5	https://arbiscan.io/tx/0x2fe723055a2ab360021db8d8d20679281c1df82c0ad6a5cc53cf37e7466e6b87
24.	https://debank.com/profile/0xd7e55f2902354b1762af36ef2c97b5acb45e05c4	https://arbiscan.io/tx/0xe3594e8aa42f606eca1f1c1273263fab8761a4105bc62059c1d0482d5a8b406c
25.	https://debank.com/profile/0xa83e8fbe108c3491f4a316d84e23693cadb5b140	https://arbiscan.io/tx/0x1b7ec67bc07e544ca2a6d37dc3e08e507f9de641ecb6c8e82554f1758a6a7496
26.	https://debank.com/profile/0xf9490b5036b219a68eb7555e7cfa066edb68db8c	https://arbiscan.io/tx/0x1ac5af5c3e14329d78ddb61297961aa08ca92a7cc666e5e00a6fc5d4254608a5
27.	https://debank.com/profile/0x11fed407a8795a39ece1a123e5cefb4ef02f5aef	https://arbiscan.io/tx/0x9637ad64fdec5143cb779d30af10366cba7c6ad73755d9b9137b7e6c4ad8e59a
28.	https://debank.com/profile/0x3b109b38dc3740c63b1d2f80f48efef21469fc57	https://arbiscan.io/tx/0x779daf90de80edde22a2bc71721ca8536bf39bd196f65f420dde46ce6b571d05
29.	https://debank.com/profile/0xed8921a75ac2e8ab833f9ed9466fafec53e88526	https://arbiscan.io/tx/0x05c12a9e018912b8a665a0cef259d9eb08f4e4efad314c75e2029d2c952ca96b
30.	https://debank.com/profile/0x8a451b7f66c9cc230c850095b5ac5cd5a1f3c9dc	https://arbiscan.io/tx/0xca1612310340f7c475c3e21f357d70bf697e274a9a4b88b06b5ca7236adb03aa
31.	https://debank.com/profile/0xa47bc1f001d461aecd9d88e620d49779c19fc8f2	https://arbiscan.io/tx/0xe99d111f2ca958f0ff840b810aa8888e53ca2c73d22e89c089508d280d5d67f1
32.	https://debank.com/profile/0xcd0eb64a1d58c77f824108c9aa0439060ccdf5b4	https://arbiscan.io/tx/0x79c86b25ba8d7609fd98345f338932990809121d54216af04a6cc87e9ff21fe4
33.	https://debank.com/profile/0xee8c4e9a1524b2bf0c6294a9c15a06f9546735ee	https://arbiscan.io/tx/0x439ce1de9d17368a7df6d8ff57a5ef3aa1957cc77b96f3858017cde51f4af042
34.	https://debank.com/profile/0x2d84ea94f67292a245076c97a9ebad9d260bba2e	https://arbiscan.io/tx/0xfed13ea166726ec7d71ad408c682af49d647a75b7173ebb1a85fc9d8a379855a
35.	https://debank.com/profile/0x1354ee9b9748fb265a16789fb4d2bb1b54312e50	https://arbiscan.io/tx/0x5184c8a880e78dda0f50376fd9576eab9915cda441aeaf3fc691013cdbcedb12
36.	https://debank.com/profile/0x707246b1af830122aadda41bddf61e18f759fdc4	https://arbiscan.io/tx/0x69f29d1834b709d1c6fee64033b7637613c06107550247576ba76521d7bc0dc9
37.	https://debank.com/profile/0x2dba4d669239fb04ebab5720fc181ae48f5159f1	https://arbiscan.io/tx/0xff9d36eacd767149001570e78bdfe7bde1e2a68c4642025e1cf0ce3acaf114f5
38.	https://debank.com/profile/0x0355786221c9c34935c61ecae9a68c8c044c0161	https://arbiscan.io/tx/0xb36f6a64588734013c8e4ffd6b7796d0bf9c3148bcd14c72acc01edbb9210b42
39.	https://debank.com/profile/0x6e43ed92ce1ba8c1b7ed405abe70981748877033	https://arbiscan.io/tx/0xa808c2555ef96c5118ea3253a59b8ff3fa785cf8781b52f76f2daafdb4d12fd0
40.	https://debank.com/profile/0x54f34ff31b8039f2d96019be59d51c8fc07d4341	https://arbiscan.io/tx/0x280215fada619af55bc1d5cfbb17f0d0334f3d673d3e2a62c2fac6f47fb69838
41.	https://debank.com/profile/0xd3570efe4023cdf53db84c5910e7f147ec9b9d0a	https://arbiscan.io/tx/0x6c348d464341d1b4b23d75498a64d3c772455f29f83ab410d68a2394fcc0a620
42.	https://debank.com/profile/0x00d116e7212cc575b3f4903a29190bbbbc52f322	https://arbiscan.io/tx/0x07595c5917ec47b43e849616bdb1c35ec6fddac08c4c56f0886f4ee0b1531250

Another similar transaction
0x5ea836c9b6524a91537a66b9905aae0c567ad12a
![image](https://github.com/connext/community-sybil-reports/assets/95530388/d264f049-b83a-455a-846d-bf16a77a211d)
0xa0c9cc79a51b2c9d8396f23a28da20aeca009524
![image](https://github.com/connext/community-sybil-reports/assets/95530388/ac8408cb-a9cd-4899-97eb-16112be13dab)
0x59e7be55a5fb2d76895b93742d7a2d256012d6ae
![image](https://github.com/connext/community-sybil-reports/assets/95530388/6655f769-5d6e-4253-a067-45f4947ad9d5)
0x0d7ee099c445e283c3177d0ed70613791fd2f5a2
![image](https://github.com/connext/community-sybil-reports/assets/95530388/e15ddacd-b7c4-4e9a-b5ed-1145ba09e8c9)
0x4bf16e85fe6f0d3d644a754699f7557cd206dc21
![image](https://github.com/connext/community-sybil-reports/assets/95530388/50a9ecd4-1291-407b-9dd1-21c19563ae13)

0x3c3b6463756c82ca72da501d7c53f3774a613d15
![image](https://github.com/connext/community-sybil-reports/assets/95530388/9f70cee8-4e0a-4885-98ef-aa3e117740fa)

0x5536d2006b92f835bff0dc92f0b2e36e4743f9d0
![image](https://github.com/connext/community-sybil-reports/assets/95530388/06fb9d74-2edb-43b0-83a2-81decd05d42a)

0x021847aaa30a9cd843f20ee25d67c42498e0d2c3
![image](https://github.com/connext/community-sybil-reports/assets/95530388/e1758b3c-56aa-4829-982a-7444e0f13099)

0x21a2a14d42e657674768154b75e8e654c5c2941f
![image](https://github.com/connext/community-sybil-reports/assets/95530388/d10793d4-68fa-4ca4-92e5-7df211943b7c)

0xd456f3757d5719e5ba738669895eac1a3c4cba14
![image](https://github.com/connext/community-sybil-reports/assets/95530388/86d819a7-a00e-46cd-98fe-5ac81b860a13)

0x35eeeccbb551a4260ed111194070706d16f154df
![image](https://github.com/connext/community-sybil-reports/assets/95530388/c5522d32-db6b-4626-9ed4-17739633d67c)

0x3aebf13d319905c382934bb33c9db73c0a87f8da
![image](https://github.com/connext/community-sybil-reports/assets/95530388/c736e6ee-e520-4b11-a68a-4cb5914882e2)

0xa19c0af2d75b30e382778b4b76dd7cc7c653eb23
![image](https://github.com/connext/community-sybil-reports/assets/95530388/14b2ac48-97fa-4de9-876e-fbabb9e6fd37)

0x014c7050ac169b7474bff7c75c653c4a49b08ea4
![image](https://github.com/connext/community-sybil-reports/assets/95530388/1cf8c172-1b30-40d4-8d75-84672b3d14e3)

0xe36cddf55252866fac28d977e7f1bcce35108bce
![image](https://github.com/connext/community-sybil-reports/assets/95530388/19ac6f2a-6589-4b50-a965-5af071af3bef)

0x4c8dc87beefacf5aaf693ff60af5a141bb1d6132
![image](https://github.com/connext/community-sybil-reports/assets/95530388/d242c210-1e6e-414e-bc8b-dece3e29e9ec)

0x75d1b87c99ed380dd7d9436e10bcf521956e1080
![image](https://github.com/connext/community-sybil-reports/assets/95530388/a76a89b0-4f02-4dc4-893f-f8328150156a)

0x88f50472daa8a0b2f1a31293329eae5a70f50f5d
![image](https://github.com/connext/community-sybil-reports/assets/95530388/c86378a0-2b6b-4692-ad7d-2ecd5ad3318e)

0x99bc877e25bcfb3ff3d61a84acc825857866046c
![image](https://github.com/connext/community-sybil-reports/assets/95530388/36615cc1-3c54-457b-8eb3-c9184b24050e)

0xec1d809c60e8c4713fb2d7775d8f1781c106db2d
![image](https://github.com/connext/community-sybil-reports/assets/95530388/9ca63c3c-4992-4f1f-aa20-98c152da9520)

0xd99eea8642df6bdda53faf0a0d1142c08df8a956
![image](https://github.com/connext/community-sybil-reports/assets/95530388/21479106-e82f-4f04-b5fa-e10bfa169013)

0xca15c62021604b1f5ab90007e16c9053cbedc87e
![image](https://github.com/connext/community-sybil-reports/assets/95530388/e3258467-4148-4de4-aacd-b4df8967595b)

0xe6ad9a32a46811d83477016ab68d46fa3f1423d5
![image](https://github.com/connext/community-sybil-reports/assets/95530388/78e3c9e8-ff77-4b5f-955f-980e0faef01d)

0xd7e55f2902354b1762af36ef2c97b5acb45e05c4
![image](https://github.com/connext/community-sybil-reports/assets/95530388/6a48ca82-b004-42fd-9032-48100185da4a)

0xa83e8fbe108c3491f4a316d84e23693cadb5b140
![image](https://github.com/connext/community-sybil-reports/assets/95530388/45abd232-0290-4ed4-bbe5-9bc1b007552b)

0xf9490b5036b219a68eb7555e7cfa066edb68db8c
![image](https://github.com/connext/community-sybil-reports/assets/95530388/0bbd8d82-0c5b-496c-b5be-26d1c749cbb7)

0x11fed407a8795a39ece1a123e5cefb4ef02f5aef
![image](https://github.com/connext/community-sybil-reports/assets/95530388/3b9b0328-836e-40fa-b393-60adcc6b44e0)

0x3b109b38dc3740c63b1d2f80f48efef21469fc57
![image](https://github.com/connext/community-sybil-reports/assets/95530388/687761b2-be3e-4c3f-80a4-ff5928f71eea)

0xed8921a75ac2e8ab833f9ed9466fafec53e88526
![image](https://github.com/connext/community-sybil-reports/assets/95530388/69e05cf6-7184-4a3f-9083-433009670d2f)

0xa47bc1f001d461aecd9d88e620d49779c19fc8f2
![image](https://github.com/connext/community-sybil-reports/assets/95530388/784b4105-10c0-412a-a4d5-4379e40b68e6)

0xcd0eb64a1d58c77f824108c9aa0439060ccdf5b4
![image](https://github.com/connext/community-sybil-reports/assets/95530388/e3f46c94-cf01-4f88-a0d1-011746eb4b4d)

0xee8c4e9a1524b2bf0c6294a9c15a06f9546735ee
![image](https://github.com/connext/community-sybil-reports/assets/95530388/672784e0-a9d7-47a4-b159-1c009312f3b8)

0x2d84ea94f67292a245076c97a9ebad9d260bba2e
![image](https://github.com/connext/community-sybil-reports/assets/95530388/ec02d4e7-aaa6-429a-9b60-3ea83980f410)

0x1354ee9b9748fb265a16789fb4d2bb1b54312e50
![image](https://github.com/connext/community-sybil-reports/assets/95530388/295cfeb5-9821-4a7d-ad7d-2e10844a816e)

0x707246b1af830122aadda41bddf61e18f759fdc4
![image](https://github.com/connext/community-sybil-reports/assets/95530388/4a155617-52ad-45c4-92f1-2f9c4d3800a6)

0x2dba4d669239fb04ebab5720fc181ae48f5159f1
![image](https://github.com/connext/community-sybil-reports/assets/95530388/40c2ded4-0d51-473d-b471-1fc9adf170b7)

0x0355786221c9c34935c61ecae9a68c8c044c0161
![image](https://github.com/connext/community-sybil-reports/assets/95530388/3641bde8-2a7e-4ed1-8ceb-73d727bd7c82)

0x6e43ed92ce1ba8c1b7ed405abe70981748877033
![image](https://github.com/connext/community-sybil-reports/assets/95530388/49ca9388-9264-413c-8937-ce6a790d7eb3)

0x54f34ff31b8039f2d96019be59d51c8fc07d4341
![image](https://github.com/connext/community-sybil-reports/assets/95530388/ca639683-47a5-4752-8647-ed5f296730df)

0xd3570efe4023cdf53db84c5910e7f147ec9b9d0a
![image](https://github.com/connext/community-sybil-reports/assets/95530388/9efa2f96-b12c-4d2a-9a76-1449655915d2)

0x00d116e7212cc575b3f4903a29190bbbbc52f322
![image](https://github.com/connext/community-sybil-reports/assets/95530388/f3f38e2d-c0ef-4993-890c-cd58b099c6ec)
![image](https://github.com/connext/community-sybil-reports/assets/95530388/4d8d6707-6271-4561-ad2c-7293af34bdaf)

Summary

All this accounts were created at the same time.
All accounts made consecutive transactions in the Connext network within minutes for comparable amounts.
If you carefully study transactions in wallets, it is easy to find additional examples which additionally proves that the accounts are owned by one person.

All this allows us to conclude that these accounts belong to one person

# Methodology
I analyzed transactions in the Arbitrum network https://arbiscan.io/ in terms to find repeating transfers at standard intervals and sequence. Next, I manually reviewed suspicious wallets via https://debank.com/. The received addresses were manually analyzed and repeated transmissions were found at standard intervals and in sequence.

# Rewards Address
0xbdd020C59D89d447A61e511c09Bc25BF444E01d8

**Comment by solidnetw** [comment]
I already reported these

**Comment by ronaskin** [comment]
![Screenshot_10](https://github.com/connext/community-sybil-reports/assets/137379395/e753e9b0-48f3-4c55-b252-d4356bf0c08a)
