### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by edwinosky** [connext/community-sybil-reports#50]
# Related Addresses

0x01af86cd3fa63f8b04b8ba7df0494a77c01c473f
0x2E8a0947833eD4AeE087C4bB7e413B0dA8E4a611 
0x5de24deae9b1940b1b94ff6b0da92e59b3bc6ad4
0x9D100F017095e53b24d81296BcA1D26742f1800F
0xa03C622D5D2cA9d581c99f2870A81733160456F6
0xC830E01Fc2a6c7D83674FA9C5ea6a3BE51aBFd3d
0xFaf6bb8F1a300130fB9dc582DC8363a50841882D
0xF82e8BC7E11A22B5ab835CA25A477203a97BDB16
0xF78F2bba5EA14419Ff7Cb5e68d192CD214ec049e
0x1278d0968454e9dcdf2fbdb834d736caaa97ae56
# Reasoning

All these addresses are directly linked to 0x01af86cd3fa63f8b04b8ba7df0494a77c01c473f, below I leave some txid where you can clearly see the movements between them

https://arbiscan.io/tx/0x35b23bac9d9565d13b3b2a00aef6d9a6c54bddf1af5ed0384946e31ea9cd1cc7  0x2E8a0 to  0x01af86 
https://arbiscan.io/tx/0x2a11dc0eaffd634e9991064d0fc2441caa67080aab1b82b4c0c270e53b412e3a  0x01af86 to 0x2E8a0
https://arbiscan.io/tx/0xb34a132869856b7d55f9a54feba3c74d6853f036565f23547ee31ea977ae3bf1  0x5de24 to 0x2E8a0
https://arbiscan.io/tx/0x98fa6a155423eafdc4ccfc8c7a294a80015f83e128633489b6a90ea42cc42001  0x01af86 to 0xd921e
https://arbiscan.io/tx/0x3357987ec6cee86e63a1a1582a15594365f650f5ac839b6969119a657ed3b930  0xd921e to 0x5de24
https://bscscan.com/tx/0x9a6cc4b0c99ad75406366417656ae0416ff79a63f673226f109ca6b246a6c2ef  0x5de24 to 0xa03C6
https://polygonscan.com/tx/0x78905f09b371e1f31a6de98bd13381719ccd4d6fa5567a979b468f9721ee9d91  0xa03C6 to 0x01af86
https://snowtrace.io/tx/0x84b3277c3caf58b4737dc2a4a0fe9b62ee22ccfbd27869ca06142c1da0eae93b  0x01af86 to 0xC830E0

Here is a transaction that links a third wallet that is not classified to the connex airdrop but if it is analyzed, it is directly linked to the main wallet and others that are classified

https://polygonscan.com/tx/0xf0fc8aee4e10d2520a83cc767a706d83a68f0617e8113241ce7e4c17b3c0d072   0xec6383 to 0x01af86

https://polygonscan.com/tx/0x4eb1726cf493d6c2fd97ac81b4787c3cd78e5bec7d6c4a8113d81ce7d0cfaac8   0xec6383 to 0xfaf6

https://polygonscan.com/tx/0x9f49554a17410003f36f6e15c8d1e402f3f274c73ac701e5f83db982177f1c40   0xec6383 to  0xF82e8B

https://polygonscan.com/tx/0x6b7aa83d1d25ad2ef4bcfa5cbcfd5d05c398a77fea904632ec486942dbd5e24a 0xec6383 to 0xF78F2

# Methodology

I managed to find the main address and using the block explorer, plus some tools like Arkham and Nansen I was able to figure out how they are connected

# Rewards Address

edwinosky.eth
0xBd1691E270485D152eb2F9f75B7c8ff4595eeC2F

**Comment by ronaskin** [comment]
![Screenshot_10](https://github.com/connext/community-sybil-reports/assets/137379395/1d0650ca-9af4-4ace-8d79-2fe94e335eb3)

**Comment by superluckyman** [comment]
0x01af86cd3fa63f8b04b8ba7df0494a77c01c473f This address was stolen, so it was associated with another address

**Comment by superluckyman** [comment]
https://debank.com/profile/0x01af86cd3fa63f8b04b8ba7df0494a77c01c473f/history
You can tell by looking at these transactions.

**Comment by Grraarrgghh** [comment]
0x2E8a0947833eD4AeE087C4bB7e413B0dA8E4a611 isnt even on the eligibility list, and while

0x01af86cd3fa63f8b04b8ba7df0494a77c01c473f
0x5de24deae9b1940b1b94ff6b0da92e59b3bc6ad4
0xa03C622D5D2cA9d581c99f2870A81733160456F6

are associated, im not seeing how they tie as a cluster to the other addresses listed. Changing status to NMI

**Comment by superluckyman** [comment]
Have you looked at the 0xec6383 address you mentioned, look at the transaction logs, it's more like an airdrop address for some program.https://debank.com/profile/0xec63831a22f287b7f0f50e46ca890767d8e574c4/history
![image](https://github.com/connext/community-sybil-reports/assets/83764333/a11866dd-973e-469a-b986-ad44a025be20)

**Comment by ArjunBhuptani** [comment]
Invalid report, these addresses are not consistently related to connext
