### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by rodrogos0amigos** [connext/community-sybil-reports#508]
# Related Addresses

Group 1

0x49f06f95c5d105ae6cda00444bbd3dda06e61cc8
0x30299c7b06a4e61ef4aed51a146dd498494336f2
0xf93b4392e7fabe50cc7fef276ba128d152e4d416
0xf85fe17faaaaddd20fa588a6c4ca06914d507a84

Group 2

0xA8fDFe346972389E90B5f706bA5674F11A356425
0x613FC8E52D98d1914baC225fcA24E96cB036B72c

Group 3 

0x83bbe9cfcc205bb8e53cba0b51d6db9386ce58b5
0x79bdda65c706cbda69c0ad4c8da1d3e91724f48d

Group 4

0x303c3d4393293e10DB2B153A9c7ef8Fc5AAF226F
0xeFb4D8C818Cb2Dff882E1C01497bF343B133E45F
0x3DdB5ba965EEc7D09774B35cfA6f7e7854F88250
0x9534e4beb4f7E07bb88F4c6A067d666c29e1b433

# Reasoning

Group 1
All accounts were created on the same day, September 24, 2021, as we can see by looking at https://debank.com/.
![image](https://github.com/connext/community-sybil-reports/assets/143542424/0e061608-be56-45eb-8bf6-004692df4d18)
![image](https://github.com/connext/community-sybil-reports/assets/143542424/b35b73be-1d64-48b2-828c-8dbbc07a9183)
![image](https://github.com/connext/community-sybil-reports/assets/143542424/2c88ecde-7491-4a7c-a525-b220acc83b3a)
![image](https://github.com/connext/community-sybil-reports/assets/143542424/b1174c0e-8027-4576-bff8-2d18392ec5bb)

NFTs are all similar and were minted at the same time.
![image](https://github.com/connext/community-sybil-reports/assets/143542424/a2182def-d6ef-4558-a5fe-357a98380504)
![image](https://github.com/connext/community-sybil-reports/assets/143542424/54db6492-0351-407a-aca3-e68f342b52f2)
![image](https://github.com/connext/community-sybil-reports/assets/143542424/f6beb26c-cbd6-46ff-ab0f-e081423bc96f)
![image](https://github.com/connext/community-sybil-reports/assets/143542424/bdbb62e5-e0d3-4ed1-825f-e5ef23587687)

The last transactions for all accounts are the same and were executed at the same time. NFTs are also minted at the same time and are the same NFT.
![image](https://github.com/connext/community-sybil-reports/assets/143542424/14f26859-85fd-4bef-813d-1da6a2abaacd)
![image](https://github.com/connext/community-sybil-reports/assets/143542424/f656f535-0d67-46e7-acc6-a6a955b8f056)
![image](https://github.com/connext/community-sybil-reports/assets/143542424/9420c9b9-cdf3-4e7a-8465-502105445d8a)
![image](https://github.com/connext/community-sybil-reports/assets/143542424/58dc127c-f366-4d0a-b3be-0e0c232ed511)

Money was withdrawn from one Bybit address to all these wallets, here are the transactions:
https://optimistic.etherscan.io/tx/0xbcdbc8e88b962e38e02838b023a9b79b7a13dffc79fd8b3fbf701b32b12a8de2
https://etherscan.io/tx/0x043be8b52ed0023ee3b082c07ca4e09f23e335014bd8d5bf9b0c1eb36c9334f8
this is a withdrawal to wallet 0xf85fe17faaaaddd20fa588a6c4ca06914d507a84

https://etherscan.io/tx/0x8adc2054a3f2b62449d38ca5d2cb8854fe8ac08726dd4372ec2ce41731db5138
https://etherscan.io/tx/0x26c9df3d0559399be1b2fac4725ae72ba2bdb764a97ef76727b9f03148926c6e
This is all withdrawal from the same Bybit wallet to wallet 0x49f06f95c5d105ae6cda00444bbd3dda06e61cc8

https://etherscan.io/tx/0x635c0c57204db1d8f46195f86f3a3acd9673b802a2858140ce34669d238dcd9b
This is a withdrawal from the same Bybit wallet to wallet 0xf93b4392e7fabe50cc7fef276ba128d152e4d416

https://etherscan.io/tx/0xba511a8ed583419d9887616230f5cfefd7937ce2bb103a3b2c2b8e93805cb958
This is a withdrawal from the same Bybit wallet to wallet 0x30299c7b06a4e61ef4aed51a146dd498494336f2

https://platform.arkhamintelligence.com/visualizer/entity/0x49f06F95C5d105ae6Cda00444bbD3DDA06E61CC8,0x30299c7B06A4E61ef4aEd51A146dD498494336f2,0xf85fe17FAAaADDd20FA588A6c4Ca06914D507A84,0xF93B4392E7fAbE50Cc7FeF276Ba128D152E4d416,0xf89d7b9c864f589bbF53a82105107622B35EaA40?flow=self&positions=%7B%22amaori%22%3A%7B%22fx%22%3A59%2C%22fy%22%3A-78%7D%2C%22azisai-sena%22%3A%7B%22fx%22%3A-43%2C%22fy%22%3A-27%7D%2C%22kana-sato%22%3A%7B%22fx%22%3A117%2C%22fy%22%3A70%7D%2C%22maiooyama%22%3A%7B%22fx%22%3A57%2C%22fy%22%3A-16%7D%2C%220xec8Bebdf0863446d84be4C0e77A96e4823562187%22%3A%7B%22fx%22%3A-162%2C%22fy%22%3A-29%7D%2C%22connext%22%3A%7B%22fx%22%3A-14%2C%22fy%22%3A71%7D%2C%220xA3B8A06238BF9f1a4dd719D679d2CE23fd4F6823%22%3A%7B%22fx%22%3A135%2C%22fy%22%3A-33%7D%2C%22bybit%22%3A%7B%22fx%22%3A-35%2C%22fy%22%3A105%7D%7D&sortDir=desc&sortKey=time&usdGte=0.1
Here we can see all the transactions and their intersections.
![image](https://github.com/connext/community-sybil-reports/assets/143542424/90c1d29c-0d6f-4085-87cd-813aaf82fcef)

Further digging into the transactions, we see that all of them sent money to one Binance wallet, namely 0x1d5549559c781c76747b57b7678ac3ed8ff7bfe1.

Here is a visual screenshot showing all these transactions, and here is a visual map of transactions.
![image](https://github.com/connext/community-sybil-reports/assets/143542424/34eac51f-a5d1-4503-969d-2682d22318d1)
https://platform.arkhamintelligence.com/visualizer/entity/0x49f06F95C5d105ae6Cda00444bbD3DDA06E61CC8,0x30299c7B06A4E61ef4aEd51A146dD498494336f2,0xf85fe17FAAaADDd20FA588A6c4Ca06914D507A84,0xF93B4392E7fAbE50Cc7FeF276Ba128D152E4d416,0x1d5549559C781C76747b57b7678Ac3eD8FF7BFE1?flow=self&positions=%7B%22amaori%22%3A%7B%22fx%22%3A59%2C%22fy%22%3A-78%7D%2C%22azisai-sena%22%3A%7B%22fx%22%3A-43%2C%22fy%22%3A-27%7D%2C%22kana-sato%22%3A%7B%22fx%22%3A117%2C%22fy%22%3A70%7D%2C%22maiooyama%22%3A%7B%22fx%22%3A57%2C%22fy%22%3A-16%7D%2C%220xec8Bebdf0863446d84be4C0e77A96e4823562187%22%3A%7B%22fx%22%3A-162%2C%22fy%22%3A-29%7D%2C%22connext%22%3A%7B%22fx%22%3A-14%2C%22fy%22%3A71%7D%2C%220xA3B8A06238BF9f1a4dd719D679d2CE23fd4F6823%22%3A%7B%22fx%22%3A135%2C%22fy%22%3A-33%7D%2C%22bybit%22%3A%7B%22fx%22%3A-35%2C%22fy%22%3A105%7D%2C%220x1d5549559C781C76747b57b7678Ac3eD8FF7BFE1%22%3A%7B%22fx%22%3A-63%2C%22fy%22%3A64%7D%7D&sortDir=desc&sortKey=time&usdGte=0.1

Group 2
Two accounts created on the same day 2021-04-06
![image](https://github.com/connext/community-sybil-reports/assets/143542424/60e5f1c1-1f7d-42a0-8873-f214468aa350)
![image](https://github.com/connext/community-sybil-reports/assets/143542424/fc7d0add-a648-46bd-a6f9-9223736b63e5)

Here we can see how cryptocurrency was thrown to each other from these accounts
![image](https://github.com/connext/community-sybil-reports/assets/143542424/461fb91c-2256-4c88-b631-7f90ebbc89eb)
https://platform.arkhamintelligence.com/visualizer/entity/0x613FC8E52D98d1914baC225fcA24E96cB036B72c,0xA8fDFe346972389E90B5f706bA5674F11A356425,0xA8fDFe346972389E90B5f706bA5674F11A356425,0xA8fDFe346972389E90B5f706bA5674F11A356425,0xA8fDFe346972389E90B5f706bA5674F11A356425?flow=self&positions=%7B%220xA8fDFe346972389E90B5f706bA5674F11A356425%22%3A%7B%22fx%22%3A-10%2C%22fy%22%3A5%7D%2C%220x613FC8E52D98d1914baC225fcA24E96cB036B72c%22%3A%7B%22fx%22%3A53%2C%22fy%22%3A8%7D%7D&sortDir=desc&sortKey=time&usdGte=0.1

Group 3 

Let's focus on these two wallets, by adding them to ARKHAM we can see balance transfers between each other, but let's not stop there and go further.
![image](https://github.com/connext/community-sybil-reports/assets/143542424/fcd99fff-9fbd-47f8-be69-2f193116c951)

We go to Debank and look at all the things we can grab onto, my eyes caught Twitter and look how similar they are, yes it's not the strongest evidence, but still the Twitter handles are similar, let's move on to other coincidences.
![image](https://github.com/connext/community-sybil-reports/assets/143542424/7873e39b-935f-4f58-9bdc-5440a678a12d)
![image](https://github.com/connext/community-sybil-reports/assets/143542424/232674e7-793d-4e74-a7d8-ba56d266d744)

The NFTs on the accounts are identical and obtained at the same time.
![image](https://github.com/connext/community-sybil-reports/assets/143542424/5abf267c-8a0f-4cf2-b068-e639e014335a)
![image](https://github.com/connext/community-sybil-reports/assets/143542424/4ce35607-2276-4eae-902e-7ae3c3944c2e)

Further digging into the transactions, I found a withdrawal to Binance on this address 0xdfd5293d8e347dfe59e90efd55b2956a1343963d, adding this address to ARKHAM and here's what we see, these two addresses sent withdrawals to the same address.
![image](https://github.com/connext/community-sybil-reports/assets/143542424/99f14d1e-86ab-4ede-b8b1-79871f77f52a)
![image](https://github.com/connext/community-sybil-reports/assets/143542424/5842820a-5c52-4302-bfee-3297a6532398)

if you look at the time, we see that withdrawals occurred on the same day and at the same time).
![image](https://github.com/connext/community-sybil-reports/assets/143542424/23873942-fdc1-448c-a7b2-cb54dbf89896)
![image](https://github.com/connext/community-sybil-reports/assets/143542424/3f7984a0-3bc2-48f1-aa59-220df08a3e48)

If this is not enough, you can see the adjacent transactions below, there are many of them between each other.
https://platform.arkhamintelligence.com/visualizer/entity/0x2A9EA5e8cDDf40730f4f4F839F673a51600C314e,0x31eFc4AeAA7c39e54A33FDc3C46ee2Bd70ae0A09,0x83bbe9CFCc205bb8E53cBa0b51d6db9386CE58B5,0x79Bdda65C706CBdA69C0AD4C8da1d3e91724f48D,0xDFd5293D8e347dFe59E90eFd55b2956a1343963d?flow=self&positions=%7B%22connext%22%3A%7B%22fx%22%3A9%2C%22fy%22%3A18%7D%2C%22poupee999%22%3A%7B%22fx%22%3A57%2C%22fy%22%3A-9%7D%2C%22pkhemapet%22%3A%7B%22fx%22%3A30%2C%22fy%22%3A-49%7D%2C%220x28b8fbCebDC3114DD7Ce20Eb0642015ea3a21718%22%3A%7B%22fx%22%3A36%2C%22fy%22%3A26%7D%2C%220x553222B267bC978ACa3C28493AEf72d924b264BD%22%3A%7B%22fx%22%3A2%2C%22fy%22%3A33%7D%2C%22binance%22%3A%7B%22fx%22%3A82%2C%22fy%22%3A-48%7D%7D&sortDir=desc&sortKey=time&usdGte=0.1

Group 4

We add these four accounts to ARKHAM and find joint transactions between them, but this is not enough yet, so we continue to investigate.
![image](https://github.com/connext/community-sybil-reports/assets/143542424/66949d74-19a5-4de2-be09-957e2c3f966b)

Looking at his account on DeBank, we start digging into transactions and find a withdrawal to Binance on May 12, 2023. (0x5bd43c5341dade42deaa349e0224f2046edbc3aa Binance) 

![image](https://github.com/connext/community-sybil-reports/assets/143542424/a0fc8cfb-c893-4935-9ebd-2add828ac72b)

We then look at the other account and find a withdrawal to the same address at the same time and on the same day.
![image](https://github.com/connext/community-sybil-reports/assets/143542424/08298e32-1889-47d1-92e6-4356232b4bb9)
https://bscscan.com/tx/0x3113be53d24cd6661c2bf5e8c5a99fdde6c821e0bbd76ce54fbbd60db9eede1e

![image](https://github.com/connext/community-sybil-reports/assets/143542424/e485bc2f-f977-4e55-8371-5bc574a0f19a)
https://bscscan.com/tx/0x89c26884a5fffd6bfba716cb2a1207c500d18b69a8acfe5e123b01b26d7f67b8

![image](https://github.com/connext/community-sybil-reports/assets/143542424/f40dde87-37b3-42b2-b046-5ae2d24ccd2c)
https://bscscan.com/tx/0x18e21edcd251a2b06e4d775ecce5e50f80fd9daf8a116fc392127e60f3565444

![image](https://github.com/connext/community-sybil-reports/assets/143542424/b66d1168-c928-468f-9b19-8d8a1842de68)
https://bscscan.com/tx/0xeee18a9595e6673377ddeb702ba15a183db5919dcda5cf29beaea7c6e501da86

https://platform.arkhamintelligence.com/visualizer/entity/0x2A9EA5e8cDDf40730f4f4F839F673a51600C314e,0x31eFc4AeAA7c39e54A33FDc3C46ee2Bd70ae0A09,0x303c3d4393293e10DB2B153A9c7ef8Fc5AAF226F,0x303c3d4393293e10DB2B153A9c7ef8Fc5AAF226F,0x303c3d4393293e10DB2B153A9c7ef8Fc5AAF226F,0xeFb4D8C818Cb2Dff882E1C01497bF343B133E45F,0xeFb4D8C818Cb2Dff882E1C01497bF343B133E45F,0xeFb4D8C818Cb2Dff882E1C01497bF343B133E45F,0x3DdB5ba965EEc7D09774B35cfA6f7e7854F88250,0x9534e4beb4f7E07bb88F4c6A067d666c29e1b433,0x5bd43c5341DadE42DEaa349E0224f2046edBc3AA?flow=self&positions=%7B%220xeFb4D8C818Cb2Dff882E1C01497bF343B133E45F%22%3A%7B%22fx%22%3A21%2C%22fy%22%3A7%7D%2C%220x303c3d4393293e10DB2B153A9c7ef8Fc5AAF226F%22%3A%7B%22fx%22%3A-24%2C%22fy%22%3A-10%7D%2C%22connext%22%3A%7B%22fx%22%3A62%2C%22fy%22%3A-33%7D%2C%220x2D19624dd8bc9BdB4Ae1460Cf0F9D6D3A2B04199%22%3A%7B%22fx%22%3A104%2C%22fy%22%3A-12%7D%2C%220xef1276D9f924843fBC53eea71c55FFEe2b1b6Ad0%22%3A%7B%22fx%22%3A24%2C%22fy%22%3A25%7D%2C%220x1F1426c16c3a811C77deb2a813968FD19BB09466%22%3A%7B%22fx%22%3A-34%2C%22fy%22%3A16%7D%2C%220x5bd43c5341DadE42DEaa349E0224f2046edBc3AA%22%3A%7B%22fx%22%3A111%2C%22fy%22%3A12%7D%2C%220x8ac6cbF9f7Bb93071D797b70C23847Cc047Ecf1c%22%3A%7B%22fx%22%3A-22%2C%22fy%22%3A-84%7D%2C%220x3DdB5ba965EEc7D09774B35cfA6f7e7854F88250%22%3A%7B%22fx%22%3A35%2C%22fy%22%3A-80%7D%2C%220x9534e4beb4f7E07bb88F4c6A067d666c29e1b433%22%3A%7B%22fx%22%3A-15%2C%22fy%22%3A-75%7D%7D&sortDir=desc&sortKey=time&usdGte=0.1

We continue our investigation and find another withdrawal to a different Binance address, an older address 0x8ac6cbf9f7bb93071d797b70c23847cc047ecf1c.
![image](https://github.com/connext/community-sybil-reports/assets/143542424/6c82778b-9c2c-4fd2-8e1f-dfcf39955931)

Upon further inspection, we notice that all the addresses we have been investigating have withdrawn funds to this address as well.
![image](https://github.com/connext/community-sybil-reports/assets/143542424/d1ba5cdb-12a7-47ce-a61c-5c66b7c623d3)

![image](https://github.com/connext/community-sybil-reports/assets/143542424/086b29e1-88db-43a7-b0bc-ad72d4a6d075)
https://platform.arkhamintelligence.com/visualizer/entity/0x303c3d4393293e10DB2B153A9c7ef8Fc5AAF226F,0x303c3d4393293e10DB2B153A9c7ef8Fc5AAF226F,0x303c3d4393293e10DB2B153A9c7ef8Fc5AAF226F,0xeFb4D8C818Cb2Dff882E1C01497bF343B133E45F,0xeFb4D8C818Cb2Dff882E1C01497bF343B133E45F,0xeFb4D8C818Cb2Dff882E1C01497bF343B133E45F,0x3DdB5ba965EEc7D09774B35cfA6f7e7854F88250,0x9534e4beb4f7E07bb88F4c6A067d666c29e1b433,0x8ac6cbF9f7Bb93071D797b70C23847Cc047Ecf1c?flow=self&positions=%7B%220xeFb4D8C818Cb2Dff882E1C01497bF343B133E45F%22%3A%7B%22fx%22%3A21%2C%22fy%22%3A7%7D%2C%220x303c3d4393293e10DB2B153A9c7ef8Fc5AAF226F%22%3A%7B%22fx%22%3A-35%2C%22fy%22%3A-23%7D%2C%22connext%22%3A%7B%22fx%22%3A62%2C%22fy%22%3A-33%7D%2C%220x2D19624dd8bc9BdB4Ae1460Cf0F9D6D3A2B04199%22%3A%7B%22fx%22%3A104%2C%22fy%22%3A-12%7D%2C%220xef1276D9f924843fBC53eea71c55FFEe2b1b6Ad0%22%3A%7B%22fx%22%3A24%2C%22fy%22%3A25%7D%2C%220x1F1426c16c3a811C77deb2a813968FD19BB09466%22%3A%7B%22fx%22%3A-34%2C%22fy%22%3A16%7D%2C%220x5bd43c5341DadE42DEaa349E0224f2046edBc3AA%22%3A%7B%22fx%22%3A111%2C%22fy%22%3A12%7D%2C%220x8ac6cbF9f7Bb93071D797b70C23847Cc047Ecf1c%22%3A%7B%22fx%22%3A62%2C%22fy%22%3A-30%7D%2C%220x3DdB5ba965EEc7D09774B35cfA6f7e7854F88250%22%3A%7B%22fx%22%3A35%2C%22fy%22%3A-80%7D%2C%220x9534e4beb4f7E07bb88F4c6A067d666c29e1b433%22%3A%7B%22fx%22%3A-15%2C%22fy%22%3A-75%7D%7D&sortDir=desc&sortKey=time&to=binance%2Cdeposit%3Abinance&usdGte=0.1

I believe that these clear violations are enough to prove their wrongdoing. I have done a tremendous amount of work to write all of this, thank you for your attention.

# Methodology

I manually checked each account for connections in ARKHAM and looked at all transactions and other information in Debank. Once I found a violator, I looked at the withdrawal transactions to various exchanges, then I inputted these wallets into ARKHAM and looked at their connections. 

After finding a connection, I searched deeper and paid attention to the time and date of these transactions. If they matched, it was a clear violation and all of their accounts were found. I believe that these clear violations are enough to prove their wrongdoing. I have done a tremendous amount of work to write all of this, thank you for your attention.

# Rewards Address

0x27B9278e8532b0F85D3158BfDF88A4977521E837

**Comment by rodrogos0amigos** [comment]
What is wrong with my report? I spent over a day writing all this down, please tell me what is wrong. If you need more evidence, I am ready to provide it. The accounts are identical, even their Twitter handles are the same.

I am confident that there is an error in the marking of my report.

**Comment by ArjunBhuptani** [comment]
Sybil groups too small

**Comment by Firsttimer001** [comment]
> What is wrong with my report? I spent over a day writing all this down, please tell me what is wrong. If you need more evidence, I am ready to provide it. The accounts are identical, even their Twitter handles are the same.
> 
> I am confident that there is an error in the marking of my report.

Make sure you report the whole crypto space for using CEX exchanges <3
