### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by valemwandy** [connext/community-sybil-reports#509]
# Related Addresses

0x9e4d15e0ecb571e7e66831334519c76130f29636
0x7bf49814598924b1ab2a33ad815054b6367cddd0
0xe099d39b893f81cacab91436549d22ef8171d4e0
0x81cb7a3b214af3c397575d175c29dc5b92211895
0x83e28d08f59343cd13ef93bb4423d67ceb80096b
0x668fab5429f363f87c17b1d9f7eada702cadae1f
0x83fcb07a4a5fa900e103b60e6b01f76cf5159652
0x6e0628093c39a1e2b21279c777d83b85df484bad
0x1d2f151766322aaec7171c0a367ab689830ccfbc
0x00b08309d67eb1d92713ac689dc7a0d26fabd230
0x3ebe316429d367399f48eb0c0c6d9ba186a2610d
0x5ab42f627386362d839ef948dc3b8ab6ed12c9e5
0x6cf9380f5e1a38e3b4c5101c1aa0211603fec13f
0x7b62d6585f0666f5cfcbea5e09baa99133478a96
0xf66a1010b53f543d513be992755680887211de49
      
# Reasoning

0x9e4d15e0ecb571e7e66831334519c76130f29636
0x7bf49814598924b1ab2a33ad815054b6367cddd0
0xe099d39b893f81cacab91436549d22ef8171d4e0

The addresses are linked by a deposit account on binance 0xd50c068536dfa0814878b7cca1819782f51bfde6. Tokens are sent between wallets on an ongoing basis.
![3](https://github.com/connext/community-sybil-reports/assets/118393766/af22e13d-1205-4dd1-9ced-d154552ffa39)
![4](https://github.com/connext/community-sybil-reports/assets/118393766/abbb1c3d-05c4-439c-bdfb-74f233981405)
![5](https://github.com/connext/community-sybil-reports/assets/118393766/41d99e9d-4296-404b-a641-8b21f81dced2)

![1](https://github.com/connext/community-sybil-reports/assets/118393766/cb224f73-e397-484e-b1a8-0f4dfbdac008)
![2](https://github.com/connext/community-sybil-reports/assets/118393766/0ba47575-97a4-4d07-b9b2-b6a31e0783de)

0x81cb7a3b214af3c397575d175c29dc5b92211895
0x83e28d08f59343cd13ef93bb4423d67ceb80096b
0x668fab5429f363f87c17b1d9f7eada702cadae1f
The addresses are linked by a deposit account on binance 0xd42d40a9a0ad1735efdef6616788f9196b00b224. Tokens are sent between wallets on an ongoing basis. I also noticed that the accounts have the same amount of transfer through the bridge and the time is the same - April 14!
![6](https://github.com/connext/community-sybil-reports/assets/118393766/fd918326-f026-4d27-8fd3-65d42fe3d884)
![7](https://github.com/connext/community-sybil-reports/assets/118393766/44272aa1-6ea7-45e5-8dad-f887b29bd142)
![8](https://github.com/connext/community-sybil-reports/assets/118393766/efdde9f3-97dd-4ce9-aabe-e5d3c2b5b60a)
![9](https://github.com/connext/community-sybil-reports/assets/118393766/a1cd7e37-ebe7-433d-bbcf-c639e7be161d)
https://platform.arkhamintelligence.com/explorer/tx/0x3fbb78daab401bed7e35be1c84b0a3c7c0f0fd5b063027379439e5b4fe6c8841
https://platform.arkhamintelligence.com/explorer/tx/0xe9f070371247e98e17a2eb53291e6810c18e349eb1bbc10f0410aaecf30fa858
https://platform.arkhamintelligence.com/explorer/tx/0x4dd8864df49d259f70313fcffb75515059982d50e06ef566a66c8902b6928bfd

0x83fcb07a4a5fa900e103b60e6b01f76cf5159652
0x6e0628093c39a1e2b21279c777d83b85df484bad
0x1d2f151766322aaec7171c0a367ab689830ccfbc

The addresses are linked by a deposit account on binance 0xcbca0c57990800e9043139bf144b12764c35005d. Tokens are sent between wallets on an ongoing basis.
![10](https://github.com/connext/community-sybil-reports/assets/118393766/8f1f3fef-474e-4a7c-88b2-539f6507b50e)
![11](https://github.com/connext/community-sybil-reports/assets/118393766/7c608c3c-9650-46d3-be50-0abdefccae6d)

0x00b08309d67eb1d92713ac689dc7a0d26fabd230
0x3ebe316429d367399f48eb0c0c6d9ba186a2610d
0x5ab42f627386362d839ef948dc3b8ab6ed12c9e5
The addresses are linked by a deposit account on binance 0xc96d07d91e167949a8e14070215c5911dc179614. Tokens are sent between wallets on an ongoing basis.

https://platform.arkhamintelligence.com/explorer/tx/0x566fa1b84061c71a7fa231b7022bd2aa52177f8c9c97fc94a882159635287058
https://platform.arkhamintelligence.com/explorer/tx/0xc7b13bac3e08e7dc2f26e287a8e3285f962560c3c888c40c63d4efa089b01947
https://platform.arkhamintelligence.com/explorer/tx/0x5b3ba028a206176ab49818064d865f5f54fa241d408b16e15e725df41c9e4b53
![12](https://github.com/connext/community-sybil-reports/assets/118393766/b0c030a1-6839-4b37-b81e-b0afc3e7b122)

0x6cf9380f5e1a38e3b4c5101c1aa0211603fec13f
0x7b62d6585f0666f5cfcbea5e09baa99133478a96
0xf66a1010b53f543d513be992755680887211de49
The addresses are linked by a deposit account on binance 0xbb8032782d8714b12100211073df5165f6fc3a72. Tokens are sent between wallets on an ongoing basis.
https://platform.arkhamintelligence.com/explorer/tx/0x9425d1863cbaecc46c714e0811fb58a32282e6cf4b364656c43f1cbe205aee0b
https://platform.arkhamintelligence.com/explorer/tx/0x3ec390ce774c16342f3533f60f50782ec5286bcdf130a59b03912895f6beec16
https://platform.arkhamintelligence.com/explorer/tx/0x69b9368256d66b59296f72284ba49fe019d721f9d5f03ce33209c68b1cba28da
![13](https://github.com/connext/community-sybil-reports/assets/118393766/5671b6d1-f62a-4ea8-8557-55cc294d0aff)
![14](https://github.com/connext/community-sybil-reports/assets/118393766/769d23e2-3d5b-4ab7-b326-113c6e0aa715)
![15](https://github.com/connext/community-sybil-reports/assets/118393766/f536ff1a-9dd3-48ba-8290-eff6a7bbe6f4)

# Methodology

Used the Arkham platform

# Rewards Address

0xc1122447a0916235c7859cd6453ceDeb0Af1B8AA

**Comment by james20170822** [comment]
Having three different addresses is extremely normal for a web3 user

**Comment by 0xrykerEth** [comment]
> Having three different addresses is extremely normal for a web3 user

not for a snitch to earn project

**Comment by Firsttimer001** [comment]
Valid reports for groups of 3 by 3

Holy shit, even someones hardware wallet would be a sybil if one prefer to use one safe wallet and one hot wallet


I cant believe this passed 

So the rule: 10 same person wallets is voided and even 2 wallets can be sybil
