### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by Zabka0x94** [connext/community-sybil-reports#51]
# Related Addresses

0x01327ca699949ca90b9dc330ea53ce299bf71795
0x02dce608f759a97ecbcd6f5b148137e4ee7a20e2
0x0e861f1d1a0d4fdc90fe18cacae65bb750105dbc
0x0e865d2d70b497ffd74941a42c9ed523553c506d
0x33cea37f72357edda0c2f47d90ab5fb95e8e1622
0x3ca1a1e02d3b8f44d2df99ccd6eca8d748959119
0x44dca60a29b3abf91e3c9089f07f6c89022b5b1c
0x7980dcd4f79f58c4568e0392dc9132fe874f682f
0x7d78677ef3b9e71a5e5696171dc55301244f579c
0x9bf8e43b74c050aac13dd6a6a17410498b0d5582
0xc7830f681bce28314d4762df23727f1273162368
0xd82fc5e578ab7ea3038686f489da73725666bd7e
0xef36026ff18b3d1f2285b0ba639c8155a0429ff2
0xff9f7dda4c0ac2b852330c22de97301cd4531568

-->

# Reasoning

All these addresses used the same software to generate trading volumes and then withdrew funds to this address 0x12476f5e2fde2f2b6179a8a884e4b53ab8fd6105.

All this happened between 2023/08/23 10:20 UTC - 2023/08/23 11:45 UTC.

-->

# Methodology

The reported addresses were identified by checking the DeBank wallet to which the funds were sent. The received addresses were analyzed to identify repeated transfers with standardized intervals and sequence.

All of these addresses withdrew funds to this wallet repeatedly, in different networks, and at the same time - 0x12476f5e2fde2f2b6179a8a884e4b53ab8fd6105

https://zkevm.polygonscan.com/tx/0x1254ffc964c2befe0e09f1b5df1ff7243b0afb8163631a846e70a0bedface2fc
https://zkevm.polygonscan.com/tx/0x5888858ed20b93fb19b64d15ac732950ec8b875f8aae9c2d18776c61d5dbd141
https://polygonscan.com/tx/0xbdb95b95f55a025991e1f5c43042c0a50ee9799e1a7df0eed6410f30a5aba1b5
https://polygonscan.com/tx/0x9906eb9627efabdd96926157c11e6e91bd51ff72c4161c125c3f7ca7ed03293a
https://polygonscan.com/tx/0x4544f2e0ab4ca488398c697d1de6056ff952ab17867cc3ad45877c95e41f510d
https://polygonscan.com/tx/0x3cd29fc9cea631df1ff89a26796079100718bbbd0bd887370623f613ffef3aca
https://arbiscan.io/tx/0x05bb8a194809e5dddf7e705c969755b7c1c02e3aa0af5e20c806518acf8f122c
https://bscscan.com/tx/0xaad0494878be3c008d309e612e484497cd861a1de11a2b2591236bdbaf276259
https://snowtrace.io/tx/0xe1bb594712268af344605c8a3f7b4d960ccfda60f2b9942c12d34e7cd30ed00f
https://explorer.zksync.io/tx/0xd96262d5cda36df03296cb5f419fab1345448cf2e33b35b48af53d6c1da75623

-->

# Rewards Address

0xAB4FA35b93156b9E492635aE149886026d315855

**Comment by Zabka0x94** [comment]
> if you google it you'll see that this address (0x12476f5e2fde2f2b6179a8a884e4b53ab8fd6105) was reported as a hacker

In any case, this hacker stole money from people who used the software

**Comment by ArjunBhuptani** [comment]
Invalid report.

While these addresses have interacted with Connext (and each other through: `0x12476f5e2fde2f2b6179a8a884e4b53ab8fd6105` - reported hacker), the interactions to Connext are not consistent enough to definitively declare that these are a sybil cluster.
