### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by maximka22222** [connext/community-sybil-reports#511]
# Related Addresses

Group 1

0x33AA887cd070EeBa4ee3B60372Cbbf8E2F793C82
0x5C127CcDD428AC57A1ffF2ec4BC1cD00dbBC9Eed

Group 2

0x9e1FF2971de914cEcaaF98a15189FA64d76b0E75
0xB02bF736Fa80dea04731f5932095E8b192EF9B9d
0xCCd9f484c21653Ffb13469e8670E722581018a15

Group 3

0x80e77e8638fF401C4c0159000f438F4Cc14c157A
0xC8555668862F2C9c0123d7A65513E8B9A86F4159

Group 4

0x8016e6b65e8098d6a3bc1a5320892d088289451b
0x6a3c31dd8546955e836079afdfd0c1fb1d22ced5
0xFa2f6E9c056590ba78Fe7aef551dD27BDbFc000a
0x74EFDD76157565c3EFd8735A85B0f9F61Ee6eaE4

# Reasoning

Group 1

Comparing these two wallets on DeBank, we do not initially see any visible similarities, but upon studying all transactions, we can see that they all withdrew to the same exchange addresses. I will show you visually.

We see one withdrawal to such exchanges as 0xd7ace1b02df070b4941fbf90a2e36ac840550aaa MEXC, and I found two Binance addresses 0xCB8cbED445Aa490dF53dc269409f4AffE1fC0c71 and 0x21a31ee1afc51d94c2efccaa2092ad1028285549

![image](https://github.com/connext/community-sybil-reports/assets/143567594/8b509f0a-30f4-4a3f-a2ae-cc51a27bb35f)
![image](https://github.com/connext/community-sybil-reports/assets/143567594/d56cb744-5702-4a16-8f7f-dcab5565a1a4)
![image](https://github.com/connext/community-sybil-reports/assets/143567594/2290d185-7a3b-43e2-9c74-cc88be85ba7c)

Now, we add all these wallets to ARKHAM and see that each wallet withdrew to all three exchange addresses. You can view all of this through the link below, which I will attach.

https://platform.arkhamintelligence.com/visualizer/entity/0x33AA887cd070EeBa4ee3B60372Cbbf8E2F793C82,0x5C127CcDD428AC57A1ffF2ec4BC1cD00dbBC9Eed,0x33AA887cd070EeBa4ee3B60372Cbbf8E2F793C82,0xCB8cbED445Aa490dF53dc269409f4AffE1fC0c71,0xDFd5293D8e347dFe59E90eFd55b2956a1343963d,0xCB8cbED445Aa490dF53dc269409f4AffE1fC0c71,0xCB8cbED445Aa490dF53dc269409f4AffE1fC0c71,0xd7ACE1b02dF070B4941fBF90a2e36ac840550AaA?flow=self&positions=%7B%22xjupitar%22%3A%7B%22fx%22%3A-17%2C%22fy%22%3A3%7D%2C%220x33AA887cd070EeBa4ee3B60372Cbbf8E2F793C82%22%3A%7B%22fx%22%3A29%2C%22fy%22%3A4%7D%2C%22connext%22%3A%7B%22fx%22%3A6%2C%22fy%22%3A-17%7D%2C%220xCB8cbED445Aa490dF53dc269409f4AffE1fC0c71%22%3A%7B%22fx%22%3A-34%2C%22fy%22%3A37%7D%2C%22binance%22%3A%7B%22fx%22%3A32%2C%22fy%22%3A40%7D%2C%22bybit%22%3A%7B%22fx%22%3A76%2C%22fy%22%3A-5%7D%2C%220xd7ACE1b02dF070B4941fBF90a2e36ac840550AaA%22%3A%7B%22fx%22%3A-1%2C%22fy%22%3A56%7D%7D&sortDir=desc&sortKey=time&usdGte=0.1

![image](https://github.com/connext/community-sybil-reports/assets/143567594/de874d76-fc2f-4bf7-82dd-9f08a9a49a85)

Group 2

Using the same method, we add these three wallets to ARKHAM and observe that they intersect with each other. I will provide a screenshot to show you visually.

![image](https://github.com/connext/community-sybil-reports/assets/143567594/8f8ce3b7-45d0-4333-8371-97b4a8bbe4ea)

https://platform.arkhamintelligence.com/visualizer/entity/0x2A9EA5e8cDDf40730f4f4F839F673a51600C314e,0x31eFc4AeAA7c39e54A33FDc3C46ee2Bd70ae0A09,0xB02bF736Fa80dea04731f5932095E8b192EF9B9d,0xCCd9f484c21653Ffb13469e8670E722581018a15,0x9e1FF2971de914cEcaaF98a15189FA64d76b0E75,0xB02bF736Fa80dea04731f5932095E8b192EF9B9d,0xCCd9f484c21653Ffb13469e8670E722581018a15,0x9e1FF2971de914cEcaaF98a15189FA64d76b0E75?flow=self&positions=%7B%220x9e1FF2971de914cEcaaF98a15189FA64d76b0E75%22%3A%7B%22fx%22%3A60%2C%22fy%22%3A-27%7D%2C%220x44609Be7E5E9A567Cc330B81C30b9958D520F5FB%22%3A%7B%22fx%22%3A86%2C%22fy%22%3A3%7D%2C%22connext%22%3A%7B%22fx%22%3A0%2C%22fy%22%3A-2%7D%2C%220xCCd9f484c21653Ffb13469e8670E722581018a15%22%3A%7B%22fx%22%3A42%2C%22fy%22%3A45%7D%2C%220xB02bF736Fa80dea04731f5932095E8b192EF9B9d%22%3A%7B%22fx%22%3A34%2C%22fy%22%3A3%7D%2C%220xBA0d97E0377924ca96594C373806994c73fe5591%22%3A%7B%22fx%22%3A-68%2C%22fy%22%3A-14%7D%2C%220x19C77F64dBfD75ddd278471791D7cE5C1023E307%22%3A%7B%22fx%22%3A-65%2C%22fy%22%3A31%7D%2C%220xFEB37531c44701c48FA9DD4256DC0f97c9568Cb9%22%3A%7B%22fx%22%3A-36%2C%22fy%22%3A54%7D%2C%220x36189eA4029b257E08C0aFBcDC3A09B45633a979%22%3A%7B%22fx%22%3A4%2C%22fy%22%3A58%7D%2C%22itmanhuang%22%3A%7B%22fx%22%3A-88%2C%22fy%22%3A12%7D%2C%220x46698AD8Bc5F451C4628805C4632c3AcbA6CcbB5%22%3A%7B%22fx%22%3A-41%2C%22fy%22%3A-29%7D%2C%220xADD80333b975F89758140845CEE327E9b34ad8ac%22%3A%7B%22fx%22%3A109%2C%22fy%22%3A13%7D%2C%22binance%22%3A%7B%22fx%22%3A98%2C%22fy%22%3A11%7D%2C%220xEf381BF8A4Aa0E0D669A92A86F05fFC0b7776B12%22%3A%7B%22fx%22%3A85%2C%22fy%22%3A41%7D%2C%220x62677143d03624Ed0f9581ab14a3EaAaA327b61B%22%3A%7B%22fx%22%3A0%2C%22fy%22%3A46%7D%2C%220x31Aee1D0744CFf3df1B942400C780fb703039369%22%3A%7B%22fx%22%3A101%2C%22fy%22%3A24%7D%7D&sortDir=desc&sortKey=time&usdGte=0.1

All wallets made transfers between each other, and it was not just a single random transfer. These were constant and frequent transfers, thus proving that it is one person who is creating multiple accounts and conducting various activities across different networks. Even when comparing different networks, the transactions are more or less the same in each network.

Group 3

We are looking at another group of wallets and immediately create a map in ARKHAM to see their intersections and start studying them more deeply. 

![image](https://github.com/connext/community-sybil-reports/assets/143567594/54562570-ed1a-424d-bf63-b3d463216e63)

https://platform.arkhamintelligence.com/visualizer/entity/0x2A9EA5e8cDDf40730f4f4F839F673a51600C314e,0x31eFc4AeAA7c39e54A33FDc3C46ee2Bd70ae0A09,0xC8555668862F2C9c0123d7A65513E8B9A86F4159,0x80e77e8638fF401C4c0159000f438F4Cc14c157A,0x80e77e8638fF401C4c0159000f438F4Cc14c157A,0x80e77e8638fF401C4c0159000f438F4Cc14c157A,0x80e77e8638fF401C4c0159000f438F4Cc14c157A,0x80e77e8638fF401C4c0159000f438F4Cc14c157A,0x80e77e8638fF401C4c0159000f438F4Cc14c157A,0x80e77e8638fF401C4c0159000f438F4Cc14c157A,0x80e77e8638fF401C4c0159000f438F4Cc14c157A,0x80e77e8638fF401C4c0159000f438F4Cc14c157A?flow=self&positions=%7B%220xC8555668862F2C9c0123d7A65513E8B9A86F4159%22%3A%7B%22fx%22%3A28%2C%22fy%22%3A11%7D%2C%220x80e77e8638fF401C4c0159000f438F4Cc14c157A%22%3A%7B%22fx%22%3A-17%2C%22fy%22%3A16%7D%2C%22connext%22%3A%7B%22fx%22%3A-1%2C%22fy%22%3A-12%7D%7D&sortDir=desc&sortKey=time&usdGte=0.1

When we go to DeBank, we see similarities between the accounts, for example, they have the same NFTs in the same quantities.
![image](https://github.com/connext/community-sybil-reports/assets/143567594/41ac91d8-aeb5-4a7e-b24f-54db0fa59050)
![image](https://github.com/connext/community-sybil-reports/assets/143567594/0890dcf4-527e-40c5-8b7e-ee25d362d6ff)

We found a withdrawal transaction to a Binance address, and upon verification, we noticed that two accounts were withdrawing to the same Binance address, almost at the same time.

https://platform.arkhamintelligence.com/visualizer/entity/0x2A9EA5e8cDDf40730f4f4F839F673a51600C314e,0x31eFc4AeAA7c39e54A33FDc3C46ee2Bd70ae0A09,0xC8555668862F2C9c0123d7A65513E8B9A86F4159,0x80e77e8638fF401C4c0159000f438F4Cc14c157A,0x80e77e8638fF401C4c0159000f438F4Cc14c157A,0x80e77e8638fF401C4c0159000f438F4Cc14c157A,0x80e77e8638fF401C4c0159000f438F4Cc14c157A,0x80e77e8638fF401C4c0159000f438F4Cc14c157A,0x80e77e8638fF401C4c0159000f438F4Cc14c157A,0x80e77e8638fF401C4c0159000f438F4Cc14c157A,0x80e77e8638fF401C4c0159000f438F4Cc14c157A,0x80e77e8638fF401C4c0159000f438F4Cc14c157A,0x96784488965730738dBF2793C27651576646A4E9?flow=self&positions=%7B%220xC8555668862F2C9c0123d7A65513E8B9A86F4159%22%3A%7B%22fx%22%3A28%2C%22fy%22%3A11%7D%2C%220x80e77e8638fF401C4c0159000f438F4Cc14c157A%22%3A%7B%22fx%22%3A-17%2C%22fy%22%3A16%7D%2C%22connext%22%3A%7B%22fx%22%3A-13%2C%22fy%22%3A-1%7D%2C%220xb1706b6Fd52921B8c6d72D8c96fE902fFaAcE679%22%3A%7B%22fx%22%3A9%2C%22fy%22%3A35%7D%2C%220x6Adea456c8A014B6cCC04e25fCD8E60d43a3F794%22%3A%7B%22fx%22%3A1%2C%22fy%22%3A31%7D%2C%220x96784488965730738dBF2793C27651576646A4E9%22%3A%7B%22fx%22%3A12%2C%22fy%22%3A40%7D%7D&sortDir=desc&sortKey=time&usdGte=0.1

![image](https://github.com/connext/community-sybil-reports/assets/143567594/6c5753b6-4514-422a-b670-1e269cb6b932)

![image](https://github.com/connext/community-sybil-reports/assets/143567594/d25f022c-6a7b-4f93-bd67-a6bb1a35172d)

Now, let me show you the deposits and their timestamps.

![image](https://github.com/connext/community-sybil-reports/assets/143567594/1fdc0699-31d8-401f-b6c6-39ea5567c246)
![image](https://github.com/connext/community-sybil-reports/assets/143567594/6914adcc-ad9f-437e-9249-d135b18dca94)

And

![image](https://github.com/connext/community-sybil-reports/assets/143567594/2f66eafa-ffac-4b96-a8d1-7e6843f4e475)
![image](https://github.com/connext/community-sybil-reports/assets/143567594/8ef4c333-2194-48bd-b029-29bf47b8f020)

Identical amounts to identical addresses at the same time, and numerous similar transactions, such as these:
![image](https://github.com/connext/community-sybil-reports/assets/143567594/5284a97c-f550-4c48-a5b5-2cbc36616304)
![image](https://github.com/connext/community-sybil-reports/assets/143567594/dbb5bbce-da3d-4eff-941a-9620be54fd9c)

Group 4

Let's move on to the fourth group, where we add all four wallets to ARKHAM and again find that they are linked, even if we go through each account, they are identical. 

![image](https://github.com/connext/community-sybil-reports/assets/143567594/1bc2d55a-ecbf-451a-a2a7-2f576e978354)
https://platform.arkhamintelligence.com/visualizer/entity/0x2A9EA5e8cDDf40730f4f4F839F673a51600C314e,0x31eFc4AeAA7c39e54A33FDc3C46ee2Bd70ae0A09,0x74EFDD76157565c3EFd8735A85B0f9F61Ee6eaE4,0x6A3c31dd8546955e836079AFdFd0C1fB1D22CED5,0x8016e6b65e8098d6A3BC1A5320892D088289451B,0xFa2f6E9c056590ba78Fe7aef551dD27BDbFc000a,0x74EFDD76157565c3EFd8735A85B0f9F61Ee6eaE4,0x6A3c31dd8546955e836079AFdFd0C1fB1D22CED5,0x8016e6b65e8098d6A3BC1A5320892D088289451B,0xFa2f6E9c056590ba78Fe7aef551dD27BDbFc000a?flow=self&positions=%7B%220xEa24F605fF7a7fAfF0ec68859E9D28B21228aEA7%22%3A%7B%22fx%22%3A-30%2C%22fy%22%3A11%7D%2C%22cryptooziron%22%3A%7B%22fx%22%3A86%2C%22fy%22%3A-20%7D%2C%22awesomedevelop%22%3A%7B%22fx%22%3A48%2C%22fy%22%3A-39%7D%2C%220xFa2f6E9c056590ba78Fe7aef551dD27BDbFc000a%22%3A%7B%22fx%22%3A92%2C%22fy%22%3A17%7D%2C%220x74EFDD76157565c3EFd8735A85B0f9F61Ee6eaE4%22%3A%7B%22fx%22%3A118%2C%22fy%22%3A-38%7D%2C%220x4d7Bbf22f733A38F1C59cD52209893F4c9639f5B%22%3A%7B%22fx%22%3A-21%2C%22fy%22%3A-12%7D%2C%220x72a7F477FbAA8eA2D1a3d70bac5D6457dEB3a9ab%22%3A%7B%22fx%22%3A-42%2C%22fy%22%3A-4%7D%2C%22connext%22%3A%7B%22fx%22%3A39%2C%22fy%22%3A5%7D%7D&sortDir=desc&sortKey=time&usdGte=0.1

Additionally, there are numerous similar transactions, such as identical amounts being sent to identical addresses at the same time.
![image](https://github.com/connext/community-sybil-reports/assets/143567594/8f16d98e-685e-49bb-816a-2da741708ff3)
![image](https://github.com/connext/community-sybil-reports/assets/143567594/a7151ca2-4664-4e17-860e-81b6f05cdfaa)
![image](https://github.com/connext/community-sybil-reports/assets/143567594/4584cf13-85ec-41e5-98af-c638d73444a4)
![image](https://github.com/connext/community-sybil-reports/assets/143567594/ffca3c4d-5098-4038-a0aa-97dc97f4724e)

Moving on to DeBank, we examine the accounts and see that two of them were even created on the same day, 2021-11-17, with the other two also being close to these dates.

![image](https://github.com/connext/community-sybil-reports/assets/143567594/0ea180d6-592f-4cc2-acfe-d719c578e742)
![image](https://github.com/connext/community-sybil-reports/assets/143567594/22cda67b-0b21-4091-a181-e604fddbdc82)
![image](https://github.com/connext/community-sybil-reports/assets/143567594/fc978be6-15d6-4a4b-affc-1f53a6a2eaae)
![image](https://github.com/connext/community-sybil-reports/assets/143567594/a94fcd06-b5a8-4980-87bb-6e3761313f6e)

Upon visiting their Twitter accounts, we see that the person who created them gave them almost identical avatars and designed them in the same way.

![image](https://github.com/connext/community-sybil-reports/assets/143567594/c92459d4-5f4f-4d16-9fae-adf61ffea20d)
This is 0x8016e6b65e8098d6a3bc1a5320892d088289451b - https://twitter.com/awesomedevelop

![image](https://github.com/connext/community-sybil-reports/assets/143567594/66d86e11-69f0-4bbf-8f33-dbba10e57185)
This is 0x6a3c31dd8546955e836079afdfd0c1fb1d22ced5 - https://twitter.com/cryptooziron

![image](https://github.com/connext/community-sybil-reports/assets/143567594/5c1745c7-7e75-4adf-b89f-ece5dd846e5d)
This is 0xfa2f6e9c056590ba78fe7aef551dd27bdbfc000a - https://twitter.com/OzironH

![image](https://github.com/connext/community-sybil-reports/assets/143567594/d4971d35-7829-42ed-88e7-0565e5d1469e)
This is 0x74efdd76157565c3efd8735a85b0f9f61ee6eae4 - https://twitter.com/crsiriusblack

Next, we go to the NFT section and again see identical NFTs on all four wallets.

![image](https://github.com/connext/community-sybil-reports/assets/143567594/dc1d6ca9-22ea-4039-9e6b-66c4c3f37310)
![image](https://github.com/connext/community-sybil-reports/assets/143567594/9968d064-4fed-4ffd-a4d6-fdc37b0a5f24)
![image](https://github.com/connext/community-sybil-reports/assets/143567594/bbce98a1-ba2a-4f7b-9c75-d9631c4adf12)
![image](https://github.com/connext/community-sybil-reports/assets/143567594/8aeeb283-344b-4112-8705-aca89bac9563)

After these coincidences, we look at their transactions. It is clear that balances were transferred from account to account, but let's look for more evidence.

They all transferred to one Binance wallet 0x6d9916b03c34854412a82143a35f5bd1c42e4d96, as shown below, demonstrating that these accounts did so.
![image](https://github.com/connext/community-sybil-reports/assets/143567594/530895a2-6c94-4747-ad23-a2bd18ef883d)
https://platform.arkhamintelligence.com/visualizer/entity/0x2A9EA5e8cDDf40730f4f4F839F673a51600C314e,0x31eFc4AeAA7c39e54A33FDc3C46ee2Bd70ae0A09,0x74EFDD76157565c3EFd8735A85B0f9F61Ee6eaE4,0x6A3c31dd8546955e836079AFdFd0C1fB1D22CED5,0x8016e6b65e8098d6A3BC1A5320892D088289451B,0xFa2f6E9c056590ba78Fe7aef551dD27BDbFc000a,0x74EFDD76157565c3EFd8735A85B0f9F61Ee6eaE4,0x6A3c31dd8546955e836079AFdFd0C1fB1D22CED5,0x8016e6b65e8098d6A3BC1A5320892D088289451B,0xFa2f6E9c056590ba78Fe7aef551dD27BDbFc000a,0x6D9916b03C34854412a82143a35F5bD1c42e4d96?flow=self&positions=%7B%220xEa24F605fF7a7fAfF0ec68859E9D28B21228aEA7%22%3A%7B%22fx%22%3A-30%2C%22fy%22%3A11%7D%2C%22cryptooziron%22%3A%7B%22fx%22%3A87%2C%22fy%22%3A-15%7D%2C%22awesomedevelop%22%3A%7B%22fx%22%3A48%2C%22fy%22%3A-39%7D%2C%220xFa2f6E9c056590ba78Fe7aef551dD27BDbFc000a%22%3A%7B%22fx%22%3A98%2C%22fy%22%3A27%7D%2C%220x74EFDD76157565c3EFd8735A85B0f9F61Ee6eaE4%22%3A%7B%22fx%22%3A117%2C%22fy%22%3A-36%7D%2C%220x4d7Bbf22f733A38F1C59cD52209893F4c9639f5B%22%3A%7B%22fx%22%3A-21%2C%22fy%22%3A-12%7D%2C%220x72a7F477FbAA8eA2D1a3d70bac5D6457dEB3a9ab%22%3A%7B%22fx%22%3A-42%2C%22fy%22%3A-4%7D%2C%22connext%22%3A%7B%22fx%22%3A11%2C%22fy%22%3A-14%7D%2C%220x485FF5C8bbebD481EECA66fCEd5B440e7BCeDAfe%22%3A%7B%22fx%22%3A92%2C%22fy%22%3A-95%7D%2C%22okx%22%3A%7B%22fx%22%3A169%2C%22fy%22%3A-13%7D%2C%220x6D9916b03C34854412a82143a35F5bD1c42e4d96%22%3A%7B%22fx%22%3A100%2C%22fy%22%3A-89%7D%7D&sortDir=desc&sortKey=time&usdGte=0.1

![image](https://github.com/connext/community-sybil-reports/assets/143567594/bbb4699b-8394-4987-a568-a63f4a57b356)
Transfer of the same coin at the same time.

I have proved everything, even visually it is visible that they are the same.

# Methodology

I found all these accounts by brute force, made a similarity map in ARKHAM and then made a more detailed investigation through DeBank, basically I clung to the fact that people were withdrawing their money to the same exchange at the same time and the same amount.

I also conducted a visual study of Twitter and nft collections, which were also the same for all these groups.

# Rewards Address

0x69099E2ff673E3C0f49cC67835317Ebd01Bc9B49

**Comment by maximka22222** [comment]
Why is there such a label here?

If necessary, I will send more information if you have any doubts.

**Comment by ArjunBhuptani** [comment]
Sybil groups too small
