### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by mrstanley888** [connext/community-sybil-reports#55]
# Related Addresses

0x23b1BaBF300C948Fa5E3f3D8F7F481879bBfd208
0xC9F3066c0b426CE9F4C4F5Dd643aa007ab867b35
0x5f3B4001c80227Db2F7633Ea7Dd97CE9dbc2ee22
0xeb790767965Cfc9d928B4F2c8f6b7584b06Ca7F5
0x20aD801cbD621BbdF83B2ec92b8321354ec47e12
0x8FF1B712dDcf2E191A135094C7db5D7690028550
0xdce2b724f538830C8aE8Abad0b4B1c9F4F2E2Fe9
0x31fB8AE1A8023Fcb786904C257FEFde29a167eCd
0x2463cF9CF60c8366f8F9ad1D3Da78906fBDd0E68
0x4e0bb68C239736Aaa814a0c98de13a5de3C2Cd14
0x006bd3566D1FA4A700e9db551DF9c934e6F2D889
0x2140006E4CD9471e555FD340cFC1100AB967F332
0x3E86EAA7173861567D8C0d6413F3A850317A21a3
0x15CF763ed4c74b8c059e401BD101426B527EA778
0xa45F809a06eFAB37d38F42F14158eC8a53C84956
0x389327FBe34B24e9f0832690c18932348e677f9B
0xE9dC3A1e2296a5ae39e333Ef1C8891A8F7E61CCA
0x6cd4196866fdc7858bCdf66Dbe01f610Da4D8073
0xaFdC7D98Ba1444599cbc590655A5e337713004EF
0x2AAF80bF31cdBC11DAe92655fEa54A623CD62153
0x8C2fD4Ee740BFd6eD4CA9E001AA53f9cdaE19c49
0x0b5B8c7e069847996fab012CDF1bd9F9A3713002
0x389327FBe34B24e9f0832690c18932348e677f9B
0xE5AE19a46207c85759A177Ed2C2ADea3cC6b98e7
0xeFB941a0d1e82311f4c069550b9dB15B4beE7Bf8
0x22515d630893Ba17bfaF19Bf2afb6639aB5BD8Ee
0xa560dcaDC6b4fA5EdE7F05Ae18022c50FA6962b9
0xA6e3d12442F71Ca64404c990cE3c06d3d2F259D5
0x59dA544a758C31d26f5889b35d9b2b8e2e2e18a4
0x68C4FC9c06739cEF90bB0cC3C300610d75843D7D
0x8Ce8F0074D80D3d6b48de219e01011986B753B44
0x97E8E0a95eB5d73De2b9142F17c8c6aB864ac76c
0x9cf67cd5EDAfC4a8C4B64f2CC6267c9889C6331c
0x8107dc457F6A0A367399d5FDcdfFA8d550B44f27
0x4565C014f9d6FBE652329455F61eb76Dcd5C6CA0
0xa55D9a75bf1a5FbfdAedF175c8eDb7ed1546d99c
0x59Cf8122AE880E5045A33e98DB189FF16cA45A03
0xB60d2E81831a00f933c95C250012f2F715968DC3
0xF14ead38D893f9e788b8c738dD9957Fa77ae5468
0x3De408CeBf44A3b6023439aC374ACe25e9D30164
0x6Cb37CeDf0016B8d470361Fd207408AD46729a9A
0x279773346908B9d4267A9576251553C421B2C0c2
0x162c5003E11020869dcF3210E34184aC6337e363
0x5f9A4074e5801AE50D4f2553b387D396972ad7b4
0xBDCFB5f5B165b8e7CA9Dc2eEd973CCe8ddf36636
0xddd654F870C1Dd5AD30fEfb39074d6184b4e1cfE
0x52153B9C36CD774a18e9A778C9208CC79BD45941
0x85009454335312A653956B5b3219e4ff2538E28D
0xEca7EC073AA0C96D8490cAC70D38467948E26B4F
0x9EcC75404ee9cb22e183Ff34F9a5A8ea703bDB6b
0xEC1dB95Df6ba502fa03bfabb5F64a469C85d6994
0x6bc551982902f2B6AAF2B4eA04e696e1B72F6349
0xF65F40a8868E6D481245529A427B8d4215F7D22E
0x728FA2A39399188878799493F7B15595021914E0
0x0B90BDc8b5689Fd766B7bedd7Cd3b50D60B45fa4
0xefFd8f6d387A281A3443daB9d244237FbC9F5f4A
0xBdbe453b0EA9F4A4c19A8826719994c1c222d70C
0xAF1E33DD99Ae57176fFAb3d57838351878129477
0x1CceBb9134bda997C67ae363BF10c53f55E8164d
0x8C393842Cc7275269C2F7604CCDBEF65b050A1C6
0xeA10C11ac4c8a09793564B368C87A736a7D60389
0x90516e51eE73Fcfa0bAe163D39744Df66e8b4Bf3
0x0a9879381ae90F71fCafB2c76Aae8eFbb2D039dE
0x879bdB641fDbA4E8CB70F6Ea09D205fD89f0F375
0xAAA98f6e2e89069B8776194d20195A155Cb62CB7
0x04DEbF5426447B652297520e8F1dAA867a97B4DA
0xC3C59cc0Fe8D73A7EE4BDB05d4835b5358BD804A
0x1fA4557E575d5d1bb74bbA1Ac3E6c74318E0CcEB
0x952a55f55628933189E2889a390c927730CCb5E0
0x382918a9bb345A9B2C9190f4E65D4a294F50A096
0x759DAC5a48FB2d453e2815220257C3e29e5c60BC
0x3F113937A347a0474a9578B104455cf59DF41f66
0x9a3027b6f90909e8DA8c924e1B4De870471f445d
0x4b2c635bA37DA012E99007682D454a4855160fC0
0x1041D2a5c3990622EdB2Ae6Bff42124900bA508a
0xbF7618bF83C8Ea104DDC1c0597c8e45dcfc689Dd
0x2D041268FA9E11C90037a36e9e51848104808dF4
0x671F1a662cb4b4D33D72BbEd1d84A8D8d11d49CC
0x1F56ED27a144217F6Fe2997Ae553980C7A560B2c
0xee7293f3F6D39E71e2BDec3CacA5c21B1F8A5461
0x9dfe96baA64e4E22bc704DED7A6271215Ad5f67D
0x9670BA8341079dFaD4e5EdA904a12ac1fD17d195
0xCdb016f9178fE987214894E7bA3a91Dd46f1cFFf
0x2664feFAeD1876a7fe07B0FD7dF2186F31a0Ac75
0x1B00FfA76351796Ec3401d8b936dD10180eD220f
0x4725BAC7EDdc920c409113Ed2550b9B9ff53d12F
0xC8593b92b6f64BEb0863Db56E2d1325C2984C0ef
0xBDCF4Cbd118aa2D36273743e4DdC743082e47513

# Reasoning

In polygon blockchain,there are fund transfer among above addresses. the original fund of these  addresses is from 0x23b1BaBF300C948Fa5E3f3D8F7F481879bBfd208. when 0x23b1BaBF300C948Fa5E3f3D8F7F481879bBfd208 finished interacting with connext, it tranfer fund to 0xC9F3066c0b426CE9F4C4F5Dd643aa007ab867b35（https://polygonscan.com/tx/0x29995855f1e458114c65a8ee0c5025bc61935d07a2e3aa170c5ddb67d040bb10）. when 0xC9F3066c0b426CE9F4C4F5Dd643aa007ab867b35 finished interacting with connext, it tranfer fund to 0x5f3B4001c80227Db2F7633Ea7Dd97CE9dbc2ee22 ( https://polygonscan.com/tx/0xb54f90a0e392ae65f00db4b7602297d86c33a63f4c9f306d6a389106729f9e2f ) and so on. You can find fund transfer one by one among above addresses from Feb-17-2022 to Mar-28-2022. for example, fund was shipped from 0xc8593b92b6f64beb0863db56e2d1325c2984c0ef  to 0xBDCF4Cbd118aa2D36273743e4DdC743082e47513 according to https://polygonscan.com/tx/0x26f786c68e9111e33da4983c3a7aacd9194f94e1a0cdce596b0de5bd8d992af8

# Methodology

In polygon blockchain,there are fund transfer among above addresses. the original fund of these  addresses is from 0x23b1BaBF300C948Fa5E3f3D8F7F481879bBfd208. when 0x23b1BaBF300C948Fa5E3f3D8F7F481879bBfd208 finished interacting with connext, it tranfer fund to 0xC9F3066c0b426CE9F4C4F5Dd643aa007ab867b35（https://polygonscan.com/tx/0x29995855f1e458114c65a8ee0c5025bc61935d07a2e3aa170c5ddb67d040bb10）. when 0xC9F3066c0b426CE9F4C4F5Dd643aa007ab867b35 finished interacting with connext, it tranfer fund to 0x5f3B4001c80227Db2F7633Ea7Dd97CE9dbc2ee22 ( https://polygonscan.com/tx/0xb54f90a0e392ae65f00db4b7602297d86c33a63f4c9f306d6a389106729f9e2f ) and so on. You can find fund transfer one by one among above addresses from Feb-15-2022 to Mar-28-2022. for example, fund was shipped from 0xc8593b92b6f64beb0863db56e2d1325c2984c0ef  to 0xBDCF4Cbd118aa2D36273743e4DdC743082e47513 according to https://polygonscan.com/tx/0x26f786c68e9111e33da4983c3a7aacd9194f94e1a0cdce596b0de5bd8d992af8

# Rewards Address

0x012e0b34b1e4D7eCd7cC94ECf60c733296f1D37E

**Comment by ArjunBhuptani** [comment]
Valid:
- Clear connection between addresses
- Consistent pattern of using Connext

https://platform.arkhamintelligence.com/visualizer/entity/0x23b1BaBF300C948Fa5E3f3D8F7F481879bBfd208,0xC9F3066c0b426CE9F4C4F5Dd643aa007ab867b35,0x5f3B4001c80227Db2F7633Ea7Dd97CE9dbc2ee22,0xeb790767965Cfc9d928B4F2c8f6b7584b06Ca7F5,0x20aD801cbD621BbdF83B2ec92b8321354ec47e12,0x8FF1B712dDcf2E191A135094C7db5D7690028550,0xdce2b724f538830C8aE8Abad0b4B1c9F4F2E2Fe9,0x31fB8AE1A8023Fcb786904C257FEFde29a167eCd,0x2463cF9CF60c8366f8F9ad1D3Da78906fBDd0E68,0x4e0bb68C239736Aaa814a0c98de13a5de3C2Cd14,0x006bd3566D1FA4A700e9db551DF9c934e6F2D889,0x2140006E4CD9471e555FD340cFC1100AB967F332,0x3E86EAA7173861567D8C0d6413F3A850317A21a3,0x15CF763ed4c74b8c059e401BD101426B527EA778,0xa45F809a06eFAB37d38F42F14158eC8a53C84956,0x389327FBe34B24e9f0832690c18932348e677f9B,0xE9dC3A1e2296a5ae39e333Ef1C8891A8F7E61CCA,0x6cd4196866fdc7858bCdf66Dbe01f610Da4D8073,0xaFdC7D98Ba1444599cbc590655A5e337713004EF,0x2AAF80bF31cdBC11DAe92655fEa54A623CD62153,0x8C2fD4Ee740BFd6eD4CA9E001AA53f9cdaE19c49,0x0b5B8c7e069847996fab012CDF1bd9F9A3713002,0x389327FBe34B24e9f0832690c18932348e677f9B,0xE5AE19a46207c85759A177Ed2C2ADea3cC6b98e7,0xeFB941a0d1e82311f4c069550b9dB15B4beE7Bf8,0x22515d630893Ba17bfaF19Bf2afb6639aB5BD8Ee,0xa560dcaDC6b4fA5EdE7F05Ae18022c50FA6962b9,0xA6e3d12442F71Ca64404c990cE3c06d3d2F259D5,0x68C4FC9c06739cEF90bB0cC3C300610d75843D7D,0x8Ce8F0074D80D3d6b48de219e01011986B753B44,0x97E8E0a95eB5d73De2b9142F17c8c6aB864ac76c,0x9cf67cd5EDAfC4a8C4B64f2CC6267c9889C6331c,0x8107dc457F6A0A367399d5FDcdfFA8d550B44f27,!socket,!polygon,!hop-protocol,!zerion,0x4565C014f9d6FBE652329455F61eb76Dcd5C6CA0,0x52153B9C36CD774a18e9A778C9208CC79BD45941,0x0B90BDc8b5689Fd766B7bedd7Cd3b50D60B45fa4?flow=all&positions=%7B%220xC9F3066c0b426CE9F4C4F5Dd643aa007ab867b35%22%3A%7B%22fx%22%3A27%2C%22fy%22%3A49%7D%2C%220x23b1BaBF300C948Fa5E3f3D8F7F481879bBfd208%22%3A%7B%22fx%22%3A-11%2C%22fy%22%3A36%7D%2C%22connext%22%3A%7B%22fx%22%3A130%2C%22fy%22%3A73%7D%2C%220xeb790767965Cfc9d928B4F2c8f6b7584b06Ca7F5%22%3A%7B%22fx%22%3A-86%2C%22fy%22%3A63%7D%2C%220x15CF763ed4c74b8c059e401BD101426B527EA778%22%3A%7B%22fx%22%3A56%2C%22fy%22%3A-37%7D%2C%220x3E86EAA7173861567D8C0d6413F3A850317A21a3%22%3A%7B%22fx%22%3A80%2C%22fy%22%3A10%7D%2C%220xaFdC7D98Ba1444599cbc590655A5e337713004EF%22%3A%7B%22fx%22%3A31%2C%22fy%22%3A-47%7D%2C%220x8C2fD4Ee740BFd6eD4CA9E001AA53f9cdaE19c49%22%3A%7B%22fx%22%3A19%2C%22fy%22%3A-56%7D%2C%220xE9dC3A1e2296a5ae39e333Ef1C8891A8F7E61CCA%22%3A%7B%22fx%22%3A6%2C%22fy%22%3A-52%7D%2C%220xE5AE19a46207c85759A177Ed2C2ADea3cC6b98e7%22%3A%7B%22fx%22%3A-6%2C%22fy%22%3A-50%7D%2C%220xa560dcaDC6b4fA5EdE7F05Ae18022c50FA6962b9%22%3A%7B%22fx%22%3A-11%2C%22fy%22%3A-42%7D%2C%220x389327FBe34B24e9f0832690c18932348e677f9B%22%3A%7B%22fx%22%3A52%2C%22fy%22%3A-57%7D%2C%220xeFB941a0d1e82311f4c069550b9dB15B4beE7Bf8%22%3A%7B%22fx%22%3A1%2C%22fy%22%3A-41%7D%2C%220xA6e3d12442F71Ca64404c990cE3c06d3d2F259D5%22%3A%7B%22fx%22%3A-24%2C%22fy%22%3A-52%7D%2C%220x22515d630893Ba17bfaF19Bf2afb6639aB5BD8Ee%22%3A%7B%22fx%22%3A-13%2C%22fy%22%3A-60%7D%2C%220x59dA544a758C31d26f5889b35d9b2b8e2e2e18a4%22%3A%7B%22fx%22%3A67%2C%22fy%22%3A-49%7D%2C%220x4e0bb68C239736Aaa814a0c98de13a5de3C2Cd14%22%3A%7B%22fx%22%3A-1%2C%22fy%22%3A11%7D%2C%220x5f3B4001c80227Db2F7633Ea7Dd97CE9dbc2ee22%22%3A%7B%22fx%22%3A-24%2C%22fy%22%3A53%7D%2C%220x8FF1B712dDcf2E191A135094C7db5D7690028550%22%3A%7B%22fx%22%3A-38%2C%22fy%22%3A45%7D%2C%22hop-protocol%22%3A%7B%22fx%22%3A-92%2C%22fy%22%3A19%7D%2C%220x2140006E4CD9471e555FD340cFC1100AB967F332%22%3A%7B%22fx%22%3A86%2C%22fy%22%3A-31%7D%2C%220x2463cF9CF60c8366f8F9ad1D3Da78906fBDd0E68%22%3A%7B%22fx%22%3A52%2C%22fy%22%3A7%7D%7D&sortDir=desc&sortKey=time&usdGte=15.000000000000004

**Comment by A-Keyboard** [comment]
@mrstanley888 Can you dm me on Discord, my discord is khlilo

**Comment by mrstanley888** [comment]
> @mrstanley888 Can you dm me on Discord, my discord is khlilo

FGH566
