### ISSUE TITLE
Sybil Report #2

### ISSUE THREAD

**Issue by neketskk** [connext/community-sybil-reports#56]
# Related Addresses
0x10f275e503471d76fe836b6dac3827daf0ac9cf9
0x170ad7af2cfbfa7a00e75c5886c396d7cb75189f
0x1e57f5e69b569c529520550f5cbf51456d8ccb85
0x2b718957354e73e52da984e024705d66b778bd00
0x302a6001dc90cc25c6883a45e8b275835c622d51
0x39788a15567d5baf247d6c72e60c771b41b2100c
0x397c97ec4b6d0e22aa73bc5de6715a91b6c5e87f
0x3a1aacb472b00c3655f8cec19b5d6e1f6c0f53c5
0x4f20bbe42a2a2fc69d58377e9f986823bdfda38b
0x54266bb36153a3ffddc85e11ab0ee8a6fe63950b
0x5d16bf50b230da8519316fc6822fcd0f9932b36e
0x69007a156b9205c01cb975dd171342456fc02b80
0x8dcdcb6e443d0bcf7c0f8eb97358116df99820c6
0xa675bbdd2199a9386c4eff3cc9fe13ce0595809c
0xba63379a4291d61cd5aa1a57bec701e75e6a4406
0xd856f89c78f8d015acc0f4b84f1015c4b73d4b94
0xdd69405f1e79e45773d9186a333428da472c9170
0xe976dde9ed8179177d0bc67b957b2c32f8fe2972
0xf18dd74d1cb7038e1b410edb04977f88ff18a434
0xf4086a7ec285db4586929341331b0fdd9ce32524
0xf9cbb7709f9314a0422e203b88ec7db89700a803
0xfc58d0e0bf03d3331249a423af59239ea103c647
# Reasoning
I found accounts on the dune with the same LP balance 
After analyzing them using the debank, I realized that the amount, date of creation, tokens and transactions very similar. 
![image](https://github.com/connext/community-sybil-reports/assets/73196137/db254217-f07a-47ed-9a72-551e63c1d33b)
![image](https://github.com/connext/community-sybil-reports/assets/73196137/7bdd8ad9-f437-429e-a75e-837258e4f895)

**After that, I conducted an analysis using ARKHAM. And I saw that they are looped in a circle in the polygon network. Which indicates that the accounts are SYBIL.**
![image](https://github.com/connext/community-sybil-reports/assets/73196137/ec5b0c81-7826-4d3c-a650-1a38aed1a807)

**Example of all transactions in file**
[direct polygon.csv](https://github.com/connext/community-sybil-reports/files/12435075/direct.polygon.csv)

# Methodology
The reported addresses were discovered during the verification of similar LP balances, through Dune. After that, similar addresses were manually checked for similarity in dates, amount of $, transactions and behavior on the accounts. Identical accounts were checked for transaction links using Ahrkham. And it was concluded that they are SYBIL.
(https://dune.com/KARTOD/connext-bridge-activity-and-top-30percent-depositors). 
[ARKHAM VISUAL](https://platform.arkhamintelligence.com/visualizer/entity/0x10f275e503471D76FE836B6DaC3827DAf0AC9Cf9,0x170AD7AF2cfBfa7a00e75C5886c396D7cb75189F,0x1e57F5E69b569c529520550F5CbF51456d8ccb85,0x2B718957354E73E52da984E024705d66B778bd00,0x302A6001dc90Cc25c6883A45e8B275835C622D51,0x39788A15567D5baf247d6c72E60c771B41B2100C,0x397c97Ec4b6d0E22aA73bc5De6715a91b6C5e87F,0x3a1AAcb472B00C3655F8cEc19b5d6e1f6C0F53c5,0x4F20BbE42a2A2Fc69D58377e9f986823BDFda38B,0x54266bB36153a3fFddC85e11ab0ee8a6fE63950b,0x5D16bf50b230da8519316FC6822fcD0F9932b36e,0x69007A156B9205c01cB975dD171342456fc02B80,0x8DcDcb6E443d0BCf7c0F8eB97358116Df99820C6,0xA675BbDD2199a9386C4EFf3cc9FE13ce0595809C,0xbA63379a4291d61Cd5aa1a57BEc701E75e6a4406,0xD856F89C78F8d015Acc0f4b84F1015c4b73d4b94,0xDd69405F1E79e45773D9186a333428dA472c9170,0xE976DDE9Ed8179177d0BC67B957b2C32F8FE2972,0xf18dd74d1cb7038e1B410edB04977f88Ff18a434,0xF4086a7eC285DB4586929341331b0FDd9ce32524,0xF9cbb7709F9314a0422e203b88Ec7DB89700a803,0xFc58D0e0bf03d3331249A423aF59239EA103C647?flow=self&positions=%7B%220xD856F89C78F8d015Acc0f4b84F1015c4b73d4b94%22%3A%7B%22fx%22%3A72%2C%22fy%22%3A-30%7D%2C%220xE976DDE9Ed8179177d0BC67B957b2C32F8FE2972%22%3A%7B%22fx%22%3A32%2C%22fy%22%3A-44%7D%2C%220x54266bB36153a3fFddC85e11ab0ee8a6fE63950b%22%3A%7B%22fx%22%3A2%2C%22fy%22%3A-49%7D%2C%220xDd69405F1E79e45773D9186a333428dA472c9170%22%3A%7B%22fx%22%3A71%2C%22fy%22%3A-18%7D%2C%220xF4086a7eC285DB4586929341331b0FDd9ce32524%22%3A%7B%22fx%22%3A31%2C%22fy%22%3A-30%7D%2C%220xA675BbDD2199a9386C4EFf3cc9FE13ce0595809C%22%3A%7B%22fx%22%3A-3%2C%22fy%22%3A-33%7D%2C%220x4F20BbE42a2A2Fc69D58377e9f986823BDFda38B%22%3A%7B%22fx%22%3A-5%2C%22fy%22%3A-18%7D%2C%220x39788A15567D5baf247d6c72E60c771B41B2100C%22%3A%7B%22fx%22%3A30%2C%22fy%22%3A-16%7D%2C%220xbA63379a4291d61Cd5aa1a57BEc701E75e6a4406%22%3A%7B%22fx%22%3A69%2C%22fy%22%3A0%7D%2C%220xF9cbb7709F9314a0422e203b88Ec7DB89700a803%22%3A%7B%22fx%22%3A66%2C%22fy%22%3A18%7D%2C%220x170AD7AF2cfBfa7a00e75C5886c396D7cb75189F%22%3A%7B%22fx%22%3A66%2C%22fy%22%3A36%7D%2C%220x397c97Ec4b6d0E22aA73bc5De6715a91b6C5e87F%22%3A%7B%22fx%22%3A29%2C%22fy%22%3A-2%7D%2C%220x1e57F5E69b569c529520550F5CbF51456d8ccb85%22%3A%7B%22fx%22%3A25%2C%22fy%22%3A15%7D%2C%220xf18dd74d1cb7038e1B410edB04977f88Ff18a434%22%3A%7B%22fx%22%3A23%2C%22fy%22%3A33%7D%2C%220x69007A156B9205c01cB975dD171342456fc02B80%22%3A%7B%22fx%22%3A-7%2C%22fy%22%3A-5%7D%2C%220x5D16bf50b230da8519316FC6822fcD0F9932b36e%22%3A%7B%22fx%22%3A-6%2C%22fy%22%3A6%7D%2C%220x3a1AAcb472B00C3655F8cEc19b5d6e1f6C0F53c5%22%3A%7B%22fx%22%3A-11%2C%22fy%22%3A24%7D%2C%220x8DcDcb6E443d0BCf7c0F8eB97358116Df99820C6%22%3A%7B%22fx%22%3A-16%2C%22fy%22%3A43%7D%2C%220x2B718957354E73E52da984E024705d66B778bd00%22%3A%7B%22fx%22%3A21%2C%22fy%22%3A46%7D%2C%220xFc58D0e0bf03d3331249A423aF59239EA103C647%22%3A%7B%22fx%22%3A64%2C%22fy%22%3A52%7D%2C%220x10f275e503471D76FE836B6DaC3827DAf0AC9Cf9%22%3A%7B%22fx%22%3A16%2C%22fy%22%3A61%7D%2C%220x302A6001dc90Cc25c6883A45e8B275835C622D51%22%3A%7B%22fx%22%3A-17%2C%22fy%22%3A62%7D%7D&sortDir=desc&sortKey=time&usdGte=0.1)
[direct polygon.csv](https://github.com/connext/community-sybil-reports/files/12435075/direct.polygon.csv)

# Rewards Address

0x482cD4246886A0D50bd04FF288cb20f53D291255

**Comment by MattLinkevich** [comment]
Yo, you r such a rat, little snitch🐀

**Comment by Nurzhas1** [comment]
Good job!

**Comment by neketskk** [comment]
**full cluster 32 wallet addresses**
0x2b718957354e73e52da984e024705d66b778bd00
0xfc58d0e0bf03d3331249a423af59239ea103c647
0x69007a156b9205c01cb975dd171342456fc02b80
0x302a6001dc90cc25c6883a45e8b275835c622d51
0x8dcdcb6e443d0bcf7c0f8eb97358116df99820c6
0xf18dd74d1cb7038e1b410edb04977f88ff18a434
0x5d16bf50b230da8519316fc6822fcd0f9932b36e
0x10f275e503471d76fe836b6dac3827daf0ac9cf9
0x3a1aacb472b00c3655f8cec19b5d6e1f6c0f53c5
0x39788a15567d5baf247d6c72e60c771b41b2100c
0x5813f4ea91742bcf938f2ec5664ae4be3ba32db4
0x2596d569fa30872808a9734ce666d6bd56d03b74
0x4009c50cc0f5410d2272f0301df79129554fa86d
0xb524e6fa23375bee3f4f2420fbe5a26d7f2fdf2f
0x2fcb9b4c05c37fb4dd246b5b9d135655d1a5ab1f
0x52f44d1d45cec6e12f86b0689b7d9aabfe27ecf3
0xac2ea39f91f0069ed586639df717061fcf776ee8
0xcc599a4e511d1050a474de53a1b72f297a12d5cf
0xe397efd18c1abfc84b348a72b81695e676c6a2ec
0x24e4b3ad81615869fe682eb31203a1d133892677
0x170ad7af2cfbfa7a00e75c5886c396d7cb75189f
0x1e57f5e69b569c529520550f5cbf51456d8ccb85
0x397c97ec4b6d0e22aa73bc5de6715a91b6c5e87f
0x4f20bbe42a2a2fc69d58377e9f986823bdfda38b
0x54266bb36153a3ffddc85e11ab0ee8a6fe63950b
0xa675bbdd2199a9386c4eff3cc9fe13ce0595809c
0xba63379a4291d61cd5aa1a57bec701e75e6a4406
0xd856f89c78f8d015acc0f4b84f1015c4b73d4b94
0xdd69405f1e79e45773d9186a333428da472c9170
0xe976dde9ed8179177d0bc67b957b2c32f8fe2972
0xf4086a7ec285db4586929341331b0fdd9ce32524
0xf9cbb7709f9314a0422e203b88ec7db89700a803

**Comment by neketskk** [comment]
https://platform.arkhamintelligence.com/visualizer/entity/0x2B718957354E73E52da984E024705d66B778bd00,0xFc58D0e0bf03d3331249A423aF59239EA103C647,0x69007A156B9205c01cB975dD171342456fc02B80,0x302A6001dc90Cc25c6883A45e8B275835C622D51,0x8DcDcb6E443d0BCf7c0F8eB97358116Df99820C6,0xf18dd74d1cb7038e1B410edB04977f88Ff18a434,0x5D16bf50b230da8519316FC6822fcD0F9932b36e,0x10f275e503471D76FE836B6DaC3827DAf0AC9Cf9,0x3a1AAcb472B00C3655F8cEc19b5d6e1f6C0F53c5,0x39788A15567D5baf247d6c72E60c771B41B2100C,0x5813f4EA91742BcF938f2ec5664aE4BE3ba32dB4,0x2596D569Fa30872808A9734cE666D6bD56D03B74,0x4009C50cC0f5410D2272F0301Df79129554fa86D,0xb524e6fa23375BEE3f4f2420FBe5a26d7F2Fdf2F,0x2fCB9B4c05C37Fb4Dd246b5b9d135655D1a5aB1F,0x52F44D1d45cec6e12f86b0689b7d9aAbFE27ecF3,0xAc2ea39F91f0069eD586639DF717061fcf776EE8,0xcC599A4E511d1050A474dE53a1b72f297a12D5Cf,0xE397efD18c1Abfc84b348A72b81695e676c6A2EC,0x24E4b3ad81615869fe682Eb31203A1D133892677,0x170AD7AF2cfBfa7a00e75C5886c396D7cb75189F,0x1e57F5E69b569c529520550F5CbF51456d8ccb85,0x397c97Ec4b6d0E22aA73bc5De6715a91b6C5e87F,0x4F20BbE42a2A2Fc69D58377e9f986823BDFda38B,0x54266bB36153a3fFddC85e11ab0ee8a6fE63950b,0xA675BbDD2199a9386C4EFf3cc9FE13ce0595809C,0xbA63379a4291d61Cd5aa1a57BEc701E75e6a4406,0xD856F89C78F8d015Acc0f4b84F1015c4b73d4b94,0xDd69405F1E79e45773D9186a333428dA472c9170,0xE976DDE9Ed8179177d0BC67B957b2C32F8FE2972,0xF4086a7eC285DB4586929341331b0FDd9ce32524,0xF9cbb7709F9314a0422e203b88Ec7DB89700a803?flow=all&positions=%7B%22connext%22%3A%7B%22fx%22%3A37%2C%22fy%22%3A-119%7D%7D&sortDir=desc&sortKey=time&usdGte=0.1

**Comment by neketskk** [comment]
[report_full.csv](https://github.com/connext/community-sybil-reports/files/12497310/report_full.csv)
Communication wallets: 32
Direct connection: 30
Incoming communication: 2

**Comment by neketskk** [comment]
I completed this cluster after rechecking

**Comment by ArjunBhuptani** [comment]
First comment is valid. Clear relationship between addresses and farming activity of Connext.

Second comment: also valid, but was reported in #219 first

Note for team: you'll need to filter @neketskk's second list above against the ones in #219, there are some present in this list that are not in other report and vice versa.

**Comment by A-Keyboard** [comment]
@neketskk Can you dm me on Discord, my discord is khlilo

**Comment by neketskk** [comment]
> @neketskk Can you dm me on Discord, my discord is khlilo
@A-Keyboard 
already answered
nick__vor my discord
