### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by Thephantom25** [connext/community-sybil-reports#57]
# Related Addresses

0x31Df6C983D5E7B6a7B5366d827F4825F05bbe7f5
0x6474Dd2d8d1f926C94dF34A415ba045F37D4ce51
0x211f7aA3D89b6f149Cb583aE48a882Ed4bC4118B
0x21E8fc9a596DcC8F6c1FE8FCa732e4Aec2E67739
0xAB567D20e147E41f0d4fe41a84415D6061Fe2d83
0x448235Cf2A7950f3ccc3522450E756e71d12e6C2
0x700BCfC45668FEa61727cd1F5b0d3B2f67218887
0xc27Ea7750EF3B9e1DD4B9274a8C33Da6E5A8f0c1
0x16562e41112BF3F574A82cF17aD04eF3afDcd1De
0x7C51949347701958EaeA54CAcc5AEACef602b10E

# Reasoning

0x2593E97A440EBb7Dd6F12Baf97116e66D05e1476

0x77C03887aAEC0079C0F9e8Ab472e42c06519Ea5e

0x6474Dd2d8d1f926C94dF34A415ba045F37D4ce51

The plot is between these 3 wallets and 10 wallets have been funded.

# Methodology

Unlike usual, these addresses are interconnected like a spiderweb, but they have used transfer wallets to protect against tracing; however, I still managed to track them down. Each address is connected to one another, and Arkham proves this as well.

Arkham proof link: https://shorturl.at/anBV9

![Ekran görüntüsü 2023-08-25 055455](https://github.com/connext/community-sybil-reports/assets/78061162/36b12977-86ac-4594-b1e1-a5cfb936c739)

Some auxiliary connection TXs

![Ekran görüntüsü 2023-08-25 060636](https://github.com/connext/community-sybil-reports/assets/78061162/9c7ae369-71d6-49c3-9827-154406799016)

https://etherscan.io/tx/0x87e3e1e1c97722fb8b08a06f98cdc6b6b365e770ec0e4dbe1d0a1812ad16c62c

![Ekran görüntüsü 2023-08-25 060902](https://github.com/connext/community-sybil-reports/assets/78061162/14a2e595-26a6-4eae-8b81-e0ea514e4c36)

https://arbiscan.io/tx/0xb2600b4e41a6a552fc22c591691f80e6c666ce4006285e55b400f019e8f36a2b

# Rewards Address

0x14ED8E78137752734Da73D820C0fD8b16861e186

**Comment by ArjunBhuptani** [comment]
Need further review.

These addresses are indeed connected to each other and Connext. However, I am not seeing consistent enough Connext usage to classify as farming.
