### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by lexus-sv** [connext/community-sybil-reports#587]
### Methodology:
I have been looking for wallets that add liquidity at the same time and checked them.
**Rewards Address:** **0xD88b3ba18e2c89f48FC14d57694021556Cc29C99**

### Group 1:
0x3648e15294a6c59d472e50ca19460336a09b0ed2
0x94e902e9bc376c7b0e4c34c75533cba358c0cb3a
0xdb19e883ab6a30f3d1159ec2c6570b37359281cd
0x735fbdd81706236d78bca514e2c20cd4113c71a6
0x0836098a08f27ef6e545743c3b53ae0ab7e953d9
 
### Reasoning:
![image](https://github.com/connext/community-sybil-reports/assets/64213722/fa171ce4-8a8e-4b69-8382-7ae1bd8b0a4a)
![image](https://github.com/connext/community-sybil-reports/assets/64213722/0a893379-aa6f-4dd4-a29d-a58d99fd207a)
![image](https://github.com/connext/community-sybil-reports/assets/64213722/4eebf35a-5129-4f61-8294-3bd436c68a3d)
![image](https://github.com/connext/community-sybil-reports/assets/64213722/ef0f9ab2-3146-4d10-b29e-801fd388d81d)
![image](https://github.com/connext/community-sybil-reports/assets/64213722/bf6c6e44-d102-4329-a258-88a5e6237e97)

All wallets were created on the same day, store money in the same networks and pools, which is too suspicious.
Add liquidity transactions to connext that happened at the same time
Hashes:
https://arbiscan.io/tx/0x2b7bc8d17897cd7bbd6148b37c545d5f638684e09e054d99173a94c22dbe3653
https://arbiscan.io/tx/0xff93159d99a97126a95f7feb34b9be004bb5180c050b13212ede7c885fbd7008
https://arbiscan.io/tx/0x42aabdca231b13cf6505d486c5644c1adc96864a8d32d9abf032bbfa4f9309ce
https://arbiscan.io/tx/0x9256a5699c8ff53eb813c0e516270577608d9fba58cda2382edb8fcd26a95ca8
https://arbiscan.io/tx/0x69d53744ef3becfcfb6fac76713c0582f0df33f8661a46730db4141dae1763e6

Also all those wallets removed liquidity from connext at the same time
Hashes:
https://arbiscan.io/tx/0xb11153336a0c6e2ac24dc665689485622c2bf8585f34c378401120e676ee970aa
https://arbiscan.io/tx/0xfbf9ab15d0800dd7f3ef0920e7b3f71ea571df1e4e779caecfc6805d715ebcbd
https://arbiscan.io/tx/0x5076fa5126e691c297b89a4932ea092344406e7907f5d78fa34890665fba45b4
https://arbiscan.io/tx/0x57fbfb7a5e5e3f79ba70c3ed259009f8afb43ffc4e06deafbd0067c7abddced2
https://arbiscan.io/tx/0x17bc63ea75802ac26e419295e8e8da0066fcfa658997f0130e437de5eaf976c9

### Group 2:
0x0a879499b9031a64db6ece9fd1c890d332872652
0x0ccdecb2bb53ef352c2501df58586f5865467f43
0xf5aed0afb716c73c8d0bac1764bb575ac7d110fa
0x213ca93c1c67685c1f36f0d4c9ca6bc751858b1b

### Reasoning:
![image](https://github.com/connext/community-sybil-reports/assets/64213722/162f0825-81d4-4bb0-9ab3-9719d31300cc)
![image](https://github.com/connext/community-sybil-reports/assets/64213722/ec639072-5c92-4d47-ad14-221335684d01)
![image](https://github.com/connext/community-sybil-reports/assets/64213722/ca2f6086-878c-47b9-80fd-0f7b87cb7af1)
![image](https://github.com/connext/community-sybil-reports/assets/64213722/1fb9d0b7-6297-45de-8120-0fff25b4f8f5)

All wallets have a similar balance, and there are a lot of networks that are almost all the same with the same distribution of funds, which is very suspicious, also these wallets added liquidity to the connext at the same time
Hashes
https://arbiscan.io/tx/0xce71cd65949a49cd3ae459c820215c05dcf7c3c821ad7fbd0352e0a9c7518beb
https://arbiscan.io/tx/0xca34e98873d9d4d72b187e14047ca283112321796478d7b6b14a65b626bba05f
https://arbiscan.io/tx/0xf4eb8ea290eedac2f096cc09d25ddb19b498847a54fc21b5059f4030b8617895
https://arbiscan.io/tx/0xe12b436c81d9dc6abb7770f7e1ed8b5ffa3542a3e4270fd45975b54f064c107a
and removed liquidity at the same time
Hashes
https://arbiscan.io/tx/0x142aa1da8b82808c2c5703a2f7170f23e06f9eb548b345581a5dbd706c125aa6
https://arbiscan.io/tx/0x1434c707c1ac69706f655f2c016bc01fba0ae63159e1aaa2d9828ead0b889ad8
https://arbiscan.io/tx/0x71c935d83c997c9d249590d88d229317d8551bdc391354e9b1af6c548f0380ba
https://arbiscan.io/tx/0x016d2832d21c155bdd2faaab446cddbd64d8d4ce4b8d0f52bd9e5b376607b8cb

### Group 3:
0x6cd693fc2b0bc5f680ea39e9d9417638aa1997ca
0x8947726be49fb33287698d22a111f7a3aa566fdb
0x00415a7aaeeb41094d77847941c4b82a695ac8f4
0x870e8ebe58da9e92556c8906d2c2f2fd2bd4cda3

### Reasoning:
![image](https://github.com/connext/community-sybil-reports/assets/64213722/1d4a33ac-bbbe-4317-b7fd-5c17160dac22)
![image](https://github.com/connext/community-sybil-reports/assets/64213722/69c82e79-1966-4efc-af57-c53711b0b1c0)
![image](https://github.com/connext/community-sybil-reports/assets/64213722/4c7ae0ce-66e6-47a0-a413-8134dc9e9ea5)
![image](https://github.com/connext/community-sybil-reports/assets/64213722/fdd6fd9b-0a23-4bbd-85f8-f8dabe5ed04f)

All wallets were registered at the same time, have a similar balance in the same networks, and added liquidity to connext at the same time
Hashes
https://arbiscan.io/tx/0x5e0fe63b2cc2aed5de16e36f7731865ce482bd4466e4eabd60c39740fa0e2e8f
https://arbiscan.io/tx/0x94b89ee0478009849389a20007ca8d8c4cbb9578f6a01d138a535be4dccb35f6
https://optimistic.etherscan.io/tx/0x5ef70ae1de673a58bd9463885dcfd80266503b631dc55eefc26b1bbf8a4a3229
https://optimistic.etherscan.io/tx/0xfe9d5d112f29fcbf9187877bb1585d50b8e70572fbaae16d9f60993a875af460
And removed liquidity at the same time
Hashes
https://arbiscan.io/tx/0xce23c3eb3eac3ba379452c8a701623a30e55c7f073dffe4637177a5168daa209
https://arbiscan.io/tx/0x0465d4eee48faf066fcc785199923f4f2ac137d45506660674c4259c75588c57
https://optimistic.etherscan.io/tx/0x0d59d8266787852e0009ea4e4b721a0022c14e7a9660d86636f59ae224460ef3
https://optimistic.etherscan.io/tx/0x47b675ca51f9d3509f316921271c548ef17c3d503d95611948c2c3e40dece805

### Group 4:
0x04919c199bf7645cf5a4e75af03eb0653ff5b7ed
0xbe664a3b2e216d23f75f02fe2bcca83ac495dc3b
0x1efc8e20f0fa04fea1e0e1f1d8fb8df15340036d
0xaea2de8bf380a2712ef12602b94a1023703d94ef
0x94a5e66d90f7642bb421b1ecb04fdbf3a13da37e

### Reasoning:
![image](https://github.com/connext/community-sybil-reports/assets/64213722/00ee4fe4-e20d-4b9c-aa50-2faf347939d6)
![image](https://github.com/connext/community-sybil-reports/assets/64213722/74f31672-6432-4e40-b391-39d66121920f)
![image](https://github.com/connext/community-sybil-reports/assets/64213722/ad231798-49b9-419f-a922-6481e7c65744)
![image](https://github.com/connext/community-sybil-reports/assets/64213722/f68f0f7c-28da-40e7-84b4-8218b5c90d91)
![image](https://github.com/connext/community-sybil-reports/assets/64213722/317e8ab7-5a89-4a52-b5aa-11c944aa33f3)

All wallets recently interacted with layerzero and abracadabra, also added liquidity to connext at the same moment 2 times
Hashes
https://optimistic.etherscan.io/tx/0x70e83088a3467eff689362f6ef9ff6994f70a381ba0ea32e852b31e39b7c1d83
https://polygonscan.com/tx/0x0778e73dcf27aab11a7e04a48538440708d154bc0a767b390b32cd3d8f1f332b
https://optimistic.etherscan.io/tx/0x9fd6b2acae6bf24a90ea834efee500523941ba8ea4ee5823bb5298352db99d7c
https://optimistic.etherscan.io/tx/0x6c8fc54c15713d8567c1fe6d0d1adc8191388250d99991307c5f26146f337d01
Hashes2
https://bscscan.com/tx/0xeb1404867a0b74177825f707e388f135ffb2d701205994e6151cdbbb3a60ea95
https://bscscan.com/tx/0xbc52b35c78727f3a1381a1916fa6d260f32638aaab610891005739bf1b7c6313
https://bscscan.com/tx/0xd817da015382611bdfa24446c2f43eaf458d95daf67327d15ed844ed91b1f5ba
https://bscscan.com/tx/0xafe4f88fc00442f6f73477f9a511aaad0e200d94562bad06588d57e0bd942eb8
And removed liquidity at the same time	
Hashes
https://bscscan.com/tx/0x2fd6ea56f058226b74bc45e3e4844bf9588c0589e17b416cdfa893a413c0ee62
https://bscscan.com/tx/0x30786710077b7e568e653ce3b589259878a0267c455d8db6349c4e8177de2b8e
https://bscscan.com/tx/0xb97c19544d65d49a90f8d101c7d08707201346c1d08648ca0c6c4745cea8003e
https://bscscan.com/tx/0xa1b8c3bd4d1b3c415efdf9866391228d32d147ed9f386b5876c9924eeeb2c1fa

### Group 5
0x245607f90c8af40214453ee92042834900161e6e
0x150acd7b42a4c982382c4ac8229c8ba3cdc00aed
0x9bdb00fb7c25ee823050cf63d21c0dad9d146041
0xa9926e9c23460f3cc34fdd80840b71bfc05c9a84
0x7e0133134c1209dd671279ea6bf39efd94da906d
0x70ef9e72b0d1467180b435995dc75153e642cccd
0xfcbf0b898d7210a9ad740c734026c6e837c0a1d9
0x4da15bbfa1f6beb5bf1ab08030347b30a757f070
0x5f5b6b17ab8d2fbe8e29030caf0b9dd2c2bdad26
0x451ac2d066b07171ac50cfeacb6616b7464b3f0c
0xdc6adf83d977d990d791debcd1ad1eb175ec3783
0xc038c5c71c4bfb48934844a22185a3271c21ffa3
0x3fbb2b213b9fca9a1f50ee1fac65d4aa23284d72
0x3d1e309c68c575cb81c76ca28626f308bf958cae
0x5387d4ed1a362fe4d52b150075c754a77b90d60a
0xe7ff50596edd34479c8b68e939317ec1c7d546e6
0x1274c769865ccbbe0bf7802414df1c6de87f78b2
0xed1b7a70d9851aad87724984964e8c7f33448dc8
0x1a4cd1c9b6baf67c1a415faaed71b43c37dc3444

### Reasoning:
![image](https://github.com/connext/community-sybil-reports/assets/64213722/a137ea88-3021-4750-9e21-fa13729c2afb)
![image](https://github.com/connext/community-sybil-reports/assets/64213722/5dc92eeb-4560-4dcb-bc49-ead302269d2e)
![image](https://github.com/connext/community-sybil-reports/assets/64213722/1841712b-ef87-4e0e-ad05-c7eac3bf75dc)
![image](https://github.com/connext/community-sybil-reports/assets/64213722/158a07d1-4679-4a59-9ce8-ef94eca55302)
![image](https://github.com/connext/community-sybil-reports/assets/64213722/0d880682-28f1-46ae-9a87-833770a193fb)
![image](https://github.com/connext/community-sybil-reports/assets/64213722/cecb2f6e-3753-4028-b6f9-eafff17b192a)
![image](https://github.com/connext/community-sybil-reports/assets/64213722/5a399d8a-6e7f-4da3-ac46-5419b0fb7cf3)
![image](https://github.com/connext/community-sybil-reports/assets/64213722/6c966738-1fbb-44a9-be4d-de7970124cb0)
![image](https://github.com/connext/community-sybil-reports/assets/64213722/92a177dd-f72b-4526-8acd-df81638e9aa4)
![image](https://github.com/connext/community-sybil-reports/assets/64213722/f0596a7b-7c33-40ad-8c65-ea5b20d7e7f5)
![image](https://github.com/connext/community-sybil-reports/assets/64213722/6cad239a-1042-4ee4-8704-b6041c087cae)
![image](https://github.com/connext/community-sybil-reports/assets/64213722/e83afe65-3d5d-4e88-a516-676674194d07)
![image](https://github.com/connext/community-sybil-reports/assets/64213722/aa634ab0-0a10-497d-a002-1a79466b7d0b)
![image](https://github.com/connext/community-sybil-reports/assets/64213722/20646a5f-7cb2-4790-9585-88af06bfbe96)
![image](https://github.com/connext/community-sybil-reports/assets/64213722/2fa74e05-2913-4226-b425-87d8161b143c)
![image](https://github.com/connext/community-sybil-reports/assets/64213722/7c0d4064-6f1e-4039-b0ff-0f246e97666e)
![image](https://github.com/connext/community-sybil-reports/assets/64213722/0c411e7e-d8c0-46ae-8a2c-144751beb41e)
![image](https://github.com/connext/community-sybil-reports/assets/64213722/4ed7effc-ea16-4642-8343-4df2ae181560)
![image](https://github.com/connext/community-sybil-reports/assets/64213722/fdb79f44-4767-46c7-addc-c79d7e441954)

All wallets have the same registration date, have identical networks for distributing funds
Also contributed liquidity to connext at the same time
Hashes
https://arbiscan.io/tx/0x84fb653d706ab8a476695389536625a3c8c21a0d467cf2a45e8e9641744be6d4
https://arbiscan.io/tx/0x21b7761238c89b3580f9b2207cb0e7dfed14c197b248b9de4e6f0ab18a8f256e
https://arbiscan.io/tx/0x89478702425d7bbc4eb095d1b315db8e80c217dd180824ea133a6ad2a97d9270
 
https://arbiscan.io/tx/0xfae60339b9f74760ea6c1dc8f458ec9e157d221f3df78336917af7b89c6f2e07
https://arbiscan.io/tx/0x54408484f86d30c1e832c4ba16dfa32074d0e3354865c3f6a3d0ba79adffd637
https://arbiscan.io/tx/0x72f53707fe56e34a41c4187e617f05fab530ec405b03e5eaa11b1218e329d1ac
https://arbiscan.io/tx/0xad15b821e6a008599193888852cdd60612603d25a6f1afa822e29abb053f1a5f
https://arbiscan.io/tx/0xfa1ce3d62b9ee751132da10706488ecfd740d23f2bb4d771103bef86f3124b68
https://arbiscan.io/tx/0x99c458c4530f7b97965cb9e0a3ee1ee39e3d2f8d2542b97ed358f6272bf40adc
https://arbiscan.io/tx/0x82e3c1554ba61015a2d1ef079299f4e22de7e85f95097db74435531dafd51bfc
https://arbiscan.io/tx/0x1a52dea1838abb31b990594dee1faa6063b066a0892c495e11bc75b97c1dcd75
 
https://arbiscan.io/tx/0x4bb6d7e8bff39d5dcc61031ea8167d5048e2bf4aef9f8f57710b644f9e699864
https://arbiscan.io/tx/0x24f9395a4c5f25be588b3a4a4bd8bf6868834bd59c6140d36f6fb945e8abf299
https://arbiscan.io/tx/0xc28af14ecbe1eb974a6e67fe7020ba09b49d7378053c74459dbc22feef09c977
https://arbiscan.io/tx/0x52ae98172489c78eb31ef7562075d50f0a4cfb67339de7211e044011890ed33e
https://arbiscan.io/tx/0xf9a90714699ebf0e858d582b544f6c02efbbca74cbefd3d09bf148418f1dde30
https://arbiscan.io/tx/0x71316e2f76f7f9f2f23d8ab938253d9c13b92d1628ec90916e5ab0d8cc9be3a5
https://arbiscan.io/tx/0x7b96aeb844e936bf3f9195c40bf37973444b1258b062d2de2f09d81cc2f2950e
https://arbiscan.io/tx/0xfa9b68fd1a34c20c24d834de5b92f0812b8adf8d1e72fa6f00e54f8b37882369

### Group 6
0x66E4F76a38d971450774aCd3b444DC8ed4C53346
0xEa02E2C24C1BC08bb0B23850446A532C7df92672
0x4743ed83b4edb1547d2b630bb5b9633252aaa9c6
0x2c7babb1d4704284ad865eb86173342a63883131
0x9bf1dc1f5aca7b1a147ce008b7b041d10613347e
0x46df8db94c2bef4180cd1117711c6fcb4eeb2b3a

### Reasoning:
![image](https://github.com/connext/community-sybil-reports/assets/64213722/6170a805-1df8-4182-8152-ea7a34d5ea9d)
![image](https://github.com/connext/community-sybil-reports/assets/64213722/12169114-1f5a-43e1-bea3-2032daf9a55a)
![image](https://github.com/connext/community-sybil-reports/assets/64213722/73c16695-d67c-4a22-accc-00133137db43)
![image](https://github.com/connext/community-sybil-reports/assets/64213722/5df0e21e-0e25-4eeb-9251-4e8e5c2f926b)
![image](https://github.com/connext/community-sybil-reports/assets/64213722/69337c0d-175b-4009-91a4-76ff3b3b424d)
![image](https://github.com/connext/community-sybil-reports/assets/64213722/7809c2e9-1389-4f93-a8bb-3c56d40bcf71)

All wallets were registered on the same day and have funds in identical networks 
Also simultaneously added liquidity to connext
Hashes
https://polygonscan.com/tx/0x9bf069d0f2c2bb1131e226f5b3dd3e62933de183cbff39a002ddd32c35b1f748
https://polygonscan.com/tx/0x28ec152553562b59a01fdd9f039a8df0a5fd91460a978f220173d4c9d65c1dca
https://bscscan.com/tx/0xad6d6fb49c7f6d5d4f507397f8428b4ad2a95d1cf2d06d5184f448a31e12106b
https://polygonscan.com/tx/0xa386ba88e3183e006a9a7ff6720c9facd6945becc7580ad4b55549c782819a63
https://polygonscan.com/tx/0x00d925b43d3ce3a6885246e0281797614875be541571de86af6d6aaef5c12724
https://bscscan.com/tx/0x6d76e5907035b42b37503151dc26080e72a9735de87b8eaacc3ddceb4703fc9c

### Group 7
0x1f998723fc8a13f668364b4196b1fe86d551e7e1
0x24686eddcc30721d3058855131b5a425b7fdb9c3
0xed349c7e6dd5076bf0d104bd4c48a5d796f9d4a2
0x9ada5bde600c44154de1894fd03955dc4ded071c

### Reasoning:
![image](https://github.com/connext/community-sybil-reports/assets/64213722/24a0571a-05e5-4674-a9ef-80fb03fae64c)
![image](https://github.com/connext/community-sybil-reports/assets/64213722/00cb5dc8-b130-4cfd-87c7-096bdb242b32)
![image](https://github.com/connext/community-sybil-reports/assets/64213722/be29fe97-9129-4023-8ce0-e4d8e59ebbdf)
![image](https://github.com/connext/community-sybil-reports/assets/64213722/6bee597d-1b2d-44cf-93c6-03a24bd01461)

All wallets have the same registration date, and funds in identical networks and pools. Also they added liquidity to connext on the same day
Hashes
https://optimistic.etherscan.io/tx/0xd1556eeafea7f7fa51834a9688cabe7579167c7adab35da4efe45b66278b8efd
https://optimistic.etherscan.io/tx/0xd983ee2a190761c679c86fc4c67ec7dde016eb55cff67496ec7b01f43c7c0118
https://optimistic.etherscan.io/tx/0x95425c231a8a4039078e1e9ca79de3d5ddd26faba48d7088816ee38374c91558
https://optimistic.etherscan.io/tx/0x992bea14c84e1df08a06b1128fb16bb6afe55d6747667e1c40380e110ca4d26b

**Comment by DikaCream** [comment]
@lexus-sv check out announcement https://discord.com/channels/454734546869551114/483734903452729345/1146869788770045982
