### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by avalyn168** [connext/community-sybil-reports#61]
# Related Addresses

```
0xf16924677fde62c15226151dc8c71de87b94f127
0x221eb6f0147394402c5b8fa935c52fbf301a9cf6
0x562e7a4d2f31a941610af1b21306fc2707b56005
0x179af09e62ed8515a475a0a4e9ecf56b98912277
0x75f668744c531bf9479efe2932dd68a530be91b7
0x2421bec9e0233df3270cdeffc49abe8a44286112
0xc151194e55d988cb7c169d6c7e4c2082533b285b
0xa0c279ce31ba1a6005a2c0115b6196f68d65acf6
0xd0b3d0f0610dde1193cb33733cad5d62ae66f1b0
0xb5e94c381e0651463461ac760449251dd9b79282
0x8641d5718ade4e3913bdebc58731498a8c206a9b
0x52eaca9c71fc225fda8ea0837622a872108fdb86
0x30224e19d984b5a55f40c629ffa6179555f15a5c
```

# Reasoning

All addresses received 1000 USDC on approximately 2:50 am UTC on 29 June 2023. After funding, each transferred funds from Polygon to Arbitrum approximately 3:20am UTC on 29 June 2023. All addresses add CUSDCLP on Arbitrum approximately 3:47am UTC on 29 June 2023. Remove liquidity approximately 5:08pm UTC on 17 July 2023. Then, all addresses deposit fund ~997 USDC on Arbitrum to Binance with the same address which is '0x8f4fbbca45f7467bacc290821263c25a6c7293d5' approximately 5:17pm UTC on 15 July 2023.
![Address Map](https://github.com/connext/community-sybil-reports/assets/106711768/db1e26e2-3537-4bda-8682-f0133a54896e)

# Methodology

I manually go through ARBISCAN and look for suspicous activities where some addresses added approximately same amount of money to the pool with same window timeframe and removed those liquidity with the same window timeframe. Then, use DeBank to track these addresses and found out that these addresses deposit all money back to Binance with the same parent address. 

# Rewards Address

0xe9910838e55541f2a69579bf64dbeac1828b75c7

**Comment by dieselbabyy** [comment]
Uh, you're doing this wrong...there's literally no information in your entire post FYI

**Comment by avalyn168** [comment]
> Uh, you're doing this wrong...there's literally no information in your entire post FYI

Thanks a lot. Already fixed sir.

**Comment by avalyn168** [comment]
![Address Map](https://github.com/connext/community-sybil-reports/assets/106711768/3dae9861-f1f3-41ae-9cbb-6edd96d36ebf)

**Comment by ArjunBhuptani** [comment]
Valid report

Clear pattern of farming connext + address are related

https://platform.arkhamintelligence.com/visualizer/entity/0xf16924677fDe62C15226151dC8C71de87b94F127,0x221EB6F0147394402C5b8fA935c52fBF301a9cf6,0x562E7A4d2f31A941610Af1b21306fc2707b56005,0x179af09e62ed8515a475A0A4e9eCF56b98912277,0x75F668744c531bF9479Efe2932dD68A530BE91B7,0x2421bEC9e0233DF3270cdEffC49ABe8a44286112,0xc151194e55D988cB7C169d6C7e4C2082533B285B,0xa0C279cE31ba1a6005a2c0115B6196F68d65acF6,0xD0b3d0F0610DDE1193cB33733cad5D62Ae66f1b0,0xb5E94C381E0651463461ac760449251Dd9b79282,0x8641d5718adE4e3913bDEBC58731498a8c206A9b,0x52EAca9C71Fc225FdA8ea0837622A872108fDb86,0x30224E19D984B5A55f40C629FFa6179555f15a5C,!arbitrum,!arbdoge-ai,!treasure-dao,!hop-protocol,!zksync,0x8f4FbBCa45F7467BACc290821263C25A6C7293d5,!0x8f4FbBCa45F7467BACc290821263C25A6C7293d5,0xb5E94C381E0651463461ac760449251Dd9b79282?chains=polygon&flow=all&positions=%7B%220xc151194e55D988cB7C169d6C7e4C2082533B285B%22%3A%7B%22fx%22%3A22%2C%22fy%22%3A4%7D%2C%220xf16924677fDe62C15226151dC8C71de87b94F127%22%3A%7B%22fx%22%3A15%2C%22fy%22%3A-48%7D%2C%220x8641d5718adE4e3913bDEBC58731498a8c206A9b%22%3A%7B%22fx%22%3A33%2C%22fy%22%3A-29%7D%2C%22disperse-app%22%3A%7B%22fx%22%3A-106%2C%22fy%22%3A17%7D%2C%22connext%22%3A%7B%22fx%22%3A74%2C%22fy%22%3A25%7D%2C%22binance%22%3A%7B%22fx%22%3A-9%2C%22fy%22%3A125%7D%2C%22coinhako%22%3A%7B%22fx%22%3A-42%2C%22fy%22%3A102%7D%2C%22ftx%22%3A%7B%22fx%22%3A-68%2C%22fy%22%3A92%7D%2C%22coinbase%22%3A%7B%22fx%22%3A-66%2C%22fy%22%3A68%7D%2C%220xa0C279cE31ba1a6005a2c0115B6196F68d65acF6%22%3A%7B%22fx%22%3A-14%2C%22fy%22%3A43%7D%2C%22hop-protocol%22%3A%7B%22fx%22%3A8%2C%22fy%22%3A-69%7D%2C%220x8f4FbBCa45F7467BACc290821263C25A6C7293d5%22%3A%7B%22fx%22%3A-45%2C%22fy%22%3A-19%7D%2C%22seawise%22%3A%7B%22fx%22%3A37%2C%22fy%22%3A66%7D%2C%220xb5E94C381E0651463461ac760449251Dd9b79282%22%3A%7B%22fx%22%3A-42%2C%22fy%22%3A-9%7D%7D&sortDir=desc&sortKey=time&timeGte=1683763200000&timeLte=1692489600000&tokens=usd-coin&usdGte=15.000000000000004

**Comment by A-Keyboard** [comment]
@avalyn168 Can you dm me on Discord, my discord is khlilo

**Comment by avalyn168** [comment]
@A-Keyboard Sent you dm on discord. Thank you.

**Comment by avalyn168** [comment]
@A-Keyboard 576GGH
