### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by Ztomepic** [connext/community-sybil-reports#66]
# Related Addresses

Group 1: Addresses on both $Next airdrop list and Arbitrum black list:

0xa03754d919d74f2cb4b5051bbf3b93a4855a9444
0xea24943c595dac8149c749a70b37e11b77fc0a4e
0x538bc2c4152a3a6fd4ed6353e9be22f56994539e
0xceee3115ee9ec10f2040ec3b4b42a6f4b8c5cb38
0x3f5d2058971dfd0103e3bf5e423620b5a42db357
0x24dbab50d9251855e662fb5a30b5649fa2b14bab
0xfaeca790a72ba38e63051c08b455c2a8fe04b407
0x750226d43c5ee850817a0df0ce930a0088cb1f76
0x581b0e594c94d5892701f6573c46d8550cfdd8e3
0x3a09a342ea47a0a63b58e0f6f0bfea7bd4523017
0xf84856531e2d89b438f7820630db02cdfb2ae69f
0x83c036ebc65e0aacf6ded941d50d57bdaa994afa
0x6d4d32907ad7160f7bc7d04a88d0a5b4331ea597
0x1e20cf62c71af22ba4afef950ab7e33969a622db
0x61432827e41979493a9ff0b8668f7efeacb15a67
0x03f74dfa586fe2f345793072440095dcf54de1ed
0xa80c78017e4630a7b5168d304097869e659f227b
0x2ac577e38f5b1128ced1b7b73862119d2ed73e4d
0x8208f1513a27eb3586f474b3c36f05dfbeb66757
0xc06f784fdf842ca3b774ba677b3c2e7420d07cf6
0xfd4d16917e14c045dc718fd541a76f0ece8c870c
0x32ba60b43c4ac07107bf51285a06fc1870f0fb39
0x027d1e3ca00b5a2fdb71818055b72dd458f15981
0x84e3e0f568ed68b4f6827fe797444b3d5b1fd8b5
0x5e611e445b62ee4ece67b58996d64ab9942cbad3
0x942fec89e62c34ecfb26694654bec567fbdf68b5
0xe19e26becff917f057ebb35217fdf4ab3252dffe
0xd60e645c391ed4374829d7ec6439b7e1c7a5438c
0xd5100b2b19bf7e5af4e93072f623a257a9561d20
0xa88e08969377206d8679823a1940ec4e80a3ea64
0x244a859fe3d326f5c7f238303d648553e0c92eb7
0x1b5ae2f3057d23a86ddf16e4bac5f11d6b83621f
0xedcce1c5bfb2553cb801f2b2404a86ebcdb5623e
0x9fa6fb926df7e649001dfda830bcb645ae98c7d6
0xcc53076aa005f6284a4a92ff047a1edb93d15c82
0x4c2be77741570b1074feb47e36eca1a8f09aa9ff
0x1c65030b6e979ca0ffdcb9a617e4914dfacc1a68
0x75f58030c190bb4288f56100f0ee49b6eeb4a134
0x5d24ca5564d6dd6989c7d2a4534ff4305970e082
0x71f00169cae33d60145f486219d5e69402189bf6
0xc2d80f49fde7ccf50ed4b3c233e4f9d055efde70
0xa132c8e9533a1a8010e3c5e77ef96d4d5252be04
0xf71c7473aea9397e038d037e005e1c4c22aa6b93
0x10bfd3d7aabfc8740a8b24187751ea641ce317c1
0x635ff07e852404b7a8343145da6630960076e08b
0x1c54c331ac240cbc5e8ab94937ce42729fc85d75
0x462a24696595297ccc6f7e6b40a653287b81b3f6
0x1d8446dee1067775a6f7e875a19c4dcebd44fb0e
0x74d114147307d774dd13c21682ecaea2c10375e2
0xdc8a278c7689057a7cf5bc7a2f97d7e8806a0c2b
0x86f3aa52a71c6f997d7f1d1eab176058adb38634
0x47076b211dffb6e19cfa717344bc173e8d302dc8
0x8a970e58a24a62f233e70358b407ce310479b08e
0xb173db8f27360f545c551f22bc480a22d33cde22
0xd3c76745e9427a75670ca07b6d233815ade82d3b
0x64d05d76f528448f6db887130135ad1b86dcce55
0x788cc587a9cf3d46d51f75735901e7ea0e6c1c55
0x525ab34c0975c6b94d28cff307172126b0e4c5a1
0xea427e8f242d8e104c6f9b8d65aafe88ca14b8f3
0xcdd6ec239116c84b87916dceef93d92ae0b64c1f
0x04aeed8657784425f32f754fd89995f0fab8e4ad
0xf3d6ab48cdb4dcbfa4932d9ea69543c22695a15d
0x598094a9478209c2d3356a4302b875c4d7be26a7
0xfc9bffa77c2b725add71f4ad88bbe228d5601eb3
0x6bda0404288459cdc35b95a0162636088dccbee8
0x86e1e4c7f59208fd30e8431bdf6dca56b63babf7
0x4cf10d3d1eeae3596a3f8da8b5de6689eb59b141
0xecc87f729b14d8b4680624fa1202b6463b0a963d
0x0fa3b89ad12512d9528ec47c3a2ab4b87633799b
0xd02ce37882ed1760327acaa5831dbf6b4e681869
0x8a05908fb5105d73d611aaf1849783cd7eac06e3
0xb7eb772a3341cd874ded1c15e54eb99a79601534
0x492aad46ad56169679616a9d84f5e1f92111ab7e
0x858e517a8e5c28e7d2fbe081a739f0276e85e69b
0xc13456a34305e9265e907f70f76b1ba6e2055c8b
0x4dc83c05fde2132f85c711087fb453a983ccb810
0x4b7ec805ae47e8696c212ee1e259a291316440d4
0x2df2d34eed59556e2929c5b5f1ef765203e9b6a1
0xd7dfa12e949fb2909b6f5775667469683ba7d8eb
0x41f53c68cce29f1dd4cac0ccdd1a4dc26643cce1
0x7eccbbabf5276c4b48bc15c4508c5b808f54e781
0xb702223d4e83ae5995c5c1c8c89880e28815bf42
0xc842f0db497b75e5d9d9e9cbf5e542202ca4b4f3
0xfc5a28d45637dc3d85844753e1dd304e5a65e06c
0xf201ce02f5332e689f449284a5e8596cf29430fb
0xa89102b5e397f753c4fca0b0bcb593b290838888
0xaa5b2b89dee91e155bf25a2949ce0f3fde09bfee
0xc2e63f57958d5ad5ced8fc18a7b763d9c8327237
0xd1ee5d05ebcc9131b7ed906f85d3121ba8d603b6
0x371ea1e8fcb52083a2a6ee8bb44bb5540939fb82
0x898a81acdb259b26001365979e4fa1a0c3e8eb5e
0x1a756c2e0468556cbf63271747937460bc2ce5e5
0xfcf7174841d19af02e59b89e6d2eedc3b4007243
0x474cfec9950f29b11a1d0b4e7b9b342a1c21a8d1
0xd1bd4e151a09c371f988f740aac982d2e7de9eba
0x0057e2e3f39928de3aeceeba93c7a88fbe615768
0x2f04134fbd11fdeb8d5f49b605e601253de5fa5e
0x109788bc85d8d3015babbf39933a16be1214550a
0x56c6be26bbcede3603f42f69ba1f4e9e2a19a270
0x1a5bcea8141ac40415783dab2d87aa448440b274
0x459bef0acc428832101f0f7cbff1ea1a9db35cc3
0xe95c621e026c605b80f51fe02cccbfa389689c6a
0x3780220f9869ecae387c3725f89679dc8ecdcb7b
0xa2eae2a749103c5631d5525d136ec7b956dd7c85
0x9a93e248519ce49b1f006b5bfc03245531d3c896
0x19d82f6571ac1005a182ad8cbb244ce27776ac20
0x7559b46d502b4c60d41d63b98482eb7320035dda
0x7e9463a9505bf728359d7d5498dea59d03b96a69
0x81bd6e450450e0d9b4aea2e19b3e998c0ed05012
0x45ab09aeca71765815da219a74125423b1d9ac88
0x64efa51222cfa21215011029d4ebf39b59f0bb70
0xe4b8bd8cb10dbf3b152ae13cbf95ec8b869420e1
0x146ab635fd9f49a57ceaeed6347fd4f9f4349ae4
0xa0aecc4a848e6f9998216e004a90b61c810febec
0xf8e823226b3baf0371a59fb0749c04fceb70e188
0x32d3fedb43cce39ce95431c9759672a4e93309c6
0x071fcdd8f8dbab01b864e2abd3d53c55edb86fb8
0xe04a9418cffe0f43fd42527bd3cfc05593eac052
0xccbde2f30fe5180f5fc9b3f66560f5b08b47e808
0xe563bad50fcaef4767116d945e35b87ef5acc4f0
0xb18da1b7ae1a53676eab1213cbdac1eaf0e84654
0x7f7d046c71d95b80553c5bb03c62d1902f04ccc2
0xdb164f2db89357a799b91c0edbff3b39ba39c69c
0x3018b55796b0b9f6b4fe6853561fd33b9261ff30
0x86d87900cbc806cad9508bff9ba7f1a2f90f1ea8
0xf656970a1994c211acda565b8fa85f045aca3e4d
0xed374ece52ab111bdbaee9f1013429f474c883ba
0x7a621e12f381d9acb25f52664dbeff7c7f42934f
0xf78504c4ae5e36ce67401dc7febd2d9700c096d8
0x5ba60b70071d7990f620162eb4b0095f76497aec
0xeec193a23755897ffbb4aeef52b84d567d207fc9
0xa2d2400a95e4920c20d2f0ce01cb76b9369a39f3
0xafb3655b5d17ea4d9e0db354de61269b5ebbe055
0x45503ea064f781b2f95ec7c6b20aecc597c12318
0xd3b2a586180c9e306b38848d31e82f9e17d76f0c
0x8d1854ef9bae977a0282fe9f21ec6dc3e171e43f
0x0be5af23c0618247628160898c60e95efe6b4ef4
0xd0d00337032332d2f0080147371a1b54db9a80f3
0xeadc92ba38a39d651154b9be7650128a3d77e31d
0xa54a961158f8e4611c544b47af75f8a002ac1eb0
0xc27ea7750ef3b9e1dd4b9274a8c33da6e5a8f0c1
0x99c9f7a9f2f995b0a761f37840bdcdb44e8d2297
0x2bd21f6abcbe1f8e1b53ab14cefa64cf8c3005d4
0x0efb002736b5bb34d190f00ca50ad42b0b1c6489
0xc5050b10cccffd4dd50b19e520c5480b96a655f0
0xbd5bf4968c8c430df8a55c5e654c19c1761069ac
0x05ec3b38b99e368e6f85d2dcf73694e3b0557614
0x42e40f05935b95acdd34156f3fb9daa5bbb55812
0x11343993930cbed71e73429b0c1787480fb9c973
0x45c9e878fc23f58045e0a307754f14099844c0f3
0x5199545b942759de1de11835a4e42892da2584bc
0x80a653bb0d51f66ee2933bf06098103f6eb4ea13
0x6afd0cf9e929bf7c46b8b729233697bc22607888
0xe5de835405edc53a2f370b217aba4200abeda20a
0x77edee3b888d9ce54df25b18a4badf9f6340d733
0x8036c27fab2691804b28b9f47239e64c15e249bf
0x597d5d67c442a6bd3d264680fba20136a7ac2324
0x2f17bcef23707f7e876353c2e61a3daaf6903c35
0x58b149407f9ef6db7441528a937c21ce3a4dd371
0x512f0b5bcd667d986d24fba820348799f602c899
0x8aab95323f450b0994d541cfd8af5bc60c47310a
0x37db4e054a5bd500ee361c48c13a2de2cc474c30
0x85039e58b9ba3b7167f16909a69e77dd67cb8bf6
0x3d0c5c0f868121a366fdc71623498fec7e7c84c8
0x12897bcabbdb34a9761562c59eab49b22b59e8b7
0xafdfd1d4257b3e4220265da26e906c879fade809
0x031856e656f04560b5e1415e7771131b4f4d573b
0x0fef653420acae6dfcb7607b99904a2a6f4906fc
0xbebd9051aa63ed001e3ce3b765fdb5db2472023d
0x187089b33e5812310ed32a57f53b3fad0383a19d
0x7e9da3ce59fd5ffbcd26e32cab1af3c38a16e8ad
0xe1c43da5fae2912ad06113b0b05b7480e222f31c
0xa068fe4f7d7c246aab1de25fab49668c5c2b8435
0x06b92a09816fdea8e861d6738ae3a0e41f905a1a
0x6d205238cd78f5db27e5ee2966de2d9580a6ae88
0xab30a75e6a48d446f9ca60b90d518f10763c8341
0x408316f1289f8eb99d364f5c5925d00ae82d87a0
0x702b65c57ebd3e4426e723bda52ff2d08c71306d
0xdaee0331d89bc78641876792a1e5b34910f6ff5b
0x2a86bbd03de6bcffcaf7f075ad72776a10cf6c42
0x011aeda0e46a82c27704a5a1c9fb8db60c094468
0xf6d93c66c852aa8a687eee745c668375b7523746
0x998c5e134d9d0b3415121c777b86cd9e819618b5
0xb16d481c54323c870b124c445111f529a80b6f8a
0x23d4da0bde5d4d94320954213b9faf7792700bb7
0x3a387a9555f0d0505150a828e2717689816ef119
0x686d4ff132b4f4ec3ef52363b5b5f5d21559f8c3
0x88711825ef687d5cb9d86aba79b827a929f8060e
0x5f831bbc519d0a13fc70a5f0aafc3e01e81d071a
0x921ec2c2b5a67066c8870c02c55c55ef6b1f7fde
0x0b160ac9d12addad9e127adac25ea0916e60dc86
0x410023d866daa0aed1f4f6fb94601cd3524ccbc0
0x701152ab7a22eae7a1bdd090f8466b6b1ea41ee5
0xb7de55f5b85a4f6f7c214fadc4b8107f114e6a62
0x4d089efeadaa734a5c01d70e54a0a7eaca3ea78c
0x2b4065b3750be8727fdaff451b2dda5437d34e26
0xcfeba2dbf3b36666462d90c4eb12891ffcab3210
0x30df16cd7d612c5b25beb0331486b127a42ac371
0x035c89aad2417fdea50a7c280fbe7ad6d87e1a93
0x1dec13be619fcb7d3d849f8a34434531d7842ae1
0x0ae3d5949202165584a270cbac7a733b0307a766
0xb20148245de359c857f45e90ca3f26823ad31722
0x153c77633fbfdac4ee4748d2cbab6399d729897b
0xa35dea1466b6cf14a1ac1a1203578908399e560f
0x71a1df0d820d29c784c04865904492ac38801a04
0x7486f5a4cfd00e03242e662f4deeca9993c57ee1
0xfd5cf3a11baf13f2cdb5b1de5cc77f5fc122820c
0x50001b347845c968053ff56cf0f3b07f144d1607
0xf86eee0c09e3764544bdeafdf499a1b7a5f25bb0
0x8836571d0ba76b888702630a6a0a577e3f65d036
0x0dcdd4f4a70ebb2eaffd5a01bd6cacde14dae4f0
0x885ac62415e534665e80ca205290a3798da91159
0xccdb0313237d3c1911de014b814095fbd11cfae4
0x7add36b80981a1d90b2099f80452686fdffce9b6
0x537d74adad607935b4fa2b085640bef99748b127
0xf02cef0456c68c1225129d50c4f53d7da2458b59
0xaa94c1bf68ead01f30a1f8f54b35ea9e06f1213b
0x9a2485730db9beb76ef40060643f1934f337d8c7
0x923ca1422aaa13d21b873974b325b68c4342efee
0x7f66547d2b2b68ef1c276e3898b417fe19f10934
0xd007bef5871bb50d6007af396fd18591931a64a1
0x21e006c5003fac1637f45f4b0616ca22888825de
0x73b5edd218956e4abb8aa150ebef30ecb3ceea74
0xeb33d974f4a48f8065a61aa1b727de627cd3da5a
0x19ccb3782570e3e65265f10224c579e7e80c7452
0x2a86e70c894bd5071bfa74aa98f620548247772f
0x0c3483e3b355986d6bb76e3cebbc8dd8ec20779c
0x829ceb00fc74bd087b1e50d31ec628a90894cd52
0x1146da4bec5034e7d03a5277ced0d66d3a223dd0
0xa7b4a57af5e777406e94da971e5d882cc33a76b4
0x03e041c4778a9d677a9de35f5205864b8f6dd821
0x32af575a9673e44583af2b24ba94b0ce7006677d
0xa87588881eb7222bba8dc602afd852f280a3c153
0x39df83cbbaffe9c13dd11566677f1a7127537d32
0xe7da5e42a550646fa0a88421a334a982d82d2404
0xec886201a7bcd0d26dd036dda4fe07bb4943d1de
0x461cde402c6b945036df1b49f2703fca22b23d7b
0xa55004f4edf9c5d5483ac0e26c587fcfd1c804f4

Group 2: Addresses on both $Next airdrop list and Hop black list:

0x261e1fbc2d5c7200de55289dfab9ebbc5fd585be
0x27d4a79f9096f1b337de23d089d27c0eca313979
0xbcf224cb3771bb32b7a9d49d573375ffa5e29b9d
0x18d072a783fae1ac81af576276dc1561cfba1013
0x6c13fc8ef50144a21702415d57ece0a09879fcfb
0x8ea502092eab16e340808dc75ef3c982e2d71d15
0xc266e461c0aa65cf7ae307783f8a7681424e0b76
0xaa6c7b556449e1d5a75b6322a256180edd1c8edc
0x891ade8337151b26dcbe6662e5180f00ed14959d
0x47e5d263778b1d6afb4468f92fc7b09b306d7997
0x131975ca3e75259e60afeb1cd34051a6804da505
0xaea79e61d658690b2cc0c4078d37ab18cfd2afaf
0xfe3142024baae2a07e257d67bf25492ef414f351
0x7506e3d710c4005c085f548c70ced46ffd5447ea

# Reasoning

They are in [$NEXT airdrop list](https://github.com/Ztomepic/next-sybils-checker/blob/main/connextAllocations.csv). But at the same time, they are found in [Arbitrum sybil attack black list](https://github.com/Ztomepic/next-sybils-checker/blob/main/arbSybilAttackers.csv)(source: [Dune](https://dune.com/queries/2226289) ) or [hop sybil attack black list](https://github.com/Ztomepic/next-sybils-checker/blob/main/hopSybilAttackers.csv)(source: [Hop official repo](https://github.com/hop-protocol/hop-airdrop/blob/master/src/data/eliminatedSybilAttackers.csv) ).

In case you guys consider one of the black lists is not accurate and willing to accept one of the black lists. I seperate sybil addresses in 2 groups:
Group 1 is on Arb black list. 
Group 2 is on Hop black list

# Methodology

I wrote a simple python script to find the intersection between connext airdrop address and (hop black list + Arb black list)
Here is my code and black lists .csv file: [Github repo: next-sybils-checker](https://github.com/Ztomepic/next-sybils-checker).

# Rewards Address
0xd152789e0e242D39CE63A06FB49b1cb0c5a1875a

**Comment by Dubinin1856** [comment]
My wallet is in this list, however i am not sybil and received ARB and Hop airdrop. So it is either a mistake or the topic starter intentionally made a fake list

**Comment by harekrishna2588** [comment]
sir the creator of sybil report #66

kindly don't create the fake list and your source from were u have taken up there also my  address is not there  i have got arb airdrop aswell  i believed its complete mistake so kindly rectify it  thank you

**Comment by harekrishna2588** [comment]
addition to which my address in the source file of sybil attacker from hop and arb is not present still my address is reported i humbly request  team to be vigilant while reviewing all the sybils because they are like insanly doing wrong

**Comment by Grraarrgghh** [comment]
After looking into a few of the addresses, many don't actually appear on either of the lists referenced. Invalid report

**Comment by Ztomepic** [comment]
> After looking into a few of the addresses, many don't actually appear on either of the lists referenced. Invalid report

I believe that addresses in group 2 are definately in both NEXT airdrop list and HOP black list.
They are later reported in #134 #268 by same reasoning.
