### ISSUE TITLE
my account is not counted for airdrop

### ISSUE THREAD

**Issue by Bhero12** [connext/community-sybil-reports#71]
![image](https://github.com/connext/community-sybil-reports/assets/142188569/b54c8233-bcba-4cfc-b273-3699ca928d29)
0x4ce268f49ef0726d602a8b0f22fcc543aa23bb51
The above is my address. I have done 5 transactions and so shows the explorer. I meet the requirements however airdrop page says i am not eligible.

**Comment by Grraarrgghh** [comment]
Not a sybil report
