### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by otto94821** [connext/community-sybil-reports#74]
# Related Addresses

0x65c5ab5ece0d8207d4be925a65ef863aef4295df
0x9cc9e8369c29047fe95504f1705cb13768d9e229
0x1d6039d97e7e01d34c06c1fe6fb947e1d349e73f
0xae6bb701cc057170f3cf1c98eba7db14d8c0aa4a
0x62af646be42e84ed80c90fc93e92d010029229f7
0x4247243bd777e3ae6c8203bbd52b198eab5c0065
0x3a886b8846c2a0c216cd57d2bdf05152877a35fb
0x342e56ec787cf352cd62b7f66e6d2c351935a9f4
0x3e06a09cce58ae12558b616dc5085b874efbdb66
0xd1b16411f73f8c5379d2b23d58d52602f26defe1
0x79e1b8c5b2982e417f7652d1e61ef343f99f2958
0x42ab34c8ff0e4cf87cde41810c0ab73da3712df6
0x7e4830a7481889cb2c543c4e56e48f56e5627afe
0x3e1ea87b995d4c7ab4feac338119ff369f7236ef
0xc0457b506151cd449820b8e0def3d9f1363cf3dc
0x01913b898ab60a470ee1c9e7a2b1dffe07a56249
0x84731090a8e7833e56fd9d261bfc9480fc6b147e
0xc4a7848e0e0db8a14f30a78124843656065b1f37
0x31d22dd981d3406e2d4a8235795b03df0e476d5e
0xaa5dbcfc6621baa9d2ead8dc32fe14cceaa0ee69
0x6ad4bd18871486c136804a2020723bf228dfad76
0x0ff5d842839752842934608b5bd7b8bd402f2808
0xa2c71f599f303be0f80fd53f4efe5baf41ede94f
0x1bb1f36a5d3e3e6d723cdb12efa99281f791e424
0xe2ce7c6f27242ef38ac228446e3a7e9044aa9ca2
0x3fbc890ae8593cc99115b95ffe5a734fb4291012
0xdb47209ceaec71da0e0312b6e9d148817a0085e2
0xdf8fde49361103ccdf8c66ce0739918c95b4cb41
0x15c6ecd673ca568828c1b4d189a15d1021eb1ce1
0xc064d2b785573e1c711cb62f1479e0473ac5a3bc
0x061ea8313eff442c506fb3264d87d7154d250052
0x1ed91f581eb08dde9f702cbb8029a91213deb879
0x7bc1f9e28356bfcbbfcdcf24298cf22b1a2f998a
0xf4930207a9c64e7de7610586748b291d5dfcc26a
0xd0bc18ece100bf6bb7a436ea14437d72f675983f
0xfb97363ed2e195ef8acaab7897f4f1be4dd95523

# Reasoning

All addresses transferred ID Token to Binance Account : 0x8ec88d334390a1cb042430ee7649455f58effd00
.Same time  2023/03/22 .
And every address was created at the same time, Active since 2022-06-22 to 2022-06-25 You can check Active since on each account from debank. 

# Methodology
Easily check all accounts, transfer ID Token from Airdrops to the same address, Binance address, at the same time. 2023/03/22 
https://debank.com/profile/0x8ec88d334390a1cb042430ee7649455f58effd00/history

# Rewards Address

0x3b1BA27F78525c1D83E99339FAf21874c4B018aB

**Comment by prathmeshkhandelwal1** [comment]
https://github.com/connext/community-sybil-reports/issues/5 Address are copied from here.
