### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by edwinosky** [connext/community-sybil-reports#84]
# Related Addresses
# Group 1
1 0x4feee4766d77cb2cfb07a617d9fedf53f94fd1af                                             
2 0xa7ea822349b0261f79a3163b4676a8fd3d8bae77 
3 0x11ddb6cbf950a3e086e8d2c146e7270c204c65f4 
4 0x3934d8c2b94f82a2874eccc85eea92b47e713cea 
5 0x14b51dbaeb36bab0465fb45cfca569eb41802735 

# Group 2
0xf0a3ac1400d7880fedc7b1261be20936b87f44bd
0xe28dd7dba26ba3fa8581fc381ffff57f4fbce3ce
0xde64c2925893a6c9841c0ab0d274a886a494f2a8
0xd17fc86bc9d50872df4d2b10d8855e1965a6baca
0xcf2cd1a1113a24cfa89f935466c46c22107fa75b
0xcddb8bca5cf442730a101c8a8a646f27fef70df3
0xcc5d6b6b4978671198ed26c53b5ca707ed8f10f8
0xc628bb860565f7b28c8ef976bb1c9435e9c3b0f3
0xb4b1e0c6f2e728c17612751f75f62278790fda3d
0xb1ad5f662231aac7ac7ed4b11eedd544fe8ffdc6
0xafad93492b75cdfb3e685c09966aa8ee6ad872c4

# Reasoning Group 1
I managed to identify a wallet that drained thousands of ARB tokens, that wallet controls many more, but only 5 managed to qualify for Connex, this would be the main Wallet, where all the funds arrive: 0xd491435f1388b7d3646bb7154b95eeb9aea3fd4a

After that, he transfers them to another wallet to then swap them.
then I leave the TXID that link each of the 5 wallets that I listed at the beginning

1 https://arbiscan.io/tx/0x5c62a4db1891879b4004fe0a13095bbe6d9d9e9ce36d68c9a017ce9478bf0e9e
2 https://arbiscan.io/tx/0x7961973a13e4247764d39f9a6525786c9c6b96eaec3ebe73eac50e9ac7f6bd95
3 https://arbiscan.io/tx/0xb133a08598f8beb04414582e191f7e10cfa9ed1a85e9a1c28fbce2578ced9870
4 https://arbiscan.io/tx/0x1281db2ffb5e3f83ae8d4f3eb0dfbfb241603e80bddd695f7a05755c6a0a883a
5 https://arbiscan.io/tx/0x2221dcf98c581dd752110535d5fd3f915744b4ac8b414eeea391ec36938dc81d

# Reasoning Group 2
This second group of wallets I got that were eligible for Connext Airdrop but are marked as ARB Sybil, since after receiving the ARB tokens they all sent to a cluster address

# Methodology
In the Connext allocation list I managed to look at a wallet that has a sybil flag in some databases, so I started to investigate it and saw that it was eligible to claim the ARB airdrop but I send them to another wallet as soon as I claim them 0xd491435f1388b7d3646bb7154b95eeb9aea3fd4a

I immediately start to investigate this wallet and I see that it is related to hundreds of other wallets that managed to claim the arbitrum airdrop, I started looking at the Connext list and I was able to identify 5 that were eligible

https://platform.arkhamintelligence.com/visualizer/entity/0xd491435f1388b7D3646Bb7154b95eEb9aea3FD4a,0x4FEeE4766D77CB2CFB07a617d9feDf53f94fD1AF,0xA7EA822349b0261F79A3163B4676a8Fd3D8bae77,0x11dDB6Cbf950A3E086e8d2C146e7270C204c65F4,0x3934D8C2b94f82a2874EcCC85eeA92B47e713cea,0x14b51dbaEb36BaB0465FB45Cfca569EB41802735?flow=all&positions=%7B%220x14b51dbaEb36BaB0465FB45Cfca569EB41802735%22%3A%7B%22fx%22%3A12%2C%22fy%22%3A66%7D%7D&sortDir=desc&sortKey=time&usdGte=0.1

# Rewards Address
edwinosky.eth
0xBd1691E270485D152eb2F9f75B7c8ff4595eeC2F

**Comment by Alexiyko** [comment]
0xde64c2925893a6C9841c0aB0D274A886A494f2A8
It`s my adress, but it`s was hacked by hacker and he put drainer to steal all my funds

**Comment by rhlsthrm** [comment]
Closing because inconclusive.
