### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by YaroslavShl** [connext/community-sybil-reports#87]
PART 1

1. 0x00cf93410f9ddfbcb14bdbdf960fc62877bac4b5
2. 0x00ee80c322d6e956d2629a73223605bbda946f2d
3. 0x00f0df30ff796dc5ebd37f468fc6a7d731625a5d
4. 0x013751db8a52f131874bbfe82e0990b9c560aa7c
5. 0x01352b05ce51e2006f9b314ab50cf4ffa1c2fc34
6. 0x014f65b7b97d2014c8a4f1dcb693d4a4fedf87cd
7. 0x01651036468c847f5f97e2b9ebd3e203e3593f94
8. 0x014fafad53232f6aa5e2e8008cf02685d97ba7ef
9. 0x056fccf01e0e02bbf882157e4e2c4396780f9be9

Wallets 1 to 5 deposited USDC into the Connext pool during the time period 2023/03/24 00:30-01:30

Wallets 6 to 9 put USDC into the Connext pool during the time period 2023/04/01 22:30-22:45

The sum of all is ~1500 USDC.

Then all wallets add another ~2000-1500 USDC to the Connext pool at the same time 2023/05/17 03:20-03:40

At the same time, all wallets transferred USDC to the OKX exchange from 600 to 977 usdc

At the same time, all wallets added USDT to the Connext pool. The amount is about the same, 2615-2625 USDT
.......
2023/05/18 17:40
All wallets have added USDT liquidity to the Connext pool 4050-5000 usdt

and so on...

all wallets have identical activity on the same days and times.

PART 2. WALLETS 10-12

Wallets created on the same day.

Wallets have identical transactions in Connext when adding liquidity.
Liquidity is added in the same amount and on the same days and times.

2023/08/10 18:26-18:30 Liquidity goes to wallets from the USDT pool

Funds are transferred via Stargate from Polygon to Arbitrum.

2023/08/10 19:35 Funds from wallets are sent to the OKEX exchange

Methodology
I manually reviewed the contract https://polygonscan.com/token/0x7f7948b1345b6a95b65a001278b480ce12ca66e5?a=0xe8c0b63edbaf0934e8198461ada30218e43df13a

Transactions were found to withdraw liquidity at the same time with the same volume.

The wallets are then examined in Debank.
I chose Analysis Mode, then Connext and Okex . tokens in transactions USDT and USDC (see my screenshot for what you need to select in Debank) , so you can see the full identity of transactions on wallets

image

Rewards Address
0x04475ad0281612601113c9902608363e8b34c6f0

**Comment by Haraqqqiri** [comment]
can you send a hash of their deposits to the exchange?
