### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by doys12** [connext/community-sybil-reports#95]
# Related Addresses

0xf9cAFEb32467994e3AFfd61E30865E5Ab32ABE68

0x32400084C286CF3E17e7B677ea9583e60a000324

0x18c4c8C7463753B745DF9d3A41084F1fB18f28d5

0xE512fb40D5811820a78692fC663627864DfA78c6

0x91b883bBea30d674b617E64271779DE2E693a1ec

0xF57a49b941F7725D858b657b9f82052C4D3FcB4d

0x0b64aA727412fC4c527aa8F14bA83cd8CF5E75Fe

0x9e2a58d257963A276452FfF1be94C0eB7E2775CC

0xa071C80E5CC76093887a04aC9aCf8f5CeDD3a0e1

0xeACD72B738dfA38Ef088e7aB94154b3013Ec8e22

# Reasoning

these addresses each received funds from the same parent address, and it happened about 10 days ago, and was done by manually transferring to each of the different addresses.

# Methodology

I traced the address using the manual method by scanning in etherscan

https://etherscan.io/address/0xeacd72b738dfa38ef088e7ab94154b3013ec8e22

https://etherscan.io/address/0xa071c80e5cc76093887a04ac9acf8f5cedd3a0e1

https://etherscan.io/address/0x9e2a58d257963a276452fff1be94c0eb7e2775cc

# Rewards Address

0x1F1C110c5152b99c1fC67AcC40fb26a0495B6b21

**Comment by Grraarrgghh** [comment]
All transfers are post snapshot. Invalid report
