### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by 11richie11** [connext/community-sybil-reports#96]
# Related Addresses

# Reasoning

I think that this is a stupid idea, you are wasting other people's time and yours on useless activities of calculating sybils, all these reports are sent by unfortunate people who are ready to pawn something for $50-100 (these are rats, not crypto enthusiasts).

I didn't take part in this project, and I don't care who gets it and who doesn't, but from the point of view of the community, you are doing complete bullshit and shooting yourself in the foot in such a market, it is clear that thanks to the cybils you have such metrics

# Rewards Address

shove that award up the ass of the biggest snitch
-->

**Comment by ArjunBhuptani** [comment]
Never gonna say goodbye
